### ISSUE TITLE
Error: 10 ABORTED: Too much contention on these documents. Please try again.    

### ISSUE THREAD

**Issue by matrix4123** [googleapis/nodejs-firestore#1022]
#### Environment details

  - OS: Docker Container, linux/arm64
  - Node.js version: 12.16.1
  - npm version:
  - `@google-cloud/firestore` version: 3.7.1

#### Steps to reproduce

I'm using a Promise.all to ADD around 6,000 new documents. I am not updating any of these, so I am a bit confused by the contention issues... my understanding is this error could happen if trying to read/update a single document more than once per second. 

```
await Promise.all(
        objects.map(record => {
          return new Promise(resolve =>
            db
              .collection("newCollection")
              .add(record)
              .then(() => {
                resolve();
              })
          );
        })
      );
```

Error:

````
Error: 10 ABORTED: Too much contention on these documents. Please try again.
    at Object.callErrorFromStatus (/usr/src/app/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.<anonymous> (/usr/src/app/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:323:22)
    at /usr/src/app/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
````

**Comment by jakeleventhal** [comment]
this can probably close - made an issue about this earlier today https://github.com/googleapis/nodejs-firestore/issues/1020

**Comment by matrix4123** [comment]
> this can probably close - made an issue about this earlier today #1020

Oh yea, probably related... I think it may have been fixed but not sure if it's been released or not.

**Comment by bcoe** [comment]
@matrix4123 inserting 6000 documents in parallel I think is likely to step on resource limits at the API level (@schmidt-sebastian can correct me if I'm wrong, I'm not an expert on this API).

An approach I might recommend is something like this:

```js
const work  = [] // an array with all the work you want to do.
const WORK_SIZE = 16;
while (work.length) {
  const chunkOfWork = work.splice(0, WORK_SIZE);
  await Promise.all(
        chunkOfWork.map(record => {
          return new Promise(resolve =>
            db
              .collection("newCollection")
              .add(record)
              .then(() => {
                resolve();
              })
          );
        })
      );
}
```

☝️ an approach like this would help control the amount of concurrency.

**Comment by matrix4123** [comment]
Hi @bcoe! I have not seen any resource limits specifically around inserting. I was following the starred note from this section:
https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes


> Note: For bulk data entry, use a server client library with parallelized individual writes. Batched writes perform better than serialized writes but not better than parallel writes. You should use a server client library for bulk data operations and not a mobile/web SDK.

I just saw this https://cloud.google.com/firestore/docs/best-practices#high_read_write_and_delete_rates_to_a_narrow_document_range

Couple things to add here:

- Each time this runs it is a brand new collection
- Not setting the document ID, letting firestore generate it
- Not doing any kind of ramp up at the moment

I'll try your recommendation for now. 

-

**Comment by bcoe** [comment]
@matrix4123 we've released as recently as 6 days ago, so #827 I believe should be out the door.

It might be worth waiting for @schmidt-sebastian's advice, who I believe is back soon.

**Comment by schmidt-sebastian** [comment]
Hello! I have some good news and some bad news: #827 is only meant to address contention that occurs within a transaction. It unfortunately doesn't address the contention that you might be seeing here.

The good news that we are currently working a new API to make bulk data entry easier. This API should ship within the next couple weeks and will implement throttling, which I believe is the one thing that is missing from your code.  

In the meantime, I would advise to lease take a look here and see if either the write limits or the suggestion to ramp up traffic gradually apply to your use case: https://firebase.google.com/docs/firestore/best-practices#ramping_up_traffic

**Comment by schmidt-sebastian** [comment]
@matrix4123 Since there is likely nothing we can in this repro at this time, do you mind filing a support request for this issue? https://cloud.google.com/support-hub

You can also send me your project ID and timestamps for the errors directly and I can follow up on a discussion we already have internally (mrschmidt (at) google.com).

**Comment by schmidt-sebastian** [comment]
Internal bug: b/154364083

**Comment by jakeleventhal** [comment]
@schmidt-sebastian if i can wait a couple of weeks on this, is there a need to still worry about implementing [what you mentioned here](https://github.com/googleapis/nodejs-firestore/issues/1022#issuecomment-615366951). Or should i be fine using the new bulk data entry once it comes out

**Comment by schmidt-sebastian** [comment]
The new Bulk Writer interface will implement throttling. If that is what you are after, you can wait for it.
