### ISSUE TITLE
Failed to start HTTP2 connection bug

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#1025]
#### Environment details

  - OS: macOS Catalina 10.15.5 Beta (19F53f)
  - Node.js version: 13.7.0
  - npm version: 6.13.6
  - `@google-cloud/firestore` version: 3.7.4

#### Steps to reproduce
<img width="1680" alt="Screen Shot 2020-04-15 at 9 06 08 PM" src="https://user-images.githubusercontent.com/15133828/79403439-f3124100-7f5c-11ea-8d26-de252004fc98.png">

**Comment by schmidt-sebastian** [comment]
@jakeleventhal Thanks for filing this. This seems like a more generic problem in establish a connection. For that reason, I moved it manually to https://github.com/grpc/grpc-node/issues/1367
