### ISSUE TITLE
Cloud function - Cannot read property 'Symbol(Symbol.iterator)' of undefined at convertValue

### ISSUE THREAD

**Issue by udox-cameron** [googleapis/nodejs-firestore#103]
Hey guys,

My cloud firestone function are getting the following error whenever they are triggered, I have seen some people are getting similar error on here and the fix was to upgrade the cloud function library. Unfortunately I have upgraded to version 0.8.0 and still get the following error.

```
exports.cleanSubmittedUrls = functions.firestore.document('url/{urlid}').onWrite((event) =>  {
	console.log('event.data', event)
	return true;
})
```

package.json
```
{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "version": "1.0.0",
  "dependencies": {
    "cors": "2.8.3",
    "express": "4.15.3",
    "firebase-admin": "5.7.0",
    "firebase-functions": "0.8.0",
    "secure-compare": "3.0.1",
    "string": "3.3.3"
  },
  "private": true
}
```

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined at convertValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/convert.js:182:44)     at convertDocument (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/convert.js:226:22)     at Firestore.snapshot_ (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/index.js:376:11)     at dataConstructor (/user_code/node_modules/firebase-functions/lib/providers/firestore.js:100:38)     at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:57:31)     at next (native)     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71     at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)     at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)     at /var/tmp/worker/worker.js:695:26
--

Thanks,
Cameron

**Comment by schmidt-sebastian** [comment]
@udox-cameron Do you know if your Firestore document may contain an empty array?

If you can reproduce this, do you mind grabbing the contents of the event object via `JSON.stringify`? Thanks.

And just to verify, the Firestore dependency you are using is 0.10.x? If you have a package-lock.json or yarn.lock, you might see an older version.

**Comment by lpellegr** [comment]
@schmidt-sebastian I am getting the exact same error. The document that trigger the function that fails with the error looks as follows:

```
{
  "attachments": [
    
  ],
  "author": {
    "email": "x@y",
    "fullName": "z",
    "jobTitle": "w"
  },
  "content": {
    "html": "<p>Simple post content<\/p>\n",
    "htmlEscaped": "&lt;p&gt;Simple post content&lt;\/p&gt;\n",
    "markdown": "Simple post content",
    "plaintext": "Simple post content"
  },
  "createdAt": "2018-01-12T14:53:27.097Z",
  "draft": false,
  "draftLabels": {
    "lR7KSMZPgznVJRsd8F0z": 1515768805616
  },
  "excerpt": "Simple post content",
  "forwardToWebhooks": false,
  "labels": {
    "lR7KSMZPgznVJRsd8F0z": true
  },
  "orderedLabels": [
    "lR7KSMZPgznVJRsd8F0z"
  ],
  "publicationTime": "2018-01-12T14:53:00.001Z",
  "slug": "my-title",
  "title": "My title",
  "tstate": false,
  "updatedAt": "2018-01-12T14:53:34.180Z"
}
```

**Comment by schmidt-sebastian** [comment]
I was just able to reproduce this. It looks like for empty arrays, ProtobufJS doesn't always return the array type.  Thanks for your patience.

**Comment by lpellegr** [comment]
@schmidt-sebastian Great! Do you have a rough idea of the time it will take to see a public release that fixes the issue?

**Comment by udox-cameron** [comment]
Hey,

I can't print out the error because I just get the error above. Here is the data it is working with.

` {"beaconfunctionsgroups":[],"beacons":["2fUU4F8"],"campaign":"POS","gid":"orgkey","status":"updated","url":"http://bfred-it.github.io/iphone-inline-video/demo/threejs.html","visibleTime":"2018-01-12T13:49:00.000Z"}`

**Comment by schmidt-sebastian** [comment]
The release for 0.10.2 and 0.11.1 contain fixes for this issue. Note that the cache on Google Cloud Functions currently still resolves firebase-admin's Firestore dependency to 0.10.1. I will notify this thread when that is no longer the case.

**Comment by schmidt-sebastian** [comment]
Note that if you redeploy your Functions, you should now be able to get the newest copy from the cache and no longer see this error.

**Comment by lpellegr** [comment]
Fantastic. Thank you!

**Comment by lpellegr** [comment]
@schmidt-sebastian Erf, I have updated the dependencies as follow:

```
    "firebase-admin": "5.6.0",
    "firebase-functions": "^0.8.0",
```

It seems that GRPC 1.8.0 is fetched. As a consequence, a lot of functions fail with the famous `Error: Stream removed` :(

**Comment by lpellegr** [comment]
@schmidt-sebastian Reverting to firebase-admin 5.5.1 and firebase-functions 0.7.5 still fetches the new dependency! Is there a way to force the old dependency so that GRPC is not fetched? that's a big issue since it breaks all our functions at this time.

**Comment by schmidt-sebastian** [comment]
Do you see this locally or on functions?

These are the results I get:

```
functions $ rm package-lock.json 

functions $ rm -rf node_modules/

functions $ npm install --save firebase-admin@5.6.0

> grpc@1.7.3 install /Users/mrschmidt/Desktop/node-review-with-fix/functions/node_modules/google-gax/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/mrschmidt/Desktop/node-review-with-fix/functions/node_modules/google-gax/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64-unknown/grpc_node.node" is installed via remote

> grpc@1.7.1 install /Users/mrschmidt/Desktop/node-review-with-fix/functions/node_modules/grpc
> node-pre-gyp install --fallback-to-build --library=static_library

[grpc] Success: "/Users/mrschmidt/Desktop/node-review-with-fix/functions/node_modules/grpc/src/node/extension_binary/node-v57-darwin-x64/grpc_node.node" is installed via remote

> protobufjs@6.8.4 postinstall /Users/mrschmidt/Desktop/node-review-with-fix/functions/node_modules/google-gax/node_modules/protobufjs
> node scripts/postinstall

npm notice created a lockfile as package-lock.json. You should commit this file.
+ firebase-admin@5.6.0
added 435 packages in 18.378s

functions $ npm install --save firebase-functions@^0.8.0
+ firebase-functions@0.8.0
added 57 packages in 5.373s

functions $ npm list | grep grpc
│ │ ├─┬ @google-cloud/common-grpc@0.5.3
│ │ │ ├── grpc@1.7.1 deduped
│ │ │ ├─┬ grpc@1.7.3
│ │ ├─┬ grpc@1.7.1
```

**Comment by lpellegr** [comment]
@schmidt-sebastian Ah sorry, the issue seems due to firebase 4.8.2 that is also used in my setup:

> ├─┬ firebase@4.8.2
> │ ├─┬ @firebase/app@0.1.6
> │ │ ├── @firebase/app-types@0.1.1
> │ │ └── @firebase/util@0.1.6
> │ ├─┬ @firebase/auth@0.3.2
> │ │ └── @firebase/auth-types@0.1.1
> │ ├─┬ @firebase/database@0.1.7
> │ │ ├── @firebase/database-types@0.1.1
> │ │ └── faye-websocket@0.11.1
> │ ├─┬ @firebase/firestore@0.2.3
> │ │ ├── @firebase/firestore-types@0.1.1
> │ │ ├── @firebase/webchannel-wrapper@0.2.6
> │ │ └─┬ grpc@1.8.0

I will try to downgrade to an older version. Do you know a compatible one?

**Comment by lpellegr** [comment]
The dependency tree is from my local setup. The error is with deployed functions :S

**Comment by lpellegr** [comment]
Using firebase `4.6.1` is fetching a compatible version of GRPC.

@schmidt-sebastian Do you think it's worth opening an issue on firebase-js-sdk?

**Comment by schmidt-sebastian** [comment]
> @schmidt-sebastian Do you think it's worth opening an issue on firebase-js-sdk?

I will get this resolved internally.
