### ISSUE TITLE
How does one even get started?

### ISSUE THREAD

**Issue by nojvek** [googleapis/nodejs-firestore#1030]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

I've spent an hour bashing my head against how to use firestore. 

```
const admin = require('firebase-admin');
const functions = require('firebase-functions');

admin.initializeApp(functions.config().firebase);

let db = admin.firestore();
```

https://firebase.google.com/docs/firestore/quickstart

what is firebase-admin, how is it related to @googleapis/nodejs-firestore?

How is this different from the "firebase/firestore" package?

Seriously, why is this so hard and fragmented? Which is the official library?

Why does the get started section in readme not have any documentation on how to authenticate?

**Comment by samtstern** [comment]
@nojvek I totally understand your confusion, let me try to explain.  

First to answer your authentication question, it looks like you were following this guide:
https://firebase.google.com/docs/firestore/quickstart#nodejs

Your issue herer alerted me to an out of date snippet on that page, so I fixed it:
https://github.com/firebase/snippets-node/commit/9eca5ffa507a7760f38a2547d731916ba75f8e5c

In general just calling `admin.initializeApp()` will find the default credentials in your environment and authenticate, you don't need to do anything else.  You could also use a specific service account by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.

There are three main libraries here you mentioned.

### 1) Google Cloud Firestore Node.JS SDK
GitHub: https://github.com/googleapis/nodejs-firestore
NPM: https://www.npmjs.com/package/@google-cloud/firestore

This is the official Node.js server SDK for Cloud Firestore.  

### 2) Firebase Admin Node.JS SDK
GitHub: https://github.com/firebase/firebase-admin-node
NPM: https://www.npmjs.com/package/firebase-admin

This library is a very thin wrapper around #1.  The main thing it does is let you set up Firestore along with other Firebase services you may be using with a single `admin.initializeApp()` call.  For all communication to the Firestore backend, it uses the `@google-cloud/firestore` library.

### 3) `firebase/firestore`:
GitHub: https://github.com/firebase/firebase-js-sdk
NPM: https://www.npmjs.com/package/@firebase/firestore

This is the Firebase *Web* client SDK.  It should not be used in Node.js server environments and it is not related to (1) or (2) here.


I hope that's all helpful!

**Comment by nojvek** [comment]
Ah thanks for explaining. Naming things is hard. 

Some general feedback: 

I wish I could edit the original documentation and have what you mentioned as a faq. Like some of the Azure documentation, you should make the google cloud/Firebase documentation a public repo so we can send pull requests. 

I understand that the documentation is there but it doesn’t seem to be written from a new user perspective who is trying to get  `Job J` done. I constantly have to ask search engine and read stackoverflow, some of which is outdated. I even found syntax typos in firestore rules doc, that if I copy-paste it would throw errors. 

Just advocating that empowering users who feel the pain to fix the pain is one of the best ways to build a frictionless product.

**Comment by samtstern** [comment]
@nojvek I hear you!  I agree, the above information is pretty hard to figure out yourself.  Of course if we added it to the "Get Started" page it might overwhelm and confuse many users.

Also we are working hard to have open source docs one day, it's a huge change for us but we do think we can get there.
