### ISSUE TITLE
Pipelined vs batched writes

### ISSUE THREAD

**Issue by 0x80** [googleapis/nodejs-firestore#104]
I am noticing some odd behavior trying to execute many write operations at once.

At first I was looping over an array of data with `for...of` using await on each set/update iteration. This is very slow of course because you are waiting for the db to respond to each action.

So I started using the `db.batch()` API and that works *a lot* faster. But unfortunately batches are limited to 500 items, so I wrote an abstraction to handle the chunking.

Then I learned from this [video](https://www.youtube.com/watch?v=66lDSYtyils&feature=youtu.be&t=1m49s) that requests can be pipelined, so I tried to map my data to an array of promises and awaited on `Promise.all`.

But I discovered that if I do this with a lot of items the SDK quickly fails on me. For example the code below tries to update data for 2.2k airlines (the data itself is only a few props).

```typescript
    const airlines = await getAirlines();
    console.log(`Fetched data for ${airlines.length} airlines`);

    const promisedUpdates = airlines.map(airline =>
      db
        .collection("airlines")
        .doc(airline.id)
        .update(airline.data, { create: true })
    );

    await Promise.all(promisedUpdates);
```

The result is:

> Fetched data for 2250 airlines
> Error: Deadline Exceeded
>     at `/Users/me/myproject/node_modules/@google-cloud/firestore/node_modules/grpc/src/client.js:554:15`

It also takes a very long time for it to fail with this timeout.

If I cut the processing in chunks of 500, everything runs smoothly and the whole process takes about 11 seconds:

```typescript
  const airlines = await getAirlines();
  console.log(`Fetched data for ${airlines.length} airlines`);

  const chunks = chunk(airlines, 500);

  for (const airlines of chunks) {
    const promisedUpdates = airlines.map(airline =>
      db
        .collection("airlines")
        .doc(airline.id)
        .update(airline.data, { create: true })
    );

    await Promise.all(promisedUpdates);
    console.log(`Committed ${airlines.length}`);
  }
```

> Fetched data for 2250 airlines
> Committed 500
> Committed 500
> Committed 500
> Committed 500
> Committed 250
> Updated 2250 airlines

I find it odd that something that takes 10s in batches like this, takes forever if you send 4x as many requests at once. So I wonder if this is a bug in the grpc client.

If requests to Firebase can be pipelined but there is somehow a maximum of what can be handled at once, I think this should be made clear in the documentation. And if everything should be chunked in certain numbers it would be helpful to have abstractions for that. It feels wrong to leave this complexity to the client logic.

For example here is the abstraction I use to do batched writes without having to count to 500 in my client code everywhere. This is not super generic / a bit specific to my needs but I think that a similar abstraction would be a welcome addition to the API.

```typescript
interface BatchMutation {
  ref: FirebaseFirestore.DocumentReference;
  data: object;
}

interface BatchUpdateOptions {
  create: boolean;
}

type BatchType = "set" | "update";

export async function commitBatch(
  type: BatchType,
  mutations: BatchMutation[],
  options?: BatchUpdateOptions
): Promise<void> {
  let batch = db.batch();
  let counter = 0;

  for (const mutation of mutations) {
    counter++;
    const { ref, data } = mutation;

    type === "update" ? batch.update(ref, data, options) : batch.set(ref, data);

    if (counter >= BATCH_LIMIT) {
      await batch.commit();
      counter = 0;
      batch = db.batch();
    }
  }

  /**
   * Finally commit the remaining batched items
   */
  await batch.commit();
}
```

**Comment by samtstern** [comment]
@0x80 apologies for the slow response.  I talked to @schmidt-sebastian about this and neither of us remembered to actually get back to you :man_facepalming: 

So first of all, the video you link to about pipelining is actually about the Realtime Database.  So if any of it applies to Firestore, that's a coincidence (in fact that video was released about 8 months before Firestore).

When you issue many many async requests at the same time you can sometime end up exceeding the limits of the backend.  As you've noticed, forming write batches makes this much better.

So the lesson is this is currently "working as intended" and we are looking at adding some auto-batching to the library internals (like you've done in your abstraction) but we have not completed that work yet.

Thank you for the very detailed issue!

**Comment by 0x80** [comment]
Thanks for getting back to me @samtstern. I found a lot of concepts from the realtime-db don't apply to Firestore, but somehow I was expecting this to work. Probably because I hadn't come across any warning about async requests in the documentation. 

Good to hear some abstractions for auto-batching will likely appear in the future 👍
