### ISSUE TITLE
Emulator : "2 UNKNOWN" error is thrown instead of exact error message

### ISSUE THREAD

**Issue by manwithsteelnerves** [googleapis/nodejs-firestore#1049]
### Environment details

  - OS: Mac OSX, Mojave
  - Node.js version: 10.14.2
  - npm version: 6.13.4
  - `Firestore Emulator` version: 1.11.3
  - `Firestore Tools` version: 8.1.1

#### Steps to reproduce

  1. Create an invalid query by providing a different first sort order parameter from the one passed in where query operator.
  2. Notice it throws "2 Unknown" error.

> at callErrorFromStatus (/functions/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
> at Http2CallStream.call.on (/functions/node_modules/@grpc/grpc-js/build/src/call.js:79:34)
> at Http2CallStream.emit (events.js:187:15)
> 

#### Expected behaviour
It should throw a valid error mentioning the exact issue instead of a generic one.

> "3 INVALID_ARGUMENT: inequality filter property and first sort order must be the same: meta.defaultKeyword and name"

#### Notes
We noticed this only on firestore emulator and not with production.

```
 const collectionRef: CollectionReference  ='users';
 let query : Query ;

 query = collectionRef.orderBy('names', 'asc');
 query.where('age','>=',25);
```
 
Thanks!

**Comment by yuchenshi** [comment]
Thanks for the detailed report @manwithsteelnerves !

This is likely an emulator issue. Project maintainers, please assign to me and I'll forward it to the right person.

**Comment by crwilcox** [comment]
@yuchenshi any update here?

**Comment by yuchenshi** [comment]
I've added some more logging to Firebase CLI starting vX.Y.Z. The next time this happens, please take a look at `firestore-debug.log` and it should contain more detailed logs.

Also, to anyone working at Google -- this is tracked internally at b/129293104 and feel free to take it from there. There are also a few internal pointers there to get us started and I think we can make some progress even without the detailed logs.

**Comment by schmidt-sebastian** [comment]
@yuchenshi Are we okay to close this? 
@manwithsteelnerves Are you still blocked on this?
