### ISSUE TITLE
stream could not be found within the project

### ISSUE THREAD

**Issue by ksbulgakov** [googleapis/nodejs-firestore#1069]
Hi!

error: Error: Unable to resolve module `stream` from `node_modules/@google-cloud/firestore/build/src/index.js`: stream could not be found within the project.

If I add stream locally (yarn add stream) it shows that url could not be found and so on until I reached "crypto" which was deprecated https://www.npmjs.com/package/crypto

#### Environment details

  - OS:  macos 10.15.4
  - Node.js version: v12.0.0 & v12.16.3
  - yarn version: v1.22.4
  - `@google-cloud/firestore` version:  "^3.7.5"

#### Steps to reproduce

  1. react-native init
  2. yarn add @google-cloud/firestore
  3.  import '@google-cloud/firestore'; (App.js)
  4. yarn android

**Comment by schmidt-sebastian** [comment]
@ksbulgakov This SDK is not indented to be used with React Native. Please take a look here: https://rnfirebase.io/firestore/usage

React Native Firestore wraps `@firebase/firestore` (our Web SDK), which lives here: https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore

**Comment by ksbulgakov** [comment]
@schmidt-sebastian 
Yes, now I use https://rnfirebase.io/firestore/usage. And I will try @firebase/firestore.
I was just wondered that @google-cloud/firestore do not see global nodejs modules during a building (other packages have no such problems).

Thank you!
