### ISSUE TITLE
Add Generic Types

### ISSUE THREAD

**Issue by bmass02** [googleapis/nodejs-firestore#109]
## Proposal
Add Generic Types with defaults to DocumentReference, CollectionReference, Query, etc.
```typescript
export class DocumentReference<D = DocumentData, U = UpdateData, P = CollectionReference<D, U>|null, S = {[subCollectionId: string]: CollectionReference}> {
```
D and U are pretty straight forward, but P would be for the parent type and S would be for the typing of subcollections. This would still be backwards compatible as providing no types would default to what is currently typed.

Currently if I want to achieve any of this I have to create wrapper interfaces for any Firestore classes I want to use and retype all of the methods, then type the collections/documents with those wrappers.

I'd be happy to make a PR with the necessary changes if you think this change is beneficial.

## Reasons
1. Typed data returned from DocumentSnapshot (i.e. eliminates the need to import types and explicitly type variables containing the data.)
2. Enforcement of parent types and subcollections and their types
3. Enforcement of update rules (i.e. if certain values should only be written on create, or if one value is changed, another should also be updated)
4. Easier to extend Firestore classes for modeling purposes (only as interface since constructors are private)

```typescript
const chatRooms = firestore.collection<ChatRoom, ChatRoomUpdateRules>('rooms')
const myChatRoomRef = chatRooms.doc(myChatRoomId)
const myChatRoomDoc = await myChatRoomRef.get()
const myChatRoomInfo = myChatRoomDoc.data() //myChatRoomInfo is of type ChatRoom

const members = myChatRoomDoc.ref.collection<Member, MemberUpdateRules>('members')
const certainMembersQuery = members.where('posts', '>=', 3).orderBy('posts').limit(10)
certainMembersQuery.onSnapshot((membersSnapshot) => {
  membersSnapshot.docChanges.forEach((change) => {
    const memberInfo = change.doc.data() //memberInfo is of type Member
  })
  membersSnapshot.docs.forEach((doc) => {
    const memberInfo = doc.data() //memberInfo is of type Member
    const otherChatRoomRef = doc.ref.parent.parent.parent.doc(otherChatRoomId) // Maintains typings of parents
  })
})
```

### Enforcing subcollections
```typescript
import * as admin from 'firebase-admin'
import * as Event from './event'

interface IOrganizationModel {
  ...
}

interface IOrganizationUpdateRules {
  ...
}

interface IOrganizationSubcollections {
  events: Event
}

export default admin.firestore().collection<IOrganizationModel, IOrganizationUpdateRules, null, IOrganizationSubcollections>('organizations')
```
```typescript
import Organizations from './organizations'

const myOrgDoc = await Organization.doc('myOrgId').get()
const myCurrentEvents = await myOrgDoc.ref.collection('events').where('end', '>=', new Date().getTime()).orderBy('end').get() // type checks successfully and holds the Event model types
const myCurrentMembers = await myOrgDoc.ref.collection('members').get() // collection('members') fails type check since 'members' is not a keyof IOrganizationSubcollections
```

**Comment by schmidt-sebastian** [comment]
Thanks for your suggestion. We will discuss this internally and will get back to you by the end of the week.

**Comment by schmidt-sebastian** [comment]
@bmass02 We talked about this internally and decided to not go forward with this for now. While this would remove cast from user code, it gives the impression that we offer type safety. Our backing NoSQL store however allows you to put any kind of document in any collection, and hency any "casting" that we would do for you is as unsafe as the casting that you are doing yourself. If you are 100% certain about your types, we suggest that you wrap our types yourself.

You may also want to look at AngularFire which basically provides what you are asking for: https://github.com/angular/angularfire2/blob/master/src/firestore/firestore.ts

**Comment by robert-king** [comment]
this answer mentions json.parse returns type of "any", perhaps "DocumentData" should be of type "any".

https://stackoverflow.com/a/51607297/632088

that way, I can do something like doSomethingWithPerson(docDataVal), without the complaint that DocumentData is not of type Person.

**Comment by imjared** [comment]
I'm not usually one to "+1" in the comments but wanted to weigh in here that this would really be a nice-to-have. 

Totally appreciate the thought you and the team put into your decision but just throwing my voice here so other folks chime in and the resounding throng of GitHub comments becomes too much for you to handle :)
