### ISSUE TITLE
Firestore does not act as admin when FIRESTORE_EMULATOR_HOST is set

### ISSUE THREAD

**Issue by samtstern** [googleapis/nodejs-firestore#1104]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: macOS
  - Node.js version: 10.19.0
  - npm version: 6.13.4
  - `@google-cloud/firestore` version: 3.8.2+

#### Steps to reproduce

See instructions here: https://github.com/firebase/firebase-tools/issues/2310#issuecomment-636843345

This issue was introduced by this PR:
https://github.com/googleapis/nodejs-firestore/pull/1095

**Comment by yuchenshi** [comment]
I'm looking into this right now. I've got a repro locally.
