### ISSUE TITLE
Update to latest google-gax

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-firestore#1109]
Are there any plans to update `google-gax` to latest version?

 **Is your feature request related to a problem? Please describe.**
I'm trying to trace firebase functions using firestore. The problem is that the grpc plugin from open telemetry only supports version 1 of the grpc client, however, google-gax 1.13..0 uses version 0.7.

 **Describe the solution you'd like**
Update gax to the latest version, so that it uses grpc-js 1.0.0. See https://github.com/googleapis/gax-nodejs/blob/v2.5.0/package.json#L17

**Comment by schmidt-sebastian** [comment]
GRPC 1.x is coming with https://github.com/googleapis/nodejs-firestore/pull/1114.

We can't take GAX 2.x until we drop Node 8 support.

**Comment by sk-** [comment]
Thanks @schmidt-sebastian, regarding Node 8 support, could you update the README, as it says:

> Our client libraries follow the Node.js release schedule. Libraries are compatible with all current active and maintenance versions of Node.js.
> legacy-8: install client libraries from this dist-tag for versions compatible with Node.js 8.

See https://github.com/googleapis/nodejs-firestore#supported-nodejs-versions.

That seem to be boilerplate for Google projects.

**Comment by schmidt-sebastian** [comment]
@sk- Thanks for pointing this out. We are actively working on making this true. I hope we can get there soon
