### ISSUE TITLE
Issuing a `Transaction.get()` with a document reference as the first operation results in a "client not yet ready" error

### ISSUE THREAD

**Issue by leeor** [googleapis/nodejs-firestore#1217]
#### Environment details

  - OS: Cloud Run instance
  - Node.js version: 12
  - npm version: 
  - `@google-cloud/firestore` version: 3.8.1

#### Steps to reproduce

  1. Create a Firestore instance
  2. Call `runTransaction`
  3. Call `Transaction.get()` with a document reference

Getting the following error:
```
INTERNAL ERROR: Client is not yet ready to issue requests.
```

Any other time when a call to `Transaction.get` is called with a query object first, everything works correctly (including any following calls to `Transaction.get` that pass a document reference). I've substituted the document reference in the first call with a query object and it worked fine.

The issue only occurred so far in my Cloud Run instances, not in local mode using an emulator with GCLOUD_PROJECT and FIRESTORE_EMULATOR_HOST set.

As a workaround, I am now initialising the Firestore client with a `projectId` which prevents the error and lets me keep using `get` with a document reference as the first transaction operation.

One last thing, this issue only started happening after I started using transactions. Without one, I could call `get` with either a query or a document reference without any issues.

Thanks!

**Comment by leeor** [comment]
@schmidt-sebastian sorry, but I never assigned a logging function, so I don't have the logs from the library itself, just the exception that was thrown to my code.

**Comment by schmidt-sebastian** [comment]
I don't think we will be able to solve this issue without logging. If you do see this again and are able to provide logs, please respond to this issue and we will work with you to resolve it.

**Comment by leeor** [comment]
Understood. However, I refactored my code to use `WriteBatch` instead after seeing that `transaction.runTransaction` is costing me anywhere between 250ms and 600ms in my Cloud Run service. I recorded the time just before the call, and again first thing inside the callback.

**Comment by schmidt-sebastian** [comment]
The transaction runner makes an RPC to obtain a transaction ID before invoking the user callback.
