### ISSUE TITLE
startAfter, bug???

### ISSUE THREAD

**Issue by angelru** [googleapis/nodejs-firestore#1223]
## Environment details

  - OS:
  - Node.js version: 12.18.0
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.8.1

I am using this query:

```
let query= db.collection(result.firstCollection)
            .doc(result.userId)
            .collection(result.collection)
            .orderBy("Id");

        if (result.lastVisibleDocument !== null) {
            query= query.startAfter(result.lastVisibleDocument)
        }
       let documentSnapshots = await query.limit(30).get();
```

   documents have an id field and its value (id Firebase)

pagination works well with any lastVisibleDocument (firebase id), but if for example I put any value "gg" it returns result, is it because some id contains gg ?, if the id "gg" does not exist, it should not return anything, I don't understand it

#### Steps to reproduce

  1. ?
  2. ?

**Comment by schmidt-sebastian** [comment]
@angelru Thanks for filing this.

If I understand correctly, you expect to get no results if you start your cursor at a non existing value. If you declare a query as such `query.orderBy('id').startAfter('gg')` it will return all documents that contain a value for the 'id' field that sorts after 'gg' (such as 'hh'). There doesn't have to be a document with an id of 'gg'.

This is working as intended. If this is not working for you, we can re-open this issue and discuss possible solutions. Thank you@
