### ISSUE TITLE
Extending existing Generic support.

### ISSUE THREAD

**Issue by Ranguna** [googleapis/nodejs-firestore#1231]
The Transaction class found in https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L309, allows the user to provide a type to describe a Document. But in some other methods, we do not have this ability, ex: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L190 and https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L199.

To make things consistent and greatly improve compile time type safety and autocompletion (even if firestore does not provide type safety as noted in #109 ), it would be good to extends the currently existing Generic support. The use case of no compile time type safety should still be supported for those that do not want to use it.

The following use case is not supported:
```ts
interface Doc {
  name: string;
}

var batch = admin.firestore().batch();

// Set the value of 'NYC'
var nycRef = admin.firestore().collection("cities").doc("NYC");
batch.set<Doc>(nycRef, {name: "New York City"});
```
This fails with the following error:
```
Argument of type 'DocumentReference<DocumentData>' is not assignable to parameter of type 'DocumentReference<Doc>'.
```

This should be possible:
```ts
interface Doc {
  name: string;
}

var batch = admin.firestore().batch();

// Set the value of 'NYC'
var nycRef = admin.firestore().collection<Doc>("cities").doc("NYC");
// or: var nycRef = admin.firestore().collection("cities").doc<Doc>("NYC");
batch.set<Doc>(nycRef, {name: "New York City"});
```

**Comment by Ranguna** [comment]
Also found a bug in the functions getting started docs. Here's the complete code from https://firebase.google.com/docs/functions/get-started:

```ts
// The Cloud Functions for Firebase SDK to create Cloud Functions and setup triggers.
const functions = require('firebase-functions');

// The Firebase Admin SDK to access Cloud Firestore.
const admin = require('firebase-admin');
admin.initializeApp();

// Take the text parameter passed to this HTTP endpoint and insert it into 
// Cloud Firestore under the path /messages/:documentId/original
exports.addMessage = functions.https.onRequest(async (req, res) => {
  // Grab the text parameter.
  const original = req.query.text;
  // Push the new message into Cloud Firestore using the Firebase Admin SDK.
  const writeResult = await admin.firestore().collection('messages').add({original: original});
  // Send back a message that we've succesfully written the message
  res.json({result: `Message with ID: ${writeResult.id} added.`});
});

// Listens for new messages added to /messages/:documentId/original and creates an
// uppercase version of the message to /messages/:documentId/uppercase
exports.makeUppercase = functions.firestore.document('/messages/{documentId}')
    .onCreate((snap, context) => {
      // Grab the current value of what was written to Cloud Firestore.
      const original = snap.data().original;

      // Access the parameter `{documentId}` with `context.params`
      console.log('Uppercasing', context.params.documentId, original);
      
      const uppercase = original.toUpperCase();
      
      // You must return a Promise when performing asynchronous tasks inside a Functions such as
      // writing to Cloud Firestore.
      // Setting an 'uppercase' field in Cloud Firestore document returns a Promise.
      return snap.ref.set({uppercase}, {merge: true});
    });
```

Here's the same code with a very basic typing:
```ts
import * as functions from "firebase-functions";
import * as admin from "firebase-admin"

admin.initializeApp();

interface Message {
  original: string;
  uppercase?: string;
}

exports.addMessage = functions.https.onRequest(async (req, res) => {
    // Grab the text parameter.
    const original = req.query.text;
    // Push the new message into Cloud Firestore using the Firebase Admin SDK.
    const writeResult = await admin.firestore().collection<Message>('messages').add({original});
    // Send back a message that we've succesfully written the message
    res.json({result: `Message with ID: ${writeResult.id} added.`, test: req.query.text, typeof: typeof req.query.text});
  });

exports.makeUppercase = functions.firestore.document('/messages/{documentId}')
    .onCreate<Message>((snap, context) => {
      // Grab the current value of what was written to Cloud Firestore.
      const original = snap.data().original;

      // Access the parameter `{documentId}` with `context.params`
      console.log('Uppercasing', context.params.documentId, original);

      const uppercase = original.toUpperCase();

      // You must return a Promise when performing asynchronous tasks inside a Functions such as
      // writing to Cloud Firestore.
      // Setting an 'uppercase' field in Cloud Firestore document returns a Promise.
      return snap.ref.set({uppercase}, {merge: true});
    });
```

With the changes in #1232, this code will fail to compile with the following error:
```
Type 'string | ParsedQs | string[] | ParsedQs[] | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```
This happens because the prop `original` should be a string, or at least an object with a prop named `toUpperCase`, since that'll be used in the `makeUppercase` function.

If you deploy that code (or run it locally) and call the `addMessage` endpoint with the the following query params: `?text[]=text1&text[]=test2`, the `makeUppercase` function will fail at run time with this error:
```
TypeError: original.toUpperCase is not a function
```
This also fails by simply not providing query params:
```
Error: Value for argument "data" is not a valid Firestore document. Cannot use "undefined" as a Firestore value (found in field "original"). If you want to ignore undefined values, enable `ignoreUndefinedProperties`.
```

Both of these bugs are easily caught by simply using interfaces/types to describe the documents.

**Comment by schmidt-sebastian** [comment]
@Ranguna Thanks for filing this issue!

As you mention, the change you proposed does not provide any type safety. We have been opposed to adding this support and have instead added converter support to the SDK,  which allows you to instantiate your own objects instances (which then satisfy an `instanceof` check). Simply casting to `Doc` exposes you a type that in the best case doesn't offer any methods and lacks a prototype, and in the worst case case doesn't even match the type's properties.

To fix your example, you would do something like this:

```
var nycRef = admin.firestore().collection("cities").doc("NYC").withConverter(...);
batch.set(nycRef, {name: "New York City"});
```

As for your sample, the sample you provided above seems to use the wrong type for `original`. If you want to use explicit types, you will have to check that `req.query.text` before assigning. Note that this is not needed with untyped collections, but would also be needed if you used `withConverter`.

Sorry for being so strict on this.

**Comment by Ranguna** [comment]
If we can't have this, what's the reason for it to be included in the `Transaction` class ?

> As for your sample, the sample you provided above seems to use the wrong type for original

Exactly my point. It as the wrong type but we can't see that if we don't use generics like this. The code in the getting started page has a bug that is easily caught if we use generics.

**Comment by schmidt-sebastian** [comment]
The Transaction class accepts typed DocumentReferences that are created with DocumentReference.withConverter(). While `DocumentReference.withConverter({ toFirestore: (_:Doc) => DocumentData, fromFirestore: (_:DocumentData) => Doc})` corresponds to the same `DocumentReference<Doc>` type as manually typing just `DocumentReference<Doc>`, the former provides proper typing support while the latter is not a supported use cast. This cast is unfortunately something we cannot prevent using the current type system (but would have liked to).

**Comment by reyawn** [comment]
> As you mention, the change you proposed does not provide any type safety. We have been opposed to adding this support and have instead added converter support to the SDK, which allows you to instantiate your own objects instances (which then satisfy an `instanceof` check). Simply casting to `Doc` exposes you a type that in the best case doesn't offer any methods and lacks a prototype, and in the worst case case doesn't even match the type's properties.

Agreed that this provides proper typing support _if you use classes_ to represent the database entities.  If the library is being used in a more functional manner (without classes!) then this can be viewed as introducing an unnecessary layer of code just to add typings. :man_shrugging:

**Comment by Ranguna** [comment]
@reyawn Well, the thing is that we don't have type validations on the firestore side, so we really do need the converter for this. A value in firestore can be changed from a number to a string without any problems and if we use interfaces to represent document structures, the field that changed from string to number would invalidate the whole idea of type safety.

The `withConverter` method allows us to do runtime type checking on the consumer side. This way, we can actually assure that the fields we are getting from firestore have the proper types by simply checking the result of `typeof` for each field, throwing in the case of type missmatch.

**Comment by Fleker** [comment]
I see this has come up a few times and I want to offer my own experience and feedback on the Firestore Node.js SDK. In my use-case, I have a number of various Firestore collections and documents which I strictly control from Cloud Functions. I use these functions as an intermediary step to do the type validation before setting or updating a document.

In this way I do not do any runtime type checking because I'm able to guarantee the types of my database. Despite this, I still have to do quite a bit of manual casting:

```typescript
const myDoc = await admin.firestore().collection(...).doc(...).get()
const myData = myDoc.data() as MySchema
```

Of course this works in my application but provides no developer productivity, particularly around modifications to the data.

```typescript
await myDoc.set(myData) // How do I know the fields are correct here?
await myDoc.update({ ... }) // Now there is even less validation
```

The suggestion of using the [`withConverter`](https://firebase.google.com/docs/reference/js/firebase.firestore.FirestoreDataConverter) seems overly complicated for my use-case, as the schemas I'm using are meant to directly reflect the database schema and would end up as a bunch of Typescript interfaces.

Additionally, the `withConverter` method only seems to be applied to setting the object as a whole and not updates. In my application I have a lot of update operations on a subset of a document's fields and could benefit from type-safety.

```typescript
interface Schema {
    x: string
}

const testConverter: FirebaseFirestore.FirestoreDataConverter<Schema> = {
  toFirestore(randomData: Schema): any {
    return {x: randomData.x};
  },
  fromFirestore(
    data: any
  ): Schema {
    return {x: data.x}
  }
};

const myDoc = await db.collection('collection').doc('doc').withConverter(testConverter).get()
const myData = myDoc.data() // Correctly a Schema type
await myDoc.set({ y: 'foo' }) // Correctly throws a type error
await myDoc.update({ y: 'foo' }) // Incorrectly ignores type error
```

This problem also exists in transactions:

```typescript
const doc = await transaction.get(db.collection('collection').doc('doc').withConverter(testConverter))
await transaction.set(doc.ref, {y: 'foo' }) // Correctly throws a type error
await transaction.update(doc.ref, {y: 'foo' }) // Incorrectly ignores type error
```

By setting generics on each of the methods, it would at least bring some type-safety on the update method calls. You can wrap in the [`Partial` type](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype) to make fields optional:

```typescript
interface MySchema {
  required: string
  optional?: number
}

class DocumentReference {
  data<T>() {
    return {} as T
  }

  set<T>(p: T) {
    return p.toString()
  }

  update<T>(p: Partial<T>) {
    return p.toString()
  }
}

const foo = new DocumentReference()
const data = foo.data<MySchema>() // Casts to a particular interface without the need of boilerplate code
data.required = 'Some new value'
foo.set<MySchema>({
  required: data.required // Mandated by type-safety
})
foo.set({foo: 'bar'}) // No type means anything goes

foo.update<MySchema>({}) // Nothing needs to be required here
foo.update<MySchema>({
  foo: 'bar' // But this still throws a type error.
})
```

This also is great for developer environments that can use auto-complete to match fields.

I'd advocate for extending generic support for the additional type-safety in these areas. Doing it in a way like I show in the snippet above would preserve backwards compatibility while improving developer productivity.

![Screen Shot 2021-05-06 at 4 17 12 PM](https://user-images.githubusercontent.com/3291635/117363364-7d8c5200-ae8a-11eb-822d-fd7a6e2080fb.png)
![Screen Shot 2021-05-06 at 4 17 37 PM](https://user-images.githubusercontent.com/3291635/117363366-7e24e880-ae8a-11eb-97b3-1c4e471e5ae9.png)

**Comment by joaqcid** [comment]
looks like we need to write a type-safe wrapper around firebase-admin ...
