### ISSUE TITLE
Use strings instead of numeric error codes (to align with other firebase SDKs)

### ISSUE THREAD

**Issue by theochampion** [googleapis/nodejs-firestore#1239]
Hey there,

I'm using firestore from `firebase-admin` in my cloud-functions and I noticed that this package uses numeric error codes instead of the string format used in other SDKs (e.g. in the `firebase-js-sdk` https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/util/error.ts#L27).

Is there a way to get the mapping from the numeric code to the string format ?

This would allow better integration with other firebase sdks. For example, this would allows to easily return firebase errors as `HttpsError`from the `firebase-functions` package:

```typescript
  try {
    // add vote to firestore
    await PostService.createVote(postId, context.auth.uid, vote);
  } catch (error) {
    console.log(error);
    throw new functions.https.HttpsError(error.code, error.message);
  }
```

It would just have to switch from the current 

```typescript
{
  code: number,
  details: string
}
```

to

```typescript
{
  code: 'ok' | 'cancelled' | 'unknown' | 'invalid-argument' | 'deadline-exceeded' | 'not-found' | 'already-exists' | 'permission-denied' | 'resource-exhausted' | 'failed-precondition' | 'aborted' | 'out-of-range' | 'unimplemented' | 'internal' | 'unavailable' | 'data-loss' | 'unauthenticated',
  message: string
}
```

note: the `details` field is renamed to `message` to align with other firebase SDKs.

I've considered doing the mapping myself but I think this would be a great addition to the SDK itself.

What do you guys think ? 

Happy to help if needed :)

**Comment by schmidt-sebastian** [comment]
@theochampion Thanks for chiming in! 

Unfortunately, we are mostly a GCloud Server SDKs that tries to do the right thing for Firebase users. Our error codes are directly returned from the libraries that drive all GCloud SDKs, which use the error codes throughout. To maintain compatibility with the GCloud ecosystem, we will likely continue to return their error codes.

We do provide a mapping for what these errors mean in our type file: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L1559

**Comment by theochampion** [comment]
Thanks for your reply @schmidt-sebastian 

I digged a bit more. It seems that the `GrpcStatus` enum you are referencing is not exported in `firebase-admin`. I therefore had to copy it and make convertion util function:

(if you see anything improvable in that solution, I'm all ears 😉 )

```typescript
/**
 * Status codes returned by Firestore's gRPC calls.
 * from: https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L1559
 */
enum GrpcStatus {
  OK = 0,
  CANCELLED = 1,
  UNKNOWN = 2,
  INVALID_ARGUMENT = 3,
  DEADLINE_EXCEEDED = 4,
  NOT_FOUND = 5,
  ALREADY_EXISTS = 6,
  PERMISSION_DENIED = 7,
  RESOURCE_EXHAUSTED = 8,
  FAILED_PRECONDITION = 9,
  ABORTED = 10,
  OUT_OF_RANGE = 11,
  UNIMPLEMENTED = 12,
  INTERNAL = 13,
  UNAVAILABLE = 14,
  DATA_LOSS = 15,
  UNAUTHENTICATED = 16,
}

const GrpcStatusToStringMap: { [key in GrpcStatus]: string } = {
  [GrpcStatus.OK]: 'ok',
  [GrpcStatus.CANCELLED]: 'cancelled',
  [GrpcStatus.UNKNOWN]: 'unknown',
  [GrpcStatus.INVALID_ARGUMENT]: 'invalid-argument',
  [GrpcStatus.DEADLINE_EXCEEDED]: 'deadline-exceeded',
  [GrpcStatus.NOT_FOUND]: 'not-found',
  [GrpcStatus.ALREADY_EXISTS]: 'already-exists',
  [GrpcStatus.PERMISSION_DENIED]: 'permission-denied',
  [GrpcStatus.RESOURCE_EXHAUSTED]: 'resource-exhausted',
  [GrpcStatus.FAILED_PRECONDITION]: 'failed-precondition',
  [GrpcStatus.ABORTED]: 'aborted',
  [GrpcStatus.OUT_OF_RANGE]: 'out-of-range',
  [GrpcStatus.UNIMPLEMENTED]: 'unimplemented',
  [GrpcStatus.INTERNAL]: 'internal',
  [GrpcStatus.UNAVAILABLE]: 'unavailable',
  [GrpcStatus.DATA_LOSS]: 'data-loss',
  [GrpcStatus.UNAUTHENTICATED]: 'unauthenticated',
};

export const grpcErrorCodeToString = (code: number) => {
  try {
    return GrpcStatusToStringMap[code as GrpcStatus];
  } catch (err) {
    return GrpcStatusToStringMap[GrpcStatus.INTERNAL];
  }
};
```

**Comment by schmidt-sebastian** [comment]
@hiranya911 Can we add this enum to the Firebase Admin types?
