### ISSUE TITLE
Please add a link to the release notes

### ISSUE THREAD

**Issue by npomfret** [googleapis/nodejs-firestore#1244]
I think it might be a good idea to add a link in the [README.md](https://github.com/googleapis/nodejs-firestore/blob/master/README.md) to the release notes.  There has been a major version bump and we need to know what's changed.  Inferring it from the commit history isn't ideal.

**Comment by schmidt-sebastian** [comment]
@npomfret We can do so - but to help you out right now please take a look at https://github.com/googleapis/nodejs-firestore/blob/master/CHANGELOG.md

**Comment by npomfret** [comment]
thanks

**Comment by laljikanjareeya** [comment]
Fixed by #1278
