### ISSUE TITLE
Make it possible to use read-only transactions

### ISSUE THREAD

**Issue by dgay42** [googleapis/nodejs-firestore#1245]
The runTransaction call creates a read-write transaction that acquires locks on the data. This is a problem when the transaction is both long-lived (so would hold locks for a long time) and reads a lot of data (or data which is frequently written), as it will delay concurrent writes.

The Firestore API offers read-only transactions as an alternative. These do not acquire locks and do not impact writes.

A plausible way to add these is to add a 'read-only' option to runTransaction, or to add a runReadOnlyTransaction call.

**Comment by schmidt-sebastian** [comment]
@dgay42 Thanks for this feature request. We just added read-only transaction to the Java client. I don't know if we have bandwidth to add it to the Node client anytime soon, but we would be willing to accept contributions.

**Comment by manwithsteelnerves** [comment]
Can someone explain how read-only transactions are different from batchGetDocuments?

**Comment by schmidt-sebastian** [comment]
There are three differences:
- You can use queries.
- You can issue multiple requests, e.g. fetch some documents and then based on that data fetch more documents.
- You can set a readTime that is in the past (up to 60s). This is also supported by BatchGetDocumnents, but not exposed via the SDK.
