### ISSUE TITLE
Regression: firestore.FieldValue.arrayRemove triggers "Element at index 0 is not a valid array element. Nested arrays are not supported."

### ISSUE THREAD

**Issue by yeldarby** [googleapis/nodejs-firestore#1259]
#### Environment details

  - OS: MacOS Catalina 10.15.5
  - Node.js version: 12.18.0
  - npm version: 6.14.4
  - `@google-cloud/firestore` version: 3.8.6

#### Steps to reproduce

We just upgraded from `firebase-admin` 8.9.1 to the current version, 8.13.0 which upgraded `@google-cloud/firestore` from 3.4.0 to 3.8.6 and are getting a new error when using `firestore.FieldValue.arrayRemove`.

Previously we could do this:
```
ref.update({
    datasets: admin.firestore.FieldValue.arrayRemove("someDataset"),
    versions: admin.firestore.FieldValue.arrayRemove("someVersion")
})
```

But in the new version this triggers a validation error: 
```
(node:92754) UnhandledPromiseRejectionWarning: Error: Element at index 0 is not a valid array element. Nested arrays are not supported.
>      at validateArrayElement (/Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/field-value.js:426:15)
>      at ArrayRemoveTransform.validate (/Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/field-value.js:398:13)
>      at /Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/document.js:783:56
>      at Map.forEach (<anonymous>)
>      at DocumentTransform.validate (/Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/document.js:783:25)
>      at WriteBatch.update (/Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/write-batch.js:379:19)
>      at DocumentReference.update (/Users/yeldarb/Code/roboflow/app/functions/node_modules/@google-cloud/firestore/build/src/reference.js:377:14)
>      at /Users/yeldarb/Code/roboflow/app/functions/token.js:1122:32
```

Wrapping it in an array like `admin.firestore.FieldValue.arrayRemove(["someString"])` doesn't seem to work either.

**Comment by schmidt-sebastian** [comment]
@yeldarby Do you mind providing a full code snippet? The error message you are seeing is guarded by Array.isArray: https://github.com/googleapis/nodejs-firestore/blob/56355f1c83b055fdbd3ed47e069df813696a1fc0/dev/src/field-value.ts#L530

As such, I cannot explain why we would throw this error for a string.

**Comment by yeldarby** [comment]
Ahhh, looks like it wasn't the string that was causing it but the array. This repros the issue and succeeds with 3.4.0 but throws with 3.8.6:

```
var admin = require("firebase-admin");
var serviceAccount = require(__dirname + "/firebase-key.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://rf-fieldvalue-bug.firebaseio.com"
});

var db = admin.firestore();

var doc = db.collection("test").doc();
doc.set({
    one: ["abc", "def", "ghi"],
    two: ["jkl", "mno", "pqr"]
}).then(function() {
    doc.update({
        one: admin.firestore.FieldValue.arrayRemove("def"),
        two: admin.firestore.FieldValue.arrayRemove(["mno", "pqr"])
    }).then(function() {
        doc.get().then(function(snapshot) {
            console.log(snapshot.data());
        });
    });
});
```

Although it looks like it was not producing the behavior I expected in 3.4.0; it was just failing silently: `{ two: [ 'jkl', 'mno', 'pqr' ], one: [ 'abc', 'ghi' ] }`

Appears the expected syntax was supposed to be `admin.firestore.FieldValue.arrayRemove("mno", "pqr")` all along.
