### ISSUE TITLE
Huge latency for non-existing documents (5secs!!!)

### ISSUE THREAD

**Issue by manwithsteelnerves** [googleapis/nodejs-firestore#1269]
#### Environment details

  - Node.js version: 10
  - npm version:
  - `@google-cloud/firestore` version: 4.1.1

#### Steps to reproduce

  1. Try requesting a non-existing id in collection
  2. Observe the delays being in the range of 5secs!

![Screenshot 2020-07-21 at 6 59 18 PM](https://user-images.githubusercontent.com/5437614/88066935-ff292280-cb8b-11ea-9780-710271232772.png)

Thanks!

**Comment by schmidt-sebastian** [comment]
@manwithsteelnerves Thanks for filing this issue.

Two questions: 
- Is this reproducible for you?
- Does this also occur if you issue other requests beforehand? 

If so, we probably need to ask you to file a customer support ticket.

**Comment by schmidt-sebastian** [comment]
I checked with the backend team - they say this should not happen for single document lookups. I also see in the trace you provided above that you got a `503` from the backend, which means that the server was not able to process your request at the time. Unfortunately, we will not be able to look at this further without looking at your project and associated logs. To allow for this, you need to file a support ticket: https://cloud.google.com/support-hub
