### ISSUE TITLE
fails to connect to emulator started through gcloud sdk docker image

### ISSUE THREAD

**Issue by jeantil** [googleapis/nodejs-firestore#1296]
1) Is this a client library issue or a product issue?

I'm not entirely sure but couldn't find a better place to file the issue.

2) Did someone already solve this?
after a couple days of searching, I was unable to find an existing bug or solutoin in https://github.com/googleapis/nodejs-firestore/issues,  https://github.com/googleapis/google-cloud-node or http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js but considering the sheer volume of these sources I may have missed it. If so I apologize in advance

#### Environment details

  - OS: Ubuntu 20.04.1 LTS
  - Node.js version: v12.18.3
  - npm version: 6.14.6
  - `@google-cloud/firestore` version: 4.2.0

#### Steps to reproduce

  1. clone https://github.com/jeantil/diggin-firebase-admin
  2. run npm install
  3. start gcloud sdk emulator through docker image: ` docker run --rm -p 8080:8080  google/cloud-sdk gcloud beta emulators firestore start --host-port=127.0.0.1:8080`
  4. run the test case : `DEBUG="digin:*" node_modules/.bin/babel-node firestore.js`

When the test case works, it will display 
```
  digin:firebase:admin start +0ms
  digin:firebase:admin trying to connect to firebase on localhost:8080 +2ms
Entered new data into the document
Updated an existing document
Read the document
Deleted the document
```
if it fails, it will display 
```
  digin:firebase:admin start +0ms
  digin:firebase:admin trying to connect to firebase on localhost:8080 +1ms
watchdog timed out!
```

I am unsure what is failing exactly but I had an older docker image (custom made based on firebase-tools) which contains the cloud-firestore-emulator-v1.9.0.jar and running this version of the emulator works consistently and running agains an image which contains cloud-firestore-emulator-v1.11.7.jar fails.

I was unable to find a repository/issue tracker for cloud-firestore-emulator and this repository seemed to be the next best thing. If this is not the place, i'll be happy to take a pointer !

**Comment by crwilcox** [comment]
@schmidt-sebastian can you include emulator folks? it seems a recent release may be interfering with the client?

**Comment by schmidt-sebastian** [comment]
@yuchenshi Does this ring a bell?

**Comment by yuchenshi** [comment]
We haven't really changed the listener logic recently and I'm curious what is going on here. I know it's hard to debug connectivity issues, but could you please try these things:

1. Use `curl` to check if you can connect to the emulator inside AND outside Docker. (e.g. `docker exec` may help for "running in the docker". Try also `netstat -l` and compare the output.
2. Try changing `--host-port=127.0.0.1:8080` to `--host-port=0.0.0.0:8080` and repeat 1.

That should get us started on this.

**Comment by jeantil** [comment]
@yuchenshi thanks for the pointers, here are the results I observe for the various commands requested 

## using `--host-port=127.0.0.1:8080`

```
> docker run --rm -p 8080:8080 google/cloud-sdk gcloud beta emulators firestore start --host-port=127.0.0.1:8080
Executing: /usr/lib/google-cloud-sdk/platform/cloud-firestore-emulator/cloud_firestore_emulator start --host=127.0.0.1 --port=8080
[firestore] API endpoint: http://127.0.0.1:8080
[firestore] If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
[firestore] 
[firestore]    export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080
[firestore] 
[firestore] Dev App Server is now running.
[firestore] 
^Y[firestore] Sep 23, 2020 7:53:25 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[firestore] INFO: Detected non-HTTP/2 connection.

```
### from host 
```
> docker ps                                                                                                                                                                                    
CONTAINER ID        IMAGE                              COMMAND                  CREATED              STATUS              PORTS                     NAMES
ea68b3d3cfbf        google/cloud-sdk                   "gcloud beta emulato…"   About a minute ago   Up About a minute   0.0.0.0:8080->8080/tcp    blissful_dewdney
```
* curl 
```
> curl http://127.0.0.1:8080                                                                                                                                                                   
curl: (56) Recv failure: Connection reset by peer
```
* netstat (which has been replaced by the `ss` command)
```
> sudo ss -ltpn | grep 8080                                                                                                                                                                     
LISTEN   0        4096                        *:8080                   *:*       users:(("docker-proxy",pid=426827,fd=4))
```
* provided sample
```
DEBUG="digin:*" node_modules/.bin/babel-node firestore.js                                                                                                                                     
  digin:firebase:admin trying to connect to firebase on localhost:8080 +0ms
watchdog timed out!
```

### from container 
```
 docker exec -it blissful_dewdney /bin/bash 
```
* curl 
```
root@ea68b3d3cfbf:/# curl http://127.0.0.1:8080 
Ok
```
* netstat (which has been replaced by the `ss` command)
```
root@ea68b3d3cfbf:/# ss -ltpn
State                    Recv-Q                   Send-Q                                       Local Address:Port                                        Peer Address:Port                                                                    
LISTEN                   0                        4096                                             127.0.0.1:32955                                            0.0.0.0:*                       users:(("java",pid=40,fd=96))                   
LISTEN                   0                        50                                               127.0.0.1:37861                                            0.0.0.0:*                       users:(("java",pid=40,fd=44))                   
LISTEN                   0                        4096                                             127.0.0.1:8080                                             0.0.0.0:*                       users:(("java",pid=40,fd=97))                   
```

## using `--host-port=0.0.0.0:8080`
```
> docker run --rm -p 8080:8080 google/cloud-sdk gcloud beta emulators firestore start --host-port=0.0.0.0:8080                                                                                 
Executing: /usr/lib/google-cloud-sdk/platform/cloud-firestore-emulator/cloud_firestore_emulator start --host=0.0.0.0 --port=8080
[firestore] API endpoint: http://0.0.0.0:8080
[firestore] If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
[firestore] 
[firestore]    export FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
[firestore] 
[firestore] Dev App Server is now running.
[firestore] 
```

### from host
```
docker ps                                                                                                                                                                                     
CONTAINER ID        IMAGE                              COMMAND                  CREATED             STATUS              PORTS                     NAMES
e4172f6a312d        google/cloud-sdk                   "gcloud beta emulato…"   56 seconds ago      Up 54 seconds       0.0.0.0:8080->8080/tcp    reverent_ishizaka
```
*  curl 
```
curl http://127.0.0.1:8080                                                                                                                                                                    
Ok
```
* netstat (aka ss)
```
sudo ss -ltpn | grep 8080                                                                                                                                                                     
LISTEN   0        4096                        *:8080                   *:*       users:(("docker-proxy",pid=428377,fd=4))           
```
* provided sample
tried with both `localhost:8080` and `127.0.0.1:8080` for `process.env.FIRESTORE_EMULATOR_HOST` same failure
```
DEBUG="digin:*" node_modules/.bin/babel-node firestore.js                                                                                                                                     
  digin:firebase:admin trying to connect to firebase on 127.0.0.1:8080 +0ms
watchdog timed out!
```

### from container 
```
 docker exec -it reverent_ishizaka /bin/bash  
```
* curl 
```
root@e4172f6a312d:/# curl http://127.0.0.1:8080
Ok
```
* netstat (which has been replaced by the `ss` command)
```
root@e4172f6a312d:/# ss -lntp 
State                    Recv-Q                   Send-Q                                       Local Address:Port                                        Peer Address:Port                                                                    
LISTEN                   0                        4096                                               0.0.0.0:8080                                             0.0.0.0:*                       users:(("java",pid=40,fd=97))                   
LISTEN                   0                        4096                                               0.0.0.0:40849                                            0.0.0.0:*                       users:(("java",pid=40,fd=96))                   
LISTEN                   0                        50                                                 0.0.0.0:43897                                            0.0.0.0:*                       users:(("java",pid=40,fd=44))                   
```

## Misc

Using the second setup `--host=0.0.0.0:8080` the `admin.js` test case actually works whereas the `firestore.js` sample doesn't work, this points to a possible issue with the firestore sample, since it is really very simple and mostly lifted from examples in the documentation it could be that  "@google-cloud/firestore" doesn't pick up the `FIRESTORE_EMULATOR_HOST` env variable by itself.

**Comment by BenWhitehead** [comment]
Alternatively you can try using host networking when you launch the docker containers so that you aren't having to traverse a network interface.
The command would change to be
```bash
docker run -it --net=host google/cloud-sdk gcloud beta emulators firestore start --host-port=127.0.0.1:8080
```

Then the emulator would bind to the same localhost as your host system.

**Comment by jeantil** [comment]
@BenWhitehead using `--net=host` results in a successful `curl` command when using `--host-port=127.0.0.1:8080` admin.js  sample does work, firestore.js still fails :(

**Comment by jeantil** [comment]
`firestore.js` is a slightly improved version of the example in the README (I switched from console to debug and added  a timeout to have faster feedback)

**Comment by yuchenshi** [comment]
@jeantil Just to make sure, does `export FIRESTORE_EMULATOR_HOST=127.0.0.1:8080` work when you actually set it to listen to `0.0.0.0`? The SDKs may not like `0.0.0.0` as the destination host since that would be unrouteable. If that's the case, we can fix the message printed by the Firestore emulator on output.

**Comment by schmidt-sebastian** [comment]
Closing this due to lack of update. @jeantil feel free to ping us and we can re-open.
