### ISSUE TITLE
Improve the types for Query.select

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-firestore#1299]
Currently `Query.select` returns a `Query<T>`. However, by specifying the fields we are interested in, we break the guarantee that the returned documents will be of type `T`.

https://github.com/googleapis/nodejs-firestore/blob/786e52f8c8b7b9c6b84ffc988190470a063d5855/dev/src/reference.ts#L1293

I think that instead, the return type should be set to `Query<DocumentData>`

**Comment by schmidt-sebastian** [comment]
That's correct. Thanks for catching.
