### ISSUE TITLE
Typescript - allow specifying doc data type with `Firestore.collection()` etc

### ISSUE THREAD

**Issue by rh389** [googleapis/nodejs-firestore#1325]
**Is your feature request related to a problem? Please describe.**
`CollectionRef` is now typed as a generic, which is helpful, but the `new Firestore().collection()` method always returns `CollectionRef<DocumentData>`, which requires developers to type-assert in a way that could be unsafe, or miss out on the benefits of the generic type.

 **Describe the solution you'd like**
It should be (optionally) possible to specify this type eg `collection<MyData>('myCollection')`.

The same applies to the top-level `doc()`, `collectionGroup()` and `getAll()` APIs.

**Comment by thebrianchen** [comment]
@rh389 Thanks for filing this issue!

Firestore's generic support is supported by the user-provided converter that converts user classes into Firestore's `DocumentData`. Exposing generics at the top-level without requiring a converter would provide a generic that doesn't guarantee type safety or provide methods the way a converter would.

From the top level, you can still get generic support by adding a converter immediately afterwards:
```typescript
const cityConverter: FirestoreDataConverter<City> = {...};
const typedCollection: Collection<City> = admin
      .firestore()
      .collection('cities')
      .withConverter(cityConverter);
```

Please see #1231 for a related issue with more context.

**Comment by rh389** [comment]
Hmm, I see - I didn't realise these generics were only intended to be used in conjunction with a runtime converter.

I guess I can see the rationale for not allowing this kind of casting without some runtime check, although IMO when the data is tightly controlled on the way in, it wouldn't be unreasonable to assert types without runtime-checking every doc retrieved.

Anyway, thanks for your prompt response and clarification 👍
