### ISSUE TITLE
not-in operator is not accepted in firestore collection query

### ISSUE THREAD

**Issue by sebitoelcheater** [googleapis/nodejs-firestore#1345]
#### Environment details

  - OS: macOS Catalina
  - Node.js version: v12.18.4
  - npm version: 6.14.8
  - `@google-cloud/firestore` version: ^4.4.0

#### Steps to reproduce

Write a query with `'not-in'` operator
Example:
```
const triggers = await admin.firestore().collection('triggers').where('id', 'not-in', []).get();
```
This exception is raised:
```
Error: Value for argument "opStr" is invalid. Acceptable values are: <, <=, ==, >, >=, array-contains, in, array-contains-any
```
According to the [documentation](https://firebase.google.com/docs/firestore/query-data/queries#in_not-in_and_array-contains-any), `'not-in'` should work.

**Comment by thebrianchen** [comment]
@sebitoelcheater Can you verify that you are on 4.4.0? You can do so by enabling logging, which should show the version number, or by verifying using `npm list`.

I've tried reproducing it on my end without success. Empty arrays are not allowed with `in` or `not-in` queries, so I'm getting an INVALID_ARGUMENT error when I run that line of code.

**Comment by sebitoelcheater** [comment]
@thebrianchen I hand't updated `firebase-admin`, my bad. Solved now, Thanks @thebrianchen!
