### ISSUE TITLE
WriteResults in runTransaction

### ISSUE THREAD

**Issue by rgmax422** [googleapis/nodejs-firestore#1349]
We realized the `commit()` function in the transaction class doesn't return `WriteResults` coming from internal `_writeBatch`. We are using the `WriteResult` return in regular `create`, `update`, `set`, and `delete` operations in our logic and need to have it in transactions too. Please check the following snippet which fully covers our need. Thanks.

```javascript
commit(): Promise<void> {
    return this._writeBatch
      ._commit({
        transactionId: this._transactionId,
        requestTag: this._requestTag,
      })
      .then(writeResults => { this.writeResults = writeResults });
  }
```

**Comment by schmidt-sebastian** [comment]
The `runTransaction` API that serves as an entry point into the transaction returns the result of the user-provided Transaction callback, which matches the Transaction APIs in the Mobile SDKs for Firestore. As we can only return one value, we will not be able to change the API to return a WriteResult without breaking our users. If you are able, I would recommend to use the `WriteBatch` API, which does return a WriteResult and still provides atomic results. This will however not work if your transactions involve reads.

We can re-consider this if there is significant demand from other users, but for now I don't think this is something we can address directly.

**Comment by rgmax422** [comment]
@schmidt-sebastian thanks for your quick response. As I mentioned, there is no need to change the returned value by `runTransaction` API. It would be good enough if you attach the `WriteResults` to the transaction instance (please check the snippet) which actually is not a breaking change.

**Comment by schmidt-sebastian** [comment]
The `commit` function is not meant to be part of the public API. If you really want to use it, and if changing the return type helps, then we can accept a PR. Please do bear in mind that we might change the implementation at a later point, as we are only committing to the API that is exposed via our API documentation.
