### ISSUE TITLE
Update throws error with top level undefined when ignoreUndefinedProperties is set

### ISSUE THREAD

**Issue by leandro-manifesto** [googleapis/nodejs-firestore#1359]
Calling `.update()` with a data object that contains `undefined` in the top level fields is throwing an error when `ignoreUndefinedProperties` is set.

I tracked it to the `validateFieldValue` function on `write-batch.ts` that calls `validateUserInput` without a `level` parameter to inform that the value being validated is already 1 level deep.

https://github.com/googleapis/nodejs-firestore/blob/dc94946f261db527f913d1ff89a2572cd9539f70/dev/src/write-batch.ts#L841-L854

I also noticed that the test that should catch this doesn't test for a top level field with `undefined`.

https://github.com/googleapis/nodejs-firestore/blob/dc94946f261db527f913d1ff89a2572cd9539f70/dev/test/ignore-undefined.ts#L90-L115

#### Code to reproduce
```typescript
const firestore = new Firestore({
  ignoreUndefinedProperties: true,
});

const col = firestore.collection('collection');
const doc = col.doc('uid');

await doc.update({
  required: 'string',
  optional: undefined,
});
```

#### Environment details
  - OS: Ubuntu 20.04 on WSL 2 on Windows 10 19041.572
  - `node` version: 14.14.0
  - `yarn` version: 1.22.5
  - `@google-cloud/firestore` version: 4.7.0

**Comment by schmidt-sebastian** [comment]
Thanks for filing this. I will get a fix out for this early next week.
