### ISSUE TITLE
Firestore not updating data in Cloud Function's scheduled function

### ISSUE THREAD

**Issue by ArcherEmiya05** [googleapis/nodejs-firestore#1369]
Good day I have an issue related to Cloud Firestore here is my SO question, please check.

[https://stackoverflow.com/questions/64917106/firebase-firestore-not-updating-data-in-cloud-functions-scheduled-function](url)

**Comment by schmidt-sebastian** [comment]
It looks like this issue was solved as per the last comment in https://stackoverflow.com/questions/64917106/firebase-firestore-not-updating-data-in-cloud-functions-scheduled-function
