### ISSUE TITLE
Upgrading from 4.7.2 to 4.8.0 causes high memory consumption

### ISSUE THREAD

**Issue by miselaytes-anton** [googleapis/nodejs-firestore#1375]
#### Environment details

  - OS: Mac OSX, Catalina
  - Node.js version: v12.18.1
  - npm version: 6.14.5
  - `@google-cloud/firestore` version: 4.8.0

#### Steps to reproduce

After updating @google-cloud/firestore from `4.7.2` to `4.8.0` some of our cloud functions memory usage has grown significantly. See the graph below for an example. After downgrading the version back to `4.7.2` the memory usage went back to normal. Unfortunately I can not provide the steps to reproduce the issue. Would be happy to provide any additional information if needed.

<img width="1062" alt="function_memory_usage_annotated" src="https://user-images.githubusercontent.com/5480808/101496089-9c34fe00-3969-11eb-8baa-da0d1c079c0a.png">

**Comment by crwilcox** [comment]
changes are https://github.com/googleapis/nodejs-firestore/compare/v4.7.2...v4.8.0

Features
Add support to build Firestore bundles (#1365) (bae82dd)
Bug Fixes
stop using GRPC channels after RST_STREAM (#1373) (504bb5f)

**Comment by schmidt-sebastian** [comment]
@miselaytes-anton - Do you recall if you were ever seeing a large number of `RST_STREAM` errors? We changed how we handle clients with RST_STREAM errors, which would increase memory consumption.

**Comment by miselaytes-anton** [comment]
Yes, indeed we saw some `RST_STREAM` errors in the cloud functions which were affected.

**Comment by schmidt-sebastian** [comment]
I have a potential fix pending in #1380 that changes the order in which we garbage collect clients. This should release the memory used by clients that are affected by RST_STREAM.

**Comment by miselaytes-anton** [comment]
After updating to 4.8.1 we no longer experience the problem. Thanks for fixing! @schmidt-sebastian
