### ISSUE TITLE
no docid if using set()

### ISSUE THREAD

**Issue by willvlad** [googleapis/nodejs-firestore#1377]
Looks like a bug with the set() method:

```
 let uid = admin.firestore().collection("users").add(userData);
console.log(uid.id); //prints id

 let uid = admin.firestore().collection("users").doc().set(userData, {merge: true});
console.log(uid.id); //prints undefined
```

**Comment by schmidt-sebastian** [comment]
`set` only returns a `WriteResult`, which returns the time of the write but not the DocumentReference. Since `add` creates a new `DocumentReference` (which is not known beforehand and thus deemed more important), it returns the DocumentReference instead of the `WriteResult`.
