### ISSUE TITLE
Implicit converstion of custom classes

### ISSUE THREAD

**Issue by brettwillis** [googleapis/nodejs-firestore#1390]
Currently, the SDK allows use of custom classes using the `withConverter()` feature, which enables back and forth conversion.

With converters, if we have a relatively large or deep data tree, then we need to traverse and deep clone every level, which is relatively intensive, and the **entire process is then repeated** immediately afterwards by the SDK's data validation process. This results in a lot of processing.

However consider a use case where we don't care about converting back from Firestore and we only care about serialising data to Firestore, i.e. one-way conversion. This is the same as converting to JSON... any object can have it's own `toJSON()` method which controls serialisation of that instance, and of course the custom classes cannot be recovered by `JSON.parse()`... it is only one-way.

See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#toJSON_behavior

### Proposal

I propose that any object can specify a `toFirestore()` method, which returns a plain object (or any plain value) to be serialised to Firestore in it's place.

The SDK's data validation process will handle classes with this method on the fly, meaning only a single pass of conversion and validation is required, and complex deep cloning implementation for a converter is not required if you're only interested in one-way conversion.

Happy to help with a PR if the idea is a good one.

**Comment by thebrianchen** [comment]
@brettwillis Thanks for the taking the time to write out such a detailed suggestion!

The converter is primarily used to facilitate easier conversions to and from Firestore. We're hesitant to expand the API surface unless it unlocks some functionality that would otherwise not be possible. If you're only interested in one-way conversions, you can call `toJSON()` on the object before passing it as `DocumentData` to Firestore, which results in one total pass from the `toJSON()` call.

Alternatively, if you want to pass in an object to a Firestore reference that already has a converter on it in a single pass, you can convert the reference's converter back to the original converter and pass in the object after converting it to JSON.

I'm going to mark this issue as closed, but feel free to ask any other questions you may have!

**Comment by brettwillis** [comment]
> We're hesitant to expand the API surface unless it unlocks some functionality that would otherwise not be possible.

@thebrianchen the majority of use cases are already technically possible with the existing converters, but this proposal would greatly simplify this some of those use cases. However there is a use case which isn't currently possible - values inside `FieldValue.arrayUnion()` etc.

What I'm highlighting about this use case, is that 
- The custom class instances may be buried in deep levels within the `DocumentData` being passed to Firestore. E.g. objects-within-objects, and objects-within-objects-within arrays... you get the point. However we write it to Firestore, it still requires a complex implementation of deep-cloning and traversing within the object. 
    - This cloning and traversing of the data is already implemented and performed in the SDK's validation. If a `toFirestore()` instance method was understood by the SDK, then the user would not need to implement such deep cloning and traversing logic. **Advantage:** simplification of existing functionality for one-way use cases.
- The custom classes may also be inside `FieldValue.arrayUnion()` for example, which has no pulic API that would allow a converter to access and convert the instance. 
    - If a `toFirestore()` instance method was understood by the SDK, then it provides a self-encapsulated way of serialising to Firestore. **Advantage:** conversion of values inside `FieldValue` was not possible. This applies not just for the one-way use case. 
 - Correct me if I'm wrong, but the SDK doesn't call converters on `update()` operations either. 
    - If a `toFirestore()` instance method was understood by the SDK, then it provides a self-encapsulated way of serialising to Firestore regardless of how it gets there. **Advantage:** not currently possible without manually converting data for `update()` operations, which is inconsistent.
    - I imagine the reason for this is because the `update()` operation could take `FieldPaths`'s and the converter has no way of anticipating what shape the data will be in. This is where a self-encapsulated method removes the ambiguity and enables conversion regardless of how it comes in.


Consider this: 
```JavaScript
ref.update({ 
  'path.to.array': FieldValue.arrayUnion({ value: new CustomClass() })
})
```

This is impossible... a top-level converter has no way of converting `FieldValue`, nor of anticipating the shape of the deep field path. Furthermore even if it was possible, such a converter would have to be manually called prior to passing into `update()` because `update()` doesn't call converters. Implement a `toFirestore()` instance method, and it just works! Furthermore, the `fromFirestore()` top-level converter would get the data back in the full shape that it understands, and would be able to rehydrate the custom class if necessary. If we were only interested in one-way converstion, then no top-level converter is necessary at all. 


I concede that adding this `toFirestore()` instance method to the API surface would create different ways of achieving the same thing, rather than just the single existing way, which may create some ambiguity (e.g. in the above situation the `toFirestore()` top-level converter would be unused). But it also unlocks some simplifications, and some more freedom/functionality/consistency in terms of `FieldValue` and `update()`.

Is the extra freedom and functionality worth the downside of introducing a different ways of achieving the same thing? I think so!! :smile: What do you think? Is there a better way of achieving this functionality?

**Comment by thebrianchen** [comment]
@brettwillis Thanks for going in-depth! I just want to make sure that I understand your core proposal correctly.

> The custom class instances may be buried in deep levels within the DocumentData being passed to Firestore. E.g. objects-within-objects, and objects-within-objects-within arrays... you get the point. However we write it to Firestore, it still requires a complex implementation of deep-cloning and traversing within the object.

I follow the spirit of your proposal, but I'm trying to understand the details. Consider the following simplified example where a `User` object contains an `Address` object:
```typescript
class User {
  name: string;
  address: Address;
}

class Address {
  street: string;
  zipcode: number;
}
```

Does your proposal mean that adding a `toFirestore()` method onto the `User` and `Address` classes would enable you to pass in a `User` object directly to a Firestore reference without needing to specify a converter? If I understand correctly, Firestore would then check for and call `toFirestore()` whenever a custom object prototype is detected and serialize accordingly? Essentially, if a `toFirestore()` method exists on `User`, Firestore would allow:
```
db.collection('foo').doc('bar').set(new User());
```

I just wanted to make sure I'm on the same page with you before responding to the rest of your points. Please let me know if this is what you had in mind, or if you envisioned changing the SDK's API surface in a different way!

**Comment by brettwillis** [comment]
Yep, that's what I mean. It would be recursive in nature, i.e. `User.toFirestore()` may return a plain object which may contain other custom classes (`Address`) somewhere in it's data.

**Comment by thebrianchen** [comment]
@brettwillis After discussing the proposal with the team, we've decided that though this approach is quite clever and opens up some interesting use cases, introducing another entry point for converters into the API surface contradicts the existing `withConverter()` interface and bloats the SDK. 

We're also looking into adding type support for `FieldValue` inside `FirestoreDataConverter` and type-safe `update()` calls with some of the new features in Typescript 4.1. Although these changes won't allow you to do everything in a single pass, it'll make adding custom classes in `FieldValue` and `update()` easier.

Again, just wanted to say thanks for taking the time to write out this proposal and detailed explanation!

**Comment by brettwillis** [comment]
@thebrianchen fair enough, I shall look forward to those improvements!
