### ISSUE TITLE
ignoreUndefinedProperties is misleading

### ISSUE THREAD

**Issue by brako** [googleapis/nodejs-firestore#1392]
In the past I did remove myself undefined properties before inserting data into Firestore. Now, I use the _ignoreUndefinedProperties_ setting from the Firestore constructor instead. I found out that if I merge a document with undefined properties, the existing properties in Firestore corresponding to the undefined ones are deleted.

I don't know if it's an issue or the intended behavior, but I think this settings name is misleading since undefined properties are not ignored.

#### Environment details

  - OS: Debian
  - Node.js version: v14.7.0
  - npm version: 6.14.7
  - `@google-cloud/firestore` version: 4.8.1

#### Steps to reproduce

```
import { Firestore } from "@google-cloud/firestore";

const db = new Firestore({
    ignoreUndefinedProperties: true
});

db.collection('collection')
    .doc('doc')
    .set({
        prop1: "prop1",
        prop2: "prop2"
    }, { merge: true });

// In Firestore we have prop1 and prop2

db.collection('collection')
    .doc('doc')
    .set({
        prop1: "prop1",
        prop2: undefined
    }, { merge: true });

// In Firestore we have only prop1 (prop2 is deleted)

```

Thanks!

**Comment by schmidt-sebastian** [comment]
@wilhuff will take care of this.

**Comment by wilhuff** [comment]
I've confirmed your findings, that this is indeed how this is working today, and that doesn't seem right. This seems like a bug that we should just fix.

**Comment by wilhuff** [comment]
I've submitted a fix and this will go out with the next release.
