### ISSUE TITLE
Node.js API transaction object undocumented

### ISSUE THREAD

**Issue by chad-autry** [googleapis/nodejs-firestore#1402]
https://googleapis.dev/nodejs/firestore/latest/Firestore_.html#runTransaction

The transaction object provided to the updateFunction is not directly documented (only indirectly via examples)

With a starting point of https://firebase.google.com/docs/firestore/manage-data/transactions, I assumed t.create/t.set were both async since its Nodejs example shows t.update being async.

That does not seem to be the case, though without the API documentation I hesitate to say it is wrong, since I don't know if it is intended to be async or not.

**Comment by thebrianchen** [comment]
@chad-autry Thanks for filing an issue and letting us know! I'll have a fix out for those docs soon, and I'll also look into cleaning the rest of the documents out a bit.

In the meantime, the update function takes in a `Transaction` object and returns a Promise. Here's a [link](https://github.com/googleapis/nodejs-firestore/blob/bae82dd4438ac03107c221c62dbce8cf6d20a4b1/dev/src/index.ts#L913) to the source code with its typings.

**Comment by chad-autry** [comment]
Looks like it should do it, I'd managed to overlook the https://googleapis.dev/nodejs/firestore/latest/Transaction.html when doing a ctrl + f on the page, that should put a nice link there in the function. Thanks
