### ISSUE TITLE
Array objects may not qualify for instanceof Array

### ISSUE THREAD

**Issue by galmath001** [googleapis/nodejs-firestore#1409]
Hello,

In reference to the following :
https://github.com/googleapis/nodejs-firestore/blob/bd15996c82967e5d90ed761c5c1225992fbc2625/dev/src/serializer.ts#L172

In some situations, for example when the GoogleCloudPlatform/node-red-contrib-google-cloud firebase module passes an array to "encodeValue", the array constructor will be different which causes "instanceof Array" to be false. This is similar to the array object being checked across frames or windows and causes "instanceof Array" to incorrectly return false.

Using the ES5 Array.isArray(val) works fine, and from what I can see, would be a suitable replacement check and is already used in that same library.

Thanks in advance for your attention to the issue,

**Comment by var-const** [comment]
Thank you for reporting this! This looks like a straightforward fix, I'll take this on.
