### ISSUE TITLE
Add type definitions for v1 and v1beta1 clients

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#1422]
Type definitions for v1 and v1beta1 exports are currently `any`.

I intended to do it myself (#1421), but `protos` is outside of `src` and since it's imported, the build output changes from `build/src` to `build/dev/src`, which would obviously require a lot of changes.

The simples fix would be to move `protos` to `src`, this way all other files and references can remain unchanged. WDYT?

**Comment by schmidt-sebastian** [comment]
Moving `dev/protos` to `src/dev/protos` sounds good to me. 

Just a heads up - you will have to change https://github.com/googleapis/nodejs-firestore/blob/master/synth.py. Let us know if you want us to do this first.

**Comment by merlinnot** [comment]
Just a small update from my side, I'm still planning to pick this up, probably within the next two-three weeks. If you guys have some time sooner than that, go ahead! :slightly_smiling_face:

**Comment by schmidt-sebastian** [comment]
@thebrianchen Is working on changes that are required to make our source generation work with the new Proto location. We might either leave it at that part, or take this issue to completion once that is done.

**Comment by merlinnot** [comment]
I'll have time for it in two to three weeks, don't wait for me if you have time to do that sooner.

**Comment by merlinnot** [comment]
Thank you, that will be very useful for me!
