### ISSUE TITLE
Using a previous document to start_after in queries returns no results if object is rehydrated.

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-firestore#1424]
While helping a SO poster, https://stackoverflow.com/questions/66159515/firestore-query-after-previous-queries-last-document, I came across what seems like a shortcoming of start_after. 

Assume a sample collection
```
ID    n
--------
a     3
b     1
b2    1
c     2
```

The following code will return `b2, c, a` objects.
```
const Firestore = require('@google-cloud/firestore');
const db = new Firestore()

let query = db.collection('0');

db.collection('0').doc('b').get().then(b => {

    query.orderBy('n').startAfter(b).get().then(snapshot => {
        snapshot.forEach(document => {
            console.log(document.id + " " + document.get('n'));
        });
    });

});
```

Now, if instead of retrieving the document 'b' we instead use a stored version that was created by `JSON.stringify(b)`

```
stringifiedB = '{"_fieldsProto":{"n":{"stringValue":"1","valueType":"stringValue"}},"_ref":{"_firestore":{"_settings":{"projectId":"crwgoog-test","libName":"gccl","libVersion":"4.9.3"},"_settingsFrozen":true,"_serializer":{"allowUndefined":false},"_projectId":"crwgoog-test","registeredListenersCount":0,"bulkWritersCount":0,"_backoffSettings":{"initialDelayMs":100,"maxDelayMs":60000,"backoffFactor":1.3},"_clientPool":{"concurrentOperationLimit":100,"maxIdleClients":1,"activeClients":{},"failedClients":{},"terminated":false,"terminateDeferred":{"promise":{}}}},"_path":{"segments":["0","b"]},"_converter":{}},"_serializer":{"allowUndefined":false},"_readTime":{"_seconds":1613160434,"_nanoseconds":745341000},"_createTime":{"_seconds":1613088642,"_nanoseconds":301495000},"_updateTime":{"_seconds":1613088642,"_nanoseconds":301495000}}'
```

```
b = JSON.parse(stringifiedB)

query.orderBy('n').startAfter(b).get().then(snapshot => {
    snapshot.forEach(document => {
        console.log(document.id + " " + document.get('n'));
    });
});

```

This returns no results, where I would expect an identical result.

**Comment by schmidt-sebastian** [comment]
Our API does not allow DocumentSnapshots to be round-tripped through JSON. JSON does not maintain the Prototype hierarchy, and anything you restore from JSON will not resemble a DocumentSnapshot. Moreover, since we do not implement our own toJSON() API, the format is not defined and can change even in patch versions without notice. 

If a DocumentSnapshot cannot be preserved between invocations, the customer needs to manually hold on to the value of `n` and the document's path. They can then do:

```
const lastRef = firestore.doc(lastDocumentPath);
query.orderBy('n').orderBy(FieldPath.documentId()).startAfter(lastValue, lastRef).get().then(snapshot => {
    snapshot.forEach(document => {
        console.log(document.id + " " + document.get('n'));
    });
});
```

**Comment by crwilcox** [comment]
Thanks @schmidt-sebastian . It seems the key is ordering by n and id, and starting after each, then you can do it with a shallow ref.
