### ISSUE TITLE
Please document the format used by exportDocuments

### ISSUE THREAD

**Issue by sk-** [googleapis/nodejs-firestore#1428]
**Is your feature request related to a problem? Please describe.**
Sometimes one will reach limitation with a firestore database, due either to a bad design, or other constraints, or one may want to stop using Firestore in favor of another db technology. However, there is no straightforward way of exporting the database and importing it into another one, because the format of the dump generated by [`exportDocuments`](https://github.com/googleapis/nodejs-firestore/blob/75d9ece19bb4a9228d004b8fe4851422b6996ca7/dev/src/v1/firestore_admin_client.ts#L254) (see [rpc](https://firebase.google.com/docs/firestore/reference/rpc/google.firestore.admin.v1#google.firestore.admin.v1.FirestoreAdmin.ExportDocuments)) is not documented. AFAIK it uses a level db representation, but it seems that many required files to read it are missing.

**Describe the solution you'd like**
Documentation on the export format used, so one could extract the data of the dump. This would avoid lock-in and would allow us to write converters to import the database into other engines.

**Describe alternatives you've considered**
Currently the only way I see to export a DB is to first export it with `exportDocuments, import it with BigQuery and finally exporting that dataset.

**Comment by thebrianchen** [comment]
@sk- Thanks for bringing this up! The full documentation for the function is further down in the file ([link](https://github.com/googleapis/nodejs-firestore/blob/75d9ece19bb4a9228d004b8fe4851422b6996ca7/dev/src/v1/firestore_admin_client.ts#L1045)), but it was pretty difficult to figure out where more granular documentation was. The Google Cloud documentation has an [article](https://cloud.google.com/datastore/docs/export-import-entities) that details the export's behavior and LevelDB's [log format](https://github.com/google/leveldb/blob/master/doc/log_format.md).

The documentation for the admin and gapic clients on the node SDK are auto-generated by the upstream proto files, so I can't make any changes directly in this repo. I'll work with the backend teams and try to add a link in the protos with more details.

**Comment by sk-** [comment]
Thanks @thebrianchen for the pointers. I was able to extract the individual records by parsing the leveldb log format. However, those records are protobufs, so one needs to know the proto definition in order to decode them.

Based on some of the data we have, I was able to come up with this proto definition:

```proto
syntax = "proto2";

message Record {
  required Path path = 13;
  repeated KeyValue field = 15;
  required PathWrapper footer = 16;
}

message Path {
  required string db = 13;
  required PathWrapper path = 14; 
}

message PathWrapper {
  repeated group PathPart = 1 {
    required string collection = 2;
    required string document = 4;  
  }; 
}

message KeyValue {
  optional Type type = 1;
  required string key = 3;
  required bool array = 4;
  repeated Value value = 5;
}

enum Type {
  NATIVE = 0;
  TIMESTAMP = 7;
  NESTED = 19;
}

message Value {
  optional int64 int = 1;
  optional bool boolean = 2;
  optional string string = 3;
  optional double double = 4;
}
```

Note: the same is true for the metadata, and in fact the [docs](https://cloud.google.com/datastore/docs/export-import-entities#metadata_files) mention it, even how to "decode" them, but they don't show what the proto definition is.

Is there any chance you can document these proto definitions?

**Comment by thebrianchen** [comment]
@sk- Thanks for digging into this! I'll forward this to the backend and docs teams to see where it's appropriate to include.

How did you decode the proto definitions?

**Comment by sk-** [comment]
@thebrianchen Thanks.

I used both https://protogen.marcgravell.com/decode, which is useful for highlighting `group`s and also `protoc --decode-raw`. Using that output and the knowledge of the data structure I was able to come up with the proto definition above.

Also note that the level db documentation is not complete, as the checksum is not exactly crc32c because the result is masked.

**Comment by sk-** [comment]
@thebrianchen is there any chance you could reopen this issue and document what the actual proto is?

**Comment by thebrianchen** [comment]
cc @schmidt-sebastian

**Comment by sk-** [comment]
@schmidt-sebastian I would respectfully request that this decision would be revised, because without it you are effectively locking your customers in.

The data does not need to be part of the API contract, it just needs to be documented. Or at the very least some guidelines should be provided so that the community could do a better job while reverse engineering your proprietary encoding.

There are projects which document in someways their implementation details.
