### ISSUE TITLE
TS: GetOptions not accepted in typescript definition of DocumentReference.get()

### ISSUE THREAD

**Issue by Gsiete** [googleapis/nodejs-firestore#1429]
According to the Official cocumentation: of DocumentReference.get()
(https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference#get)
the method takes 1 optional argument of type GetOptions (https://firebase.google.com/docs/reference/js/firebase.firestore.GetOptions)
However, on the typescript definition of this library that's missing:
https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L1021

#### Environment details
- `@google-cloud/firestore` version: 4.9.4

Thanks!

**Comment by schmidt-sebastian** [comment]
@Gsiete Thanks for the report. We have two JavaScript clients. The documentation you pointed is for our Web-based client (https://www.npmjs.com/package/firebase), which supports an offline cache. GetOptions allow you define the cache behavior for this Web client.

`@google-cloud/firestore` does not have an offline cache and as such does not offer `GetOptions`. Our API docs live here: https://googleapis.dev/nodejs/firestore/latest/index.html

**Comment by Gsiete** [comment]
@schmidt-sebastian Sorry, I should have sent this ones:
https://firebase.google.com/docs/reference/node/firebase.firestore.DocumentReference#get
https://firebase.google.com/docs/reference/node/firebase.firestore.GetOptions

Because I actually did have some issues with caching with firebase-admin some time ago.

**Comment by schmidt-sebastian** [comment]
There are two Node SDKs, which is pretty confusing :) The links above are for the Node version of the Web SDK which has a built-in cache and supports GetOptions.
