### ISSUE TITLE
*HUGE* memory leaking with firestore

### ISSUE THREAD

**Issue by hza** [googleapis/nodejs-firestore#1443]
#### Environment details

  - OS: X 10.15.5
  - Node.js version: v15.8.0
  - npm version: 7.5.0
  - `@google-cloud/firestore` version: 4.9.6

#### Steps to reproduce

  1.  Create local db: `firebase emulators:start --project test`
  2. Run ts example:

```typescript
import { Firestore } from '@google-cloud/firestore';
import express from 'express';

async function main() {
  const app = express()

  const firestore = new Firestore({
    projectId: "test",
    host: "localhost:8080",
    ssl: false
  });

  await firestore.collection('memory').doc("leak").set({ "leak": true });

  app.get('/', async (req, res) => {
    const doc = await firestore.collection('memory').doc("leak").get();
    res.send({ message: doc.data() });
  })

  app.listen(3000)
}

main()
```

   3. `autocannon -c 100 -d 40 -p 10 localhost:3000`

enjoy the memory leaking like a river.

**Comment by schmidt-sebastian** [comment]
Thank you for reporting this. We will try to reproduce and share our findings.

**Comment by crwilcox** [comment]
@schmidt-sebastian any update on this?

**Comment by schmidt-sebastian** [comment]
cc @rafikhan

**Comment by rafikhan** [comment]
@hza Can you please give us more information on what you measured exactly and when to assess the leak? For example, once autocannon stopped generating traffic did you see memory usage go down?

**Comment by hza** [comment]
@rafikhan I understood my mistake. The problem appears only with node.js *DEBUG* mode. 

Created https://github.com/hza/memory-leak with code and steps to see what i have catch.

So, the problem is probably with node.js/debug. You may close this issue.

**Comment by schmidt-sebastian** [comment]
Thanks for the update.
