### ISSUE TITLE
TypeScript: v1.FirestoreAdminClient is not constructable.

### ISSUE THREAD

**Issue by MarcPorciuncula** [googleapis/nodejs-firestore#1444]
Caused by the new typings added in https://github.com/googleapis/nodejs-firestore/commit/47238a926471dee8bdeaa38bcb5f772c7f20349f.

It seems that `v1.FirestoreAdminClient` (as well as `v1.FirestoreClient` and `v1beta1.FirestoreClient`) is exported as instance instead of class.

#### Environment details

  - OS: macos
  - Node.js version: 12.19.0
  - npm version: 6.14.8 (using yarn v2.4.1)
  - `@google-cloud/firestore` version: 

#### Steps to reproduce

In TypeScript, try to instantiate `firestore.v1.FirestoreAdminClient`.

`tsc` output:
```
src/functions/backup-firestore/handler.ts:15:22 - error TS2351: This expression is not constructable.
  Type 'FirestoreAdminClient' has no construct signatures.

15   const client = new firestore.v1.FirestoreAdminClient()
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by schmidt-sebastian** [comment]
We will get this fixed & released shortly.
