### ISSUE TITLE
Trigger support for withConverter

### ISSUE THREAD

**Issue by larssn** [googleapis/nodejs-firestore#1449]
I'll make it brief:

Would be nice if the `onCreate`, `onWrite`, `onUpdate` and `onDelete` triggers had support for `withConverter`:

```
firestore
  .document(`businesses/{businessId}`)
  .withConverter(new BusinessConverter())
  .onWrite(async (change, context) => {
    const business: Business = change.after.data()
  })
```

Thanks

**Comment by schmidt-sebastian** [comment]
@larssn Thanks for this suggestion. Do you mind filing this issue here: https://github.com/firebase/firebase-functions/issues

Unfortunately, I am not able to transfer it since it belongs to a different GitHub organization.
