### ISSUE TITLE
Apply converters eagerly

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#1458]
**Is your feature request related to a problem? Please describe.**

One of the services I was working on required 3 GBs of RAM to store data of ~160k documents. There was no memory leak, as the memory usage was stable over time. I thought that it's fairly significant, so I started looking into potential issues.

I found out that Firestore converters are applied lazily, when `data` method on a `Document` is called:

https://github.com/googleapis/nodejs-firestore/blob/42ade788be6e9c1ba01b6e81779e5185d5cc75cd/dev/src/document.ts#L396-L404

In addition, the original `_fieldsProto` is kept even after applying the converter lazily.

Why both keeping `_fieldsProto` and lazy application of the converter are an issue for me?
- Return value of my converter is significantly smaller than the original document (and field masks are not supported, see https://issuetracker.google.com/issues/171904233).
- I do not need the original `_fieldsProto` for any use (it's not actually exposed).

I tested an implementation with eager application of converters and I observed 90% lower memory usage (from 3.2 GBs to ~400 MBs), as well as noticeably lower CPU usage (garbage collection).

Given the significant gains I observed, I decided to propose this change in the implementation for the benefit of the Community.

 **Describe the solution you'd like**

I'd like the converters (both default serializer and user-provided) to be eagerly applied. I'd also like to see references to the native representation (`_fieldsProto`) to be removed once data is converted.

 **Describe alternatives you've considered**

None.

 **Additional context**

None.

**Comment by wu-hui** [comment]
Hi, that sounds like a very good performance improvement!

Do you mind opening a PR with your change?

**Comment by merlinnot** [comment]
Thank you for the insights and taking time to write it down in detail. Your points are valid, I can't see that much of a benefit if we can't remove the original proto - and we can't because of `get`.

The gains I had are so large because of the lack of projections (field masks/`Query.select()`) in Watch. If we could drop the original proto, I imagine we'd still see roughly 50% gain here, but indeed `Snapshot.get()` is an issue.

I imagine we could potentially add it as an option (opt-in for those who don't need `Snapshot.get()`), but that would complicate the API and the implementation.

I'll leave it up to you to decide - I can work on implementing this as an option if you'd see enough value in it and could help me with the API committee. For the time being, I'll close the issue, but please let me know if there's some interest from your side.
