### ISSUE TITLE
Unable to compile the project

### ISSUE THREAD

**Issue by manwithsteelnerves** [googleapis/nodejs-firestore#1459]
1) Is this a client library issue or a product issue?
Client Library issue

2) Did someone already solve this?
  No

3) Do you have a support contract?
No

#### Environment details

  - OS: Mac OSX Mojave
  - Node.js version: 10.14
  - `@google-cloud/firestore` version: "4.9.8

#### Steps to reproduce

  1. Download the copy from github
  2. npm install
  3. tsc

Once I download the latest copy from git and try to compile, I see the below errors.

```

dev/conformance/runner.ts:450:17 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

450                 resolve();
                    ~~~~~~~~~

  ../../../../../usr/local/lib/node_modules/typescript/lib/lib.es2015.promise.d.ts:33:34
    33     new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
    An argument for 'value' was not provided.

dev/src/util.ts:48:5 - error TS2322: Type 'Promise<R | undefined>' is not assignable to type 'Promise<R>'.
  Type 'R | undefined' is not assignable to type 'R'.
    'R' could be instantiated with an arbitrary type which could be unrelated to 'R | undefined'.
      Type 'undefined' is not assignable to type 'R'.
        'R' could be instantiated with an arbitrary type which could be unrelated to 'undefined'.

48     this.promise = new Promise(
       ~~~~~~~~~~~~

dev/system-test/firestore.ts:481:16 - error TS2790: The operand of a 'delete' operator must be optional.

481         delete allSupportedTypesObject.pathValue;
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

dev/test/index.ts:683:12 - error TS2790: The operand of a 'delete' operator must be optional.

683     delete expected.pathValue;
               ~~~~~~~~~~~~~~~~~~

[11:39:46 AM] Found 4 errors. Watching for file changes.
```

Any special setup required to compile from source? I actually need to modify few things in this library for my project.

Thanks!

**Comment by wu-hui** [comment]
Can you follow instructions from https://github.com/googleapis/nodejs-firestore/blob/master/CONTRIBUTING.md to see if this solves your problem?

**Comment by schmidt-sebastian** [comment]
@manwithsteelnerves If this is still an issue, can you reply here? We will then re-open.

**Comment by manwithsteelnerves** [comment]
@schmidt-sebastian I was able to compile by running 
```
npm run compile
```

But, is there any way to use 
```
tsc -w 
```
as  its easy to check the errors instantly by watching rather than running the compiler for every change. Moreover prettier syntax is too strict and needs constant fixing.
