### ISSUE TITLE
Timestamp.fromMillis can't handle nanoseconds.

### ISSUE THREAD

**Issue by robario** [googleapis/nodejs-firestore#1463]
1) Is this a client library issue or a product issue?
This is the client library issue.

2) Did someone already solve this?
no.

3) Do you have a support contract?
no.

#### Environment details

  - OS: macOS Big Sur 11.2.3
  - Node.js version: v14.16.0
  - npm version: 6.14.12
  - `@google-cloud/firestore` version: 3.8.6

#### Steps to reproduce

  1. `$ node -pe 'require("@google-cloud/firestore/build/src/timestamp").Timestamp.fromMillis(1000.1);'`
     
     More than 1000 milliseconds may be an abnormal case.
     
     ```
     ./node_modules/@google-cloud/firestore/build/src/validate.js:191
                 throw new Error(invalidArgumentMessage(arg, 'integer'));
                 ^
     
     Error: Value for argument "nanoseconds" is not a valid integer.
         at Object.validateInteger (./node_modules/@google-cloud/firestore/build/src/validate.js:191:19)
         at new Timestamp (./node_modules/@google-cloud/firestore/build/src/timestamp.js:74:20)
         at Function.fromMillis (./node_modules/@google-cloud/firestore/build/src/timestamp.js:126:16)
         at [eval]:1:66
         at Script.runInThisContext (vm.js:133:18)
         at Object.runInThisContext (vm.js:310:38)
         at internal/process/execution.js:77:19
         at [eval]-wrapper:6:22
         at evalScript (internal/process/execution.js:76:60)
         at internal/main/eval_string.js:23:3
     ```

     - `$ node -pe 'require("@google-cloud/firestore/build/src/timestamp").Timestamp.fromMillis(999.1);'`
     
       Less than 1000 milliseconds is always a normal case.
       
       ```
       Timestamp { _seconds: 0, _nanoseconds: 999100000 }
       ```

> Making sure to follow these steps will guarantee the quickest resolution possible.

https://github.com/googleapis/nodejs-firestore/blob/42ade788be6e9c1ba01b6e81779e5185d5cc75cd/dev/src/timestamp.ts#L110
The above line will be
`        const nanos = Math.round((milliseconds - seconds * 1000) * MS_TO_NANOS);`
or to avoid minus's round-off error
`        const nanos = Math.round(milliseconds * MS_TO_NANOS - seconds * 1000 * MS_TO_NANOS);`

**Comment by thebrianchen** [comment]
@robario Thanks for catching this! We should have a fix out in the coming weeks.

**Comment by robario** [comment]
Please do not use `floor`.
The `floor` make `Timestamp.fromMillis(1000.4);` to `Timestamp { _seconds: 1, _nanoseconds: 399999 }`.
I think it should be `Timestamp { _seconds: 1, _nanoseconds: 400000 }`.
Let's rethink that.

**Comment by robario** [comment]
I think this is a better.
```typescript
// sample code
const milliseconds = 1000.41234567;
const seconds = Math.floor(milliseconds / 1000);
let nanos = milliseconds * MS_TO_NANOS - seconds * 1000 * MS_TO_NANOS;
// nanos === 412345.6700000763 including rounding error
nanos = Math.floor(nanos); // Given the number of significant digits, floor is a good choice here.
// nanos === 412345
```

**Comment by robario** [comment]
I'm very sorry... It was my mistake... It was supposed to be that way.
