### ISSUE TITLE
Using firebase emulator with bazel

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#1469]
**Is your feature request related to a problem? Please describe.**
There is no good way to execute tests via bazel via normal bazel commands if the emulator is required
 **Describe the solution you'd like**
A bazel import from firestore that has a dependency on the emulator running and is able to determine if it needs to be spun up or not based on test targets being cached or not.
 **Describe alternatives you've considered**
1. Creating custom bazel targets that are not cached that run with `concurrently` to run alongside the emulator.
2. Running the emulator outside of bazel, then running the bazel command. This will get caching, but I can't use bazel without the emulator then.

**Comment by dconeybe** [comment]
Hi @jakeleventhal. Can you close this issue and re-create it in https://github.com/firebase/firebase-tools?
