### ISSUE TITLE
Serialization of ref's results in credential leakage

### ISSUE THREAD

**Issue by geemanjs** [googleapis/nodejs-firestore#1481]
Hey,

#### Environment details

  - OS: Mac OS
  - Node.js version: 10.24.1
  - npm version: 6.14.2
  - `@google-cloud/firestore` version: 4.8.1
  - In my case I was using the `firebase-admin` library @ version 9.6.0

#### The issue
I recently built a "JSON rest api" around some entities stored in firestore and whilst testing noticed that when serializing entites to JSON that contained `ref`s the `client_email` / `private_key` landed in the response. Whilst not an "issue" with the firestore client itself as users probably should convert/remove refs prior to serialization. I couldn't help but think that this could be an easy thing to do by mistake and has the potential for a large impact on any firestore project involved. Hence me raising this issue.. I'm wandering if the client itself should protect those credentials by overriding the `toJSON` function.

Heres a cut down code snippet that demonstrates what I saw: 
```
# Create an item
const itemRef = admin.firestore().collection("items").doc("1");
await itemRef.set({ "test": "item" })

# Add the item as a ref
admin.firestore().collection("boxes").doc("1").set({ items: [item1] })

# Get the box and serialize it
const boxSnap = await admin.firestore().collection("boxes").doc("1").get();
console.log(JSON.stringify(boxSnap.data()));

# The output ends up like this...
{
  "items": [
    {
      "_converter": {},
      "_firestore": {
        "_backoffSettings": {
          "backoffFactor": 1.3,
          "initialDelayMs": 100,
          "maxDelayMs": 60000
        },
        "_clientPool": {
          "activeClients": {},
          "concurrentOperationLimit": 100,
          "failedClients": {},
          "maxIdleClients": 1,
          "terminated": false,
          "terminateDeferred": {
            "promise": {}
          }
        },
        "_projectId": "my-project",
        "_serializer": {
          "allowUndefined": false
        },
        "_settings": {
          "credentials": {
            "client_email": "firebase-adminsdk-xhtmm@my-project.iam.gserviceaccount.com",
            "private_key": "-----BEGIN PRIVATE KEY-----<the whole admin private key here>"
          },
          "firebaseVersion": "9.6.0",
          "libName": "gccl",
          "libVersion": "4.8.1 fire/9.6.0",
          "projectId": "my-project"
        },
        "_settingsFrozen": true,
        "bulkWritersCount": 0,
        "registeredListenersCount": 0
      },
      "_path": {
        "segments": [
          "items",
          "1"
        ]
      }
    }
  ]
}
``````

**Comment by rafikhan** [comment]
Hi @geemanjs. Thank you for taking the time to share your thoughts and experience on the SDK. As you learned, References are not meant to be serialized and their usage is a choice developers must make when modeling data. Your suggestion to override `toJSON` can solve the problem but modifying global state is usually dangerous and introduce other unexpected bugs so we try to avoid things like it.

Thanks again for writing to us and let us know if you have any more thoughts on the SDK!
