### ISSUE TITLE
Firebase transactions with read operations after write operations

### ISSUE THREAD

**Issue by Veargan** [googleapis/nodejs-firestore#1482]
#### Environment details

  - npm version: 6.14.6
  - Node.js version: 12.8.3
  - node engine: 12
  - `@google-cloud/firestore` version: 4.5.0
  - `firebase-admin`: 9.6.0
  - `firebase-functions`: 3.13.2

#### Steps to reproduce

[Docs](https://firebase.google.com/docs/firestore/transaction-data-contention#isolation_within_a_transaction) states that you can execute reads after writes, but as it turns out you cannot. Is that a bug or misleading documentation?

1. Call a cloud function or trigger background function
```
const onFirestoreTestsWrite = functions.firestore
  .document('tests/{testId}')
  .onWrite(async (change, context) => {
    await admin.firestore().runTransaction(async (t) => {
      const testDoc = await admin.firestore().collection('tests').doc().get();
      t.set(testDoc.ref, {});
      t.get(testDoc.ref);
    });
  });
```
```
const tests_get = async (req, res) => {
  try {
    const test = await admin.firestore().runTransaction(async (t) => {
      const testDoc = await admin.firestore().collection('tests').doc().get();
      t.set(testDoc.ref, {});
      return t.get(testDoc.ref);
    });
    res.send({id: test.id});
  } catch (e) {
    res.status(400).send({ error: e['message'] });
  }
};
```
Will result in error:
```
Error: Firestore transactions require all reads to be executed before all writes.
    at Transaction.get (/workspace/node_modules/@google-cloud/firestore/build/src/transaction.js:76:19)
    at /workspace/lib/firestore/tests-write.js:46:11
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Transaction.runTransaction (/workspace/node_modules/@google-cloud/firestore/build/src/transaction.js:323:26)
    at async /workspace/lib/firestore/tests-write.js:43:5 
```

**Comment by rafikhan** [comment]
Hi @Veargan, the documentation link you sent me says `Queries and reads inside a transaction do not see the results of previous writes inside that transaction`. Where did you see that reads are allowed after writes?

**Comment by Veargan** [comment]
@rafikhan yep, there's part about isolation, but also a note: 

> Only the server client libraries support transactions with read operations after write operations. For transactions in the mobile/web SDKs, document reads must come before document writes.

**Comment by schmidt-sebastian** [comment]
We will fix the documentation. The SDKs do not support read after writes. The Mobile and Server SDKs only differ in how they obtain locks for documents that are read as part of a transaction.

**Comment by schmidt-sebastian** [comment]
Filed b/186414961 for documentation fix.

**Comment by schmidt-sebastian** [comment]
Documentation has been updated internally and will be rolled out with the next update,
