### ISSUE TITLE
The return type of docChanges in QuerySnapshot is not generic

### ISSUE THREAD

**Issue by EvolveYourMind** [googleapis/nodejs-firestore#1483]
The method `docChanges` of `QuerySnapshot` returns an array of `DocumentChange` that is not generic

https://github.com/googleapis/nodejs-firestore/blob/c2e01646401f72520a4775a1f678634667225e6d/types/firestore.d.ts#L1467

A possible fix could be:
```ts
docChanges(): DocumentChange<T>[]; 
```

**Comment by schmidt-sebastian** [comment]
Thanks for catching. Fix coming.
