### ISSUE TITLE
Property 'bulkWriter' does not exist on type 'Firestore'.ts(2339)

### ISSUE THREAD

**Issue by scowling** [googleapis/nodejs-firestore#1496]
#### Environment details

  - OS: Windows 10
  - Node.js version: v14.8.0
  - npm version: 6.14.9
  - `@google-cloud/firestore` version: 4.11.0

#### Steps to reproduce

  1. `import { Firestore } from '@google-cloud/firestore';`
  2. `const f = new Firestore();`
  3. `const bulkwriter = f.bulkWriter();`

Produce typescript error:
`Property 'bulkWriter' does not exist on type 'Firestore'.ts(2339)`

**Comment by wu-hui** [comment]
Hi @scowling 

I tried myself, and `BulkWriter` seems to exist, I cannot reproduce this error. Can you provide a more detailed reproduction steps, ideally a mini repo would be super helpful.
