### ISSUE TITLE
Why use this package instead of firebase admin. (Bundle size of this package is bigger 😱)

### ISSUE THREAD

**Issue by Lucas-Geitner** [googleapis/nodejs-firestore#1499]
Hello,

I use this package instead of firebase-admin because i was thinking it was lighter when i only use firestore, 

But i'm surprise to see in bundlephobia that it's the opposite, 

<img width="733" alt="Capture d’écran 2021-05-07 à 11 44 51" src="https://user-images.githubusercontent.com/20271305/117431531-a3b4ff00-af29-11eb-9c6b-75e5d8007e41.png">
<img width="681" alt="Capture d’écran 2021-05-07 à 11 45 04" src="https://user-images.githubusercontent.com/20271305/117431555-ab74a380-af29-11eb-8e14-23ed96be572e.png">

Does anyone have a feedback on this ?

Thanks a lots,

**Comment by schmidt-sebastian** [comment]
Closing for now. We will re-open if there is a follow up. Thank you!
