### ISSUE TITLE
BulkWriter generating RESOURCE_EXHAUSTED errors

### ISSUE THREAD

**Issue by kachler** [googleapis/nodejs-firestore#1515]
#### Environment details

  - OS: macOS 10.14.6
  - Node.js version: 10.16.1
  - npm version: 6.9.0
  - `@google-cloud/firestore` version: 4.12.0

#### Steps to reproduce

I'm attempting to use the BulkWriter to backfill a new field onto approximately six million documents in a Firestore collection. I'm running the script below on test batches, around 10,000 - 20,000 docs, and I'm receiving the error`{"code":8}` which I believe is  `RESOURCE_EXHAUSTED`. Have I done something incorrectly in the script, or perhaps I'm missing something entirely? 

Any help would be appreciated!

```javascript
const { Firestore } = require('@google-cloud/firestore');
const fs = require('fs');
const { differenceInSeconds } = require('date-fns');

const folder = 'input';
const fileName = 'bq-results-20210422';

const collectionName = 'orders';
let totalCounter = 0;

async function bulkWriter() {
    try {
        const sDate = new Date();
        console.log(`Start time: ${sDate}`);

        await fs.writeFileSync(`./output/writeSuccess.json`, '');
        await fs.writeFileSync(`./output/writeFailures.json`, '');

        const docData = await fs.readFileSync(`./${folder}/${fileName}.json`, 'utf-8').split('\n');

        const firestore = new Firestore();
        let bulkWriter = firestore.bulkWriter();

        bulkWriter
            .onWriteResult((documentRef, result) => {
                const docId = JSON.stringify(documentRef._path.segments[1]);
                fs.appendFileSync(`./output/writeSuccess.json`, `{"fsDocId":${docId}}\n`);
            });

        for (const data of docData) { 
            const { fsDocId } = JSON.parse(data);
            const documentRef = firestore.doc(`${collectionName}/${fsDocId}`);
            
            bulkWriter.update(documentRef, { isLocal: false })
                .catch(error => fs.appendFileSync(`./output/writeFailures.json`, `${JSON.stringify(error)}\n`))

            totalCounter++;
        };
        
        await bulkWriter.close().then(() => {
          console.log('Executed all writes');
        });
        console.log(`Total: ${totalCounter}`);

        const eDate = new Date();
        console.log(`End time: ${eDate}`);
        console.log(`Running time (in seconds): ${differenceInSeconds(eDate, sDate)}`);  
    } catch(error) {
        console.error(error);
    };
};

bulkWriter();

**Comment by thebrianchen** [comment]
@kachler The error you are seeing corresponds to `RESOURCE_EXHAUSTED` ([grpc documentation](https://grpc.github.io/grpc/core/md_doc_statuscodes.html)). Are you hitting these errors for all of your writes, or just a subset of them? Do the writes succeed after retrying? You can write a custom error handler using `BulkWriter.onWriteError()` to force BulkWriter to automatically retry the error, or log how many times the operation has failed ([class](https://github.com/googleapis/nodejs-firestore/blob/c2c160663f1d3338d6e156cefe65633f2c2690a1/dev/src/bulk-writer.ts#L276)).

In the meantime, could you also file a support ticket and share the ticket number here? That way, I can take a look at the underlying logs when the error is thrown. Thanks!

**Comment by kachler** [comment]
Thanks, @thebrianchen! I updated the ticket to reflect the correct error, `RESOURCE_EXHAUSTED`. I also ran another batch with 10,000 updates and included the following custom `onWriteError` handler. Out of 10,000 updates, I logged 136 errors. Most appear to have retried, but only 9,984 updates triggered the `onWriteResult` handler.

I will create a support ticket now.

#### Error:
```json
{"error":{"code":8,"documentRef":{"_firestore":{"_settings":{"libName":"gccl","libVersion":"4.12.0"},"_settingsFrozen":true,"_serializer":{"allowUndefined":false},"_projectId":"beautycounter-prod","registeredListenersCount":0,"bulkWritersCount":0,"_backoffSettings":{"initialDelayMs":100,"maxDelayMs":60000,"backoffFactor":1.3},"_clientPool":{"concurrentOperationLimit":100,"maxIdleClients":1,"activeClients":{},"failedClients":{},"terminated":false,"terminateDeferred":{"promise":{}}}},"_path":{"segments":["orders","477149029"]},"_converter":{}},"operationType":"update","failedAttempts":1}
```

#### onWriteError Handler
```javascript
bulkWriter
            .onWriteError((error) => {
                const docId = JSON.stringify(error.documentRef._path.segments[1]);
                fs.appendFileSync(`./output/writeErrors.json`, `{"fsDocId":${docId}, "errorCode": ${error.code}},"failedAttempts":${error.failedAttempts}, "error":${JSON.stringify(error)}\n`);

                if ((error.code === UNAVAILABLE || error.code === RESOURCE_EXHAUSTED) && error.failedAttempts < MAX_RETRY_ATTEMPTS) {
                        return true;
                    } else {
                        const docId = JSON.stringify(error.documentRef._path.segments[1]);
                        fs.appendFileSync(`./output/writeFailures.json`, `{"fsDocId":${docId}, "errorCode": ${error.code}},"failedAttempts":${error.failedAttempts}, "error":${JSON.stringify(error)}\n`);
                        return false;
                    }
                });
```

**Comment by kachler** [comment]
The ticket id is 28019534.

**Comment by thebrianchen** [comment]
@kachler After looking at the logs, it seems you are likely are hitting the 10MiB/sec limit on writes, which is causing the `RESOURCE_EXHAUSTED` errors that you see. There are two possible scenarios here:
- Scenario 1: BulkWriter automatically sends documents in batches of 20, so sending a batch of 20 documents that exceed the 10MiB limit. If this is the case, retrying the batch will not do anything.
- Scenario 2: BulkWriter is sending writes faster than the 10MiB/sec limit. If this is the case, slowing down the BulkWriter throughput or retrying more aggressively can resolve the issue.

I'll look into adding a fix on the SDK to avoid this, but in the meantime, can you try the following workarounds:
1. Call `bulkWriter.flush()` every 5-10 writes (you don't have to wait for the promise) to prevent batches with large documents from hitting the limit (addresses Scenario 1).
2. Increase MAX_RETRY_ATTEMPTS in `onWriteError` (hacky workaround to Scenario 2)
3. Configure `BulkWriterOptions` to specify a maximum rate limit (addresses Scenario 2).

Sorry for the trouble you've been experiencing! If you could give these workarounds a try and let us know, that would help us a lot and plan an appropriate fix.

**Comment by kachler** [comment]
Sure, I can re-add `bulkWriter.flush()` every 5-10 writes and run another test. How do I configure the `BulkWriterOptions`? I don't see it mentioned in the documentation.

**Comment by thebrianchen** [comment]
See this [link](https://googleapis.dev/nodejs/firestore/latest/global.html#BulkWriterOptions) to the documentation.

**Comment by kachler** [comment]
Good news! I was able to run several batches of 10,000-20,000 documents, flushing every 10 writes and `maxOpsPerSecond` set to 100, without any errors.
