### ISSUE TITLE
Export different FieldValue types

### ISSUE THREAD

**Issue by saiichihashimoto** [googleapis/nodejs-firestore#1547]
**Is your feature request related to a problem? Please describe.**
Having typescript types that are "loose" enough to be used where they aren't wanted leaves room for error. For example, if I type a firestore field to be an array in my runtime code, I must also allow `FieldValue` to let `FieldValue.arrayUnion` work, but that will open it up to `FieldValue.increment` as well, which defeats the typescript typing.

 **Describe the solution you'd like**
I'd like `FieldValue.___` to return the [different underlying types](https://github.com/googleapis/nodejs-firestore/blob/b39dd3c65549fb1a651c1722d8ea2c038e152417/dev/src/field-value.ts#L257) instead of [returning the same type for all of its static operations](https://github.com/googleapis/nodejs-firestore/blob/2406f6adf938126b642482ec34cd1094920d0442/types/firestore.d.ts#L1804), preferably having `arrayUnion` and `arrayRemove` to allow for generics to type it even further.

 **Describe alternatives you've considered**
~~Augmenting the module to allow for it.~~ Augmenting the module isn't possible, since you can't [redefine a property to be more specific in typescript](https://stackoverflow.com/a/48692419/4806413). Instead, you would have to cast it to a custom type. Adds a burden to the project where Firestore could return a more specific type. It looks something like this:

```
export interface ArrayUnionTransform<T> extends FirestoreAdmin.FieldValue {
	elements: T[];
}

export interface ServerTimestampTransform extends FirestoreAdmin.FieldValue {
	type: 'ServerTimestampTransform';
}

export const arrayUnion = <T>(...args: T[]): ArrayUnionTransform<T> => FirestoreAdmin.FieldValue.arrayUnion(...args) as ArrayUnionTransform<T>;

export const serverTimestamp = (): ServerTimestampTransform => FirestoreAdmin.FieldValue.serverTimestamp() as ServerTimestampTransform;

```

**Comment by thebrianchen** [comment]
@saiichihashimoto Thanks for the suggestion! This is definitely something we can consider adding with our next breaking change release. How would you separate the different underlying types? I'm guessing a `arrayUnion` and `arrayRemove` would have the same underlying type, whereas `increment` and `serverTimestamp` would have different types as well.

Could you mock up a sample of how you intend to use this in a ts playground? That would be very helpful.

**Comment by saiichihashimoto** [comment]
`arrayUnion` and `arrayRemove` could take a generic, something like `arrayUnion<T>(args: ...T) => ArrayFieldValue`.

**Comment by saiichihashimoto** [comment]
I added a quick snippet of what I have to do to accomplish this.
