### ISSUE TITLE
What's the best way of recursively deleting a collection ?

### ISSUE THREAD

**Issue by ojm-it** [googleapis/nodejs-firestore#1603]
There are two options for recursively deleting a collection. Either :
- Use `firebase_tools.firestore.delete`
- Use `firestore.recursiveDelete`

What is the best way, in terms of price and performance, to recursively delete a collection? How many read/delete operations are performed by each of these solutions?

**Comment by thebrianchen** [comment]
@ojm-it Thanks for writing in!

>  How many read/delete operations are performed by each of these solutions?

Both the CLI delete and the `recursiveDelete()` functions will perform a read and a delete operation for each document deleted. 

> What is the best way, in terms of price and performance, to recursively delete a collection?

The actual performance varies based on the number, size, and key-range of documents you are deleting, and you'll have to perform your own benchmarks for your use case. The `recursiveDelete()` function has built in retry behavior, and allows you specify success and error handlers. Unlike the CLI-delete, which deletes documents in atomic batches, `recursiveDelete()` deletes documents in parallel. 

I'm going to mark this issue as closed but feel free to ask any other questions you may have.
