### ISSUE TITLE
Why are snapshot.updateTime & firebase.firestore.FieldValue.serverTimestamp() inconsistent

### ISSUE THREAD

**Issue by goleary** [googleapis/nodejs-firestore#1610]
I'm not sure if this is the best place to open this ticket as this seems like a platform level issue rather than a particular sdk.

That said, I'm very confused why setting a property to `firebase.firestore.FieldValue.serverTimestamp()` does not result in it being consistent with the `snapshot.updateTime`.

Here is an example of the offending behaviour: 
![image](https://user-images.githubusercontent.com/16123225/134411231-2f7ee21a-a101-4037-ad29-602a5584c07d.png)

If this is the latest update to the document, why is it that the `snapshot.updateTime` differs from the server generated timestamp form this property changing?

There are many instances where I'd like to be able to sort/filter based on document `updateTime` which already isn't possible without explicitly writing it into the documents themselves using the `serverTimestamp` sentinel.  The fact that these are not consistent makes it even more difficult to manage this behaviour & ensure that the document properties are being properly updated.

**Comment by schmidt-sebastian** [comment]
@goleary Thanks for filing this issue.

While we generally agree that this behavior is surprising, it is expected based on the underlying implementation. The `serverTimestamp()` sentinel gets evaluated at the beginning of request processing, while the `updateTime` represents when the document was written to our Storage layer. The difference in values represents the processing time between these two operations.

**Comment by goleary** [comment]
Thanks for your response!

Disappointed that this is how it's implemented. It would be lovely to be able to use `createTime` & `updateTime` for sorting/filtering and it seems to be impossible to actually write these values to the document which makes an implementation that relies on these being accurate much more difficult to achieve. 😭

**Comment by tilgovi** [comment]
@schmidt-sebastian sorry if I'm reviving a dead thread here, but can you say where the "storage layer" sits in relation to transaction coordination? Will multiple documents written in the same transaction or bulk write have the same `updateTime`?

**Comment by cherylEnkidu** [comment]
Hi tilgovi,

It is the same for Transaction and batched writes:

>The serverTimestamp() sentinel gets evaluated at the beginning of request processing, while the updateTime represents when the document was written to our Storage layer.

Also, all document inside single Transaction and Batched write will have the same `serverTimestamp()` and `updateTime`
