### ISSUE TITLE
listDocuments() return 100000 of array and that makes memory leak.

### ISSUE THREAD

**Issue by wimpykid719** [googleapis/nodejs-firestore#1616]
Hi!
Now I'm writing scripts for delete Firestore data.
My scripts deployed cloud functions memory is 1024MB.
and I had stack for memory leak.  

Because in my case `listDocuments()` makes 100000 of array data.
and return them at onetime. 

**So I want to limit the return data.**
Does `listDocuments()` have kind of option to limit the document data?

I'm using `listDocuments()` for making the delete path. 
Try to get Ids.

```
const dbColPath = 'collection/document/collection/document/collection/document/collection'
db.collection(dbColPath).listDocuments()
```

`/collection/document/collection/document/collection/document/collection/documents(The id is like this 20210930114547 this is almost random)/collection/documents(random ID)/field`

※ 20210930114547 it's a day of the data added.

and I think can't use Query API and limits(), startAt() because that documents doesn't have field.
Do you have any ideas? Please🙇🏻‍♂️

PS
I found  `listDocuments(request, optionsOrCallback)`  can take two value.
and request has pageSize options and tried to use them like this.
[firestore_client.ts#L1343](https://github.com/googleapis/nodejs-firestore/blob/4585b710c2e37dbe0c747c700949968c47bf84d0/dev/src/v1/firestore_client.ts#L1343)

```
const dbColPath = 'collection/document/collection/document/collection/document/collection'
const request = {pageSize: 3}
const docsRefs = await db.collection(dbColPath).listDocuments(request)
```

But noting happen to results. I think I'm missing somethings.
Please help me.

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
 **Describe the solution you'd like**
 **Describe alternatives you've considered**
 **Additional context**

**Comment by schmidt-sebastian** [comment]
To use https://github.com/googleapis/nodejs-firestore/blob/4585b710c2e37dbe0c747c700949968c47bf84d0/dev/src/v1/firestore_client.ts#L1343, you have to use the so called "Gapic" client. The `listDocuments()` method in the main Firestone API does not support limiting the number of results.

I believe that you can do something like this:

```
import { v1 } from `@google-cloud/firestore`;

const gapicFirestore = new v1.FirestoreClient();
const docs = gapicFirestore.listDocumentsAsync();

for await (let doc of docs) { 
    //
}
```

**Comment by wimpykid719** [comment]
I think is that same things. Probably docs value gets 100000 of array.
How to limit them?

You said `listDocuments()` doesn't support limiting the number of results.
But Is that reduce the file size with same array data?

Sorry I'm confusing.

> You can also use https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/v1/firestore_client.ts#L1343 directly, which lets you control the output size. It's a bit tricky to get started with though.

[fix: speed up listDocuments pagination](https://github.com/googleapis/nodejs-firestore/pull/1344#issuecomment-931408856)

**Comment by schmidt-sebastian** [comment]
Sorry I linked to the wrong method: https://github.com/googleapis/nodejs-firestore/blob/4585b710c2e37dbe0c747c700949968c47bf84d0/dev/src/v1/firestore_client.ts#L1510

This method returns an async iterator and does not capture all results in memory first. The code sample above shows the usage.

**Comment by wimpykid719** [comment]
Thank you.
I tried this code but I got error.

```
const Firestore = require('@google-cloud/firestore');
const gapicFirestore = new Firestore.v1.FirestoreClient({
    projectId: 'xxx',
    keyFilename: 'keyPath',
  })

const request = {
    pageSize: 3,
    parent: 'path/path/path/...'
  }
  const docsRefs = await gapicFirestore.listDocumentsAsync(request)
  for await (let doc of docsRefs) {
    console.log(doc)
}
```

error
```
(node:599) UnhandledPromiseRejectionWarning: Error: 3 INVALID_ARGUMENT: Invalid resource field value in the request.
    at Object.callErrorFromStatus (/my-root-folder/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/my-root-folder/node_modules/@grpc/grpc-js/build/src/client.js:179:52)
    at Object.onReceiveStatus (/my-root-folder/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/my-root-folder/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /my-root-folder/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:599) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:599) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by schmidt-sebastian** [comment]
Please match the request here: https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/reference.ts#L2526

`parent` should be a fully-qualified path that points to the location one level up, `collcectionId` is the collection you are interested in. For this to work, you may have to look at our REST API documentation for some guidelines.
