### ISSUE TITLE
Recurring DEADLINE_EXCEEDED errors using bulkWriter

### ISSUE THREAD

**Issue by trex-quo** [googleapis/nodejs-firestore#1625]
Error: 4 DEADLINE_EXCEEDED: Deadline exceeded at BulkWriterOperation.onError (/workspace/node_modules/@google-cloud/firestore/build/src/bulk-writer.js:95:37) at BulkCommitBatch.bulkCommit (/workspace/node_modules/@google-cloud/firestore/build/src/bulk-writer.js:192:36)

#### Environment details

  - OS: Ubuntu 18.04 (Firebase Cloud Functions)
  - Node.js version: 10
  - npm version: 6.14.14
  - `@google-cloud/firestore` version: 4.14.1

#### Steps to reproduce

Here is a small code sample that represents the cause of the error:
```
return apiRequest.then(res => {
   const bulkWriter = admin().firestore().bulkWriter();
   for (const obj of res.objects) {
      const databaseObject = formatObj(obj);
      bulkWriter.set(
         admin().firestore().doc(`path/${obj.id}`),
         databaseObject,
         { merge: true }
      )
   }
   
   return bulkWriter.close();
}
```

This code block succeeds >99% of the time, however it has failed with the above error more than 10 times in the past month, and we are using the most up-to-date version of Firestore that contains updates to the bulkWriter in the changelog. In some cases, we are only writing 50 objects to the database and still receiving the DEADLINE_EXCEEDED error, so we are unsure exactly what is causing this to happen. Any insight into the cause of this issue would be greatly appreciated. 

Thanks!

**Comment by schmidt-sebastian** [comment]
@trex-quo It is hard to say what is causing these errors. You seem to running into this on Cloud Functions. Are you able to provide us with the project ID and the timestamp of your invocation? The best way to do this is via a Support Request: https://cloud.google.com/support-hub

BulkWriter retries DEADLINE_EXCEEDED errors up to ten times. If you want to customize this behavior you can define your own error handler: https://cloud.google.com/nodejs/docs/reference/firestore/latest/firestore/bulkwriter#_google_cloud_firestore_BulkWriter_onWriteError_member_1_

**Comment by schmidt-sebastian** [comment]
Please let us know if setting your own retry handler does not resolve the issue. If you have specific questions about the state of your project, please reach out to us via Support Hub.
