### ISSUE TITLE
GPL2 License issue

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/nodejs-firestore#1636]
Hi 

There is a GPL2 licensing issue on `node-forge@0.10.0` which is the indirect dependency as below

@google-cloud/firestore@4.15.1 > google-gax@2.24.1 >  google-auth-library@7.10.1 > gtoken@5.3.0 > google-p12-pem@3.1.0 > node-forge@0.10.0 

[here](https://github.com/digitalbazaar/forge/blob/cbebca3780658703d925b61b2caffb1d263a6c1d/LICENSE) is the link to license page

**Comment by thebrianchen** [comment]
The license also specifies that BSD is allowed, which would fall under appropriate licensing requirements for this package. Marking this issue as closed, but feel free to ask any other question.

cc @rafikhan
