### ISSUE TITLE
firestore timestamp type error { _seconds _nanoseconds }

### ISSUE THREAD

**Issue by KoreanThinker** [googleapis/nodejs-firestore#1637]
#### Environment details

  - OS: intel mac
  - Node.js version: 14
  - npm version: 6.14.14
  - `@google-cloud/firestore` version: 4.5.1
  - I'm using firebase-admin : v10.0.0

#### Steps to reproduce

I don't know when happen...

I wraped every Date type with this `Timestamp`
```js
const Timestamp = (v) => admin.firestore.Timestamp.fromDate(v)
```
like this
```js
const newTime = Timestamp(new Date())
```

Basically it work well. but some time type broken like this

<img width="286" alt="스크린샷 2021-12-01 오후 10 16 45" src="https://user-images.githubusercontent.com/48207131/144243212-6d8c1eb3-2afb-47b2-a126-c38312725006.png">

I'm sorry, but I don't know how to reproduce it.

**Comment by dconeybe** [comment]
Hi @KoreanThinker. I'll take a look at this, but I have a few questions.

1. When you say "broken like this" what are you referring to? I see a screenshot but I'm not sure what's "broken" about it. Could you specify what you expect to see?
2. Could you provide a small code sample that I could use to reproduce? The extra context will be helpful for investigation.

Thank you.

**Comment by schmidt-sebastian** [comment]
@KoreanThinker We need more information to proceed. If you are able to provide answer's to @dconeybe please let us know and we will re-open the issue.

**Comment by mdinos** [comment]
Possibly related, began as an issue when upgrading to `v5.0.0`+ (nothing else was changed)

When testing an object with `jest` which has a `Timestamp` field...

<img width="338" alt="Screenshot 2022-01-10 at 16 26 48" src="https://user-images.githubusercontent.com/32902031/148801372-65b79ba3-1f45-4980-8604-28a279208f47.png">

Importing `Timestamp` as follows:

```node
const { Timestamp } = require('@google-cloud/firestore')
```

Asserting similar to this:
```node
const testObject = {
  // ... other stuff
  time: new Timestamp(),
}
const expectedStructure = {
  // ... other stuff
  time: expect.any(Timestamp)
}

expect(testObject).toMatchObject(expectedStructure)
```

**Comment by mdinos** [comment]
<img width="566" alt="Screenshot 2022-01-10 at 16 47 07" src="https://user-images.githubusercontent.com/32902031/148804578-3f0b2f5d-05fa-4c36-99dd-6620274e6a30.png">

Well now we have a new dependency issue, there is a vulnerability in a TLS library that Google use for all of its firebase libraries, which we need to wait for them to update. 

Essentially, we're waiting for https://github.com/googleapis/google-p12-pem/pull/384 to be merged and propagated through a bunch of repos...

I'll look into how to turn off low security vulnerabilities causing an exit in `npm ci` tomorrow.

**Comment by dconeybe** [comment]
@mdinos If you don't mind, could you create a brand new issue for your issue, and provide a link to this issue as a reference?
