### ISSUE TITLE
Firestore negative zero (-0) is stored as integerValue instead of doubleValue

### ISSUE THREAD

**Issue by Yonom** [googleapis/nodejs-firestore#1638]
This issue is about an inconsistency between the firestore JS SDK and the nodejs SDK. Firestore JS SDK stores negative zero (-0) has a double value with the correct sign. The NodeJS SDK does not do so. This leads to loss of data (the number's sign) as well as some odd behavior when trying to query documents saved from the JS SDK based on -0.

#### Environment details

  - OS: macOS
  - Node.js version: 16.13
  - npm version: 8.1
  - `@google-cloud/firestore` version: 4.15.1

#### Steps to reproduce

  1. write negative zero to a document

```js
await firestore.collection('test').doc('test').set({ number: -0 })
```

  2. read the document and ensure the value is negative zero

```js
const doc = await firestore.collection('test').doc('test').get();
const expectedToBeNegativeZero = doc.data().number;
console.assert(Object.is(expectedToBeNegativeZero, -0))
```

Firebase Web SDK: ✅ Works as expected
Firebase Node.JS SDK: ❌ Value is 0 instead of -0

**Comment by dconeybe** [comment]
Hi @Yonom. Thanks for the report. I'll take a look into it.

**Comment by Yonom** [comment]
@dconeybe thanks, I have also submitted a PR with a fix 👍
