### ISSUE TITLE
FR: Gerneric document/collection types

### ISSUE THREAD

**Issue by hannojg** [googleapis/nodejs-firestore#1644]
**Is your feature request related to a problem? Please describe.**

I've used the firestore client SDKs and there we can set the type for a document specifically, like this:
```js
firestore().doc<UserType>(`users/${userId}`)
```

The return type when we get this document's data is the `UserType` (or undefined). This gives great DX, as the data object isfully typed.

In the current type definitions for `nodejs-firestore` we don't have such generic types, and its always `DocumentData`.

 **Describe the solution you'd like**

It'd be great if we could also set generic types when working with our documents and collections, just as in the client SDKs. 

 **Describe alternatives you've considered**

To use `as` types in the code where you want to have full type support for the data object. However, I feel the types of this library should really be aligned with all the other SDKs/js libs.

 **Additional context**
/

**Comment by schmidt-sebastian** [comment]
Thanks for reporting this. This comes up quite a bit, but unfortunately we cannot support this directly. Here is an example:

```
class User {
   uid: string;

}

User user;

const userCollection = firestore.collection<User>("users");
const doc = userCollection.doc("userA");
await doc.set(user); // All good

user = (await doc.get()).data();
assert(user instanceof User) // This is now false
```

We cannot instantiate (or type-check) the generic type on the users behalf. This is why we cannot accept your contribution.

Please take a look at our converter support: https://github.com/googleapis/nodejs-firestore/blob/main/types/firestore.d.ts#L143
