### ISSUE TITLE
Update() requires either a single Javascript object or an alternating list of field/value pairs

### ISSUE THREAD

**Issue by judos** [googleapis/nodejs-firestore#1657]
#### Environment details

  - OS: win10 pro
  - Node.js version: 16.13.1
  - npm version: 8.1.4
  - `@google-cloud/firestore` version: 4.15.1

#### Steps to reproduce

From the api it's pretty clear that the following call should be valid, but it fails with an exception, possibly wrongly interpreting what parameter is what.

When I remove the precondition { exists: true } the call works.
ref is a DocumentReference and the document data already exists in the firestore.
```
const data = { migrated: false, creator: 'Test', title: 'test', type: 'document' };
const result = await this.ref.update(data, { exists: true });
```

Results directly in this exception:
```
[INFO]  [18:32:08] { migrated: false, creator: 'Test', title: 'test', type: 'document' }
[INFO]  [18:32:08] Request: 500 for POST /api/content-items/2pvHClRVTZVXOxSslhz9 Error
[ERROR] [18:32:08] Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "preconditionOrValues" is not a valid precondition. "exists" is not an allowed precondition.
    at WriteBatch.update (\node_modules\@google-cloud\firestore\build\src\write-batch.js:378:23)
    at DocumentReference.update (\node_modules\@google-cloud\firestore\build\src\reference.js:392:14)
    at DocumentReferenceWrapper.<anonymous> (\src\models\firebase\document-reference-wrapper.ts:48:37)
    at Generator.next (<anonymous>)
    at \src\models\firebase\document-reference-wrapper.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (\src\models\firebase\document-reference-wrapper.ts:4:12)
    at DocumentReferenceWrapper.update (\src\models\firebase\document-reference-wrapper.ts:30:16)
    at ContentItemController.<anonymous> (\src\controllers\content-item.controller.ts:41:17)
    at Generator.next (<anonymous>)
```

The error does not make sense for the typings provided by firestore.d.ts:
```
/**
     * Updates fields in the document referred to by this `DocumentReference`.
     * The update will fail if applied to a document that does not exist.
     *
     * Nested fields can be updated by providing dot-separated field path
     * strings.
     *
     * @param data An object containing the fields and values with which to
     * update the document.
     * @param precondition A Precondition to enforce on this update.
     * @return A Promise resolved with the write time of this update.
     */
    update(data: UpdateData, precondition?: Precondition): Promise<WriteResult>;
```

What is going wrong here? Is this really a wrong typing in the d.ts and I'm not supposed to use the method as documented?

**Comment by schmidt-sebastian** [comment]
Thanks for reporting. `Update()` only supports a `lastUpdateTime` precondition. `exists: true` is the default and should not be specified. The full error here is:

```
Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "preconditionOrValues" is not a valid precondition. "exists" is not an allowed precondition.
```

**Comment by judos** [comment]
So the parameter should be changed to UpdatePrecondition and then not contain the exists property. Otherwise it's confusing.

The error message actually says the 'exists' is not allowed but I didn't see that.

**Comment by barticus** [comment]
Hello,
I also ran into this. It is because the firebase types specify [this field here](https://github.com/googleapis/nodejs-firestore/blob/789d9eb7f54b5329b17ef759f29252d17da47e26/types/firestore.d.ts#L1127). If it is not the correct typing for that function call, can you use an Omit or something to remove that property for the update function?
