### ISSUE TITLE
Why do FieldValue.arrayUnion and FieldValue.arrayRemove fail when not at least one argument is provided?

### ISSUE THREAD

**Issue by jofas** [googleapis/nodejs-firestore#1682]
Hi,

I hope this is the right place to ask this question (I don't know if this is something that is not supported by firestore or the node.js client). I was trying to replace my local set union with a call to `FieldValue.arrayUnion`. My problem is, that the set I want to provide to `FieldValue.arrayUnion` can be empty, something that is not supported by the node.js client. This is an error:

```js
const admin = require("firebase-admin");
const firestore = require("firebase-admin/firestore");

async function main() {
  const ref = admin.firestore().collection("foo").doc("bar");
  
  const newElements = [];

  // Error: FieldValue.arrayUnion requires at least 1 argument
  await ref.update({"baz": firestore.FieldValue.arrayUnion(...newElements)});
}

main();
```

Could anyone tell me why `FieldValue.arrayUnion` and `FieldValue.arrayRemove` require at least one argument? From my vantage point, unionizing a set or array with an empty set is just a NOP and not a reason for failure. Same goes for removing no element from an array.

**Comment by schmidt-sebastian** [comment]
We want to make sure you do not trigger seemingly unexpected behavior:

```
ref.update({"baz": firestore.FieldValue.arrayUnion()});  // Charges you for a single write even though you didn't do anything
```

```
ref.set({"baz": firestore.FieldValue.arrayUnion()}, {merge:true);  // Creates an empty object
``` 

This is our reasoning. If there is significant demand to loosen our validation, we can do so. For now, I would prefer keeping the API as is. Hence, I am closing the issue - but we do appreciate your feedback.
