### ISSUE TITLE
FR: Make fieldPath in set method behave like in update method

### ISSUE THREAD

**Issue by sirkrisp** [googleapis/nodejs-firestore#1689]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**
set({"a.b.c": "xyz"}) creates a field "a.b.c" with value "xyz" whereas update({"a.b.c": "xyz"}) creates a nested Map field. I keep forgetting this difference and it's pretty annoying.

 **Describe the solution you'd like**
set({"a.b.c": "xyz"}) should create nested fields

**Comment by ehsannas** [comment]
Thanks for raising this @sirkrisp . As you have noticed in the documentation, `update` takes an [`UpdateData`](https://firebase.google.com/docs/reference/node/firebase.firestore#updatedata). This allows the user to update only a part of a nested map without touching the rest of the map. [`set`](https://firebase.google.com/docs/reference/node/firebase.firestore.DocumentReference#set), however, overwrites all contents of the document and therefore takes the data as a map. This has been a conscious design choice.

**Comment by sirkrisp** [comment]
As you know, `set` also takes the `merge` option as argument - and, thus, there are cases where a `set` operation does not overwrite all contents. It also leads to ambiguous cases (at least for end users): Imagine someone creates a document with a field "a.b" and a map "a" with key "b". So what should happen if you call `.update({"a.b": ...})`? Anyway, your choice. Cheers, Krispin
