### ISSUE TITLE
Increment does not reliably execute

### ISSUE THREAD

**Issue by goodspeed3** [googleapis/nodejs-firestore#1699]
#### Environment details

  - OS: Google Cloud Fxn
  - Node.js version: 14
  - npm version: 7.21.1
  - `@google-cloud/firestore` version: 4.15.1

#### Context
Increment does not reliably increment, even with distributed counters and <1 write/second.  Below, I pasted a log of one of the times that increment DID NOT work.  80-90% of the time, it works as expected, i.e., post-increment tokens is actually incremented as expected.  Note that I even delay reading post-increment tokens by 2 seconds to give system the time to process incrementing.

Here's my current structure:
/users/{userId}/shards/{shardId} contains all the increments split by shards.  This tracks all increments perfectly at the moment.  
In the users/{userId} doc, I have a 'tokens' property that I want to increment based on writes to the shard.  Again, sometimes this property is properly incremented most of the time, and for a minority of times, it is not.  There is no failure message, only success messages result.  There isn't a ton of write traffic either.

#### Steps to reproduce

  1. Increment tokens property in /users/{userId}/shards/{shardId}
  2. OnWrite of /users/{userId}/shards/{shardId}, increment token property on /users/{userId}

###
```
function incrementCounter(docRef, setObj, numShards = 5) {
    const shardId = Math.floor(Math.random() * numShards);
    const shardRef = docRef.collection('shards').doc(shardId.toString());
    return shardRef.set(setObj, {merge: true});
  }


async function verifyEmailHook() {
....
            const preUserRes = await db.collection("users").doc(userId).get()
            console.log(`preincrement ${tokensIssued} tokens ${userId}: ${preUserRes.data().tokens}`  )

            await incrementCounter(db.collection("users").doc(userId), {
                tokens: admin.firestore.FieldValue.increment(tokensIssued),
                totalTasksVerified: admin.firestore.FieldValue.increment(numTasksVerified),
                totalTasksRejected: admin.firestore.FieldValue.increment(numTasksRejected)
            })

            await new Promise(resolve => setTimeout(resolve, 2000));
            const postUserRes = await db.collection("users").doc(userId).get()
            console.log(`postincrement tokens ${userId}: ${postUserRes.data().tokens}`  )

...
}
```

Logs with userId removed:
```
2022-03-14 11:03:04.932 PDT
verifyEmailHook
4k0j8pr572p2
preincrement 50 tokens: 20
Default
2022-03-14 11:03:05.047 PDT
tokenShardHandler
3yrngex062ag
user before { tokens: 0 } after { tokens: 50, totalTasksVerified: 1 }
Default
2022-03-14 11:03:05.047 PDT
tokenShardHandler
3yrngex062ag
Shard: 0 incrementing tokens by 50 
Default
2022-03-14 11:03:05.047 PDT
tokenShardHandler
3yrngex062ag
Shard: 0 incrementing totalTasksVerified by 1 
Default
2022-03-14 11:03:07.046 PDT
verifyEmailHook
4k0j8pr572p2
postincrement tokens: 20 // <---------- NOTE: THIS SHOULD SAY 70!!
```

```


exports.tokenShardHandler = functions.firestore
.document('users/{userId}/shards/{shardId}')
.onWrite(async (change, context) => {

    //whenever there's a change
    if (!change.before.exists || (change.before.exists && change.after.exists)) {
        const db = admin.firestore();
        let beforeData = change.before.data()
        let afterData = change.after.data()
        console.log("user", context.params.userId, "before", beforeData, "after", afterData)
        const userObjUpdate = {}
        for (let key of Object.keys(afterData)) {
            if (!afterData[key] || afterData[key] === 0) continue
            if (!beforeData || !beforeData[key]) {
                console.log(`Shard: ${context.params.shardId} incrementing ${key} by ${afterData[key]} for ${context.params.userId}`)
                userObjUpdate[key] = admin.firestore.FieldValue.increment(afterData[key])

            } else if (afterData[key] > beforeData[key]) {
                console.log(`Shard: ${context.params.shardId} incrementing ${key} by ${afterData[key] - beforeData[key]} for ${context.params.userId}`)

                userObjUpdate[key] = admin.firestore.FieldValue.increment(afterData[key] - beforeData[key])
            }
        }
        if (Object.keys(userObjUpdate).length > 0) {
            console.log(userObjUpdate)
            await db.collection("users").doc(context.params.userId).update(userObjUpdate)
        }
    
    }
})

```

**Comment by dconeybe** [comment]
@goodspeed3 Thank you for reporting this issue. I'm trying to follow your code but it's a bit hard to wrap my head around and fill in the blanks. Would it be possible to create a standalone app that reproduces the issue that I could clone and reproduce for myself? What you're describing is definitely undesirable behavior.

**Comment by goodspeed3** [comment]
Thanks for the response.  Turns out there was another long running function writing to the tokens property with stale data that was overwriting over the properly incremented value.

**Comment by dconeybe** [comment]
Glad you were able to solve the problem. All the best!
