### ISSUE TITLE
collection.add() function crashes on objects with keys containing undefined values

### ISSUE THREAD

**Issue by Glorifundel** [googleapis/nodejs-firestore#1730]
I ran into a difficult issue to troubleshoot when attempting to add an event to a firestore collection which is being used as a logging mechanism.  Specifically I found that objects which contained key/value pairs where the value was undefined was causing the add() function to crash  (no reason provided by a catch block)

Example (when the limit parameter is not provided / undefined):
import {Firestore} from '@google-cloud/firestore';

const firestore = new Firestore('someproject')

const ExampleApi: HttpFunction = (req, res) => {
  const limit = req.parameters.limit;  // undefined
  const user= req.parameters.user;  // "bill"
  const log = { user, limit }  // { user: 'bill', limit: undefined }

  firestore.collection('api-log').add(log)  // crash on add(log) due to limit being undefined
}

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

1) Is this a client library issue or a product issue?

client library issue, I think its reasonable that this case is addressed.  ( JSON.parse() handles this case fine )

2) Did someone already solve this?
  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
No entry related to this issue.
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
No entry related to this issue.
  - Search or ask on StackOverflow (engineers monitor these tags): http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
I can "fix" it by scrubbing for undefined values in objects, but the client should accept this input.

3) Do you have a support contract?
Please create an issue in the [support console](https://cloud.google.com/support/) to ensure a timely response.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS:  Cloud Function
  - Node.js version:  Nodje.js 17
  - npm version:  Whatever CF uses
  - `@google-cloud/firestore` version:    "@google-cloud/firestore": "^5.0.2",

#### Steps to reproduce

See above

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by wu-hui** [comment]
This is intended behavior, you can disable this with a custom setting here: https://googleapis.dev/nodejs/firestore/latest/Firestore.html#Firestore

This has to be on a global level however.

**Comment by Glorifundel** [comment]
Thank you for the response Wu-Hui!

I'll move forward with ensuring all content is appropriately scrubbed since this is not considered a bug.  I'm hesitant to use a global parameter to circumvent standard behavior.
