### ISSUE TITLE
query.onSnapshot doesn't seem to support async callbacks

### ISSUE THREAD

**Issue by anindha** [googleapis/nodejs-firestore#1737]
Can the onNext callback we can pass to onSnapshot be asynchronous? Please see the wrapper we wrote around the onSnapshot call.

```javascript
const docListener = (docRef, callback) => {
	try {
		return docRef.onSnapshot(async (snapshot) => {
			await callback(snapshot.exists ? snapshot.data() : null);
		});
	} catch (err) {
		logger.error(err);
	}
};

const queryListener = (query, callbacks) => {
	try {
		return query.onSnapshot(async (snapshot) => {
			let changes = snapshot.docChanges();
			for (let change of changes) {
				const callback = callbacks[change.type];
				if (callback) {
					await callback(change.doc.id, change.doc.data());
				}
			}
		});
	} catch (err) {
		logger.error(err);
	}
};
```

**Comment by MarkDuckworth** [comment]
Passing an async onNext to onSnapshot(onNext) should not be a problem. Are you experiencing an issue?

I cannot provide feedback on your overall implementation. Please see the following resources, which may help you evaluate your code: 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function
- https://github.com/googleapis/nodejs-firestore/blob/ce9abfd8cd65d0d2be4dd7f6a56fb679a100296a/dev/src/reference.ts#L2380

**Comment by MarkDuckworth** [comment]
If you believe there is an issue, please reply with a description of the expected and actual behavior, steps to reproduce, library version, and os version.

**Comment by MarkDuckworth** [comment]
> Can you confirm that await is being used for onNext?

It is not. See my previous reply for the link if you are interested in reviewing the source for `onSnapshot()`. 

I'm unable to determine where you are seeing unexpected behavior in the SDK. Perhaps you can provide a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the problem?

**Comment by anindha** [comment]
@MarkDuckworth The behaviour is expected seeing the onNext is not being await'd. Would it be possible to add await to onNext call for the Node and web client libraries?

**Comment by MarkDuckworth** [comment]
We're still not connecting on what you are trying to accomplish. I do understand that you want the library to behave something like 
````
onSnapshot(onNextAsync) {
   ...
   await onNextAsync(...);
````

I do not understand why? Can you please clarify your use case for this? Are you expecting this to allow your outer `try {...} catch` to catch an error thrown in `onNext`?

**Comment by anindha** [comment]
Our `onNext` callback is async so if the client library doesn't add `await` then code within our callback will behave synchronously without awaiting. Here is a snippet of a callback we have:
```javascript
const callback = async (data) => {
	if (data?.deviceRtpCapabilities) {
		this.#deviceRtpCapabilities = data.deviceRtpCapabilities;
		this.#producerTransport = await new TransportManager(this.#router, this.#refs.producerTransport());
		this.#consumerTransport = await new TransportManager(this.#router, this.#refs.consumerTransport());

		this.#producerStore = await new ProducerStore(this.#publish, this.#unpublish, this.#producerTransport, this.#refs);
		this.#consumerStore = await new ConsumerStore(
			this.#subscribe,
			this.#consumerTransport,
			this.#router,
			this.#deviceRtpCapabilities,
			this.#refs.consumers()
		);
	}
};
```

**Comment by anindha** [comment]
This was a bug on our part. Sorry for the confusion and thanks for your help @MarkDuckworth. We were missing an async/await.

**Comment by MarkDuckworth** [comment]
Happy to hear that you fixed it @anindha! Thanks for the follow up.
