### ISSUE TITLE
RetryOptions is not a constructor

### ISSUE THREAD

**Issue by michaelAtCoalesce** [googleapis/nodejs-firestore#1780]
getting the following error on setting a document. 

TypeError: require(...).RetryOptions is not a constructor 

![image](https://user-images.githubusercontent.com/96628583/192048983-e5d063b2-0c30-4dcb-adc6-a2a8a8ba8601.png)

"@google-cloud/firestore@^5.0.2":
  version "5.0.2"
  resolved "https://registry.yarnpkg.com/@google-cloud/firestore/-/firestore-5.0.2.tgz#36923fde45987f928a220d347f341c5602f9e340"
  integrity sha512-xlGcNYaW0nvUMzNn2+pLfbEBVt6oysVqtM89faMgZWkWfEtvIQGS0h5PRdLlcqufNzRCX3yIGv29Pb+03ys+VA==
  dependencies:
    fast-deep-equal "^3.1.1"
    functional-red-black-tree "^1.0.1"
    google-gax "^2.24.1"
    protobufjs "^6.8.6"

**Comment by tom-andersen** [comment]
Thank you for reaching out to us!

I looked into the code and found the likely culprit to be a line that was recently changed.

I think you are running version 5.0.2 from before the change was released in version 6.2.0 on September 13, 2022. Could you try using a more recent version of Firestore SDK?

**Comment by tom-andersen** [comment]
Thanks for reporting this issue! There does not seem to be any further action item on this issue and hence we are closing it. Please feel free to reopen this issue or file a new one if you need further assistance.
