### ISSUE TITLE
Missing `protos` types

### ISSUE THREAD

**Issue by hspak** [googleapis/nodejs-firestore#1782]
#### Environment details

  - OS: macOS (12.6)
  - Node.js version: v16.16.0
  - npm version: 8.11.0
  - `@google-cloud/firestore` version: 6.0.0 and 6.3.0
  - Typescript: 4.7.4

#### Steps to reproduce

[Unlike some other `@google-cloud/` client libraries](https://github.com/googleapis/nodejs-functions), this one doesn't appear to export `protos`. Some types are completely inaccessible because of this.

Example
```ts
import { v1, protos } from '@google-cloud/firestore'; // Would be great to have protos access here

const client = new v1.FirestoreAdminClient();
const someOpName = '<insertSomeOpName>';
const resp = await client.checkExportDocumentsProgress(someOpName);

// Despite `checkExportDocumentsProgress` having the following type signature:
//
//   checkExportDocumentsProgress(
//     name: string
//   ): Promise<
//     LROperation<
//       protos.google.firestore.admin.v1.ExportDocumentsResponse,
//       protos.google.firestore.admin.v1.ExportDocumentsMetadata
//     >
//   >; 
//
// Typescript is believes the metadata type is the generic interface Metadata:
// 
//   error TS2339: Property 'outputUriPrefix' does not exist on type 'Metadata'.
//
// So it would be great if we can provide this type hint to avoid this issue.
// But 'protos' is not exported so I'm not sure how to access this type.
const meta: protos.google.firestore.admin.v1.ExportDocumentsMetadata = resp.metadata;
```

**Comment by tom-andersen** [comment]
Thank you for the suggestion.

I brought this up for team discussion, and will let you know whether this is a change we want.

I am a little concerned about calling Firestore service with gRPC directly. Is there a reason you aren't using the SDK? Some Firestore protos have fairly complicated semantics, so I am of the opinion that calls should be made through SDK to avoid this trouble. I would rather we improve SDK.

**Comment by hspak** [comment]
Thank you for the prompt response!

>I am a little concerned about calling Firestore service with gRPC directly. Is there a reason you aren't using the SDK?

I don't think I quite understand -- the snippet I shared does use the SDK. This proposal is to expose the type so that Typescript can use the correct type (I've had to resort to an `as any` cast to access `outputUriPrefix` without Typescript complaining).

If there's a better way to satisfy Typescript without exposing the protos definitions, that would be great as well!

**Comment by tom-andersen** [comment]
The SDK I am referring to is the `const firestore = new Firestore(...)` client.
https://github.com/googleapis/nodejs-firestore#using-the-client-library

But after looking a little closer, I realize, the _admin_ protos aren't covered by the SDK.

The gRPC client that you are using is simply generated from the published protos found here: https://github.com/googleapis/googleapis/tree/master/google/firestore/admin/v1

You could roll your own.

In the meantime, I will see if we can better expose the _admin_ protos you are referencing.

**Comment by tom-andersen** [comment]
Use:

```
import { Metadata } from 'google-gax';
```

Then you can write:

```
let metadata: Metadata | null = resp.metadata;
```
