### ISSUE TITLE
GeoPoint type conflicting with geo field generation in firestore database

### ISSUE THREAD

**Issue by bidoubiwa** [googleapis/nodejs-firestore#1799]
## Issue

When creating a `geoPoint` type field in my firestore collection, it suggests adding a `latitude` and a `longitude`. These are then named `_latitude` and `_longitude` behind the curtain.

For example, when creation a field called `myGeoPoint`, inside a `onWrite` hook, the provided document has the following format
```
{
   "myGeoPoint": {
       "_latitude": 1, 
      "_lonigude: 2
}
```

Nonetheless, in the types provided by `firebase-admin/lib/firestore` which itself fetches the types from this repository, the GeoPoint is declared as follows:

https://github.com/googleapis/nodejs-firestore/blob/bcaecb45b7911073bb968542df0267ba81d4462d/types/firestore.d.ts#L548-L566

Which creates a type conflict when developing my extension using the provided types from `firebase-admin/lib/firestore`.

I can see, however, that in the `dev` folder, the type is already updated to the new behavior:

https://github.com/googleapis/nodejs-firestore/blob/53801bdfc234a7a94f6f5b86b842ea329da48152/dev/src/geo-point.ts#L31-L33

#### Environment details

  - OS: iOS
  - Node.js version: v16.15.1
  - npm version:
    "firebase-admin": "^11.3.0", which uses "@google-cloud/firestore" "^6.4.0"
    "firebase-functions": "^3.16.0",

**Comment by tom-andersen** [comment]
Thanks for reaching out. I will be looking into this to see if there is a good workaround and also see how we can improve the API.

**Comment by tom-andersen** [comment]
I think I might be missing a little context here, but I don't quite understand the problem.

The following defines the type for purposes of type checking.
[nodejs-firestore/types/firestore.d.ts](https://github.com/googleapis/nodejs-firestore/blob/bcaecb45b7911073bb968542df0267ba81d4462d/types/firestore.d.ts#L548-L566)

The implementation below adheres to the above type.
[nodejs-firestore/dev/src/geo-point.ts](https://github.com/googleapis/nodejs-firestore/blob/53801bdfc234a7a94f6f5b86b842ea329da48152/dev/src/geo-point.ts#L31-L33)

The internal representation of `_latitude` and `_longitude` should be ignored and not used as it is an internal detail of the implementation. In fact, I believe TypeScript should prevent you from accessing them. There are getters for `latitude` and `longitude` on this class that should satisfy the type and provide access to values.

When you create GeoPoints, use the constructor:

```
{
   "myGeoPoint": new GeoPoint(1, 2)
}
```

Please provide a little more context if I misunderstood anything.

**Comment by tom-andersen** [comment]
@bidoubiwa

I took a look at issue you reference.

> Install Meilisearch Firestore extension. [Search queries return correct results, including "_geo" fields but with "_latitude" & "_longitude". - [Works]

The above comment that fields "_latitude" & "_longitude" are returned seems to indicate the adaptor is not run, since you rename those properties.

> Add test documents with _geo in Firestore. - [Works]

How exactly are documents being added?

As far as I can tell, the adaptor you have written should work, so long as data is Firestore truly is `GeoPoint`s. There are getters on the `geoPoint` instance. However, if you use something like JSON.stringify, you will see the internal properties:
https://github.com/googleapis/nodejs-firestore/blob/53801bdfc234a7a94f6f5b86b842ea329da48152/dev/src/geo-point.ts#L62-L81

Can you verify that GeoPoints and not simply maps are written to firestore?

**Comment by baek-b** [comment]
@tom-andersen 

I'm adding test documents to firebase manually through the firebase console. I can confirm the data is of type Geopoint. Below are the screenshots of data from the firebase console and from an API call post-sync with meilisearch database.  This field is renamed within the adapter [here](https://github.com/meilisearch/firestore-meilisearch/blob/main/functions/lib/adapter.js). However, latitude and longtitude value are not adapted to lat and lng respectively.

<img width="865" alt="image" src="https://user-images.githubusercontent.com/13601357/205056598-3ffebb44-373a-4bbf-8a3c-26141762cedd.png">


<img width="444" alt="image" src="https://user-images.githubusercontent.com/13601357/205056521-a80213c4-cca7-475d-8fd2-4e9711f6b616.png">

**Comment by tom-andersen** [comment]
Are you able to demonstrate problem with GeoPoints in a simple example?

I was able to create a Cloud Function that successfully logs GeoPoint data. I use the console to create/update documents, and the cloud function produces expected log messages.

```
import * as functions from "firebase-functions";
import * as firestore from "firebase-admin/firestore";

exports.logGeoPoint = functions.firestore.document("/messages/{documentId}")
    .onUpdate((snap, context) => {
      const after = snap.after.data();
      if (!after) return Promise.resolve();
      const geo = after._geo;
      if (geo instanceof firestore.GeoPoint) {
        functions.logger.log("GEO", geo.latitude, geo.longitude);
      } else {
        functions.logger.log("OTHER", geo);
      }
      return Promise.resolve();
    });
```

**Comment by bidoubiwa** [comment]
Mmmh, indeed.

```js
import * as functions from 'firebase-functions'
import * as firestore from 'firebase-admin/firestore'

export const indexingWorker = functions.handler.firestore.document.onWrite(
  async (snap: functions.Change<DocumentSnapshot>): Promise<void> => {
    const after = snap.after.data()

    if (!after) return Promise.resolve()

    console.log({ after }) // >  { after: { _geo: GeoPoint { _latitude: 0, _longitude: 0 } } }

    const geo = after._geo
    if (geo && geo instanceof firestore.GeoPoint) {
      functions.logger.log('GEO', geo.latitude, geo.longitude)
    } else {
      functions.logger.log('OTHER', geo)
    }
})
```

It does enter the `if` and `geo.latitude` and `geo.longitude` correctly printed. Is this a javascript thing that I'm missing? Sorry if it is.
Seems like my IDE was also misleading me. 

<img width="1338" alt="Screenshot 2022-12-05 at 13 15 59" src="https://user-images.githubusercontent.com/33010418/205635153-714958b6-2fe2-4f62-8f0c-b3a5f8427e6a.png">


Anyway, it works! Thanks a lot for your patience

**Comment by bidoubiwa** [comment]
Hey! Sorry to come back with this. What is your version of firestore-admin? While doing `yarn build` builds the plugin correctly, I'm not able to run the tests: 

>     Cannot find module 'firebase-admin/firestore' from '__tests__/adapter.test.ts'

**Comment by busybox11** [comment]
Hi @tom-andersen, sorry to ping you - hope this isn't bothering you.

I still have the same issue as described here and in #33.

How am I supposed to properly handle this situation in my data structure types? I have already defined a custom `FirestoreGeoPoint` object with the following definition:
```ts
type FirestoreGeoPoint = {
	_latitude:  number;
	_longitude: number;
}
```

`firebase-admin/firestore` returns a standard JS object with `{ _latitude, _longitude }` properties when fetching a document, but initializing a new GeoPoint object via the class doesn't expose those properties - which causes a TypeScript error, because my data structure expects a `FirestoreGeoPoint`.

Do I have to update all my functions and data structures to handle GeoPoint classes, or is there a proper way to make the currently defined types as-is while being able to create and set new GeoPoints with them?

Again, I hope this isn't bothering you. I feel like I'm missing something here - but it's been hours (maybe even days) and I still can't wrap my head around this, lol. Thank you for your  time!

**Comment by MarkDuckworth** [comment]
@busybox11,

It sounds one place in your application you are making REST/gRPC calls and parsing the result to an object of your type `FirestoreGeoPoint`. Then elsewhere in your application you are using the Firestore SDK which accepts/returns a `GeoPoint` instance. Your `FirestoreGeoPoint` type and the `GeoPoint` class don't have the same interface. If you want a common interface, you will have to convert one type to the other.

The Firestore Node SDK has feature [FirestoreDataConverter](https://googleapis.dev/nodejs/firestore/latest/global.html#FirestoreDataConverter) which may be helpful for you to convert the `GeoPoint` class to your `FirestoreGeoPoint` type when reading or writing with the Firestore SDK.

**Comment by busybox11** [comment]
@MarkDuckworth thank you for your answer!

I am retrieving the JSON-encoded firebase object from my app via the REST API. It automatically converts the GeoPoint to the _latitude and _longitude obj. 

I did not know about the FirestoreDataConverter, thank you so much for sharing this! It will be very useful for compatibility while I entirely migrate to a monorepo with actual GeoPoint objects. It looks like this is exactly what I need.
