### ISSUE TITLE
runTransaction delaying ~2 seconds before beginning transaction callback

### ISSUE THREAD

**Issue by jamesw6811** [googleapis/nodejs-firestore#1824]
1) Is this a client library issue or a product issue?
client

2) Did someone already solve this?
Looked everywhere, couldn't find.

3) Do you have a support contract?
No.

If the support paths suggested above still do not result in a resolution, please provide the following details.

#### Environment details

  - OS: Ubuntu using a container: mcr.microsoft.com/devcontainers/javascript-node:0-18
  - Node.js version: 18.13.0
  - npm version: 8.19.3
  - `@google-cloud/firestore` version: "@google-cloud/firestore": "^6.4.2",

#### Steps to reproduce

  1. Run this code:
 
```

import {Firestore} from '@google-cloud/firestore';
const db = new Firestore();

...

const ref = db.collection("activeGrids").doc(coordsToText(x,y));
    console.log("beginning Firestore transaction " + new Date().getTime())
    const {gridserveraddress, needToAllocate} = await db.runTransaction(async (t) => {
        console.log("recieved Firestore transaction doc get start " + new Date().getTime());
        const doc = await t.get(ref);
        console.log("recieved Firestore transaction doc get end " + new Date().getTime());
        const response = {gridserveraddress:null, needToAllocate:false};
        if (doc.exists) {
            if (doc.data().status==="running"){
            response.gridserveraddress = doc.data().address;
            }
        } else {
            t.set(ref, {gridXY: coordsToText(x,y), gridX: x.toString(), gridY: y.toString(), status: "allocating", address: "allocating"});
            response.needToAllocate = true;
        }
        return response;
    });
```

receive this console log:

beginning Firestore transaction 1676082651327 (t=0 seoncds)
recieved Firestore transaction doc get start 1676082653102 (t+1.8 seconds)
recieved Firestore transaction doc get end 1676082653235 (t+1.9 seconds)

**Comment by milaGGL** [comment]
Hi @jamesw6811, thank you for this bug report. I'll take a look and keep you updated on the progress.

**Comment by milaGGL** [comment]
Hi @jamesw6811, there are multiple reasons could have contributed to the delay.
1. To be able to run a transaction, there is a separate request send to backend first, and this might have contributed to the 2 seconds a bit.  Please check where your app is running, and to best ensure low latency, use server client libraries from a [Google Cloud compute product as close to your Cloud Firestore database as possible](https://cloud.google.com/about/locations#products-available-by-location).
2. Server SDKs uses [pessimistic concurrency controls](https://firebase.google.com/docs/firestore/transaction-data-contention#data_contention_in_the_server_client_libraries).This means there are locks being placed on backed.  If this is the problem, you could try to implement your own optimistic concurrency with preconditions. Or maybe you could switch to web client that has optimistic concurrency. 
3. Another cause might be the number of transactions running per second. There is a soft [limit](https://firebase.google.com/docs/firestore/quotas#writes_and_transactions) of 500/second write rate to the same collection, to ensure better performance.  Could you please check 
     * How many transaction are you running per second?
     * How many concurrent clients are you running?
     
     
If the points above haven't been able to solve the problem, could you please enable debug log with [firebase.firestore.setLogLevel('debug')](https://firebase.google.com/docs/reference/js/firestore_#setloglevel) on your app, and send the log output to me? You can paste it here (redacting any sensitive information) or email it to me at [milamamat@google.com](mailto:milamamat@google.com).

**Comment by jamesw6811** [comment]
Thanks Mila, this is helpful. This is in my local dev environment, so I'll report back if the delay persists running on cloud compute.
