### ISSUE TITLE
Update DocumentSnapshot and QueryDocumentSnapshot to use Typescript strict mode

### ISSUE THREAD

**Issue by lordalisat** [googleapis/nodejs-firestore#1828]
Currently, the QueryDocumentSnapshot overwrites DocumentSnapshot with exists: true and removes undefined versions. In DocumentReference queries, however, after checking 'exists', the data() is incorrectly identified as possibly undefined. 
My suggestion would be to add separate classes with `exists=true` and `exists=false`, and add a combining type so typescript correctly identifies the optional fields to exist. 

```js
  /**
   * A `DocumentSnapshot` contains data read from a document in your Firestore
   * database. The data can be extracted with `.data()` or `.get(<field>)` to
   * get a specific field.
   *
   * For a `DocumentSnapshot` that points to a non-existing document, any data
   * access will return 'undefined'. You can use the `exists` property to
   * explicitly verify a document's existence.
   */
  export class ExistingDocumentSnapshot<T = DocumentData> {
    protected constructor();

    /** True if the document exists. */
    readonly exists: true;

    /** A `DocumentReference` to the document location. */
    readonly ref: DocumentReference<T>;

    /**
     * The ID of the document for which this `DocumentSnapshot` contains data.
     */
    readonly id: string;

    /**
     * The time the document was created. Not set for documents that don't
     * exist.
     */
    readonly createTime: Timestamp;

    /**
     * The time the document was last updated (at the time the snapshot was
     * generated). Not set for documents that don't exist.
     */
    readonly updateTime: Timestamp;

    /**
     * The time this snapshot was read.
     */
    readonly readTime: Timestamp;

    /**
     * Retrieves all fields in the document as an Object. Returns 'undefined' if
     * the document doesn't exist.
     *
     * @return An Object containing all fields in the document.
     */
    data(): T;

    /**
     * Retrieves the field specified by `fieldPath`.
     *
     * @param fieldPath The path (e.g. 'foo' or 'foo.bar') to a specific field.
     * @return The data at the specified field location or undefined if no such
     * field exists in the document.
     */
    get(fieldPath: string | FieldPath): any;

    /**
     * Returns true if the document's data and path in this `DocumentSnapshot`
     * is equal to the provided one.
     *
     * @param other The `DocumentSnapshot` to compare against.
     * @return true if this `DocumentSnapshot` is equal to the provided one.
     */
    isEqual(other: DocumentSnapshot<T>): boolean;
  }
  
  export class NonExistingDocumentSnapshot<T = DocumentData> {
    protected constructor();

    /** True if the document exists. */
    readonly exists: false;

    /** A `DocumentReference` to the document location. */
    readonly ref: DocumentReference<T>;

    /**
     * The ID of the document for which this `DocumentSnapshot` contains data.
     */
    readonly id: string;

    /**
     * The time this snapshot was read.
     */
    readonly readTime: Timestamp;
  }

  export type DocumentSnapshot<T = DocumentData> = ExistingDocumentSnapshot<T> | NonExistingDocumentSnapshot<T>
```

**Comment by tom-andersen** [comment]
Thank you for the suggestion!

A more narrow the return type does seem like an improvement.

For this to be seriously considered we need to see how this will simplify usage. At this point, since the return type of methods is DocumentSnapshot, I don't see how this helps. People will still need to check type being calling the `data()` method, if I understand correctly. How is this different that calling exists()?

If you can demonstrate the pain point, and how this change will simplify usage, then we can keep that in mind when making future changes. We are always looking for good suggestions!

**Comment by lordalisat** [comment]
The problem I currently have with calling the data() type after exists is that the following flow will not compile correctly with typescript, because data() can be undefined according to the type.
```js
const doc= await db
    .collection(USER_COLLECTION)
    .doc(id)
    .get();
  if (!doc.exists) {
    throw new Error("User does not exist");
  }
  const user = doc.data();
  return user.name;
```

While this can be solved by explicitly casting doc.data() to DocumentData (or some other type if using a converter), this removes the type safety and would make the following valid typescript code as well, while this could result in a runtime error.

```js
const doc= await db
    .collection(USER_COLLECTION)
    .doc(id)
    .get();
  const user = doc.data() as DocumentData;
  return user.name;
```

**Comment by dconeybe** [comment]
Drive-by comment: What about checking `user === undefined` instead of `doc.exists`? It's not a perfect solution but fixes the typing issue.

i.e.

```ts
const doc= await db
  .collection(USER_COLLECTION)
  .doc(id)
  .get();
const user = doc.data();
if (!user) {
  throw new Error("User does not exist");
}
return user.name;
```

At the line `return user.name` the TypeScript compiler will assume that `user` is _not_ `undefined` because if it were then it would have entered the "if" block above and terminated the function with an exception.

**Comment by lordalisat** [comment]
While I have been doing that myself to fix this issue, the current documentation states that you should use `docSnap.exists`, which has caused some confusion before at work.

**Comment by tom-andersen** [comment]
This cause of issue appears to be with documentation. Please use the feedback link on documentation that caused confusion.

The suggested change would prevent existing code from compiling, and is therefore a breaking change. It would prevent existing usage pattern of checking `data() === undefined`, and for that reason we won't be moving ahead with this change.
