### ISSUE TITLE
[FR] Improve serialization of the Timestamp object

### ISSUE THREAD

**Issue by mamichels** [googleapis/nodejs-firestore#1835]
This FR is in regard to the serialization of an Firestore document containing Firestore specific `Timestamp` objects.

Currently a document with a `Timestamp` object will serialize to something like:
```json
{
    "foo": "bar",
    "date": {
        "_nanoseconds": 894092000,
        "_seconds": 1673957525
    }
}
```
It not only leaks private fields of the given `Timestamp`, any consumer may hardly do anything useful with this data.
In (my) ideal scenario we would serialize this `Timestamp` into an UTC string. As a result the former example would look like this:
```json
{
    "foo": "bar",
    "date": "2023-01-01T00:00:00.000Z"
}
```

As per my understanding this should be a minor change within the implementation of `Timestamp`, but I cannot grasp any possible indirect implications. 
Would you say we should give it a go or do you already foresee major blocking issues here?

**Comment by mamichels** [comment]
Oh, seems like I missed something. This is in regard to using `JSON.stringify` e.g. if directly used on a firestore document.
```js
const doc = await new Firestore().collection("foo").doc("bar").get();
console.log(JSON.stringify(doc.data()));
```

For some context, the issue came up when using Firestore documents which are further published to PubSub, which requires the object to be of type `Buffer`. E.g.: https://github.com/googleapis/nodejs-pubsub/blob/main/samples/publishMessage.js#L48

**Comment by dconeybe** [comment]
Ok thank you @mamichels. I'll take a closer look at this next week.

**Comment by dconeybe** [comment]
After discussing as a team, we decided to put this request into our feature backlog. As a result, we don't have a time frame for this being implemented, if ever. We need to better understand the implications of this change, especially for use cases that may do "cloning" of Timestamp objects using `JSON.parse(JSON.stringify(x))`.

In the meantime, you can get the desired behavior yourself by specifying a `replacer` argument to `JSON.stringify()`, like this:

```js
const replacer = (key, value) => {
  if (value instanceof Firestore.Timestamp) {
    return value.toDate().toISOString();
  }
  return value;
}

JSON.stringify(obj, replacer);
```
