### ISSUE TITLE
Firestore Filter.OR clarification

### ISSUE THREAD

**Issue by danReynolds** [googleapis/nodejs-firestore#1845]
Super exciting to see OR queries support! https://github.com/googleapis/nodejs-firestore/pull/1800. I have a clarifying question. In the past, I've been able to chain filters like so:

```
collection
  .where('first_name', '==', 'Luke')
  .where('last_name', '==', 'Skywalker')
```

But with OR queries, this doesn't seem to work:

```
collection
  .where('first_name', '==', 'Luke')
  .where(
    Filter.or(
      Filter.where('last_name', '==', 'Skywalker'),
      Filter.where('last_name', '==', 'Vader'),
    )
  )
```
I would expect chained `where` filters to implicitly be an AND filter, but instead this just doesn't recognize the `first_name` filter and just applies the filters in the OR.

I don't see any examples of chained `where` filters with ORs in the tests either: https://github.com/googleapis/nodejs-firestore/pull/1800/files#diff-125d2691e92cbcf1ba84da13cadc8c0b87b22d3557406a61b371869f2c4b97d3

Instead, the query that works is to put everything within a single `where`:

```
collection
  .where(
    Filter.and(
      Filter.where('first_name', '==', 'Luke'),
      Filter.or(
        Filter.where('last_name', '==', 'Skywalker'),
        Filter.where('last_name', '==', 'Vader'),
      )
    )
  )
```

Is it intended that chained `where` calls results in this unexpected behavior? Thanks!

**Comment by MarkDuckworth** [comment]
Hi @danReynolds, thanks for reaching out. 

> I would expect chained where filters to implicitly be an AND filter

Correct, that is the expected behavior.

> instead this just doesn't recognize the first_name filter and just applies the filters in the OR

I tested both code snippets and I saw the same (expected) behavior from both. Can you provide the sample data you were testing against? Here's what I used:

```
  it.only(
      'Implicit AND',
      async () => {
        const collection = await testCollectionWithDocs({
          doc1: {first_name: "Luke", last_name: "Skywalker"},
          doc2: {first_name: "Darth", last_name: "Vader"},
          doc3: {first_name: "Darth", last_name: "Maul"},
          doc4: {first_name: "Ben", last_name: "Kenobi"},
          doc5: {first_name: "Anakin", last_name: "Skywalker"},
          doc6: {first_name: "Luke", last_name: "Starkiller"}
        });

        // implicit AND
        expectDocs(
            await collection
                .where('first_name', '==', 'Luke')
                .where(
                    Filter.or(
                        Filter.where('last_name', '==', 'Skywalker'),
                        Filter.where('last_name', '==', 'Vader'))
                )
                .get(),
            'doc1'
        );

        // explicit AND
        expectDocs(
            await collection
                .where(
                    Filter.and(
                        Filter.where('first_name', '==', 'Luke'),
                        Filter.or(
                            Filter.where('last_name', '==', 'Skywalker'),
                            Filter.where('last_name', '==', 'Vader'))
                    ))
                .get(),
            'doc1'
        );
      });
```

**Comment by MarkDuckworth** [comment]
@danReynolds, I'm going to close this because I wasn't able to reproduce it and there has been a few weeks of inactivity after requesting more info to help me reproduce it. If you feel this is still an issue, please let me know and we can resume looking at it. Thanks
