### ISSUE TITLE
Getting Cold start latency of 5+ seconds even after using the preferRest option for firebase-admin 

### ISSUE THREAD

**Issue by HarshitPersona** [googleapis/nodejs-firestore#1851]
Thanks for stopping by to let us know something could be better!

Linked issues- https://issuetracker.google.com/issues/158014637 and https://github.com/firebase/firebase-admin-node/pull/1901

#### Environment details

  - OS: macOS Ventura
  - Node.js version: 18
  - npm version: 9.5.1
  - `@google-cloud/firestore` version: 6.5.0

Thanks!

**Comment by ehsannas** [comment]
Hey @HarshitPersona , can you provide more information about your environment? Are you sending the requests from your local machine (macOS)?

**Comment by HarshitPersona** [comment]
I have written a cloud function in GCP in Nodejs18 environment which is connecting to the firestore database through firebase-admin library. See below for the code snippet-

`
let isAlreadyInitialized = false;
let db;

const middleware = async (req, res) => {
  try {
    const apiKey = req.headers["x-api-key"];
    if (!apiKey)
      return res.status(401).send({ message: "A valid API Key is required!" });

    const { initializeApp } = require("firebase-admin/app");
    const {
      initializeFirestore,
      getFirestore,
    } = require("firebase-admin/firestore");

    if (!isAlreadyInitialized) {
      const app = initializeApp();
      initializeFirestore(app, { preferRest: true });
      db = getFirestore(app);
      isAlreadyInitialized = true;
    }

    const query = db.collection("apps").where("apiKey", "==", apiKey);

    const querySnapshot = await query.get();
      return res.send({ tests: "This is a test response!" });
  } catch (e) {
    return res.status(500).send(e);
  }
};

exports.fetchCreative = middleware;
`

If you notice here- return res.send({ tests: "This is a test response!" }); I have send back a test response but this response is taking 5+ seconds on cold starts even though I used preferRest option as you can see in the above code.

**Comment by HarshitPersona** [comment]
"firebase-admin": "^11.8.0" - this is my dependency

**Comment by ehsannas** [comment]
Thanks for reporting @HarshitPersona .

Would you be able to answer these questions that'll help us understand what's going on?

1- How are you measuring the latency/delay? It's conceivable that a part (or majority) of what you have measured is in network latency for the response, not the time it took to update the database.

2- What would your measurement be if you set `preferRest` to `false`?

3- What would your measurement be if you don't interact with Firestore? Meaning, your cloud function just does `initializeApp();` and then `return res.send({ tests: "This is a test response!" });`?

**Comment by ehsannas** [comment]
Closing since there's been no response in 3 weeks. Feel free to comment if the above information comes to light.
