### ISSUE TITLE
FR: trigger security rules from admin api

### ISSUE THREAD

**Issue by ericeslinger** [googleapis/nodejs-firestore#1852]
This may be more of a firestore FR than a node-api one, but I'm working with the node API so starting here.

I have spent a while making some pretty specific security rules for  CRUD+L on my firestore. I also have a firebase functions backend that serves as a little HTTP gateway for some stuff that wants to be a little more complicated than direct document writes. All of those functions require authZ checks, and they're usually in a very similar format to the rules I've already written ("allow user X to take this action only of they or any of the groups they are a member of has been granted this permission").

I _could_ just manually mirror the security rules and write out some fetches and javascript to apply similar logic on this check, and return a true/false. In fact, that's what I am doing. But I would love something _like_ the rules test environment. What I want is

```
  const userUID = req.auth.user.id;
  const token = { ... some other data I have handy };
  const allowed = await getFirestore().authorize({
    action: 'create',
    path: `/profiles/${profileId}/likers/${userUID}`,
    user: userUID,
    token
  });
  if (!allowed) {
    return(403);
  }
  await doSomestuff()
}
```

The idea here is that I can usually express the authorization logic of some non-primitive action via a POST request on my functions endpoint as "allow this if this user has this privilege on that document", and I'd like to be able to keep all my security rules in one place, instead of having parallel versions of functions and direct primitive writes.

**Comment by ehsannas** [comment]
Thanks for the suggestion @ericeslinger . I will bring it up for discussion with the team.

**Comment by ehsannas** [comment]
It turned out that the team had thought about such a feature in the past. There's no specific timeline in mind at this time. (internally tracked by b/285006062).
