### ISSUE TITLE
Why are we publishing multiple firestore packages to npm?

### ISSUE THREAD

**Issue by ofrobots** [googleapis/nodejs-firestore#186]
I was told that I should try `firestore`. Searching on npm, I found that we are publishing two distinct packages

* This one, as `@google-cloud/firestore`.
* [`@firebase/firestore`](https://www.npmjs.com/package/@firebase/firestore).

As a Node.js developer, this is incredibly confusing to me. Why is Google shipping two different packages? Which one am I supposed to use?

/cc @JustinBeckwith @lukesneeringer @jonparrott

**Comment by schmidt-sebastian** [comment]
The `@firebase/firestore` is the Node version of the fully-fledged Web SDK. The main differentiator is its support for latency compensation and an authentication model that is centered around third-party auth.

`@google-cloud/firestore` is our Admin SDK for Firestore. It is meant to directly interact with the Firestore backend and all data is directly retrieved from the backend. The Server SDK also uses Service Account-based authentication and is meant to be run in trusted environments.

I agree that our messaging could be improved here and will open an internal issue to improve our documentation.
