### ISSUE TITLE
Critical security vulnerability in protobufjs 7.0.0

### ISSUE THREAD

**Issue by scopsy** [googleapis/nodejs-firestore#1888]
There is a security vulnerability disclosed in https://github.com/advisories/GHSA-h755-8qp9-cq85 which affects all versions above 7.0.0.

The issue was resolved in 7.2.4.

We are using the firebase admin package which depends on the firestore package.

#### Environment details
  - `@google-cloud/firestore` version: 6.7.0

**Comment by MarkDuckworth** [comment]
Thanks for the PR. We will merge it. Is there any reason that updating your dependency tree didn't work, for example by using 'npm update' or 'yarn upgrade'? The previous version range (`"protobufjs": "^7.0.0"`) should not have prevented you from getting the patched protobufjs v7.2.4.
