### ISSUE TITLE
document .get() method times out sometimes, with no errors

### ISSUE THREAD

**Issue by paul-uz** [googleapis/nodejs-firestore#1895]
We are using the firestore JS SDK in a Lambda function, running on AWS.

We are seeing the code for `await collection.doc(<doc_id>).get();` timeout under seemingly random circumstances (we are unable to reliably replicate the timeouts)

Using lots of console logs, we narrowed it down to the .get() method, but even with the call inside a try/catch, we don't get any error logs coming through at all.

Is firestore rate limited at all in anyway?

**Comment by tom-andersen** [comment]
What version of Firestore SDK are you using?
What version of NodeJS are you using?
Does your client perform a large number of reads and writes?

You can enable logging by using `setLogFunction`. For example:

```
Firestore.setLogFunction(msg => {console.log(`DEBUG: ${msg}`)})
```

We have some quotos listed here: https://firebase.google.com/docs/firestore/quotas

Could you provide some logs when this happens after you set the log function?

**Comment by paul-uz** [comment]
V6.7.0 of the Firestore SDK on NodeJS 18.

I'm doing a simple get() for one document. No mass updates or inserts.

Not hitting any quotas shown in the account.

I'll try setting the logging function.

What I'm seeing is that with the collection.doc().get() call in a try catch block, the function hangs just before it should make the get() call and does not throw any errors to be caught and logged out in the catch block.

It happens randomly and I've now seen it time out after 5 minutes. I can  then run the same code again and it will be fine, doing the get() in less than 100ms.

**Comment by tom-andersen** [comment]
@paul-uz Thanks for the update! Can you share what AWS configuration settings can cause problems?

**Comment by paul-uz** [comment]
> @paul-uz Thanks for the update! Can you share what AWS configuration settings can cause problems?

I made some edits to my Lambda to allow egress to the Internet, as it sits in a VPC so it can communicate with our RDS database.

I mistakenly added it to a public subnet which caused the issue sporadically as Lambda would randomly pick that subnet sometimes.
