### ISSUE TITLE
Error trying to use named database instead of (default)

### ISSUE THREAD

**Issue by 27lakshay** [googleapis/nodejs-firestore#1901]
I'm trying to use a different cloud firestore database named "temp" instead of the (default) one in firebase-admin.
The instance gets initialized successfully but when I try to run any operation it fails.

Code: 
const DBInstance = getFirestore(AppInstance, "temp");

Error: 
Error: 3 INVALID_ARGUMENT: The request was for database 'projects/foyer-work/databases/temp' but was attempting to access database 'projects/foyer-work/databases/(default)'

**Comment by wu-hui** [comment]
I tried to reproduce this with latest admin sdk `"firebase-admin": "^11.10.1",` and it worked as expected.
