### ISSUE TITLE
Library should implement SLA-compliant retry policies

### ISSUE THREAD

**Issue by samatcolumn** [googleapis/nodejs-firestore#1914]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

 **Is your feature request related to a problem? Please describe.**

We have had a few instances where Firestore requests began failing en masse, as described here:
https://github.com/firebase/firebase-admin-node/issues/1903

In one case we had an hour-long outage. I contacted Google Cloud support to say that this is an SLA violation (we use Cloud Firestore multi-regional) but their response was that it is my responsibility to retry this kind of failure and therefore the SLA was not violated.

 **Describe the solution you'd like**

Official client libraries like this one should implement Google-recommended best practices for handling retryable errors. It would be one thing if I was using the HTTP or gRPC API directly, but because I am using this Googler-maintained client library I was not expecting to have to add my own error handling for very uncommon gRPC error codes like `2 UNKNOWN` and I did not learn about this expectation until our business had already had a major outage.

 **Describe alternatives you've considered**

I could do this myself, but this would mean wrapping all Firestore calls in paranoid retry loops.

 **Additional context**

N/A

**Comment by cherylEnkidu** [comment]
Hi @samatcolumn,
Could you please provide support ticket id?

**Comment by samatcolumn** [comment]
@cherylEnkidu sure, one ticket ID is 45978287. Here's a quote from that case:

> According to the Cloud Firestore SLA [1], the application is responsible for waiting for a period of time before retrying the request. This means that after the first error, there is a minimum back-off interval of 1 second and for each consecutive error, the back-off interval increases exponentially up to 32 seconds. I checked the error logs during the overloading period [redacted] and found that [you] did not seem to retry [2], I would like to confirm with you whether you have implemented exponential backoff in Cloud functions. Thanks in advance.

The SLA link:
https://cloud.google.com/firestore/sla-20180724#definitions

**Comment by cherylEnkidu** [comment]
Hi @samatcolumn ,
Thank you for quickly provide the info. A fix is working in progress: https://github.com/empirical-org/Empirical-Core/pull/11122

**Comment by samatcolumn** [comment]
@cherylEnkidu thanks for getting back to me! I'm a bit confused on the relationship between empirical-org and Google ... is the idea that the fix outlined there will be upstreamed into the core library?

**Comment by samatcolumn** [comment]
@cherylEnkidu just following up here: is there a plan to bring a fix into **this** library?

**Comment by jeffreyvalle** [comment]
@cherylEnkidu Is there an update on this? Will the fix you reference be added to this library? We just started to experience this error today on code that is unchanged and previously working without error for weeks. Thanks.

**Comment by cherylEnkidu** [comment]
Hi,

The fix should be patched in the backend. There is no version update required for the SDK. If you are still experiencing this problem, @samatcolumn @jeffreyvalle could you please provide the support ticket id so the backend team can take a look?

**Comment by samatcolumn** [comment]
@cherylEnkidu can you explain the connection between this ticket and the PR you linked? https://github.com/empirical-org/Empirical-Core/pull/11122

From what I can tell `empirical-org` is not linked to Google Cloud.

Also I don't believe a backend-only fix is sufficient to close this ticket. As long as that error code exists in the gRPC spec, it seems reasonable to expect this library to have SLA-compliant retries.

**Comment by cherylEnkidu** [comment]
Hi @samatcolumn ,

Thank you for your question, I will add more explanation.

There are two things happened here:

1. Firestore is using the Cloud UberMint server, which overloading issue around 2023-10-03, currently this problem has been fixed by bumping the memory for all the UM tasks.

2. The error message delivers the wrong error code and error message, which is fixed in the PR linked previously, belong to ESF/Ubermint client.

Thank you for your patient again, please let me know if you are still experiencing this issue.

**Comment by cherylEnkidu** [comment]
Hi,

I will close this ticket for now. For people still suffer from the similar issue, please open a new ticket and provide a support ticket id.
