### ISSUE TITLE
No GitHub release for 7.0.0

### ISSUE THREAD

**Issue by IchordeDionysos** [googleapis/nodejs-firestore#1915]
I really like the way releases are handled and documented.

For the 7.0.0 release however there is no GitHub release, if one could be added that would be awesome!

<img width="1187" alt="image" src="https://github.com/googleapis/nodejs-firestore/assets/10195482/3c2dc60e-2b96-4413-832d-a9d63e30a929">

**Comment by milaGGL** [comment]
Hi @IchordeDionysos, the release notes have been updated to version 7.0.0.  Thank you for catching this and reporting it us!
