### ISSUE TITLE
[Documentation] Disambiguate DocumentRef.create documentation 

### ISSUE THREAD

**Issue by cedvdb** [googleapis/nodejs-firestore#1921]
The documentation for the create method could be improved to explain exactly what "The write fails if the document already exists " means. Will the call throw an error ? If so it's not listed in throws. If it does nothing, then it should say it does nothing instead of "fails".

```ts
    /**
     * Creates a document referred to by this `DocumentReference` with the
     * provided object values. The write fails if the document already exists
     *
     * @param data The object data to serialize as the document.
     * @throws Error If the provided input is not a valid Firestore document.
     * @return A Promise resolved with the write time of this create.
     */
    create(data: WithFieldValue<T>): Promise<WriteResult>;
```

**Comment by ehsannas** [comment]
Looks like we have the more complete documentation here: 

https://github.com/googleapis/nodejs-firestore/blob/7a9d17bdd5fca3d91e66f7500c035140a7397c33/dev/src/reference.ts#L368-L388

we should update the comment in firestore.d.ts

**Comment by cedvdb** [comment]
That documentation is not more complete in that aspect.

It should be:

```
    * @throws {Error} If the provided input is not a valid Firestore document or if the document already exist.
```

The word fail is ambiguous, imo

**Comment by ehsannas** [comment]
Agreed
