### ISSUE TITLE
Update google-gax dependency to 4.x.x for @google-cloud/firestore 6.x.x

### ISSUE THREAD

**Issue by foges** [googleapis/nodejs-firestore#1930]
**Is your feature request related to a problem? Please describe.**

google-gax has a couple of dependencies that should be devDependencies. The most problematic being a (prod) dependency on protobufjs-cli, which pulls in jsdoc, (all of) lodash, and a couple of others, for a total of about 7MB of unnecessary dependencies. 

@google-cloud/firestore 6.x.x currently depends on google-gax 3.x.x. I realize this is no longer the case in @google-cloud/firestore 7.x.x, but there are many packages that still depend on @google-cloud/firestore  6.x.x.

My chain of (prod) dependencies is `firebase-admin > @google-cloud/firestore > google-gax > protobufjs-cli`

 **Describe the solution you'd like**
Bump the version of google-gax to to 4.x.x 

 **Describe alternatives you've considered**
Bumping the version of @google-cloud/firestore in firebase-admin, but @google-cloud/firestore 6.x.x > 7.x.x seems like a bigger change than the google-gax change.

 **Additional context**
None

**Comment by tom-andersen** [comment]
Thanks for the information. I will take a closer look.

**Comment by tom-andersen** [comment]
This represents a breaking change. `@google-cloud/firestore` version 6.x.x is compatible with Node 12, but `google-gax` 4.x.x is not. Updating `google-gax` was intentionally held back until we did a major version bump to 7.x.x.

The Admin SDK will be updated to depend on `@google-cloud/firestore` version 7.x.x. I know a developer is scheduled to work on this, but I can't provide any details on timeline.
