### ISSUE TITLE
Unstable write/reading time after multiple executions

### ISSUE THREAD

**Issue by Decezaris** [googleapis/nodejs-firestore#1938]
I have a `cloud function gen1` that is triggered by `pubsub event`, this topic receives all iot devices telemetries and the function is called about 5x/s, each call has a device id and this id is a document on firestore, each device id send messages every 10s. It's working fine most of the time, with a durantion of ~300ms, but sometimes the reading or writting operations take so long... some cases about 19s just for reading check the prints bellow

![19sgraph](https://github.com/googleapis/nodejs-firestore/assets/23064759/f05dc9d9-6ebc-47d2-b9dd-500bb7d9e20d)
### Logs for this case
check it out just for read a document with a small size

![19s](https://github.com/googleapis/nodejs-firestore/assets/23064759/d1e188ed-71e9-4696-a72e-4b6f7d76fafb)

### Reading the same document in another exection:

![19safter](https://github.com/googleapis/nodejs-firestore/assets/23064759/01d13e27-ee43-48f4-b424-6e4bf764ee2f)

just to antecipate, It's not memory this function only takes 120MB and the config was set to 512MB.

Thanks!

**Comment by Decezaris** [comment]
About the query is performed in a subcollection that had three documents inside

```javascript
  return db
    .collection(METERS_COLLECTION)
    .doc(meterId)
    .collection(DAYS_COLLECTION)
    .orderBy("creationDate", "desc")
    .limit(1)
    .get();
 ```

**Comment by MarkDuckworth** [comment]
Hi @Decezaris, there are a few possibilities here.

First, let's try something easy. Can you set Firestore's [`preferRest`](https://opensource.corp.google.com/github/prinfo?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fleveldb%2Fpull%2F4) setting to true? `preferRest` will cause your `get()` call to use our REST transport instead of our gRPC transport. The REST transport was introduced to speed up library loading on function cold start, which may be what you're experiencing.

If `preferRest` doesn't help you, then we'd want to see some logs from the Firestore SDK. Enable logging with [`setLogFunction()`](https://opensource.corp.google.com/github/prinfo?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fleveldb%2Fpull%2F4), and share the log output for a slow function execution and a normal function execution in a Gist or using a Firebase support request. Also, can you include the version of the Firestore SDK you're using?

**Comment by Decezaris** [comment]
> Hi @Decezaris, there are a few possibilities here.
> 
> First, let's try something easy. Can you set Firestore's [`preferRest`](https://opensource.corp.google.com/github/prinfo?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fleveldb%2Fpull%2F4) setting to true? `preferRest` will cause your `get()` call to use our REST transport instead of our gRPC transport. The REST transport was introduced to speed up library loading on function cold start, which may be what you're experiencing.
> 
> If `preferRest` doesn't help you, then we'd want to see some logs from the Firestore SDK. Enable logging with [`setLogFunction()`](https://opensource.corp.google.com/github/prinfo?q=https%3A%2F%2Fgithub.com%2Ffirebase%2Fleveldb%2Fpull%2F4), and share the log output for a slow function execution and a normal function execution in a Gist or using a Firebase support request. Also, can you include the version of the Firestore SDK you're using?

Thanks for the reply. I will try that. I'm using the latest version `v7.1.0`

**Comment by Decezaris** [comment]
The `preferRest` does not worked 😔

here is the output of slow and normal executions: [Debug logs](https://gist.github.com/Decezaris/0a72d4bd38d3ee7c3d18328a821ccb75)

**Comment by Decezaris** [comment]
I've updated the gist file with this case now, it's something strange with `ZM4Je`  log on slow code sample. The link is the same

![slow](https://github.com/googleapis/nodejs-firestore/assets/23064759/d15fd37b-9a08-47c3-8738-7e0cf66b1226)

**Comment by Decezaris** [comment]
#### Some errors bellow

![error](https://github.com/googleapis/nodejs-firestore/assets/23064759/308028d2-5b0a-441d-97d6-bff7dec0dfc6)

**Comment by Decezaris** [comment]
#### Another slow reading...

![anothererror](https://github.com/googleapis/nodejs-firestore/assets/23064759/53621887-d118-43ab-8a2f-633c67328c55)

**Comment by Decezaris** [comment]
Any news @MarkDuckworth? If you need something else, just ask!

**Comment by MarkDuckworth** [comment]
@Decezaris, I reviewed your logs. Thanks for providing them. This does not look like an issue with the Firestore SDK. It looks like the slow responses are related to the backend, so you will get better help if you file a support request with Firebase or GCP.

If you don't have a GCP support contract, then I recommend filing with Firebase Support: https://firebase.google.com/support/troubleshooter/fcm

If you do have a GCP support contract, then that may be your preferred way to file a support request.

I'm going to close this ticket for now, but you can reference it in your support request.
