### ISSUE TITLE
Firestore query "and" inside other "and" function not working

### ISSUE THREAD

**Issue by iconlynx** [googleapis/nodejs-firestore#1949]
I've been trying to create a query of this kind: 
const queryWithFilters = query(collection(db, 'rentOffers'),
          and(
            where('propertyType', 'in', filters.flatType),
            and(where('price', '>=', filters.priceRange[0]),
              where('price', '<=', filters.priceRange[1]))
        ));

propertyType is a string, price is a number
filters.flatType is a string[], filters.priceRange contains two values [min flat price, max flat price] ([number, number])

For some reason if I create two separate queries, they always return a few objects from firestore that fit the set criteria, but I can't make one more complicated query like above.

const queryWithPriceRange = query(collection(db, 'rentOffers'), and(where('price', '>=', filters.priceRange[0]),where('price', '<=', filters.priceRange[1])));

const queryWithPropertyType = query(collection(db, 'rentOffers'), where('propertyType', 'in', filters.flatType));

As I've said they can return compatible values. Is there any possible fix to that?

**Comment by dconeybe** [comment]
The code you've provided looks like you are using https://github.com/firebase/firebase-js-sdk. If that is the case, could you close this issue and log your issue there, making sure to fill out the issue template as much as possible?
