### ISSUE TITLE
Query class not exported correctly

### ISSUE THREAD

**Issue by LK** [googleapis/nodejs-firestore#198]
It seems like the `Query` class is not properly exported from this module. It is [listed](https://github.com/googleapis/nodejs-firestore/blob/master/src/index.js#L1265) [three](https://github.com/googleapis/nodejs-firestore/blob/master/src/index.js#L1301) [times](https://github.com/googleapis/nodejs-firestore/blob/master/src/index.js#L1310) in the main `index.js` file's exports, only the second of which looks to be the correct object.

A temporary workaround which gets the `Query` class from the superclass of `CollectionReference`:

```
const Query = Object.getPrototypeOf(CollectionReference.prototype).constructor;
```

**Comment by schmidt-sebastian** [comment]
Thanks for sending this over. This will be fixed as part of #200.
