### ISSUE TITLE
Block exposing private keys

### ISSUE THREAD

**Issue by abhishekwebcode** [googleapis/nodejs-firestore#1984]
Please see suggested Pull Request #1983 for the fix

#### Environment details

  - OS: MacOS
  - Node.js version: 
  - npm version: 21.5.0
  - `@google-cloud/firestore` version:  7.2.0

#### Steps to reproduce

  1. Install the latest version of this library from https://www.npmjs.com/package/@google-cloud/firestore
  2. Initialise the firestore object using a JSON private key (Service Account)
  3. Get any object like the original firestore object or Make a WriteBatch, CollectionReference, DocumentSnapshot
  4. Run JSON.stringify() method on any object obtained in the step above (3), the private key is exposed because the spelling of toJSON method in https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/index.ts#L748 is not correct
  it should be toJSON instead of toJson, so the method is not getting activated which was meant to prevent serialisation of internal this._settings object when the firestore object is being serialised via JSON.stringify

**Comment by milaGGL** [comment]
Hi @abhishekwebcode , thank you for reporting this issue. I tried to repro the bug, but running `JSON.stringify()` on `CollectionReference`, `DocumentSnapshot` did not expose the private key. 

This is my code:
```
const { Firestore } = require('@google-cloud/firestore');

const firestore = new Firestore();
const collRef = firestore.collection('test-collection');
console.log("JSON.stringify(collRef): \n",JSON.stringify(collRef))

const cityRef = firestore.doc('test-collection/doc1');
cityRef.get().then((docSnap) => { 
  if (docSnap.exists) {
    console.log("JSON.stringify(docSnap): \n", JSON.stringify(docSnap))
  } else {
    console.log("Document not found.");
  }
})
```
Could you please provide a complete code to repro the bug?

**Comment by abhishekwebcode** [comment]
Hey @milaGGL, Please read this full message , thanks
The issue was present in 
firebase-admin@11.11.1  and 
@google-cloud/firestore@6.8.0

I installed the latest version and the problem is not there.
But now i see that the serialization exposure of private keys is being successully stopped because of 
https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/index.ts#L1451 so in my Pull Request #1983 , I have removed the unused and unreachable code. 
1. The removed code is no longer required
2. The removed code is defining toJson method on the _settings object which anyways is wrong since correct spelling is toJSON . The code doesn't work and is waste, you can see this by removing the https://github.com/googleapis/nodejs-firestore/blob/main/dev/src/index.ts#L1451 function which again introduces the problem

I request you to kindly review my pull request, let me know if you still have any thoughts.
Exited to make a open source contribution, Thanks

**Comment by milaGGL** [comment]
Thank you for your contribution @abhishekwebcode. Closing this ticket as the PR is merged.
