### ISSUE TITLE
Improve network latency of `runTransaction()` routine

### ISSUE THREAD

**Issue by brettwillis** [googleapis/nodejs-firestore#2015]
If I correctly understand the routine for `runTransaction()`, as referenced below, then when running a *read-write* transaction, a [`documents:beginTransaction`](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/beginTransaction) request is *always* issued before running the `updateFn`.

https://github.com/googleapis/nodejs-firestore/blob/e598b9daf628cbc54dc10dab80bb0f46e2a3e2a2/dev/src/transaction.ts#L593-L598

This means we wait for an entire network round trip before beginning the transaction, every attempt.

I also noticed that the [`documents:runQuery`](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/runQuery) and [`documents:batchGet`](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/batchGet) APIs support a `newTransaction` parameter, which would allow the SDK to lazily start a transaction on the first read request, without the additional sequential network round trip.

Lazily starting the transaction on the first read would *always* eliminate one entire sequential network round trip for every read-write transaction. I feel that this is quite a significant impact for high performance applications.

Some implications
- The transaction would be started server-side on first read (eliminate `documents:beginTransaction` and use `newTransaction`). 
- All read operations would need to use `documents:batchGet`, `documents:runQuery`, `documents: runAggregationQuery` (i.e. not `documents:get`) which is fine.
- Subsequent reads would be queued until the first read completes, so as to use that same transaction ID returned. In many cases, transaction reads would be sequential anyways, and if not, the user can improve performance of parallel initial reads using `getAll()`. The only exception is if there is a mix of document IDs and queries (cannot be batched together in one request). Regardless, currently *all* reads are queued after the `documents:beginTransaction` call anyways so there is no downside.
- If there are no reads before the transaction is committed, then [`documents:commit`](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.documents/commit) is called without a transaction.

Thoughts?

**Comment by brettwillis** [comment]
@tom-andersen I'm pinging you here because of your comment https://github.com/googleapis/nodejs-firestore/issues/1994#issuecomment-1924814441 quoted below.

> There is an unfortunate implementation detail that transactions will send a begin transaction request, followed by your get document requests.

While the PR #2002 you mention may improve performance when `readTime` is specified, it doesn't look like it addresses the more common performance problem and proposal described here?

**Comment by brettwillis** [comment]
No worries! Would you be interested in accepting a PR, or would you prefer to keep it within the team?

**Comment by tom-andersen** [comment]
For something like this that doesn't require changes to the API surface, we will very happily accept a PR!
