### ISSUE TITLE
When support for range and inequality filters on multiple fields in a single query and support for query explain will be added to the library?

### ISSUE THREAD

**Issue by HannaCiucka** [googleapis/nodejs-firestore#2034]
Looking at the release notes from March 27th for Firestore [1], there are two new features in the preview available:
- support for query explain
- support for range and inequality filters on multiple fields in a single query

What is the plan for adding these updates from the @google-cloud/firestore to the firebase-admin library?

[1] https://cloud.google.com/firestore/docs/release-notes#March_27_2024

Secondly, which one out of firebase-admin OR @google-cloud/firestore should be used in general for firestore for server side?

Thank you in advance!

**Comment by MarkDuckworth** [comment]
@HannaCiucka,

These features should be supported in firebase-admin currently.

Firebase-admin simply re-exports types from @google-cloud/firestore. So, if you install the latest versions of dependencies (using `npm update`, `yarn upgrade`, or similar), this should install the latest version of @google-cloud/firestore that is supported by the version of firebase-admin you have installed.

Firebase-admin is used when you need support for other Firebase products (not just Firestore). [See more](https://firebase.google.com/docs/firestore/client/libraries#firebase_admin_sdks).
