### ISSUE TITLE
Types file for ImportDocumentsRequest does not match published doc

### ISSUE THREAD

**Issue by gregfenton** [googleapis/nodejs-firestore#2043]
#### Environment details

  - `@google-cloud/firestore` version: 7.3.1 (via firebase-admin v12.0.0)

#### Steps to reproduce

  1. The [documentation for `importDocuments()`](https://cloud.google.com/firestore/docs/reference/rest/Shared.Types/ImportDocumentsMetadata) shows there is a property named `namespaceIds` for the input (request object)
  2. The [.d.ts definition of ImportDocumentsRequest](https://github.com/googleapis/nodejs-firestore/blob/392ecf37d3ead79b90e5bbe9e54ca677a026c525/types/protos/firestore_admin_v1_proto_api.d.ts#L1183) does not show any such property

This is a conflict.  Both of the above should be consistent with the declared/documented fields.

**Comment by dconeybe** [comment]
Drive-by comment: This is possibly the same root cause as https://github.com/googleapis/nodejs-firestore/issues/2035 where the types files stopped being updated by autosynth/owlbot back in August 2021 (2.5 years ago).

**Comment by MarkDuckworth** [comment]
v7.9.0 incudes the updated auto-gen types, adding the missing property `namespaceIds`, among other things.
