### ISSUE TITLE
Timestamp.fromDate using local time not UTC time

### ISSUE THREAD

**Issue by rrrfffrrr** [googleapis/nodejs-firestore#2049]
#### Environment details

  - OS: Any OS
  - Node.js version: v18.20.2
  - npm version: 10.5.0
  - `@google-cloud/firestore` version: 6.8.0

#### Steps to reproduce
  1. Create a field with following value Timestamp.fromDate(new Date())
  2. Check saved value in firestore console

#### Expected
 If create a field at 12PM, we should can get 12PM UTC+{local timezone}

#### What really get
 If create a field at 12PM, we get (12PM + {local timezone}) UTC+{local timezone}

#### How to fix it
Since date using local time and firestore require utc time as input, Remove timezone offset from the time
https://github.com/googleapis/nodejs-firestore/blob/6dbe4b0baac261f03f9032765b375938ce5e46d7/dev/src/timestamp.ts#L96
```js
return Timestamp.fromMillis(date.getTime() + date.getTimezoneOffset() * 60 * 1000); 
```
And it still not fixed in v7.7.0

**Comment by dconeybe** [comment]
Thank you for the bug report. I'll take a look into this and get back to you. My immediate thought, though, is that this would be a breaking change and requires a great deal of care. An alternative to modifying the behavior of `fromMillis()` may be to simply add a new method, something like `fromMillisUTC()`.

**Comment by rrrfffrrr** [comment]
> Thank you for the bug report. I'll take a look into this and get back to you. My immediate thought, though, is that this would be a breaking change and requires a great deal of care. An alternative to modifying the behavior of `fromMillis()` may be to simply add a new method, something like `fromMillisUTC()`.

Yes it can be mess up every old codes.
Currently, i`m making new `fromLocalDate(date: Date)` and using it.
I hope there is no bug and it was just my misunderstand of the timestamp calculation.

**Comment by rrrfffrrr** [comment]
I'm sorry, My devops team report me that the server was set to UTC not local time.
Should i close or waiting for you?

**Comment by dconeybe** [comment]
I can close it. Thanks for letting me know!
