### ISSUE TITLE
Expose serializer.ts methods in public API

### ISSUE THREAD

**Issue by mklaber** [googleapis/nodejs-firestore#2057]
**Is your feature request related to a problem? Please describe.**

My team and I have written a Cloud Function that listens to Cloud Firestore `google.cloud.firestore.document.v1.written` events, serializes them as JSON objects, and publishes them to a Pub/Sub topic. We followed the [latest example](https://cloud.google.com/functions/docs/calling/cloud-firestore#example_1_hello_function) which encourages the use of `CloudEvent` and protobuf. The problem is... there isn't much in the way of useful documentation, code, or libraries for converting that decoded cloud event to a JSON representation (e.g., without things like `"isActive": {"booleanValue": true }`, `"datePurchased":{"seconds":"1717145220","nanos":90913000}`, `"middleName":"NULL_VALUE"`, etc.).

 **Describe the solution you'd like**

Make [`decodeValue`](https://github.com/googleapis/nodejs-firestore/blob/6dbe4b0baac261f03f9032765b375938ce5e46d7/dev/src/serializer.ts#L262C3-L262C14) available in the public API.

 **Describe alternatives you've considered**

* Write my own decoder that largely copies and pastes from serializer.ts
* Switch away from CloudEvent in favour of more classic Firestore Functions similar to what is done in the [firestore-bigquery-export](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export) extension

 **Additional context**

Ideally there'd be a Firebase extension similar to [firestore-bigquery-export](https://github.com/firebase/extensions/tree/next/firestore-bigquery-export) that routes messages to Pub/Sub rather than BigQuery. Or even an EventArc Destination that is just a Pub/Sub topic?

**Comment by dconeybe** [comment]
Thank you for your request and I apologize for the difficulty you are experiencing. After talking with the team, we have decided _not_ to expose the functionality from `serializer.ts` as part of the public API. The class has many transitive dependencies on other internal code which we are not prepared to expose and maintain.

**Comment by mklaber** [comment]
@dconeybe okay, alternatively, can you or the team provide guidance or an example of how to translate a CloudEvent document back to a JSON representation? (or reassurance that such a mechanism is coming eventually?)

**Comment by taeold** [comment]
One option you could consider is to use https://github.com/firebase/firebase-functions, e.g.

```
import {
  onDocumentWritten,
  Change,
  FirestoreEvent
} from "firebase-functions/v2/firestore";

exports.myfunction = onDocumentWritten("users/marie", (event) => {
     // Get an object with the current document values.
    // If the document does not exist, it was deleted
    const newValues =  event.data.after.data();

    // Get an object with the previous document values
    const previousValues =  event.data.before.data();
})
```

You don't necessarily have to use the Firebase CLI to deploy your functions written with Firebase Functions SDK, though you may need to add yet another dependency on `firebase-admin`(https://firebase.google.com/docs/admin/setup#add-sdk) since Firebase Functions SDK relies on some of its feature to construct a write-able Firestore snapshot.
