### ISSUE TITLE
Please clarify about findNearest() method.

### ISSUE THREAD

**Issue by pogorv12** [googleapis/nodejs-firestore#2217]
Hello!

I want to ask you to clarify guideline for vector based search findNearest() method.

There is difference between how it is described in the doc and how it is implemented in the library (I have the latest firebase-admin 12.6.0  installed).

So, the doc (https://firebase.google.com/docs/firestore/vector-search#make_a_nearest-neighbor_query) isays :
```
// Requires a single-field vector index
const vectorQuery: VectorQuery = coll.findNearest({
  vectorField: 'embedding_field',
  queryVector: [3.0, 1.0, 2.0],
  limit: 10,
  distanceMeasure: 'EUCLIDEAN'
});
```
While the working definition is:
```
const vectorQuery: VectorQuery = coll.findNearest({
  'embedding_field',
   [3.0, 1.0, 2.0],
  { limit: 10,
  distanceMeasure: 'EUCLIDEAN'
});
```

The vector distance value and threshold as described in https://firebase.google.com/docs/firestore/vector-search#vector-distance and https://firebase.google.com/docs/firestore/vector-search#distance-threshold not available at all.

Method description from the package looks like this:

```
/**
     * Returns a query that can perform vector distance (similarity) search with given parameters.
     *
     * The returned query, when executed, performs a distance (similarity) search on the specified
     * `vectorField` against the given `queryVector` and returns the top documents that are closest
     * to the `queryVector`.
     *
     * Only documents whose `vectorField` field is a `VectorValue` of the same dimension as `queryVector`
     * participate in the query, all other documents are ignored.
     *
     * @example
     * ```typescript
     * // Returns the closest 10 documents whose Euclidean distance from their 'embedding' fields are closed to [41, 42].
     * const vectorQuery = col.findNearest('embedding', [41, 42], {limit: 10, distanceMeasure: 'EUCLIDEAN'});
     *
     * const querySnapshot = await aggregateQuery.get();
     * querySnapshot.forEach(...);
     * ```
     *
     * @param vectorField The field path this vector query executes on.
     * @param queryVector The vector value used to measure the distance from `vectorField` values in the documents.
     * @param options Options control the vector query. `limit` specifies the upper bound of documents to return, must
     * be a positive integer with a maximum value of 1000. `distanceMeasure` specifies what type of distance is
     * calculated when performing the query.
     */
    findNearest(
      vectorField: string | FieldPath,
      queryVector: VectorValue | Array<number>,
      options: {
        limit: number;
        distanceMeasure: 'EUCLIDEAN' | 'COSINE' | 'DOT_PRODUCT';
      }
    ): VectorQuery<AppModelType, DbModelType>;
```

No distanceResultField or distanceThreshold fields.

Please advice how to get distanceResultField and distanceThreshold fields working.
Thanks

**Comment by MarkDuckworth** [comment]
What version of `@google-cloud/firestore` are you using? Check with `npm list @google-cloud/firestore`.

Support for `distanceResultField` and `distanceThreshold` was added in `@google-cloud/firestore@7.10.0`. If you don't have this version, upgrade with `npm upgrade` (or if you're not using npm, then use the appropriate command for the package manager you are using).

FWIW, the older definition of `findNearest(vectorField, queryVector, options)` is still supported alongside the new definition `findNearest(vectorQueryOptions)`.

**Comment by pogorv12** [comment]
Thank you @MarkDuckworth ! You explanation helps.

I had @google-cloud/firestore@7.8.0 despite the latest firebase-admin@12.6.0. Update to @google-cloud/firestore@7.10.0 solved the issue.
