### ISSUE TITLE
preferRest behavior with multiple app instances 

### ISSUE THREAD

**Issue by michaelAtCoalesce** [googleapis/nodejs-firestore#2220]
question regarding the preferRest behavior - is it specific to the Firestore app instance? 

it does appear to be a setting on a firebase app instance, but it also sounds like there is some tracking to load grpc libraries if an onSnapshot is called, so wanted to double check. 

I.e. what happen if two app instances are initialized, one with preferRest:true and another with preferRest:false. Do they use their own independent transport or is the underlying transport shared?

thanks!

**Comment by MarkDuckworth** [comment]
@michaelAtCoalesce, 

Two instances of Firestore in the same app will not share client pools or options.

```
  const dbRest = new Firestore({
    projectId: projectId,
    preferRest: true
  });

  const dbGrpc = new Firestore({
    projectId: projectId,
    preferRest: false
  });

  // Request 1 with preferRest:true client. This uses a REST client.
  await dbRest.collection("0000-rest").get();

  // Request 2 with preferRest:false client. This uses a gRPC client.
  await dbGrpc.collection("0000-grpc").get();

  // Request 3 with preferRest:true client. This uses a REST client.
  await dbRest.collection("0000-rest").get();
```

Is your goal to have one Firestore instance that uses REST and another that uses gRPC? If so, can you tell us more about why you are trying to do that?
