### ISSUE TITLE
Defining TypeScript interface types for documents of a Snapshots

### ISSUE THREAD

**Issue by IchordeDionysos** [googleapis/nodejs-firestore#265]
Wouldn't it be somehow possible to define the types of the documents which are returned by `snapshot.data()` and `snapshot.get()` even better with TypeScript?

Currently, when calling these methods on a snapshot, the type is unknown...
I think this could be even better if we as developers could define and describe the documents which are fetched into snapshots.
I think that maybe one could use generics where an interface type is put in like this:

```typescript
const userSnap: FirebaseFirestore.DocumentSnapshot<UserDoc> = await firestore.collection("users").doc(uid).get();
const languageRef: FirebaseFirestore.DocumentReference = userSnap.get("language");
```

Here I define in a generic the type that the object should have when I call `snapshot.data()`:
```typescript
const userSnap: FirebaseFirestore.DocumentSnapshot<UserDoc>
```
I define a type `UserDoc` which I can then define as a generic of `DocumentSnapshot` and with this definition the call to `.data()` returns an object with the correct type of `UserDoc`
**AND**
even better would be if even the call to `snapshot.get()` would return the correct type here:
```typescript
const languageRef: FirebaseFirestore.DocumentReference = userSnap.get("language");
```
So that I don't explicitly have to define the type of `languageRef` and TypeScript knows exactly that the type should be of `FirebaseFirestore.DocumentReference`, without any further type definition.

So this code:
```typescript
const userSnap: FirebaseFirestore.DocumentSnapshot = await firestore.collection("users").doc(uid).get();
const languageRef: FirebaseFirestore.DocumentReference = userSnap.get("language");
```
becomes this:
```typescript
const userSnap: FirebaseFirestore.DocumentSnapshot<UserDoc> = await firestore.collection("users").doc(uid).get();
const languageRef = userSnap.get("language");
```

In my opinion a lot more readable and with a good typescript compatilbe editor at least as good as defining the type manually each time you call `.get()` or `.data()`

I love to hear what you think, if this is possible or something as useful for others as it would be for me.

**Comment by schmidt-sebastian** [comment]
Hi @IchordeDionysos ! This is actually a feature requests that shows up every once in a while. Please take look at the response in https://github.com/googleapis/nodejs-firestore/issues/109.

**Comment by creativecreatorormaybenot** [comment]
@schmidt-sebastian Am I right under the impression that this feature request has been implemented now?

The `DocumentSnapshot` class seems to allow generic document data:

```ts
export class DocumentSnapshot<T = DocumentData>
```

**Comment by creativecreatorormaybenot** [comment]
Either way, what works for me is the following (using the example from the original comment):

```ts
const userSnap: FirebaseFirestore.DocumentSnapshot<UserDoc> = await firestore.collection("users").doc(uid).get();
// Assert non-undefined using .data()!
const languageRef = userSnap.data()!.language;
```

**Comment by IchordeDionysos** [comment]
@creativecreatorormaybenot you are generally using `.withConverter` with this :)

**Comment by creativecreatorormaybenot** [comment]
@IchordeDionysos Ok that is pretty sweet, thanks 🙂

Was it also newly added? I found some usage guide - do you know if there are official docs for it?

**Comment by creativecreatorormaybenot** [comment]
@IchordeDionysos That is pretty sweet, thanks 😋 

For reference:

```dart
const userConverter = {
  toFirestore(user: User): firebase.firestore.DocumentData {
    return {name: user.name, id: user.id};
  },
  fromFirestore(
    snapshot: firebase.firestore.QueryDocumentSnapshot,
    options: firebase.firestore.SnapshotOptions
  ): User {
    const data = snapshot.data(options)!;
    return new User(data.name, data.id);
  }
}
```

**Comment by schmidt-sebastian** [comment]
@creativecreatorormaybenot Yes, this is implemented (as shown by your code snippets).
