### ISSUE TITLE
Change the src/index module.exports.v1beta1 to use generated method.

### ISSUE THREAD

**Issue by landrito** [googleapis/nodejs-firestore#27]
## What

The generated client samples depend on the the `module.export.v1beta1` of the `src.index.js` file to export a method that instantiates a client. In order for the samples to be correct (and for the future regenerations of the samples to be correct) the export must be changed.

## Fix

1. Make sure nothing depends on the current v1beta1.
2. Regenerate the firestore client.
3. Copy the correct method over.
4. Export as `v1beta1` in `src/index.js`

prior discussion found at: https://github.com/googleapis/toolkit/issues/1599

**Comment by lukesneeringer** [comment]
@landrito We fixed this, right? Or is Firestore lagging behind the clients generated more recently?

**Comment by landrito** [comment]
I don't think this problem exists with your refactor. The samples will be correct after a regeneration of the generated client.
