### ISSUE TITLE
Project ID not automatically determined from key file

### ISSUE THREAD

**Issue by DiogoRMax** [googleapis/nodejs-firestore#305]
Error when I do not use an environment variable to set the project ID

#### Environment details

  - OS: Windows NT 10.0 build 17134 (Windows 10) 
  - Node.js version: v8.9.3
  - npm version: 5.10.0
  - `@google-cloud/firestore` version: 0.16.0

#### Steps to reproduce

  1. Let firestore be configured using only keyFilename
  2. Use get method in document

```js
const Firestore = require('@google-cloud/firestore');

const firestore = new Firestore({
    project_id: 'grupo-ler-fire',
    keyFilename: './keys/FIRE-firebase-adminsdk.json',
    timestampsInSnapshots: true,
});

firestore.collection('Folders').doc('108#766302424')
        .get()
        .then(snap => {
            console.log(snap.data());
        });
```

```
(node:9412) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Sorry, we cannot connect to Cloud Services without a project
 ID. You may specify one with an environment variable named
 "GOOGLE_CLOUD_PROJECT".
(node:9412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by schmidt-sebastian** [comment]
As far as I can tell, we never extracted the Project ID from the service account credentials. If there are no objections, then I am going to mark this as a feature request. We likely want to do this in other clients as well (e.g. Java).

**Comment by DiogoRMax** [comment]
@schmidt-sebastian 

When I used only keyFilename in firestore version 0.10.0 it works correctly, it was only break when I updated those days...

**Comment by schmidt-sebastian** [comment]
I looked at this some more. This broke with the GAX update in https://github.com/googleapis/nodejs-firestore/pull/225

@JustinBeckwith Do you mind taking a look?

**Comment by JustinBeckwith** [comment]
Sure thing!

**Comment by JustinBeckwith** [comment]
So I just took a look - and this appears to "work on my machine" ™️.  Taking a closer look at your code snippet:

```js
const firestore = new Firestore({
    project_id: 'grupo-ler-fire',
    keyFilename: './keys/FIRE-firebase-adminsdk.json',
    timestampsInSnapshots: true,
}); 
```

It looks like you're trying to define the `projectId`, but you're using `project_id`.  Aside - can you verify your `FIRE-firebase-adminsdk.json` has a `project_id` field in it?

**Comment by JustinBeckwith** [comment]
Greetings!  If you're still running into issues, please do let us know.  Otherwise - I'm closing this out for now 👋
