### ISSUE TITLE
Error: Cannot find module "."

### ISSUE THREAD

**Issue by mhdevnet** [googleapis/nodejs-firestore#316]
#### Environment details

  - OS: WSL or WIndows 10 PowerShell
  - Node.js version: 9..8.0
  - npm version: 6.2.0
  - `@google-cloud/firestore` version: 0.16.0

#### Steps to reproduce

  1. Create Netlify functions app using Netlify Functions: https://www.netlify.com/docs/functions/
  2. Install firebase-admin
  3. Import firebase-admin
  4. Load firestore: `admin.firestore()`

This appears to happen in the google-cloud package:

```
webpackMissingModule
$folder/node_modules/@google-cloud/firestore/build/src/index.js:24
./node_modules/@google-cloud/firestore/build/src/index.js
$folder/node_modules/@google-cloud/firestore/build/src/index.js:24
__webpack_require__
$folder/webpack/bootstrap 9583bf4009469bcec19d:678
fn
$folder/webpack/bootstrap 9583bf4009469bcec19d:88
get
$folder/node_modules/firebase-admin/lib/firebase-namespace.js:329
```

Specifically this line:

```
const libVersion = require(pkgUp.sync(__dirname)).version;
```
Does anyone have any insight?

**Comment by schmidt-sebastian** [comment]
I suspect that Webpack removes the package.json here in a manner that we don't support. We have dealt with a couple issues related `pkgUp` lately, and I am inclined to fix this on our end by removing this dependency.
