### ISSUE TITLE
When using snapshot.data() ids are not returned... 

### ISSUE THREAD

**Issue by cbullokles** [googleapis/nodejs-firestore#323]
To get a complete object including Id + data is needed to iterate the complete array.....

var data = db.collection("users")
  .get()
  .then(users => {
    data.forEach( user => {
      console.log(`All ${user.id} -> ${JSON.stringify(user.data())}`);
    })
  }).catch( catchError => {
    console.log(catchError);
});

It would be great that user.data() method returns also the id, to avoid iterate the complete collection to rebuild the user object with all the intormation.

Cristian

**Comment by schmidt-sebastian** [comment]
This has been brought up before, but we decided to leave the API as is for now. Currently, data() is exactly the data that was passed to us (minus some type conversion that we do implicitly to make types for Firestore more friendly) and we don't modify what the backend sends us. For now, we have to ask you to include the ID in the document as a normal field value. We know that this is a little cumbersome, but it is the best compromise we currently offer.
