### ISSUE TITLE
404 on @google-cloud/projectify@^0.3.0

### ISSUE THREAD

**Issue by esschul** [googleapis/nodejs-firestore#326]
#### Environment details

  - OS: macos 10.12.6
  - Node.js version: 8.9.4
  - npm version: 6.3.0
  - `@google-cloud/firestore` version: latest

#### Steps to reproduce

  1. try to install firestore
  2. get 404 on @google-cloud/projectify@^0.3.0

Here's a copy from my terminal

es:nodetest espen$ npm init
This utility will walk you through creating a package.json file.
It only covers the most common items, and tries to guess sensible defaults.

See `npm help json` for definitive documentation on these fields
and exactly what they do.

Use `npm install <pkg>` afterwards to install a package and
save it as a dependency in the package.json file.

Press ^C at any time to quit.
package name: (nodetest) 
version: (1.0.0) 
description: 
entry point: (index.js) 
test command: 
git repository: 
keywords: 
license: (ISC) 
About to write to /Users/espen/dev/code/tmp/nodetest/package.json:

{
  "name": "nodetest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Espen Schulstad <espen.schulstad@telenor.com>",
  "license": "ISC"
}

Is this OK? (yes) 
es:nodetest espen$ ls
package.json
es:nodetest espen$ npm i @google-cloud/firestore
npm ERR! code E404
npm ERR! 404 Not Found: @google-cloud/projectify@^0.3.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/espen/.npm/_logs/2018-08-23T10_07_48_455Z-debug.log
es:nodetest espen$ 

Also here is the output from the debug-log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '@google-cloud/firestore' ]
2 info using npm@6.3.0
3 info using node@v8.9.4
4 verbose npm-session 87233ea6f31cb2b4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/@google-cloud%2ffirestore 2442ms
8 silly pacote tag manifest for @google-cloud/firestore@latest fetched in 2464ms
9 timing stage:loadCurrentTree Completed in 2732ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule @google-cloud/firestore@0.16.1 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/deep-equal 58ms
18 http fetch GET 200 https://registry.npmjs.org/is 61ms
19 http fetch GET 200 https://registry.npmjs.org/extend 62ms
20 http fetch GET 200 https://registry.npmjs.org/functional-red-black-tree 63ms
21 http fetch GET 200 https://registry.npmjs.org/google-gax 62ms
22 http fetch GET 200 https://registry.npmjs.org/lodash.merge 64ms
23 http fetch GET 200 https://registry.npmjs.org/bun 69ms
24 http fetch GET 200 https://registry.npmjs.org/google-proto-files 69ms
25 http fetch GET 200 https://registry.npmjs.org/protobufjs 66ms
26 silly pacote range manifest for deep-equal@^1.0.1 fetched in 76ms
27 silly resolveWithNewModule deep-equal@1.0.1 checking installable status
28 silly pacote range manifest for is@^3.2.1 fetched in 78ms
29 silly resolveWithNewModule is@3.2.1 checking installable status
30 silly pacote range manifest for functional-red-black-tree@^1.0.1 fetched in 79ms
31 silly resolveWithNewModule functional-red-black-tree@1.0.1 checking installable status
32 silly pacote range manifest for google-gax@^0.18.0 fetched in 79ms
33 silly resolveWithNewModule google-gax@0.18.0 checking installable status
34 silly pacote range manifest for extend@^3.0.1 fetched in 80ms
35 silly resolveWithNewModule extend@3.0.2 checking installable status
36 silly pacote range manifest for lodash.merge@^4.6.1 fetched in 79ms
37 silly resolveWithNewModule lodash.merge@4.6.1 checking installable status
38 silly pacote range manifest for bun@^0.0.12 fetched in 83ms
39 silly resolveWithNewModule bun@0.0.12 checking installable status
40 silly pacote range manifest for google-proto-files@^0.16.1 fetched in 82ms
41 silly resolveWithNewModule google-proto-files@0.16.1 checking installable status
42 silly pacote range manifest for protobufjs@^6.8.6 fetched in 81ms
43 silly resolveWithNewModule protobufjs@6.8.8 checking installable status
44 http fetch GET 200 https://registry.npmjs.org/through2 30ms
45 silly pacote range manifest for through2@^2.0.3 fetched in 33ms
46 silly resolveWithNewModule through2@2.0.3 checking installable status
47 http fetch GET 404 https://registry.npmjs.org/@google-cloud%2fprojectify 1592ms
48 silly fetchPackageMetaData error for @google-cloud/projectify@^0.3.0 404 Not Found: @google-cloud/projectify@^0.3.0
49 timing stage:rollbackFailedOptional Completed in 22ms
50 timing stage:runTopLevelLifecycles Completed in 4364ms
51 silly saveTree nodetest@1.0.0
51 silly saveTree └─┬ @google-cloud/firestore@0.16.1
51 silly saveTree   ├── bun@0.0.12
51 silly saveTree   ├── deep-equal@1.0.1
51 silly saveTree   ├── extend@3.0.2
51 silly saveTree   ├── functional-red-black-tree@1.0.1
51 silly saveTree   ├─┬ google-gax@0.18.0
51 silly saveTree   │ ├─┬ google-proto-files@0.16.1
51 silly saveTree   │ │ └── protobufjs@6.8.8
51 silly saveTree   │ ├── protobufjs@6.8.8
51 silly saveTree   │ └── through2@2.0.3
51 silly saveTree   ├── google-proto-files@0.16.1
51 silly saveTree   ├── is@3.2.1
51 silly saveTree   ├── lodash.merge@4.6.1
51 silly saveTree   ├── protobufjs@6.8.8
51 silly saveTree   └── through2@2.0.3
52 verbose stack Error: 404 Not Found: @google-cloud/projectify@^0.3.0
52 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
52 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
52 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
52 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
52 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
52 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
52 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
52 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
52 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
52 verbose stack     at runCallback (timers.js:789:20)
52 verbose stack     at tryOnImmediate (timers.js:751:5)
52 verbose stack     at processImmediate [as _immediateCallback] (timers.js:722:5)
53 verbose cwd /Users/espen/dev/code/tmp/nodetest
54 verbose Darwin 16.7.0
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@google-cloud/firestore"
56 verbose node v8.9.4
57 verbose npm  v6.3.0
58 error code E404
59 error 404 Not Found: @google-cloud/projectify@^0.3.0
60 verbose exit [ 1, true ]

**Comment by schmidt-sebastian** [comment]
Do you mind trying this on a different network. This is the output I am seeing:

```
>  npm info @google-cloud/projectify

@google-cloud/projectify@0.3.0 | Apache-2.0 | deps: none | versions: 3
A simple utility for replacing the projectid token in objects.

dist
.tarball https://registry.npmjs.org/@google-cloud/projectify/-/projectify-0.3.0.tgz
.shasum: adb984ac61f7ec855558ef677621b2488c50d05d
.integrity: sha512-ic3vU+rBLlQ9rU6vyMcQ/GoYQX9hP0P56jdbnSkGvXrVnO1DtYrkPV3Qg/NUrpAfKnmNC4hb0O/v2hCj8uGnbQ==
.unpackedSize: 18.3 kB

maintainers:
- fenster <npm@fenster.name>
- google-node-team <node-team-npm@google.com>
- justinbeckwith <justin.beckwith@gmail.com>
- ofrobots <ofrobots@google.com>

dist-tags:
latest: 0.3.0  

> npm install --save @google-cloud/projectify

+ @google-cloud/projectify@0.3.0
added 1 package from 1 contributor and audited 1 package in 0.742s
found 0 vulnerabilities
```

**Comment by JustinBeckwith** [comment]
I am like 99% this was an outage on npm:
https://status.npmjs.org/incidents/rr5rtq3lhvph

Please do let us know if you're still having issues!

**Comment by esschul** [comment]
Still having issues!

Tried it now, here are the logs from debug:

47 http fetch GET 404 https://registry.npmjs.org/@google-cloud%2fprojectify 1030ms
48 silly fetchPackageMetaData error for @google-cloud/projectify@^0.3.0 404 Not Found: @google-cloud/projectify@^0.3.0
49 timing stage:rollbackFailedOptional Completed in 1ms
50 timing stage:runTopLevelLifecycles Completed in 2354ms
51 silly saveTree asdf@1.0.0
51 silly saveTree └─┬ @google-cloud/firestore@0.16.1
51 silly saveTree   ├── bun@0.0.12
51 silly saveTree   ├── deep-equal@1.0.1
51 silly saveTree   ├── extend@3.0.2
51 silly saveTree   ├── functional-red-black-tree@1.0.1
51 silly saveTree   ├─┬ google-gax@0.18.0
51 silly saveTree   │ ├─┬ google-proto-files@0.16.1
51 silly saveTree   │ │ └── protobufjs@6.8.8
51 silly saveTree   │ ├── protobufjs@6.8.8
51 silly saveTree   │ └── through2@2.0.3
51 silly saveTree   ├── google-proto-files@0.16.1
51 silly saveTree   ├── is@3.2.1
51 silly saveTree   ├── lodash.merge@4.6.1
51 silly saveTree   ├── protobufjs@6.8.8
51 silly saveTree   └── through2@2.0.3
52 verbose stack Error: 404 Not Found: @google-cloud/projectify@^0.3.0
52 verbose stack     at fetch.then.res (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/fetch.js:42:19)
52 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
52 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
52 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
52 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
52 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
52 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
52 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
52 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
52 verbose stack     at runCallback (timers.js:810:20)
52 verbose stack     at tryOnImmediate (timers.js:768:5)
52 verbose stack     at processImmediate [as _immediateCallback] (timers.js:745:5)
53 verbose cwd /Users/fenrir/dev/code/udp/mappe uten navn
54 verbose Darwin 17.6.0
55 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "@google-cloud/firestore"
56 verbose node v8.11.4
57 verbose npm  v6.4.0
58 error code E404
59 error 404 Not Found: @google-cloud/projectify@^0.3.0
60 verbose exit [ 1, true ]

**Comment by esschul** [comment]
My current fix is to clone it out and installl it locally.
