### ISSUE TITLE
How is this library different from firebase-admin?

### ISSUE THREAD

**Issue by clocksmith** [googleapis/nodejs-firestore#327]
Can you please add a section in the documentation (preferably near the top) on when to use this over firebase-admin? Do they serve 2 different purposes? Would one ever need both?

https://firebase.google.com/docs/admin/setup

Thanks

EDIT: 
google-cloud/firestore is an optional dependency of firebase-admin:
https://github.com/firebase/firebase-admin-node/blob/master/package.json

I am generally confused about these 2 libraries.

**Comment by hiranya911** [comment]
`firebase-admin` provides many APIs -- Auth, Database (RTDB), Cloud Messaging, Firestore and more. Firestore support in `firebase-admin` is based on this library. Specifically `admin.firestore()` returns the same object as `new Firestore()`.

If you're only accessing Firestore, there's no reason to prefer one library over the other. But if you're also using other Firebase services/APIs, then `firebase-admin` is the only choice.

**Comment by CloudinaryDemo** [comment]
Ah, now I get it.

**Comment by jlara310** [comment]
Overview of Cloud Firestore SDKs and client libraries: https://cloud.google.com/firestore/docs/reference/libraries#server_client_libraries

**Comment by WuHarry** [comment]
then how the unpacked size for `@google-cloud/firestore` is almost 5 times the size of `firebase-admin`...

**Comment by schmidt-sebastian** [comment]
`@google-cloud/firestore` is an optional dependency of firebase-admin-node: https://github.com/firebase/firebase-admin-node/blob/master/package.json#L65
You have to install it explicitly.
