### ISSUE TITLE
npm i fails on Node 10.9.0 / Ubuntu 18.04 

### ISSUE THREAD

**Issue by NawarA** [googleapis/nodejs-firestore#330]
Hi, I cant install this library. I get the following error when I run the `npm i` command:
```
nawar@dev:~/dev/API$ npm i @google-cloud/firestore
npm ERR! Unexpected end of JSON input while parsing near '...ame":"protobufjs","ve'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nawar/.npm/_logs/2018-08-28T15_39_17_576Z-debug.log
```
I noticed the libary's build status is "Failing". Is your current release stable on Node 10.9 on Ubuntu 18? Any idea how to resolve this issue? Seems to have to do with the protobuf dependency? 

#### Environment details

  - OS: Ubuntu 18.04
  - Node.js version: 10.9.0
  - npm version: 6.2.0
  - `@google-cloud/firestore` version: current build

#### Steps to reproduce

  1. `npm i @google-cloud/firestore`
  2. output is `npm ERR! Unexpected end of JSON input while parsing near '...ame":"protobufjs","ve'`

Thanks!

**Comment by schmidt-sebastian** [comment]
The current build should work on Node 10 & Ubuntu. The build failure that you see on NPM is from one of the PRs that hasn't yet been merged.

**Comment by schmidt-sebastian** [comment]
Please re-open if this is still an issue.

**Comment by NawarA** [comment]
I resolved the issue. Bad NPM cache. Use `npm cache clean --force` to resolve
