### ISSUE TITLE
Update synth.py to use new generated code location

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-firestore#333]
Notes from this comment here:
https://github.com/googleapis/nodejs-firestore/pull/331#issuecomment-417029784

@kinwa91 can you please work with @schmidt-sebastian to get generation working again?

**Comment by schmidt-sebastian** [comment]
@kinwa91 Is there work remaining now that https://github.com/googleapis/nodejs-firestore/pull/337 is submitted?

**Comment by kinwa91** [comment]
This is fixed via #337
