### ISSUE TITLE
Dependency on GRPC breaks services that don't enable statically-linked binaries (Serverless Providers)

### ISSUE THREAD

**Issue by keithwhor** [googleapis/nodejs-firestore#34]
Hey team. We have a few developers on [StdLib](https://stdlib.com/) dependent upon https://github.com/firebase/firebase-admin-node for interfacing with Firebase.

As of the latest release, with `@google-cloud/firestore`, the dependency on the node-gyp compiled `grpc` module breaks builds on our serverless platform: we very explicitly do not support statically-linked binaries in the expected fashion from NPM.

This isn't technically a problem on your end; we can (and probably should) update to support `node-gyp` / etc., but this is also a gentle ask if there is equivalent functionality of the `grpc` module not dependent on `node-gyp`? We can tell our developers to just use older packages - it's just non-standard for something so high-level to use statically-linked binaries.

**Comment by schmidt-sebastian** [comment]
@lukesneeringer Is there something we can do here?

**Comment by jmdobry** [comment]
>  if there is equivalent functionality of the `grpc` module not dependent on `node-gyp`?

At this moment, no

**Comment by noomerzx** [comment]
Are you created project on cloud platform console ? I've got some problem with grpc with that way and try creating new project on firebase console and pick firestore instead of realtime db on database section then use the same code that have some error with grpc but this time it's work.

**Comment by jmdobry** [comment]
It's unrelated, their platform does not support packages with native bindings.

**Comment by schmidt-sebastian** [comment]
@keithwhor 
The next release of Firebase Admin will change the way that Firestore is initialized, which should no longer load Firestore's static dependencies when you are not actively using it. While this doesn't solve the root problem that Firestore cannot be used in these restricted Node environments, it should unblock usage of the other Firebase SDKs.

Please follow the issue in the firebase-admin repo: https://github.com/firebase/firebase-admin-node/issues/104
The PR that fixes the dependency loading is https://github.com/firebase/firebase-admin-node/pull/110

Thanks!
