### ISSUE TITLE
Auto-generated code drops custom options

### ISSUE THREAD

**Issue by kinwa91** [googleapis/nodejs-firestore#343]
With the update of the Veneer client in https://github.com/googleapis/nodejs-firestore/pull/225, we no longer pass along custom options to the `FirestoreClient` constructor.

https://github.com/googleapis/nodejs-firestore/blob/0ff5a47108c25eccb9ccad085bebd440fcdb0b99/dev/src/v1beta1/firestore_client.js

```js
function v1beta1(options) {
  options = extend(
      {
        scopes: v1beta1.ALL_SCOPES,
      },
      options);
  var gaxGrpc = new gax.GrpcClient(options);
  return new firestoreClient(gaxGrpc);
}
```

While `options` is passed to GrpcClient, it is not passed to `new firestoreClient()`. We therefore lose our client library header (gccl) and can no longer change the client to point to other host (such as QA).

**Comment by kinwa91** [comment]
@alexander-fenster I wonder if that piece of logic `(extend... scopes.. ALL_SCOPE)` was from an older version of the generator, or if it's some custom logic for firestore.
So would the fix here be to simply regenerate `v1beta1` and let gapic overwrite `dev/src/v1beta1/index.js`?

**Comment by kinwa91** [comment]
Perhaps @schmidt-sebastian would know as well?

**Comment by kinwa91** [comment]
It's very odd for firestore that we're exporting `FirestoreClient` as `module.exports`, calling it `v1beta1`.

The call signature for firestore is

```javascript
const firestore = require('@google-cloud/firestore');
const client = new firestore.v1beta1(); // this is in fact FirestoreClient as exported from v1beta1/firestore_client.js
```
while normally for gapic-generated APIs it should be invoked like so:
```javascript
const vision = require('@google-cloud/vision');
const client = new firestore.v1beta1.ImageAnnotatorClient();
```

**Comment by schmidt-sebastian** [comment]
Regenerating the client has been on our todo list for a while. If the tests are passing, then I don't see a problem with it.

**Comment by schmidt-sebastian** [comment]
@kinwa91 Is this still an issue?

**Comment by schmidt-sebastian** [comment]
The updated version of the code now directly exposed the FirestoreClient constructor, and hence all options are passed through.
