### ISSUE TITLE
Use shared TypeScript definitions for common types such as CollectionReference, DocumentReference, WhereFilterOp, etc.

### ISSUE THREAD

**Issue by kossnocorp** [googleapis/nodejs-firestore#349]
I use Firestore both on the back-end and front-end environments. The problem is that the client library uses `@firebase/firestore-types` package (https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore-types/index.d.ts) while in Node.js types are defined in `@firebase/firestore` (https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts). For the most parts, the interfaces are identical, but because they're defined individually, it prevents me from using shared helpers that I can use both in the browser and on the server.

For instance, I'm trying to create typed wrapper:

![screen recording 2018-08-24 at 01 14 pm](https://user-images.githubusercontent.com/52201/45471935-4dbd3880-b73b-11e8-902b-19c9f354d3a6.gif)

But I can't make it work in both environments because it depends on defenition of `CollectionReference`, `DocumentReference`, `WhereFilterOp`, etc:

<img width="490" alt="image 2018-09-13 at 10 10 59 am" src="https://user-images.githubusercontent.com/52201/45472665-92e26a00-b73d-11e8-9c81-8fc4613cd3f8.png">

**Comment by kossnocorp** [comment]
I've created a copy of this issue in https://github.com/firebase/firebase-js-sdk: https://github.com/firebase/firebase-js-sdk/issues/1225

**Comment by schmidt-sebastian** [comment]
Hi @kossnocorp! As you may have noticed, we have gone through great efforts to keep the typings for the Server and Client SDK as similar as the possibly could be.  Underlying, we however have two very different SDKs. They not only do not share a code base, but offer very different features. 

The Node Server SDK is meant to be used to directly communicate with Firestore through Service Accounts and exposed some server-only features that are not available in other clients (such as field masks, transaction support for Query results and others). The Web SDK, on the other hand, supports document caching, metadata updates for queries and third-party authentication.

While we do intend to keep the API surface as similar as possible, it is not our intention that the types match exactly. For this reason, we will likely not be able to offer shared types.

**Comment by kossnocorp** [comment]
@schmidt-sebastian I got you, thank you for clarifying this! I think I can find a way to make my wrapper universal.

Also, thank you for your great work!

**Comment by Robula** [comment]
@schmidt-sebastian We've just hit this issue looking for answers. I understand the SDKs work differently but for the majority of the features we're using; the APIs are the same. Surely it is not the intention that we cannot share common Firestore functionality (repository models) between backend Node and frontend JS?

@kossnocorp Did you much luck finding a solution?

**Comment by kossnocorp** [comment]
@Robula yeah, I've built a universal wrapper for Firestore: https://github.com/kossnocorp/typesaurus

**Comment by garyo** [comment]
@kossnocorp this is great -- Google, please consider adding this layer! Would be very helpful for all of us using Firebase on front end and back end.
