### ISSUE TITLE
Can no longer write map values created with `new` in 0.8.2 (breaking change)

### ISSUE THREAD

**Issue by jephir** [googleapis/nodejs-firestore#37]
Previously, it was possible to write map values created with `new`, example:

```js
		function Bar() {
			this.value = 42
		}
		return this.db
			.collection("test")
			.doc("test")
			.set({
				foo: new Bar(),
			})
```
In 0.8.2 this now fails with:

`Error: Cannot encode type ([object Object]) to a Firestore Value`

Possibly caused by this change:

https://github.com/googleapis/nodejs-firestore/commit/1d5c2cc0c0d6f0d2d0527a2fa1f53779789d4874#diff-10a61011168244555609992da5f53f1cR1175

**Comment by schmidt-sebastian** [comment]
This is somewhat intended as we don't only want to support plain objects. I will look into this and see if we can allow this specific use case (and allow for simple objects).

**Comment by schmidt-sebastian** [comment]
We discussed this internally and would like to not revert back to the previous behavior. Our guarantee is that we can deserialize any data that we accept in out serialization. While it is certainly possible for us to serialize custom JS classes, we don't have a way to deserialize back into their specific types. Any data that we would read back from Firestore would therefore not pass the`instanceof Bar` check.

With that said, I'm going to close this issue for now. It is certainly possible that we revisit this decision in the future.
