### ISSUE TITLE
Collection Ref add method promise returns WriteResult instead of Document Ref

### ISSUE THREAD

**Issue by vinaymavi** [googleapis/nodejs-firestore#372]
This issue related to documentation https://cloud.google.com/nodejs/docs/reference/firestore/0.17.x/CollectionReference#add in this add method promise returns WriteResult ref instead of Document Ref.

**Comment by schmidt-sebastian** [comment]
@vinaymavi Can you clarify if there is any unexpected behavior? .add() is meant to return a DocumentReference: https://github.com/googleapis/nodejs-firestore/blob/b045d5b0195cdc8fb29b25e30f66f7662461adda/dev/src/reference.ts#L1877

This allows you to later fetch the document that we create. Without the reference, we would not be able to convey the autogenerated ID.

**Comment by schmidt-sebastian** [comment]
Closing for now. Please re-open should you still encounter this problem.
