### ISSUE TITLE
batch.commit(): 413:Request Entity Too Large

### ISSUE THREAD

**Issue by moander** [googleapis/nodejs-firestore#394]
Hi,

WriteBatch seems to be limited by gRPC request size. Is there any tool available in the library to calculate if a batch is over it's limit?

#### Environment details

  - `@google-cloud/firestore` version: 0.17.0

**Comment by moander** [comment]
Now I'm doing a Buffer. byteLength(JSON.stringify(payload)) but I'm not sure if this size is even close to what actually goes over the grpc wire ;)

**Comment by schmidt-sebastian** [comment]
Closing this for now. If we get more feedback, we can evaluate this further.

**Comment by dobromyslov** [comment]
Got same error when tried to save array of 7000 short string values in one document.
