### ISSUE TITLE
keyFilename and env variables

### ISSUE THREAD

**Issue by JFGHT** [googleapis/nodejs-firestore#397]
Basically I'm having a similar problem to this one: https://github.com/googleapis/google-cloud-node/issues/136

and I didn't find in the docs any other approach than the keyFilename which it only accepts a string to the path of the file.

**Comment by leeuwd** [comment]
Check https://github.com/googleapis/nodejs-firestore/issues/91

**Comment by leeuwd** [comment]
For future reference and/or help others: if you use the `credentials: {...}` object to initialize Firestore and retrieve the `client_email` and `private_key` values from the [Firebase environment configuration](https://firebase.google.com/docs/functions/config-env) (e.g. values set with `firebase functions:config:set someservice.key="THE API KEY"`), you have to [fix line endings](https://github.com/googleapis/google-cloud-node/issues/1173#issuecomment-199183259):

```js
functions.config().private_key
```

becomes

```js
functions.config().private_key.replace(/\\n/g, '\n'),
```
