### ISSUE TITLE
FR: allow DocumentReference.select similar to Query.select

### ISSUE THREAD

**Issue by goldensunliu** [googleapis/nodejs-firestore#42]
Hey guys,
    I have been snooping around the source code and documentation. It seems like the only way to do apply a field mask to the result and returns only the specified subset of fields is through the Query.select method. 
https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/Query#select
https://github.com/googleapis/nodejs-firestore/blob/master/src/reference.js#L1080

Is there any plan or ways to enable the same feature when getting a single document via DocumentReference? The code seems plenty of references to https://cloud.google.com/firestore/docs/reference/rest/v1beta1/DocumentMask which is used to restrict a get or update operation on a document to a subset of its fields, but I didn't have any luck tracking down usage of this in DocumentReference.get

#### Relevant Code:
```javascript
// based on the select example at https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/Query#select
let collectionRef = firestore.collection('col');
let documentRef = collectionRef.doc('doc');

documentRef.set({x:10, y:5}).then(() => {
  return collectionRef.where('x', '>', 5).select('y').get();
}).then((res) => {
  console.log(`y is ${res.docs[0].get('y')}.`);
});
// would like to be able to also do
documentRef.select('y').get().then((snapShot) => {
  console.log(`snapShot only has one field ${snapShot}`);
  // Expected output: {y: 5}
});

**Comment by goldensunliu** [comment]
I have also filed this against https://github.com/firebase/firebase-js-sdk/issues/272 since I am not sure where the source of development on the firestore part is housed.

**Comment by goldensunliu** [comment]
https://github.com/firebase/firebase-js-sdk/issues/212 answers this

**Comment by IchordeDionysos** [comment]
@goldensunliu Are you sure that that the issue in the Firebase JS SDK really answers this?
As I understood the answer from @wilhuff, is that this won't appear in the JS CLIENT SDK as you are having offline capabilities there and so on.

I don't see a problem in the ADMIN SDK to add such a method to the DocumentReference. As far as I know, there is no caching in the ADMIN SDK, so it should be no problem to allow a snippet/method like this:

```js
admin.firestore().document("path/to/a/document").select("y").get().then(snap => {
    console.log(`snapShot only has one field ${snap.data()}`);
    // Expected output: {y: 5}
});
```

Or am I wrong?

**Comment by wilhuff** [comment]
@IchordeDionysos you're right: the comments in firebase/firebase-js-sdk#212 specifically relate to the mobile clients and the complications of interacting with the cache while offline. These concerns do not apply to the nodejs or admin SDKs.

`document(..).get()` translates into a [BatchGetDocumentsRequest](https://github.com/googleapis/googleapis/blob/201d7be7f9da925df93bc52f8108963284f61aed/google/firestore/v1beta1/firestore.proto#L272) RPC, which includes a document mask, so this should be possible to implement.

In the meantime you can work around this by writing the following for some `documentRef`:

```js
const projectId = // ... your project id 
const path = 'path/to/a/document';
db.document(path)
    .parent  // i.e. the collection containing the document
    .where('__name__', '==', `projects/${projectId}/databases/(default)/documents/${path}`)
    .select(...)
```
Note that the result will be a query snapshot rather than a document snapshot, but it should get you what you want in the short term.

@schmidt-sebastian holler if I got this wrong.

**Comment by schmidt-sebastian** [comment]
A more concise version would be as follows:

```
const docRef = db.doc('path/to/a/document');
docRef.parent.where(Firestore.FieldPath.documentId(), '==', docRef).select(...)
```

**Comment by triplef** [comment]
It would be great to have this issue re-opened for consideration.

As mentioned above, the comments in firebase/firebase-js-sdk#212 don’t apply to the Admin SDK. It would be great to have a `DocumentReference.select()` function implemented there.

**Comment by schmidt-sebastian** [comment]
We are currently debating on how to best implement this. Please stay tuned.
