### ISSUE TITLE
Document with a number type property fails, if number is zero

### ISSUE THREAD

**Issue by timojuonoja** [googleapis/nodejs-firestore#436]
#### Environment details

  - OS: Linux
  - Node.js version: 8.10.0
  - npm version: 5.6.0
  - `@google-cloud/firestore` version: 0.18.0

#### Steps to reproduce

  1. `collection('col1').doc('doc1').set({ number: 0 })`
  2. Fails with `Error: Invalid use of type "undefined" as a Firestore argument.`

**Comment by schmidt-sebastian** [comment]
Do you mind sharing more of you code? I am not able to reproduce this:

```
    const ref = firestore.doc('col/doc');
    return ref.set({ number: 0 });
```

Logs:
```
Firestore (0.18.0) 2018-11-09T00:55:07.001Z 9ZfUT [Firestore.request]: Sending request: {"database":"projects/.../databases/(default)","writes":[{"update":{"name":"projects/.../databases/(default)/documents/col/doc","fields":{"number":{"integerValue":0}}}}]}
Firestore (0.18.0) 2018-11-09T00:55:07.613Z 9ZfUT [Firestore.request]: Received response: {"writeResults":[{"transformResults":[],"updateTime":{"seconds":"1541724798","nanos":668307000}}],"commitTime":{"seconds":"1541724906","nanos":682288000}}
```

**Comment by timojuonoja** [comment]
Whoops, maybe the problem is not then number zero. I was just assuming that because I could not find any other reason for `"undefined"`.

Here is test code:
```
import faces from 'facesjs'

export const test = https.onCall(async () => {
  try {
    const data = { face: faces.generate() }
    console.log("Data", JSON.stringify(data))
    await db.collection('test').doc('doc').set(data)
    return {}
  } catch (err) {
    console.log(err)
    throw new https.HttpsError('internal')
  }
})
```

And here is the result as attachment:
![2018-11-09 08 37 42](https://user-images.githubusercontent.com/7699788/48247266-56f51980-e3fb-11e8-8133-98dc4d3ffdb8.png)

**Comment by timojuonoja** [comment]
But I realized that it is even better to stringify the content for storing that onto firestore. So my code works fine now, but I just wanted you to know about the problem.

**Comment by timojuonoja** [comment]
@schmidt-sebastian Ok. I'm using firestore for the first time, so therefore I have still lot to learn. Thanks for the reply.
