### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by NawarA** [googleapis/nodejs-firestore#456]
Hey folks, your latest version of Firestore throws a warning. Maybe try updating your source code so doesnt throw a deprecation warning / or use deprecated methods? Or maybe update your `grpc` or `google-auth-library` dependency 

#### Environment details

  - OS: `Ubuntu 18 LTS`
  - Node.js version: `11.1.0`
  - npm version: `the one included in 11.1.0`
  - `@google-cloud/firestore` version: `0.18.0`

#### Steps to reproduce

  1. Make a request to Firestore
  2. Request succeeds AND throws the following warning:

```bash
(node:27738) [google-auth-library:DEP004] DeprecationWarning: The `getRequestMetadata` method on the `OAuth2` class has been deprecated, and will be removed inthe 3.0 release of google-auth-library. Please use the `getRequestHeaders` method instead.
{ DeprecationWarning: The `getRequestMetadata` method on the `OAuth2` class hasbeen deprecated, and will be removed in the 3.0 release of google-auth-library.Please use the `getRequestHeaders` method instead.
    at Object.warn (/home/nawar/dev/API/node_modules/@google-cloud/firestore/node_modules/google-auth-library/build/src/messages.js:35:17)
    at JWT.getRequestMetadata (/home/nawar/dev/API/node_modules/@google-cloud/firestore/node_modules/google-auth-library/build/src/auth/oauth2client.js:232:18)
    at /home/nawar/dev/API/node_modules/grpc/src/credentials.js:151:23
    at /home/nawar/dev/API/node_modules/grpc/src/credentials.js:121:5
  name: 'DeprecationWarning',
  code: 'google-auth-library:DEP004' } undefined
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by schmidt-sebastian** [comment]
We will release a new version with an upgraded GRPC dependency shortly.
