### ISSUE TITLE
Cloud Firestore in Datastore mode

### ISSUE THREAD

**Issue by mattfysh** [googleapis/nodejs-firestore#459]
It might be an idea to highlight that this library does not work with "Cloud Firestore in Datastore mode" - somewhere high up in the readme

**Comment by rockwotj** [comment]
Yeah we should point people to the CloudDatastoreV1 package at: https://github.com/googleapis/nodejs-datastore

**Comment by schmidt-sebastian** [comment]
Added note which should show up with the next release.
