### ISSUE TITLE
INTERNAL UNHANDLED ERROR:  TypeError: protobufjs.newBuilder is not a function

### ISSUE THREAD

**Issue by sauravexodus** [googleapis/nodejs-firestore#46]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS: Mac OSX High Siera 10.13
  - Node.js version: 8.6.0
  - npm version: 5.5.1
  - @google-cloud/firestore version: '0.57.0'/4.6.0

#### Steps to reproduce

  1. Simply writing a .get() query on db.collection('collectionName')
  2. See this error in console
`Firestore (4.5.2) 2017-10-29T13:14:59.576Z: INTERNAL UNHANDLED ERROR:  TypeError: protobufjs.newBuilder is not a function
log.ts:50
    at loadProtos (/Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/platform_node/load_protos.js:37:30)
    at /Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/platform_node/load_protos.js:23:9
    at /Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/util/node_api.js:58:9
    at Promise (<anonymous>)
    at Object.nodePromise (/Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/util/node_api.js:57:12)
    at Object.loadProtosAsync (/Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/platform_node/load_protos.js:22:23)
    at NodePlatform.loadConnection (/Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/platform_node/node_platform.js:28:30)
    at FirestoreClient.initializeRest (/Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/core/firestore_client.js:218:14)
    at /Users/sourav/Documents/TestProjects/nodeTest/node_modules/@firebase/firestore/dist/cjs/src/core/firestore_client.js:109:54
    at <anonymous>`

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by schmidt-sebastian** [comment]
Can you provide the output of `npm list`? Thanks.

**Comment by ruucm-working** [comment]
same err 
```
Firestore (4.5.2) 2017-11-08T18:50:54.318Z: INTERNAL UNHANDLED ERROR:  
```

**Comment by schmidt-sebastian** [comment]
@sauravexodus and @ruucm-working: 

`@google-cloud/firestore` is meant to be used for Node on servers. The Web SDK is meant for browsers. Can you confirm that you are using the right SDK?

Please follow the setup instructions here: https://firebase.google.com/docs/firestore/quickstart

**Comment by schmidt-sebastian** [comment]
Closing this for now. Please re-open should this issue persist.

**Comment by shalomvolchok** [comment]
In case anyone comes looking here, as I just did. I was just experiencing this same issue and I found that as of yesterday, the web sdk now supports nodejs with firebase@4.7.0. https://firebase.google.com/support/release-notes/js
