### ISSUE TITLE
Remove QuerySnapshot.forEach

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-firestore#481]
I am not sure of the purpose of this particular method and think we could remove it to reduce the surface area of the client. A user can always iterate over QuerySnapshot.

## using current code
```
query.get().then(querySnapshot => {
  querySnapshot.forEach(documentSnapshot => {
    console.log(`Document found at path: ${documentSnapshot.ref.path}`);
  });
});
```

## without this code
```
query.get().then(querySnapshot => {
  for (const doc of querySnapshot.docs) {
    console.log(`Document found at path: ${documentSnapshot.ref.path}`); 
  }
});
```

**Comment by schmidt-sebastian** [comment]
I will bring this up in our Firestore-internal API meeting.

**Comment by jadekler** [comment]
cc @mikelehen any news on this?

**Comment by mikelehen** [comment]
Yes, sorry.  We discussed this and decided that we want to keep it (it's a nice convenience function, it's more efficient than iterating of the `.docs` array, and removing it would be a breaking change we don't want to make).  From Chris's comments on the doc, I'm pretty sure he's okay with this resolution, but please holler if anybody has concerns.
