### ISSUE TITLE
Chaining db.collection()

### ISSUE THREAD

**Issue by PatrickHeneise** [googleapis/nodejs-firestore#483]
I just tried to build a query component for a simple list. I'd like to filter/orderBy/limit the list given certain parameters:

```
let list = firestore.collection(collection)
if (order) {
  list.orderBy(order)
}
```

This didn't work. In the `list` object, the _fieldOrders are not set: `  _fieldOrders: {}`

When I write `firestore.collection(collection).orderBy(order)`, `_fieldOrders` looks like this:

```
  _fieldOrders: [ FieldOrder { field: [Object], direction: 'ASCENDING' } ],
```

This is the same for `limit` (`_queryOptions: {}` vs. `  _queryOptions: { limit: 1 }`).

#### Environment details

  - OS: macOS
  - Node.js version: v8.12.0
  - npm version: v6.4.1
  - `@google-cloud/firestore` version: v0.19.0

#### Steps to reproduce

```
let list = firestore.collection(collection)
if (order) {
  list.orderBy(order)
}

// _fieldOrders is {}, but should be [ FieldOrder { field: [Object], direction: 'ASCENDING' } ]
```

Thanks!

**Comment by schmidt-sebastian** [comment]
The query class is immutable and all query methods return a modified instance. Please rewrite your code as such:

```
let list = firestore.collection(collection)
if (order) {
  list = list.orderBy(order)
}
```

**Comment by PatrickHeneise** [comment]
Thanks. Would be great to fix that though, since chaining is a common pattern.
