### ISSUE TITLE
Enums are not properly documented.

### ISSUE THREAD

**Issue by jmdobry** [googleapis/nodejs-firestore#50]
The proto contains enums that are namespaced under the messages that used them, as seen here:

https://github.com/googleapis/googleapis/blob/master/google/firestore/v1beta1/query.proto#L63
https://github.com/googleapis/googleapis/blob/master/google/firestore/v1beta1/query.proto#L82
https://github.com/googleapis/googleapis/blob/master/google/firestore/v1beta1/query.proto#L116

but in the generated [proto doc](https://github.com/googleapis/nodejs-firestore/blob/master/src/v1beta1/doc/google/firestore/v1beta1/doc_query.js#L163) the enums are not properly documented, so the enums don't show up on [cloud.google.com](https://cloud.google.com/nodejs/docs/reference/firestore/latestl/)

This probably needs to be fixed in googleapis/toolkit

**Comment by schmidt-sebastian** [comment]
The enum values now show up correctly in the documentation: https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1beta1#google.firestore.v1beta1.StructuredQuery.CompositeFilter.Operator
