### ISSUE TITLE
Typings: Cannot destructure array anymore when calling getAll

### ISSUE THREAD

**Issue by ushu** [googleapis/nodejs-firestore#501]
Since PR #443 has been merged, the signature for `Firestore.getAll()` has changed from

```javascript
getAll(...documents: DocumentReference[]): Promise<DocumentSnapshot[]>
```

to

```javascript
getAll(documentRef: DocumentReference, ...moreDocumentRefsOrReadOptions: Array<DocumentReference|ReadOptions>): Promise<DocumentSnapshot[]>
```

with this change, we cannot use array destructuring anymore to "prepare" the refs to fetch in advance.

For example, I used to do the following:

```javascript
// step 1 - select the documents to fetch
const userIDs = ... 
const usersRef = admin.firestore().collection("users")
const userRefs: DocumentReference[] = userIDs.map(id => usersRef.doc(id))

// step 2 - Grab-them-all
const snaps = await admin.firestore().getAll(...userRefs)
``` 

this won't work anymore (I tried to update TS but it did not fix it), the only workaround is to do something like:

```javascript
const snaps = await admin.firestore().getAll(
  // extract the first item
  userRefs[0],
  // and then process the remaining elements
  ...(userRefs.slice(1))
)
```

#### Environment details

  - OS: Mojave
  - Node.js version: 10.12.0 (TS 3.2.2)
  - npm version: 6.4.1
  - `@google-cloud/firestore` version: 0.19.0

#### Steps to reproduce

  1. Create a project with Typescript support
  2. Type the code above (with `.getAll(...userRefs)`) → it won't compile

Edit: added #502 to restore previously-working behavior

Regards

**Comment by mikelehen** [comment]
I'll take a look at this later today, but I wonder if we can solve this by having 2 overloads.

**Comment by cxam** [comment]
@mikelehen not sure if you had any time to look at this yet but I've just created a PR (https://github.com/googleapis/nodejs-firestore/pull/515) that fixes this issue by overloading the getAll function.
