### ISSUE TITLE
Firestore emulator auth connection issues

### ISSUE THREAD

**Issue by sergeybekrin** [googleapis/nodejs-firestore#514]
#### Environment details

  - OS: macOS 10.14.2
  - Node.js version: 8.15.0
  - yarn version: 1.12.3
  - `@google-cloud/firestore` version: 0.19.0
  - firestore emulator version: 1.2.2

#### Description

Hey there! 👋

I'm trying to connect to local firestore emulator for testing, but it seems to have auth issues. I've checked `@firebase/testing` package for a reference, and the only clue I have is [token hjacking](https://github.com/firebase/firebase-js-sdk/blob/master/packages/testing/src/api/index.ts#L122) which I can't achieve in any possible way I've tried with this module.

It there maybe a way to override access token to `owner` or a way to add custom auth headers I'm missing? Thanks.

#### Steps to reproduce

1. Run the emulator:
```sh
java -Duser.language=en -jar ~/.cache/firebase/emulators/cloud-firestore-emulator-v1.2.2.jar --port 8080 --rules firestore.rules
```

```
// firestore.rules
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

2. Connect to it:
```javascript
const grpc = require('grpc');

const firestore = new Firestore({
  projectId: 'test-lzqnvo3eh', // project id is random for each run
  timestampsInSnapshots: true,
  sslCreds: grpc.credentials.createInsecure(),
  servicePath: 'localhost',
  port: 8080,
  'grpc.initial_reconnect_backoff_ms': 100,
  'grpc.max_reconnect_backoff_ms': 100,
});
```

3. Run sample operation:
```javascript
await firestore.doc('foo/bar').set({ value: 42 });
```

#### Logs

* firestore client logs:
```sh
Firestore (0.19.0) 2019-01-04T14:49:41.334Z ##### [Firestore]: Initialized Firestore
Firestore (0.19.0) 2019-01-04T14:49:42.490Z eyadC [WriteBatch.commit]: Sending 1 writes
Firestore (0.19.0) 2019-01-04T14:49:42.547Z ##### [Firestore]: Initialized Firestore GAPIC Client
Firestore (0.19.0) 2019-01-04T14:49:42.550Z eyadC [Firestore.request]: Sending request: {"database":"projects/test-lzqnvo3eh/databases/(default)","writes":[{"update":{"name":"projects/test-lzqnvo3eh/databases/(default)/documents/foo/bar","fields":{"value":{"integerValue":42}}}}]}
Firestore (0.19.0) 2019-01-04T14:49:43.467Z eyadC [Firestore.request]: Received error: { Error: 7 PERMISSION_DENIED: false for 'create' @ L4, false for 'update' @ L4 }
Firestore (0.19.0) 2019-01-04T14:49:43.467Z eyadC [Firestore._retry]: Request failed with unrecoverable error
```

* firestore emulator output: 
```sh
API endpoint: http://[::1]:8080
API endpoint: http://127.0.0.1:8080
Dev App Server is now running.

Jan 04, 2019 3:28:37 PM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
INFO: Adding handler(s) to newly registered Channel.
Jan 04, 2019 3:28:37 PM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
INFO: Detected HTTP/2 connection.
```

**Comment by mikelehen** [comment]
cc/ @ryanpbrewster 

I think this isn't a supported scenario yet (right now the emulator is targeted at testing rules and works best when used via the `@firebase/testing` module), but Ryan may know if there is a trick to make this work.

**Comment by ryanpbrewster** [comment]
1. Is there some reason you cannot use the `@firebase/testing` SDK? It has some of these auth features built in.

2. If you really do want to use this directly, you can attach credentials using gRPC metadata. Here's how we [construct it](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/platform_node/grpc_connection.ts#L51) and here's how we [attach it](https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore/src/platform_node/grpc_connection.ts#L144) to the RPC. I'm not as familiar with this SDK, let me see if there's some easy hook you can use.

**Comment by ryanpbrewster** [comment]
Ah, I see, this is more of a server SDK.

If you end up using the RPCs directly (e.g., calling `firestore.getDocument` or `firestore.commit`) then you can pass in the gRPC metadata as indicated in the previous document.

The helper methods (e.g., `firestore.doc("my_collection/my_doc").set`) do not accept or pass through any extra arguments, so it's not easy to use them with auth. There is some way to pass in a `Credentials` object to the Firestore client, but it's not obvious to me what that object is supposed to do. I'll find someone more familiar with this code and see what we can do.

Thanks for reporting this!

**Comment by ryanpbrewster** [comment]
Short-term workarounds:

1. Use open rules in the emulator. This won't help you test your security rules, but this SDK is normally authenticated using an admin service account, which bypasses security rules, so maybe that's not a blocker. Doing this will let you test most of the other behavior.
2. Manually edit this SDK. I think you want to add an "Authorization" header right here: https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/index.ts#L924. Let me know if you're interested in more details here.

**Comment by sergeybekrin** [comment]
@ryanpbrewster thanks for the tips! I've tried both using open rules and injecting auth header [by extending Firebase class](https://gist.github.com/sergeybekrin/ce90de067838ed4136f657673e292df7). Permission error is now gone, but any update operation fails with `AssertionError [ERR_ASSERTION]: Expected one write result per operation, but got 0 results for 1 operations` and some methods fails with `operation failed: expected Firestore query semantics but got DATASTORE` on emulator side.

It seems that current state of the emulator is not quite suitable for integration testing. I'll stick to unit tests for now, thanks a lot for your help!

**Comment by sbekrin** [comment]
Quick update: firestore-emulator v1.3.0 seems to be working as expected (except datastore methods like `.listDocuments()`) and looks more or less suitable for testing 🎉

**Comment by ryanpbrewster** [comment]
Glad to hear it. There are a few additional features we've recently added that I'm hoping prove helpful, and tighter integration with Cloud Functions in the pipeline. Stay tuned :)

**Comment by schmidt-sebastian** [comment]
This error is also thrown if the rules deny all access to the Firestore database. I had to change the rules that are defined in "firestore.rules". Would it be possible to return a more descriptive error in this case?
