### ISSUE TITLE
getCollections declaration is missing in firestore.d.ts

### ISSUE THREAD

**Issue by mmlleevvyy** [googleapis/nodejs-firestore#52]
#### Environment details
  - OS: MacOs 10.13
  - Node.js version: 8.1.4
  - npm version: 5.5.1
  - @google-cloud/firestore version: 0.8.2

#### Steps to reproduce
Typescript declaration file (firestore.d.ts) is missing getCollections() method for Firestore class and DocumentReference class.

**Comment by schmidt-sebastian** [comment]
Thanks for pointing this out! PR is coming.
