### ISSUE TITLE
Enable noImplicitAny?

### ISSUE THREAD

**Issue by joecervino** [googleapis/nodejs-firestore#525]
I was wondering if this library is ready to be worked on to enable noImplciitAny. I see a TODO in the tsconfig file asking to remove the "false" assignment for noImplicitAny once source is finished migrating to TS

**Comment by mikelehen** [comment]
Unfortunately not. There's a large outstanding PR to migrate a bunch more code to TypeScript: https://github.com/googleapis/nodejs-firestore/pull/512  Any work done to remove noImplicitAny would need to happen after that PR lands.
