### ISSUE TITLE
Include database export and import in library

### ISSUE THREAD

**Issue by AniX** [googleapis/nodejs-firestore#545]
I'd like to use the nodejs-firestore library to export and import collections, instead of sending bare requests to the REST API at 

`https://firestore.googleapis.com/v1beta1/projects/${projectId}/databases/(default):exportDocuments`

The Firestore documentation contains a [code sample](https://cloud.google.com/firestore/docs/solutions/schedule-export#appjs) how to use the REST API from a request handler in App Engine.

However, I believe it would me more intuitive if we could use the nodejs-firestore library to create export or import jobs in Firestore.

I'm not very skilled with Node.js, but I figure something like this for the [Method: projects.databases.exportDocuments](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases/exportDocuments):

```javascript
const Firestore = require('@google-cloud/firestore');

const firestore = new Firestore({
  projectId: 'YOUR_PROJECT_ID',
  keyFilename: '/path/to/keyfile.json',
});

const database = firestore.databases('my_database');
var operation = database.exportDocuments({
  'collectionIds': [
    'Users',
    'Customers'
  ],
  'outputUriPrefix': 'gs://my-bucket/folder_foo'
});
```

Certainly, something similar could be done with [Method: projects.databases.importDocuments](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases/importDocuments)

**Comment by schmidt-sebastian** [comment]
We currently don't expose the Admin API of Firestore in our server clients. This feature request will be addressed when we add this support.
