### ISSUE TITLE
Where is the client library reference doc site?

### ISSUE THREAD

**Issue by jadekler** [googleapis/nodejs-firestore#562]
I'm struggling to find a link to a docsite (godoc, javadoc equivalent) in the README. Where can I find this?

**Comment by mikelehen** [comment]
FWIW- The reference docs are here: https://cloud.google.com/nodejs/docs/reference/firestore/0.20.x/

Presumably we should add that to the github README or something though.

**Comment by jadekler** [comment]
Please do, or in the github landing page header.

**Comment by schmidt-sebastian** [comment]
I have good news! We actually do have the (outdated) API docs linked to in the [README.md](https://github.com/googleapis/nodejs-firestore/blob/master/README.md). The link is at the very bottom in the "What's Next" section. In the meantime, I am trying to get the docs for 1.0.2 published, but that is another issue altogether. Hence, I am closing this issue for the time being :)
