### ISSUE TITLE
Error: Argument "updateFunction" is not a valid function.

### ISSUE THREAD

**Issue by jineshshah36** [googleapis/nodejs-firestore#574]
Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version: 10.15.1
  - npm version:
  - `@google-cloud/firestore` version: 1.0.2

#### Steps to reproduce

  1. Call firestore.runTransaction with an async function
  2. You will get the error Error: Argument "updateFunction" is not a valid function.
  3. The issue is that isFunction checks for [object Function] when an async function produces [object AsyncFunction]

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dinvlad** [comment]
Same issue here, this is breaking our production builds with `firebase-admin`.

**Comment by schmidt-sebastian** [comment]
We can fix this in the next release. Thanks for letting us know!
