### ISSUE TITLE
Transactions are preforming an extra round trip

### ISSUE THREAD

**Issue by rockwotj** [googleapis/nodejs-firestore#575]
Run transaction starts with a call to BeginTransaction
  https://github.com/googleapis/nodejs-firestore/blob/0dcea7f932383883aa8cc5f370b894a8ec99326f/dev/src/index.ts#L619

However, this requires an extra server around trip adding unnecessary latency.

All read operations allow you to create a transaction, so this could be deferred until the first read.

https://github.com/googleapis/googleapis/blob/eba92c8f27ef337c38ee65aecc905497ed9d92ce/google/firestore/v1beta1/firestore.proto#L353

/cc @samtstern @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know! We'll address this in one of our upcoming releases.

**Comment by schmidt-sebastian** [comment]
Closing this due to low impact and limited engineering resources. We can revisit if needed.
