### ISSUE TITLE
"Error 3: Order must include __name__" when using "limit"

### ISSUE THREAD

**Issue by bmass02** [googleapis/nodejs-firestore#59]
#### Environment details

  - OS: 10.12.6 (16G29)
  - Node.js version: v8.1.4
  - npm version: 5.4.2
  - @google-cloud/firestore version: 0.9.0

#### Steps to reproduce

  1. Follow instructions for setting up Nodejs Firestore [here](https://cloud.google.com/nodejs/docs/reference/firestore/0.9.x/module-@google-cloud_firestore)
  2. Run this [file](https://gist.github.com/bmass02/3fa498fa401c271b6ca4d1b7b90b8688)
  3. If you add ```orderBy('__name__')```, it gets past the error, but fails at return value of ```query.comparator()``` (specifically ```reference.js:1679:19```).

#### Extra info

Proto built from query (without ```orderBy('__name__')```):
```
{
  "parent":"projects/<projectId>/databases/(default)",
  "structuredQuery":{
    "from":[
      {
        "collectionId":"collectionId"
      }
    ],
    "orderBy":[
      {
        "field":{
          "fieldPath":"index"
        },
        "direction":"ASCENDING"
      }
    ],
    "limit":{
      "value":5
    }
  }
}
```

(with ```orderBy('__name__')```):
```
{
  "parent":"projects/<projectId>/databases/(default)",
  "structuredQuery":{
    "from":[
      {
        "collectionId":"collectionId"
      }
    ],
    "orderBy":[
      {
        "field":{
          "fieldPath":"index"
        },
        "direction":"ASCENDING"
      },
      {
        "field":{
          "fieldPath":"__name__"
        },
        "direction":"ASCENDING"
      }
    ],
    "limit":{
      "value":5
    }
  }
}
```
Request built using the web version (follow setup [here](https://firebase.google.com/docs/firestore/quickstart); file [here](https://gist.github.com/bmass02/bd9015d829ace9d0574a9d8f01fed9f2)):

```
{
  "database":"projects/<projectId>/databases/(default)",
  "addTarget":{
    "query":{
      "structuredQuery":{
        "from":[
          {
            "collectionId":"collectionId"
          }
        ],
        "orderBy":[
          {
            "field":{
              "fieldPath":"index"
            },
            "direction":"DESCENDING"
          },
          {
            "field":{
              "fieldPath":"__name__"
            },
            "direction":"DESCENDING"
          }
        ],
        "limit":2
      },
      "parent":"projects/<projectId>/databases/(default)"
    },
    "targetId":2
  }
}
```

**Comment by schmidt-sebastian** [comment]
The Firestore SDK equivalent of `__name__` is `Firestore.FieldPath.documentId()`.

If you change your query to

```
const query = collRef.orderBy('index').orderBy(Firestore.FieldPath.documentId()).limit(5)
```

it will work as expected. We probably need to update our error message to make sure that this is more obvious.
