### ISSUE TITLE
I cant increment() in my firestore.d.ts file

### ISSUE THREAD

**Issue by momoDragon** [googleapis/nodejs-firestore#597]
I am on version: 
+ @google-cloud/firestore@1.2.0

This is the firestore.d.ts file:
https://pastebin.com/eEHg83kf
(i cant find increment() in there)

This is what i am trying to do:
admin.firestore.FieldValue.increment(1)

**Comment by momoDragon** [comment]
This is the error i am getting on firebase cloud functions logs:
TypeError: admin.firestore.FieldValue.increment is not a function
    at exports.setAvailableItemsCount.functions.firestore.document.onUpdate (/srv/index.js:203:74)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by mikelehen** [comment]
@momoDragon I just verified that it's showing up for me:

```
$ npm install firebase-admin
...

$ grep "increment(" node_modules/\@google-cloud/firestore/types/firestore.d.ts
    static increment(n: number): FieldValue;
```

If your `node_modules/\@google-cloud/firestore/types/firestore.d.ts` doesn't include it, can you double check the version number at the bottom of `node_modules/\@google-cloud/firestore/package.json` to make sure it's 1.2.0?

**Comment by bcoe** [comment]
@momoDragon that file you've provided looks like an older version of the firesore types, perhaps try the following:

`npm uninstall @google-cloud/firestore`
`rm -rf node_modules/*`
`npm i @google-cloud/firestore@1.2.0`

:point_up: let me know if this does the trick for you :+1:

**Comment by momoDragon** [comment]
rm -rf node_modules/* didnt work for me so i just manually deleted the file.
And then reinstalled functions. works like a charm! thanks a million!

**Comment by momoDragon** [comment]
Souldent just by upgrading functions by npm do the job without deleting and reinstalling? Why the extra steps?

**Comment by bcoe** [comment]
@momoDragon the extra steps should not be necessary, I'm wondering if there was something odd in your `package-lock.json`, which uninstalling and reinstalling would help correct.

I don't expect that you should need to do this again.

**Comment by momoDragon** [comment]
Ok my firestore.d.ts has the increment function after the reinstall of modules.

however my console log still giving me errors
TypeError: admin.firestore.FieldValue.increment is not a function
    at exports.setAvailableItemsCount.functions.firestore.document.onUpdate (/srv/index.js:196:73)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)

**Comment by bcoe** [comment]
@momoDragon could you provide some source-code, or a link to a repository that reproduces the issue? I'm curious what operation you're attempting to perform.

`FieldValue` I believe might be a class, so `increment` would be on its prototype and not exist until you `new` the object.

Let me know what you're trying to achieve, and I might be able to provide some sample code.

**Comment by momoDragon** [comment]
var docRef = admin.firestore().collection('vendors').doc(user.email);

                docRef.update({
                   'availableItemsCount'  :  admin.firestore.FieldValue.increment(1),
                });

**Comment by bcoe** [comment]
@momoDragon I think there's just a slight misunderstanding happening here about the increment API (I've opened an issue to document it better); here's how you'd go about implementing a field:

```js
process.env.GOOGLE_APPLICATION_CREDENTIALS = '/usr/local/google/home/bencoe/.config/qa-firestore.json'

const {Firestore, FieldValue} = require('@google-cloud/firestore');
async function main() {
    const firestore = new Firestore();

    const document = firestore.doc('folks/bob');

    await document.set({
      name: 'Bob',
      age: 33,
    });
    console.log('Entered new data into the document');

    // Update an existing document.
    await document.update({
      age: FieldValue.increment(33)
    });
};

main().catch(console.error);
```

Note that I import `FieldValue` from the main library, and then simply call it directly: `FieldValue.increment(N)`.

**Comment by momoDragon** [comment]
Btw my usage is for cloud functions node.js
Getting this error from your usage:
ReferenceError: FieldValue is not defined
    at exports.setAvailableItemsCount.functions.firestore.document.onUpdate (/srv/index.js:196:46)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)


![Screenshot_42](https://user-images.githubusercontent.com/40727575/55764846-cef56780-5a9f-11e9-8049-9b708f326402.png)
![Screenshot_43](https://user-images.githubusercontent.com/40727575/55764865-d74da280-5a9f-11e9-8675-8eb6654b5c04.png)

**Comment by mikelehen** [comment]
cc/ @hiranya911 who owns the Admin SDK and might know if there's some reason this wouldn't be working (we added `FieldValue.increment()` in a recent `@gcloud/firestore` release, but it's apparently not showing up / working via the admin SDK).

**Comment by momoDragon** [comment]
Any update on the situation?

**Comment by mikelehen** [comment]
@momoDragon This is working for me.  I ran "npm install firebase-admin" and then put this in a .ts file and ran it:
```
import * as admin from 'firebase-admin';

admin.initializeApp({...});
const db = admin.firestore();
const doc = db.doc('foo/bar');
doc.update({count: admin.firestore.FieldValue.increment(1) }).then(() => console.log('success'));
```

And it printed "success" and the value was incremented.  If you're still having issues, perhaps you can provide an [MCVE](https://stackoverflow.com/help/mcve)?

**Comment by bcoe** [comment]
@mikelehen I think the problem is that @momoDragon is using `@google-cloud/firestore`; it would seem that the admin functionality works as expected in the npm package `firebase-admin`, but not in the npm package `@google-cloud/firestore`.

----

@momoDragon perhaps you could use the `firebase-admin` library for the time being, and I'll work on talking to the right people to consolidate the two libraries.

**Comment by bcoe** [comment]
@momoDragon what might be very helpful at this point to help us debug further also, would be if you could provide us with either a small GitHub repository that demonstrates your issues, or a gist.

@mikelehen and I are scratching our heads trying to figure out exactly how you're initializing your admin instance.

**Comment by momoDragon** [comment]
const admin = require('firebase-admin');
this is how i initialize

**Comment by mikelehen** [comment]
If you’re still stuck, can you provide your full code and the output of
‘npm ls’?

**Comment by momoDragon** [comment]
https://pastebin.com/LeiaUraL
here is the code

**Comment by momoDragon** [comment]
i edited my comment link ^

**Comment by mikelehen** [comment]
And the output of `npm ls`?

**Comment by schmidt-sebastian** [comment]
Hey :) Sorry to chime in here so late. You need to make sure that the you are staying "within" your client. That is, if you are using the `@google-cloud/firestore` package, you should do (pseudocode):

```
const {Firestore, FieldValue} = require('@google-cloud/firestore');
const firestore = new Firestore();
firestore.update('foo', FieldValue.increment(1));
```

If you are using the Admin SDK/Cloud Functions:
```
const admin = require('firebase-admin');
admin.initializeApp();
const firestore = new admin.Firestore();
firestore.update('foo', admin.Firestore.FieldValue.increment(1));
```

The code in the pastebin (https://github.com/googleapis/nodejs-firestore/issues/597#issuecomment-481960556) works for me after adding `admin.initializeApp()`.

**Comment by momoDragon** [comment]
@schmidt-sebastian  my original code already had `admin.initializeApp();` but it still didnt work. I am using cloud functions.

**Comment by schmidt-sebastian** [comment]
Please provide the output of `npm ls`.

**Comment by momoDragon** [comment]
How do i get the npm output ?

**Comment by schmidt-sebastian** [comment]
You need to run the `npm ls` command in the Command Line from the directory that includes the `package.json` and `node_modules` folder.

**Comment by momoDragon** [comment]
npm output 
https://pastebin.com/sv3xUnjk

package.json
https://pastebin.com/5AAB5wJL

**Comment by schmidt-sebastian** [comment]
Your NPM output looks good to me. There are a couple errors at the bottom, but they seem unrelated.
The package.json if from `firebase-admin` though. Do you have the package.json for your own project?

**Comment by momoDragon** [comment]
`
{

  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "scripts": {
    "lint": "eslint .",
    "serve": "firebase serve --only functions",
    "shell": "firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions",
    "logs": "firebase functions:log"
  },
  "dependencies": {
    "firebase-admin": "~6.0.0",
    "firebase-functions": "^2.1.0"
  
  },
  
  "devDependencies": {
    "eslint": "^5.12.0",
    "eslint-plugin-promise": "^4.0.1"
  },
  "engines": { "node": "8" },
  "private": true
}


`

**Comment by momoDragon** [comment]
@schmidt-sebastian  The issue was on my packages.json !. instead of ^ for the versioning it was ~ so my project wasent using the latest version. Thanks a million.

**Comment by PaulBouisset** [comment]
Hi, I run into the same issue as momoDragon. My cloud function return the following error : 
`admin.firestore.FieldValue.increment is not a function`

I use :  "firebase-admin": "^6.5.1" 

Did the syntax changed ?

**Comment by schmidt-sebastian** [comment]
Firebase Admin 6.5.1 is somewhat old and may not have included this feature. Do you mind upgrading to a newer version?

**Comment by ReaperTech** [comment]
Try **npm i firebase-admin@latest** in your functions directory. If you just run **npm i firebase-admin** it will change "firebase-admin": "~6.5.1" to "firebase-admin": "^6.5.1" but won't install the latest. This solved my problem.
