### ISSUE TITLE
document increment functionality

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-firestore#598]
It would be useful to update samples to demonstrate increment functionality.

see: #597

**Comment by schmidt-sebastian** [comment]
@bcoe Thanks for filing this issue. We can certainly always improve our documentation, but I don't think `FieldValue.increment()` is an important enough feature to be part of our top-level samples.

Instead, I hope that our existing API documentation will answer most questions. Please take a look at the snippet here:
https://cloud.google.com/nodejs/docs/reference/firestore/1.1.x/FieldValue#.increment

We also have a more involved sample that shows how you can use the same API with the web client: https://firebase.google.com/docs/firestore/solutions/counters

Lastly, we recently published a blog post about this feature: https://firebase.googleblog.com/2019/03/increment-server-side-cloud-firestore.html
This blog post does not contain code snippets, though.

I believe that this documentation should cover most use cases and will close this issue for now.
