### ISSUE TITLE
Looking for Error Codes

### ISSUE THREAD

**Issue by dyllandry** [googleapis/nodejs-firestore#602]
Using this api has been a pleasure so far, thanks for maintaining it.

Updating a document can return a rejected promise with error code 5: `No document to update`.

Is there a part of the nodejs-firebase api to check error codes against? I'd like to include some semantics in my error checking. I found google's definition for their [error structure](https://cloud.google.com/firestore/docs/reference/rest/v1beta1/Status), but nothing particular to that in the [firestore api](https://cloud.google.com/nodejs/docs/reference/firestore/1.2.x/index-all).

**Comment by schmidt-sebastian** [comment]
@dyllandry Thanks for filing this request.

We don't have any specific error codes for Firestore, but you can take a look at the underlying GRPC error codes here: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md

As you can see here 5 translates to `NOT_FOUND`.
