### ISSUE TITLE
How to delete multiple document from firestore using where clause

### ISSUE THREAD

**Issue by amitransinha** [googleapis/nodejs-firestore#64]
Hi,
Here is my code.
`var jobskill_ref = db.collection('job_skills').where('job_id','==',post.job_id);
 jobskill_ref.delete();`

**Error which i am receiving**
**jobskill_ref.delete is not a function**

**Comment by samtstern** [comment]
@amitransinha for future reference this type of question probably belongs on StackOverflow.

There's no way to say "delete all the results of this query" but you can do this yourself in two steps using [batched writes](https://cloud.google.com/firestore/docs/manage-data/transactions#batched-writes)

```javascript
// First perform the query
db.collection('job_skills').where('job_id','==',post.job_id).get()
  .then(function(querySnapshot) {
        // Once we get the results, begin a batch
        var batch = db.batch();

        querySnapshot.forEach(function(doc) {
            // For each doc, add a delete operation to the batch
            batch.delete(doc.ref);
        });

        // Commit the batch
        return.batch.commit();
  }).then(function() {
      // Delete completed!
      // ...
  }); 
```

**Comment by theochampion** [comment]
Note that if planning on deleting more than 500 documents at a time, you'll have to split your batch deletes to stay under the limit as specified [here](https://firebase.google.com/docs/firestore/manage-data/transactions) ;)

**Comment by mbcod3** [comment]
I want to filter a collection where user can select multiple filters. For each filter I would do

db.collection('any').where('field', '==', filter1).get()
db.collection('any').where('field', '==', filter2).get()

I can't compound .where because the two filters can be on different fields. 
Is there anyway to make a single request i.e. batch read just like batch write?
