### ISSUE TITLE
"@grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0"

### ISSUE THREAD

**Issue by cyraid** [googleapis/nodejs-firestore#659]
If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS: Windows 10
  - Node.js version: 9.11.2
  - npm version: 5.6.0
  - `@google-cloud/firestore` version: 2.0.0

#### Steps to reproduce

  1. db = new Firestore(config)
  2. db.collection("/stuff").doc("a");
  3. doc.create( {hi: "world"} );

This will give you the "Error: @grpc/grpc-js only works on Node ^8.13.0 || >=10.10.0"

**Comment by cyraid** [comment]
I realize I only have node 9.11.2, but I can't change that on the server.. Is there any way to have this work with node 9.11.2?

**Comment by schmidt-sebastian** [comment]
@cyraid Thanks for reporting this issue and sorry for disappointing you! Node 9 was End of Lifed in [June 2018](https://github.com/nodejs/Release). We currently only support releases considered active by the Node working group. If you need to use an older version of Node, your best bet is to stick with 1.x Firestore until you can upgrade your Node environment. 

You should also be able to pass in your GRPC module to the Firestore constructor. I have never tested this, but it looks like it would work as such:

```
const firestore = new Firestore( { grpc:require('grpc') } );
```
