### ISSUE TITLE
get all documents from a collection is not working as I expect

### ISSUE THREAD

**Issue by Nilegfx** [googleapis/nodejs-firestore#671]
#### Environment details

  - OS: Mac
  - Node.js version:v10.11.0
  - npm version: 6.4.1
  - `@google-cloud/firestore` version:2.1.1

I am super new in google cloud services and I might not get it right from the documentation but I could NOT get all the documents stored in a collection (for some statistical reasons). even with limits, orderBy and other queries the result is "consistently"  inconsistent :D

as I said,n ot sure if it is a bug or I got it wrong.

#### Steps to reproduce
```javascript
const { Firestore } = require('@google-cloud/firestore');

// Create a new client
const firestore = new Firestore();
// create new collection
let collectionRef = firestore.collection('things');

async function addDocuments() {
  let addOperationsPromises = [];

  // add 25 question
  for (let i of Array(25)) {
    addOperationsPromises.push(collectionRef.add({ level: 1 }));
  }
  await Promise.all(addOperationsPromises);
}

async function getDocuments() {
  let snapshot = await collectionRef.get();
  console.log(snapshot.docs);
}

addDocuments();
getDocuments();
```

@bcoe thanks for your support.

**Comment by schmidt-sebastian** [comment]
Thanks for taking the time to let us know about your issue. We had a regression with a dependency that we recently fixed. Can you make sure that you are using the latest dependencies?

Additionally, can you provide your output of `npm list`? I want to verify that you are using @grpc/grpc-js version 0.4.0 and not 0.4.1. 0.4.1 exhibits the issue you described. We updated Firestore to downgrade gRPC back to 0.4.0.

**Comment by Nilegfx** [comment]
Hi @schmidt-sebastian 


here is what I did after according to your explanation of the issue: 

- uninstalled both `firebase-admin` (as I originally installed it thought it is the right one) and `@google-cloud/firestore`
- installed  `@google-cloud/firestore` again.
- removed `node_modules` directory
- ran npm install again
 
now I've `@grpc/grpc-js@0.4.0` and this solved the issue, however, I start getting this warning 
```
(node:44125) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 connectivityStateChanged listeners added. Use emitter.setMaxListeners() to increase limit
```
which I think it happened because of my loop mentioned above to add 25 item I created 25 Promises. I am not sure if I had this warning before (I don't think so).

**Comment by bcoe** [comment]
@schmidt-sebastian thanks for the quick response. I was helping @Nilegfx in person at JSConf EU and didn't think to look at `grpc-js` version.

@Nilegfx I'm glad your issue has been resolved 🎉 

Don't hesitate to reach out if you bump into more issues.
