### ISSUE TITLE
Add a settings flag for creating insecure credentials

### ISSUE THREAD

**Issue by samtstern** [googleapis/nodejs-firestore#674]
**Is your feature request related to a problem? Please describe.**

When using this library to connect to the Cloud Firestore emulator, you have to change the firestore settings like this:

```js
firestore.settings({
        projectId: 'samstern-projectdoesnotexist',
        port: 8080,
        servicePath: 'localhost',
        sslCreds: grpc.credentials.createInsecure(),
    });
```

In order to provide `sslCreds` I have to import `grpc` and make sure that I resolve to the same version of grpc as the one used by this library.  This is fairly inconvenient.

For instance with the change from `grpc` to `grpc-js` recently I had to change my testing code, but the change was not obvious since I was depending on an implementation detail of this library.

 **Describe the solution you'd like**

I would prefer that this library provide a new flag in `firestore.settings` like `insecureCredentials: true` or `sslEnabled: false` that would do the same thing under the hood.

Firestore already has this on other platforms.  For instance on Android:

```java
  FirebaseFirestoreSettings settings =
        new FirebaseFirestoreSettings.Builder()
                .setHost("10.0.2.2:8080")
                .setSslEnabled(false)
                .build();
```

 **Describe alternatives you've considered**

It's possible that we could infer this from `servicePath: localhost` but I don't need that much magic.

 **Additional context**

The Functions emulator built into the Firebase CLI automatically points the Firestore SDK at the emulator, and we have run into a bunch of issues related to needing to resolve `grpc` so this would help us a lot.

**Comment by samtstern** [comment]
cc @abeisgoat @ryanpbrewster

**Comment by schmidt-sebastian** [comment]
@samtstern Do we still need to do this if we take care of https://github.com/firebase/firebase-admin-node/issues/472?

**Comment by samtstern** [comment]
@schmidt-sebastian definitely less urgent if that lands, but I think environment variables are pretty messy and would prefer to have something like this also.
