### ISSUE TITLE
DocumentSnapshot returned by onSnapshot has undefined properties

### ISSUE THREAD

**Issue by Minitour** [googleapis/nodejs-firestore#682]
Basically I am trying to monitor a document and so I use the `onSnapshot` function.

The problem is that within the response I check if the document exists and then I check if the last time it was updated is the same as when I had in `knownDocument`.

`knownDocument` gets initialised within the function  `updateRecord`.

I am doing this "if check" because for some reason the callback gets invoked multiple times (even without calling updateRecord). I might be mis-using `onSnapshot`, but according to the documentation it should get the callback invoked as soon as a new document is available. 

#### Environment details

  - OS: `Windows 10`
  - Node.js version: `10.15.3`
  - npm version: `6.9.1`
  - `@google-cloud/firestore` version: `2.1.1`

#### Steps to reproduce

```javascript
const doc = db.collection('cameras').doc(cameraId);
cancelSubscription = doc.onSnapshot(documentSnapshot => {
        if (documentSnapshot.exists) {

            if (knownDocument == undefined) {
                console.log('knownDocument is undefined')
                updateRecord(documentSnapshot);
                return
            }
// The next if statement throws an exception because `updateTime` is undefined in both objects.
            if (!documentSnapshot.updateTime.isEqual(knownDocument.updateTime)) {
                console.log('knownDocument is not equal to documentSnapshot')
                updateRecord(documentSnapshot);
            }

        }
    }, err => {
        console.log(`Encountered error: ${err}`);
    });
```

**Comment by schmidt-sebastian** [comment]
@Minitour Thanks for letting us know about your issue. Can you share how you initialize Firestore? I wonder if you are accidentally using the `@firebase/firestore` Mobile SDK, which doesn't expose a document's update time.

**Comment by Minitour** [comment]
@schmidt-sebastian 
```javascript
const App = require('./firebase-application');
const db = App.firestore();
```
```javascript
// firebase-application.js

const firebase = require('firebase');

const FirebaseApplication = firebase.initializeApp({
    apiKey: "",
    authDomain: "",
    databaseURL: "",
    projectId: "",
    storageBucket : "",
    messagingSenderId: ""
});

module.exports = FirebaseApplication;
```

Thanks for the quick reply!

**Comment by Minitour** [comment]
I think I see the problem...
A bit embarrassing

**Comment by schmidt-sebastian** [comment]
You are using the Firebase Mobile SDK, which lives here https://github.com/firebase/firebase-js-sdk/tree/master/packages/firestore and is published as `firebase` or `@firebase/firestore` on NPM.

The NPM module for this Server SDK is `@google-cloud/firestore`. Our Server SDK support `updateTime`. The Mobile SDKs do not expose this property since they allow for local edits, in which case we cannot provide an accurate update time. 

To better understand which SDK to use, please take a look at: https://firebase.google.com/docs/firestore/client/libraries

**Comment by Minitour** [comment]
@schmidt-sebastian Thanks for the clarification, I was a bit mislead due to the word `Client` in the name `Cloud Firestore: Node.js Client` and so I assumed this was a frontend SDK.

Is there a Node.js frontend SDK that can be used for frontend projects that are node.js based like `electron` and others?

If not are there any plans for this SDK to also be available as a client side?

**Comment by schmidt-sebastian** [comment]
We recommend to use the `firebase` NPM package for Electron.
