### ISSUE TITLE
add support for emulator

### ISSUE THREAD

**Issue by Bala-raj** [googleapis/nodejs-firestore#687]
according to the emulator, we should use FIRESTORE_EMULATOR_HOST env var.

https://cloud.google.com/sdk/gcloud/reference/beta/emulators/firestore/start

```
firestore_1  | API endpoint: http://0.0.0.0:8080
firestore_1  | If you are using a library that supports the FIRESTORE_EMULATOR_HOST environment variable, run:
firestore_1  | 
firestore_1  |    export FIRESTORE_EMULATOR_HOST=0.0.0.0:8080
firestore_1  | 
firestore_1  | Dev App Server is now running.
```

But still, this SDK is pointing to the cloud if we are using gcloud CLI. is this something intended or it's because of the emulator still in beta?

**Comment by schmidt-sebastian** [comment]
This should work with the new 2.2 release of Firestore. What version are you using?

**Comment by Bala-raj** [comment]
My bad exactly the same day I installed the latest version but seems they released after that. 

Anyway, it works now thank you.
