### ISSUE TITLE
JOIN query in firestore

### ISSUE THREAD

**Issue by maranac0d3r** [googleapis/nodejs-firestore#695]
How to perform this?

[https://stackoverflow.com/questions/56661462/perform-join-query-in-google-cloud-firestore/56666799](https://stackoverflow.com/questions/56661462/perform-join-query-in-google-cloud-firestore/56666799)

Is below query possible ?
db.collection("posts").where("userid","oneOf",["userid_1","userid_2","userid_3"])

db.collection("posts").where("participants","array_contains",["part_1","part_2"])

**Comment by schmidt-sebastian** [comment]
@maranac0d3r Thanks for reporting! As luck would have it, this is in our feature pipeline, but we can't promise a release date. For now, please see the response in the StackOverflow.
