### ISSUE TITLE
Export Serializer

### ISSUE THREAD

**Issue by joonhocho** [googleapis/nodejs-firestore#705]
Please export Serializer. I am trying to cache firestore data on Redis and Timestamp field needs its (de)serializer.
I can write my own, but it's always best to use the source version.

It should be a simple one liner change like this: https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/index.ts#L74

```typescript
export {Serializer} from './serializer';
```

**Comment by bcoe** [comment]
Today, you should be able to do the following:

```js
const {Serializer} = require('@google-cloud/firestore/build/src/serializer')
```

:point_up: would this do the trick for you, or do you think we should keep this open as a feature request?

**Comment by schmidt-sebastian** [comment]
I am afraid of making the Serializer part of the Public API and would advise you to follow @bcoe's suggestion if you can.
