### ISSUE TITLE
System test flaky

### ISSUE THREAD

**Issue by schmidt-sebastian** [googleapis/nodejs-firestore#708]
The system test is flaky (see https://source.cloud.google.com/results/invocations/6ba7b0c3-e141-4fea-a875-48c64a520f5b/targets)

**Comment by jiren** [comment]
I think before the start of system test cases collections should be deleted.

**Comment by schmidt-sebastian** [comment]
We use random collection names in our system tests. Deleting entire collections is currently an async process that requires walking the document hierarchy.
