### ISSUE TITLE
Long running transaction always fails

### ISSUE THREAD

**Issue by swftvsn** [googleapis/nodejs-firestore#727]
#### Environment details

  - OS: Firebase Functions
  - Node.js version: 8
  - `@google-cloud/firestore` version: 2.2.4

We have a cloud function that is executed hundreds of times a day and it has always worked so far. However, we're doing some pretty heavy stuff inside the transaction, and now we have a transaction that takes roughly 3 minutes to compute. It seems that the transaction always fails if it takes that long inside the transaction. How can I set longer timeout?

**Comment by schmidt-sebastian** [comment]
@swftvsn Thanks for filing this issue! We currently don't offer a straightforward way to control how much time you can spend between document reads and the transaction commit. I can only advise you that it is beneficial for your project to keep this time as short as possible. 

Any read during a transaction places a write lock on the documents you are reading. Any other modifications to these documents will remain queued while the transaction is pending, which can degrade the performance across your client base. If you cannot decrease the scope of your transaction, consider the optimistic locking support offered by the WriteBatch API:

```
    const ref = coll.doc('doc');
    const batch = firestore.batch();
    const doc = await ref.get();
    batch.update(ref, {foo: 'bar'}, {updateTime:doc.updateTime});
    await batch.commit();
```
