### ISSUE TITLE
Later rollback of transactions

### ISSUE THREAD

**Issue by nicolaiwolko** [googleapis/nodejs-firestore#730]
## Concrete Request:
I would appreciate the possibility to **rollback a transaction after doing the commit** by myself.

## My cause:
That would allow me to test the outcome of a transaction (To do reads after the writes) and decide by myself if the transaction was successful or not.

## Alternative
Another solution for my problem would be to have another callback function which will be executed after the commit but could result in a rollback. Could be called a "test" callback.

## Possible solution:
We could achieve this by making the **Transaction class accessable**:
https://github.com/googleapis/nodejs-firestore/blob/56933478d8633759d853a8ed578e8204f8714eed/dev/src/transaction.ts#L67

At the very moment the transaction object and its transaction ID seems to be unreachable:
https://github.com/googleapis/nodejs-firestore/blob/56933478d8633759d853a8ed578e8204f8714eed/dev/src/transaction.ts#L72

But there already are commit and rollback functionality, unfortunately also hidden:
https://github.com/googleapis/nodejs-firestore/blob/56933478d8633759d853a8ed578e8204f8714eed/dev/src/transaction.ts#L384
https://github.com/googleapis/nodejs-firestore/blob/56933478d8633759d853a8ed578e8204f8714eed/dev/src/transaction.ts#L398

**Comment by schmidt-sebastian** [comment]
@nicolaiwolko Thanks for your suggestions! 

We currently don't hav plans to make our internal transaction API public, as this will expose our user to its retry and error handling logic. That being said, you might be able to achieve what you suggested if you can transform your transaction into a WriteBatch. Note that you can optimistically lock documents in a WriteBatch by using Preconditions:

```
const docSnap = await docRef.get();
const batch = firestore.batch();
batch.update(docRef, 'field', 'value', {lastUpdateTime:docSnap.updateTime});
await batch.commit();
```
