### ISSUE TITLE
Serializer does not check object for a prototype before calling hasOwnProperty()

### ISSUE THREAD

**Issue by lookfirst** [googleapis/nodejs-firestore#732]
Latest version.

https://github.com/googleapis/nodejs-firestore/search?q=hasOwnProperty&unscoped_q=hasOwnProperty

The bigger issue is that if I try to save an object into the firestore was created with `Object.create(null)`, the save fails due to the object not having hasOwnProperty. It is quite difficult to debug as a result

Related reasoning and background and example code: 

* https://github.com/graphql/express-graphql/issues/177
* https://github.com/graphql/graphql-js/pull/504
* https://github.com/apollographql/apollo-server/issues/3149

**Comment by lookfirst** [comment]
Exact reasoning: https://github.com/graphql/express-graphql/issues/177#issuecomment-273955947

**Comment by thebrianchen** [comment]
@praveenqlogic01  Thanks for your PR! We'll review this, make some changes to the PR, and then merge it in.

**Comment by thebrianchen** [comment]
@lookfirst I've been trying to reproduce the error in tests on our master branch, but it seems that calling `update`, `set`, or `create` with `Object.create(null)` or `{foo: Object.create(null)}` all seem to work fine.

What is your entry point that causes failures?

**Comment by lookfirst** [comment]
I think you'd need to pass in a top level object to set and that object is going to need to have some properties on it.

```
const foo = Object.create(null);
foo.bar = 'ack';
set(foo);
```

Not sure if this has an effect on the codepath, but I also run everything through a `transaction`.

There is an example in [this comment](https://github.com/apollographql/apollo-server/issues/3149#issuecomment-521056031) via [this gist](https://gist.github.com/trevor-scheer/e7f4022b5ce81ade7b79a206d16e9fd4#file-index-js-L22) to build the object which would be passed through to the set.

**Comment by lookfirst** [comment]
@thebrianchen Thank you so much!
