### ISSUE TITLE
error: project contains a Cloud Datastore database and does not support Cloud Firestore API calls

### ISSUE THREAD

**Issue by smarigowda** [googleapis/nodejs-firestore#76]
#### Environment details

  - OS: Mac
  - Node.js version: v6.11.3
  - npm version: 3.10.10
  - @google-cloud/firestore version: "@google-cloud/firestore": "^0.10.0"

OSTML0195470:firestoreNodeJS sma54$
#### Steps to reproduce

  1. Follow the steps listed here https://cloud.google.com/nodejs/docs/reference/firestore/0.8.x/

I first got the following error:

[Running] node "/Users/sma54/SAN/github/firestoreNodeJS/test.js"
(node:39182) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: The project firestoredemo-186515 does not exist or it does not contain an active Cloud Datastore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=firestoredemo-186515 to add a Cloud Datastore database. Note that Cloud Datastore always has an associated App Engine app and this app must not be disabled. [Done] exited with code=0 in 1.691 seconds

Then I clicked on the link and created a Cloud Datastore database. 

Then I am getting the following error.

[Running] node "/Users/sma54/SAN/github/firestoreNodeJS/test.js"
(node:39232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: This project contains a Cloud Datastore database and does not support Cloud Firestore API calls. [Done] exited with code=0 in 2.02 seconds

**Comment by smarigowda** [comment]
Created service account using Firebase console. This resolved the issue.

**Comment by andremw** [comment]
@smarigowda, I'm going through the same problem, but I cannot find where to create this service account.
I already have Firestore configured manually in Firebase console(it even has some collections and documents defined), but I couldn't manage to create this datastore service account in the console.

Could you clarify it to me?

**Comment by smarigowda** [comment]
<img width="1465" alt="firebase-service-account-page" src="https://user-images.githubusercontent.com/1831259/38257647-83706fa0-3758-11e8-9af3-5f992cfb197a.png">

**Comment by nuwanu** [comment]
@ysfjwd Just Enable  Google Cloud Firestore
![image](https://user-images.githubusercontent.com/33627609/39813486-3fcfd48a-53ae-11e8-8542-f348e21bf54c.png)

**Comment by lyleaf** [comment]
Can we choose to use Firestore rather than Datastore via a command line? I'm having this message: Error: The Cloud Firestore API is not available for Cloud Datastore projects.
    at Http2CallStream.call.on (/srv/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:71:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

**Comment by Hedayet** [comment]
@lyleaf, if you haven't used cloud datastore yet, you can migrate to firestore from cloud datastore dashboard.
![Screenshot 2019-11-16 at 17 58 34](https://user-images.githubusercontent.com/6074651/68992807-e1881880-089a-11ea-8379-030df4cc3607.png)
