### ISSUE TITLE
Sentinel values/FieldValue failed the type check when coming from package

### ISSUE THREAD

**Issue by 5argon** [googleapis/nodejs-firestore#760]
#### Environment details

  - OS: macOS
  - Node.js version: 8
  - npm version: 
  - `@google-cloud/firestore` version: 2.3.0

#### Steps to reproduce

My code has a `static` method that when called, instantiate an object to be set to a Firestore document.  It is just a map with some basic fields, plus a `timestamp` with sentinel value `FieldValue.serverTimestamp()`. It works fine and submitted fine to the Firestore server. I checked on the server and the sentinel value became a real timestamp as expected.

However I `tsc` and packaged that code, then use the static method from my other package, then submit the same map that was working. Now the sentinel value fail the type check test, even though the debugged type clearly says `ServerTimestampTransform`

```
     Error: Value for argument "data" is not a valid Firestore document. Couldn't serialize object of type "ServerTimestampTransform" (found in field serverConstants.timestamp). Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).
```

 which should pass the transpiled `serializer.js` which is this condition :

```
    else if (value instanceof field_value_1.FieldTransform) {
```

So this `value` when coming from a package, is no longer an `instanceof` `FieldTransform`. Do you have any idea why? Or where should I log in the module to help pinpoint the problem why `instanceof` wouldn't be `true` anymore?

I have checked my transpiled code, the `serverTimestamp()` seems to go to the type definition file that says it should  return `FieldValue` from `firebase-admin`, which then goes to `@google-cloud/firestore` one.

<img width="1023" alt="Screenshot 2019-09-18 19 32 49" src="https://user-images.githubusercontent.com/5653276/65148834-233b4500-da4b-11e9-9c04-28d9a32715a4.png">

The `FieldTransform` which is included in the `serializer.js` conditional seems to be an `extends` of `FieldValue`. And `ServerTimestampTransform` is one `extends` over `FieldTransform`.

So I suspect that before, this `serverTimestamp()` returns (real?) `ServerTimestampTransform` and so it passed `instanceof FieldTransform`. However right now, it returns a (weird?) `ServerTimestampTransform` that is just a `FieldValue` and not yet `FieldTransform` and fails. (?) And if that is so, why the debug message is able to say "ServerTimestampTransform" when it is not an instance of `FieldTransform` at the same time?

<img width="535" alt="Screenshot 2019-09-18 19 35 33" src="https://user-images.githubusercontent.com/5653276/65149401-37cc0d00-da4c-11e9-8026-49468cee66bf.png">

```
ServerTimestampTransform (pass) > FieldTransform (pass) > FieldValue (fail)
``` 

Or is it because of the type definition file of the following underlying `static` method is "gating" the type which would have been `ServerTimestampTransform` to go down to `FieldValue`?

```
    static serverTimestamp() {
        return ServerTimestampTransform.SERVER_TIMESTAMP_SENTINEL;
    }
```

I am running the test with `mocha` and `ts-node` together. And if I create a test that do `FieldValue.serverTimestamp()` and use it all in the test code, then it is not a problem. Only when the sentinel value come from inside a package that it is a problem.

**Comment by 5argon** [comment]
I think I got a clue now. This "package" I am talking about is a local package, pointed to it with "file:" in the "dependencies" in package.json. And so it appears in my `node_modules` as a symlink. Then, unlike other packages added with normal `npm install`, it got its own `node_modules`, and its own `@google-cloud/firestore`! (Unlike other modules, they may use the same `@google-cloud/firestore` in my main `node_module`)

Then it turns out maybe I am getting a `ServerTimestampTransform.SERVER_TIMESTAMP_SENTINEL` of type `ServerTimestampTransform` in the 2nd `node_modules` and it is not an instance of `ServerTimestampTransform` in the first one. I am not sure how to do local module that it use the same `@google-cloud/firestore` so the type check became compatible?

**Comment by schmidt-sebastian** [comment]
@5argon Thanks for filing this detailed issue! It looks like you managed to resolve it, but I wanted to confirm that the behavior you are seeing is somewhat expected. Our `instanceof` checks only work within the Firestore library itself. If you use two different copies of Firestore, any Prototype matching via instanceof will likely not produce the desired results. 

In the past, we have discussed relaxing these checks, but ultimately decided to leave them in place. If we start to accept FieldTransforms from other Firestore versions, internal implementation details will leak into our public API and guaranteeing compatibility between releases will become much more difficult. 

We have, however, tried to improve the user experience by providing better errors: https://github.com/googleapis/nodejs-firestore/blob/d15f29d71b27e867b192bcffa2ee7b75c5429d9f/dev/src/validate.ts#L58
It looks like we are not catching this particular case via this error handler, and I will make sure that we expand this check.

**Comment by AndroidGuyDD** [comment]
I discoverd the same problem too. 
What is the recommended way of having a local nodejs package with firebase dependencies inside a package with the same firebase dependencies?

webservice (node package with firebase dependecies)
---> dataPackage: is local package which in turn uses  firebase dependecies

When using `serverTimestamp()` within the local package, the above mentioned error occurs.

**Comment by schmidt-sebastian** [comment]
The best way to avoid this is to not use one package's `FieldValue.serverTimestamp()` with the other packages instance. `FieldValue.serverTimestamp()` from `@google-cloud/firestore` is different than the instance provided `by @firebase/firestore`. Each SDK can only use its own FieldValue. 

On top of that, you also need to ensure that you only have one version of the SDKs installed, as it is also not possible to use types from a different SDK version. That means that `@google-cloud/firestore v3.8.4`s FieldValue can also not be used with `@google-cloud/firestore v3.8.5`.

We have some idea on how to make this better, but there is no short term fix.

**Comment by pehagg** [comment]
@elbakerino, I'm having the same exact problem as you. Were you able to resolve the issue somehow?

**Comment by elbakerino** [comment]
In the meantime i've stopped [hoisting](https://github.com/lerna/lerna/tree/2.x#--hoist-glob) packages in lerna - this option seems to no longer exist in the newest lerna version.

I think that already solved it, as I've also reduced firestore usage, couldn't find it in a current monorepo.

**Comment by jflemingframe** [comment]
also having this same issue
Attempting to make a shared package with reusable code, running the same exact version of firebase-admin in both (consumer and the package) and encountering this.
