### ISSUE TITLE
Expose an API to close channels

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#769]
**Is your feature request related to a problem? Please describe.**

Running more than one instance of Firestore in isolated, disposable contexts is not possible, as the underlying connection makes it impossible for these clients to be cleared from memory.

An example would be to use [Node.js VM](https://nodejs.org/api/vm.html).

 **Describe the solution you'd like**

I'd like to see an API to close all open streams, so the client can be garbage collected.

 **Describe alternatives you've considered**

Hacking my way into `@grpc/grpc-js`, which exposes this API.

 **Additional context**

Here's an example of what it can cause :)

![Screen Shot 2019-09-30 at 21 39 01](https://user-images.githubusercontent.com/10390061/65910328-c173c700-e3ca-11e9-92eb-00a37c6c7303.png)

**Comment by schmidt-sebastian** [comment]
@bcoe / @BenWhitehead / @JustinBeckwith Thoughts? I am not opposed, especially since we now offer `terminate()` in the Mobile SDKs.

**Comment by JustinBeckwith** [comment]
No concerns from me, but I defer to @bcoe and @BenWhitehead

**Comment by BenWhitehead** [comment]
Sounds like a good thing to me, this also already exists in the Java server sdk via ([`close`](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/firestore/Firestore.html#close--)).

**Comment by bcoe** [comment]
@schmidt-sebastian, @BenWhitehead we should loop in @alexander-fenster to this conversation too 😄;  there was conversation about functionality along the lines of `client.unref()` which result in garbage collection as soon as there's no work on the wire.

**Comment by merlinnot** [comment]
Thanks for picking it up @schmidt-sebastian! We're also doing some work to make it actually work with `@grpc/grpc-js`: https://github.com/grpc/grpc-node/pull/1083.

**Comment by schmidt-sebastian** [comment]
We are currently stuck trying to get the new Typescript generator to play nicely with the repo, but hope to have this resolved early next week. If you are blocked by this, I am not opposed to applying the changes manually to `dev/v1/firestore_client.js`, but note that this will be temporary.

**Comment by merlinnot** [comment]
Hey, thank you for the update, much appreciated. One more week of oversized VMs won’t kill anyone, so take your time 🙂

**Comment by merlinnot** [comment]
@schmidt-sebastian Is it now unblocked with changes made in v3? 😃

**Comment by schmidt-sebastian** [comment]
Yes! @thebrianchen will take care of this.

**Comment by merlinnot** [comment]
@thebrianchen @schmidt-sebastian Thank you so much! Feels like I got my Christmas gifts early 😄 On a more scientific side, I reduced my socket usage by 96.875% and memory usage by 1.4 GBs per thread!
