### ISSUE TITLE
Streams do not provide the full Node.js stream API (Lack of Symbol.asyncIterator)

### ISSUE THREAD

**Issue by novemberborn** [googleapis/nodejs-firestore#789]
`Query#stream()` returns a stream that doesn't quite implement the Node.js stream API. For instance `[Symbol.asyncIterator]` is missing.

#### Environment details

  - Node.js version: 12.13.0
  - npm version: 6.12.1
  - `@google-cloud/firestore` version: 2.5.0

#### Steps to reproduce

  1. Create a query and call `stream()` on it
  2. On the resulting object, invoke [`[Symbol.asyncIterator]()`](https://nodejs.org/api/stream.html#stream_readable_symbol_asynciterator)
  3. This crashes, since that property is `undefined`

**Comment by bcoe** [comment]
@novemberborn :wave: small world :smile: thanks for the bug report :+1: have you found a reasonable workaround for the time being for the work you're doing?

**Comment by novemberborn** [comment]
Hey @bcoe! Yea, I've got some code to read the stream and provide an async iterator over it.
