### ISSUE TITLE
Snapshot listeners connection health

### ISSUE THREAD

**Issue by HristoDobchev** [googleapis/nodejs-firestore#791]
Hello,

In our project we are using the live update feature of the Firestore database. Our application is written in nodejs and is using the nodejs-firestore library (^2.3.0) to receive collection updates with the onSnapshot listener. However we notice that sometimes our listeners get disconnected over time. We are not sure why and currently can't reproduce the issue or debug it. One reason is that we are missing the logs from the server side and we see no logs in the client even if the debugging is turned on. 
My question is if there are any means to check if the connection to the listener is alive from the client side? Something like heartbeat (ping) so that we know when the listener is no longer updated? What is the best practice to tackle such issues?

Best regards,
Hristo

**Comment by schmidt-sebastian** [comment]
@HristoDobchev Thanks for posting this! Our listeners should re-connect when the connection drops and should otherwise invoke the `onSnapshot` callback with an error. If you don't see this error, then at least the SDK thinks that the connection is still up. Can you confirm that you are not getting and error and not getting document updates even though you should be? If that is the case, we might have to turn on GRPC level logging to look at your connection logs.

**Comment by HristoDobchev** [comment]
Hi,

Thanks for your answer. Let me clarify it a little. Does this mean that if there is no connection between the client and the Firestore server for a long period of time the client will invoke the onSnapshot callback on itself? I am asking about a situation where the server cannot contact the client listener (lost connection). When I tested it locally on my laptop and disconnected it from the network I was not able to see any errors on the client side. It seems normal if the server cannot reach the client. And my question was if there are healthchecks executed from the client (listener) side to the server to check whether the connection is still alive? Because if there aren't any active checks (pings) then the client might never know that the connection to the server was lost (this is what we observe).
Regarding the specific problem we face on GCP I can write an issue (bug). But here I just want to consult regarding the best practices to monitor such connection issues in general.

Thanks,
Hristo

**Comment by schmidt-sebastian** [comment]
The SDK will call onSnapshot with an error if it detects that the network is unavailable. Unfortunately, there are lots of reason why the client may not detect that the network is unavailable, and it looks like this is what is happening here. To help mitigate this and allow GRPC to discover dropped connections sooner, you can manually enable GRPC keepalives (similar to heartbeats, more about it here:https://github.com/grpc/grpc/blob/master/doc/keepalive.md). 

The setting for this is `grpc.keepalive_time_ms` and you can be passed to the Firestore constructor.

**Comment by HristoDobchev** [comment]
This was very helpful. I will try these params to see whether it makes any difference.
Thanks a lot for your explanation.

**Comment by schmidt-sebastian** [comment]
Perfect! Let us know if this helps. If you are still experiencing problems it likely makes sense to open an issue in https://github.com/grpc/grpc-node.
