### ISSUE TITLE
GRPC error - Stream refused by server 

### ISSUE THREAD

**Issue by rodrigoreis22** [googleapis/nodejs-firestore#793]
I'm using Firebase Firestore and noticed some occasional GRPC errors, this is the stack trace:
```
{ Error: Stream refused by server
    at Http2CallStream.call.on (/var/task/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/client.js:96:45)
    at Http2CallStream.emit (events.js:203:15)
    at Http2CallStream.EventEmitter.emit (domain.js:448:20)
    at process.nextTick (/var/task/node_modules/@google-cloud/firestore/node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 14,
  details: 'Stream refused by server',
  metadata: Metadata { internalRepr: Map {}, options: {} } }
```

Unfortunately after trying again the error is gone, a few of my customers reported it.. I'm unable to reproduce it.

  - OS: AWS Linux / AWS Lambda
  - Node.js version: 10.16.0
  - npm version: 6.9.0
  - `@google-cloud/firestore` version: 2.4.0

**Comment by schmidt-sebastian** [comment]
@rodrigoreis22 Thank you for reporting this! Unfortunately, to be able to look at this more deeply we would need to take a look at our backend logs. We can only do so if you file a Google Cloud Support Request, which you can include project specific information and timestamps. Please take a look here: https://cloud.google.com/support/

**Comment by dooleyb1** [comment]
Resolved personally by updating node modules FROM:

```
    "firebase-admin": "^8.7.0",
    "googleapis": "^42.0.0",
```

TO:

```
    "firebase-admin": "^9.1.1",
    "googleapis": "^59.0.0",
```

**Comment by devmanateam** [comment]
I got the same error when creating over 10k cloud tasks to several queues.
this is occasionally caused without reason, I cannot reproduce this error.
https://prnt.sc/vi6g2g
this is the error log.

**Comment by bcjordan** [comment]
I got the same error once at around 15 million Google Cloud Function requests which access Firestore in Datastore mode. Versions are:

```
"firebase-admin": "^10.0.2",
"firebase-functions": "^3.18.1"
"@google-cloud/datastore": "^6.6.2",
```
