### ISSUE TITLE
Timestamp.now() fails when using Firestore Emulator 

### ISSUE THREAD

**Issue by Brian-McBride** [googleapis/nodejs-firestore#801]
When using the emulator `gcloud beta emulators firestore start` or `firebase emulators:start --only firestore` creating a record using the Timestamp value fails. 

#### Environment details

  - OS: Testing on MacOS
  - Node.js version: v10.16.0
  - npm version:6.13.1
  - `@google-cloud/firestore` version: 2.6.0

#### Steps to reproduce

In my unit tests, I am setting up my database via:
```
import {initializeAdminApp} from '@firebase/testing';
const firebase = initializeAdminApp({ projectId: "my-project" });
 // @ts-ignore
 setDb(firebase.firestore());
```
Annoyingly, firebase testing doesn't match `@google-cloud/firestore` as if you don't use ts-ignore you get this error:
> Type 'Firestore' is missing the following properties from type 'Firestore': getAll, listCollections

In my actual function:
```
import { Timestamp } from '@google-cloud/firestore';
const id="someTestId";
const docRef = db.collection(COLLECTION_NAME).doc(id);
const data = {
    id,
    name: "my name",
    created: Timestamp.now(),
    modified: Timestamp.now(),
};
await docRef.set(data);
```

This will result in the error:
> FirebaseError: Function DocumentReference.set() called with invalid data. Unsupported field value: a custom object (found in field created)

This code works perfectly on the actual Cloud Firebase server. 
Now, I am using `@google-cloud/firestore` in production. I suppose I could switch over to `firebase-admin` and try there, but I would prefer to keep this in Cloud Firestore over Firebase Firestore. 

All I want to do is have rock solid unit testing. The mock libraries for Firestore are pretty poor and only maintained by the community. And this makes it impossible to use the emulator (if you need timestamps). 

Maybe there is a different way to connect to the emulator that supports this properly?

**Comment by Brian-McBride** [comment]
I found some resolution that is not documented anywhere.

First, don't use `@firebase/testing`. That lib doesn't work with `@google-cloud/firestore`.  Where is the testing library for @google-cloud? 

Connect to the local firestore by
```
import { Firestore } from '@google-cloud/firestore';
import { credentials } from '@grpc/grpc-js';
const db = new Firestore({
      projectId: 'some-project-id',
      port: 8080,
      servicePath: 'localhost',
      sslCreds: credentials.createInsecure(),
    }),
```

This seems to resolve the Timestamp.now(). You loose all the assertions from the testing library, but then again, you can always write your own.

The documentation should be changed to reflect this. Oh, DON'T use the `grcp` npm library. You have to use `@grpc/grpc-js` (which is what the Firestore library uses)

**Comment by ryanpbrewster** [comment]
Brian is correct, the `@firebase/testing` library is intended to help test client applications. `initializeAdminApp` actually constructs a normal client application that happens to have admin access (to bypass security rules).

As you've noticed, this does not work the same as the server SDKs. The upside is that the server SDKs should work "out of the box" if you set the `FIRESTORE_EMULATOR_HOST` environment variable (the emulator should print out a helpful message when you start it up). With the environment variable set you should be able use
```
import { Firestore } from '@google-cloud/firestore';
const db = new Firestore({ projectId: "my-test-project" });
```
and immediately start talking to the emulator.
