### ISSUE TITLE
Performance of listDocuments() is poor in large collections

### ISSUE THREAD

**Issue by leolabs** [googleapis/nodejs-firestore#825]
#### Environment details

  - OS: Irrelevant
  - Node.js version: 10
  - npm version: 6.10.2
  - `@google-cloud/firestore` version: 2.2.4

Using `listDocuments()` on a large collection (> 2000 entries) takes a lot longer than expected, especially compared to using `get()`. I've written a script to benchmark the two functions and the differences are extreme.

```
Getting available docs with listDocuments()... 28.82s, 2336 documents
Getting available docs with get()... 0.79s, 2336 documents
```

Where could this difference come from? I think that it'd be good to either fix this performance issue or to add a remark in the docs that `listDocuments()` can be slow in large collections.

**Comment by leolabs** [comment]
Here's the script I used to test the performance on a collection called `dfl`:

```typescript
import firebase from 'firebase-admin';

import options from '../firebase.config';
const admin = firebase.initializeApp(options);

(async () => {
  process.stdout.write('Getting available docs with listDocuments()... ');
  const start1 = Date.now();
  const docs1 = await admin
    .firestore()
    .collection('dfl')
    .listDocuments();
  const end1 = Date.now();
  process.stdout.write(
    `${((end1 - start1) / 1000).toFixed(2)}s, ${docs1.length} documents\n`,
  );

  process.stdout.write('Getting available docs with get()... ');
  const start2 = Date.now();
  const docs2 = await admin
    .firestore()
    .collection('dfl')
    .get();
  const end2 = Date.now();
  process.stdout.write(
    `${((end2 - start2) / 1000).toFixed(2)}s, ${docs2.docs.length} documents\n`,
  );
})();
```

**Comment by schmidt-sebastian** [comment]
@leolabs Thanks for bringing this to our attention. `.get()` and `.listDocuments()` are actually very different under the hood. `.get()` is a single request that streams all results back, while `.listDocuments()` invokes multiple requests and paginates the results automatically. Unfortunately,  the page size is by default just 20, which results in an enormous request overhead for large collections. 

The pending PR #838 sets the page size we use to the maximum allowed page size (300), which should speed things up quite considerably. 

Thank you for bringing this to our attention!
