### ISSUE TITLE
Improve documentation for UpdateData method

### ISSUE THREAD

**Issue by crwilcox** [googleapis/nodejs-firestore#831]
A customer filed feedback about our docs for UpdateData being sparse. We should improve these.

![image](https://user-images.githubusercontent.com/638797/71231228-e711bd80-22a1-11ea-806c-c556d92b2a62.png)
https://cloud.google.com/nodejs/docs/reference/firestore/1.3.x/global?authuser=0#UpdateData

Can be updated at https://github.com/googleapis/nodejs-firestore/blob/9ef582aa0508a3d02fb036f741c8c51e5ff4307c/dev/src/index.ts#L159

b/134887602

**Comment by schmidt-sebastian** [comment]
@jlara310 Juan, is this something you could look at? We use the same documentation here and on iOS, Web and Android.
