### ISSUE TITLE
Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution.

### ISSUE THREAD

**Issue by agersoncgps** [googleapis/nodejs-firestore#84]
According to the Firebase Cloud Firestore documentation for orderBy this should work:

`var facultyQuery = facultyRef.where("Middle School", "==", true).orderBy('bb_last_name', 'desc');`

I also tried this to make sure it wasn't the Map data causing issues:

`var facultyQuery = facultyRef.where("department", "==", "Core Teacher").orderBy('bb_last_name', 'desc');`

However it produces the error: 

`Error: Firestore: Operation was rejected because the system is not in a state required for the operation`s execution. (firestore/failed-precondition).`

Both of these simpler cases work just fine:
```
var facultyQuery = facultyRef.orderBy('bb_last_name', 'asc');
var facultyQuery = facultyRef.where("department", "==", "Core Teacher");
```

But when I combine the where and the orderBy, something I have done before with other Firestore collections, it fails. The documentation also states that "...queries that only use equality clauses don't need additional indexes" so I did not think I needed one.

<img width="413" alt="spkcb" src="https://user-images.githubusercontent.com/336441/33860505-35cd16ea-dea7-11e7-8bca-c2539af1a6e7.png">

**Comment by schmidt-sebastian** [comment]
This has been forwarded to our backend team.

**Comment by Cawfree** [comment]
I'm getting the same exception thrown when attempting to `orderBy` on equality-driven `where` conditions. I attempted to work around this problem by ensuring that the field I'm using to `orderBy` also has a manual index (desc) assigned to it, but this didn't seem to have any effect.

**Comment by schmidt-sebastian** [comment]
@agersoncgps In the error message that you are seeing, there should be a http link that allows you to add an index. Any query that you issue that uses more than one field needs a composite index, and you need to define these indices beforehand.  Please take a look here: https://firebase.google.com/docs/firestore/query-data/indexing

Queries that only involve one field will work with a the built-in indices.

**Comment by agerson** [comment]
The link appears if you run adb logcat if you are running on Android, but not in the Chrome error console, which is where I think it should be. Where would an iOS developer see it?

**Comment by schmidt-sebastian** [comment]
On Android and on iOS, these errors are returned as part of the error argument on the callback that you pass. In Objective-C, for example, this looks like:

` ``
[query getDocumentsWithCompletion:^(FIRQuerySnapshot *documentSet, NSError *error) {
    // error contains the link in its message
  }];
```

I looks like you need to turn on debug logging for these errors to show up on the Web.  They should instead result in a failed Promise and we should be returning these errors in the `err` argument of this failed Promise. This is currently not the case and I will file an issue to fix this.

Note that this repository is about the NodeJS server client for Firestore, which *does* return the error in the failed Promise. The GitHub repository for the Web client is https://github.com/firebase/firebase-js-sdk

**Comment by jeremyfrancis** [comment]
> The link appears if you run adb logcat if you are running on Android, but not in the Chrome error console, which is where I think it should be. Where would an iOS developer see it?

I just did console.log(JSON.stringify(error)) and clicked the link in Chrome. Added for me right away.
