### ISSUE TITLE
Trigger into firestore not called -> exception thrown

### ISSUE THREAD

**Issue by mpilalex** [googleapis/nodejs-firestore#85]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS:Google Cloud
  - Node.js version: 6.11
  - npm version:
  - @google-cloud/firestore version: 0.10

#### Steps to reproduce

  1. Create trigger to subcollection document create, change, Insert into firestore subcollection document with array value
  2. You will see 

TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined     at convertValue (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/convert.js:182:44)     at convertDocument (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/convert.js:226:22)     at Firestore.snapshot_ (/user_code/node_modules/firebase-admin/node_modules/@google-cloud/firestore/src/index.js:376:11)     at dataConstructor (/user_code/node_modules/firebase-functions/lib/providers/firestore.js:100:38)     at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:57:31)     at next (native)     at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71     at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)     at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:53:36)     at /var/tmp/worker/worker.js:695:26
--

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by schmidt-sebastian** [comment]
Thanks for reporting this. This is the same issue as https://github.com/firebase/firebase-functions/issues/149. I will move the discussion there.
