### ISSUE TITLE
new FieldPath (Value for argument "fieldPath" is not a valid Firestore document.)

### ISSUE THREAD

**Issue by larssn** [googleapis/nodejs-firestore#857]
#### Environment details

  - OS: MacOS
  - Node.js version: 8
  - npm version: 6.13.4
  - `@google-cloud/firestore` version: 3.3.0

#### Steps to reproduce

So we just redeployed a new update to Cloud Functions, and the following code (that used to work), now breaks.

```
const snapshot = await this.col
      .where(new FieldPath('integrations', this.integration.id), '==', '' + id)
      .get();
```

It breaks with:
`Error: Value for argument "fieldPath" is not a valid Firestore document. Couldn't serialize object of type "Path". Firestore doesn't support JavaScript objects with custom prototypes (i.e. objects that were created via the "new" operator).`

Not sure why that would be a problem all of a sudden. I assume `FieldPath` is still supported?

The import for FieldPath comes from:
`import { FieldPath } from '@google-cloud/firestore';`

Thanks!

**Comment by larssn** [comment]
Rolling back the two dependencies:
```
"@google-cloud/firestore": "^2.6.1",
"firebase-admin": "~8.6.1",
```
makes the problem go away.

**Comment by schmidt-sebastian** [comment]
You are likely using two conflicting versions of Firestore. If you are also directly importing `@google-cloud/firestore` please make sure that you are using the same version that is pulled in by `firebase-admin`. If the versions disagree, and you use one SDKs type with the other SDK (e.g. you pass @google-cloud/firestore v3 types to firebase-admin's Firestore at version 2.x) you will see the error as described.

**Comment by larssn** [comment]
@schmidt-sebastian Alright, but it doesn't seem like that is the issue.

If I do a `npm list @google-cloud/firestore`, I get:
```
├── @google-cloud/firestore@3.3.3 
└─┬ firebase-admin@8.9.0
  └── @google-cloud/firestore@3.3.3 
```
and thats it.

My package.json is the following:

```
"dependencies": {
    "@google-cloud/firestore": "^3.3.3",
    "@google-cloud/pubsub": "^1.2.0",
    "body-parser": "^1.19.0",
    "date-fns": "^2.9.0",
    "express": "^4.17.1",
    "firebase-admin": "^8.9.0",
    "firebase-functions": "^3.3.0",
    "got": "^9.6.0",
    "nanoid": "^2.1.9",
    "rxjs": "^6.5.4",
    "source-map-support": "^0.5.16"
  },
  "private": true,
  "devDependencies": {
    "@firebase/testing": "^0.16.5",
    "@types/chai": "^4.2.7",
    "@types/express": "^4.17.2",
    "@types/got": "^9.6.9",
    "@types/mocha": "^5.2.7",
    "@types/nanoid": "^2.1.0",
    "chai": "^4.2.0",
    "mocha": "^6.2.2",
    "mocha-webpack": "^2.0.0-beta.0",
    "rimraf": "^3.0.0",
    "ts-loader": "^6.2.1",
    "tslint": "^5.20.1",
    "typescript": "^3.7.4",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.10",
    "webpack-node-externals": "^1.7.2"
  }
```

But if no one else has seen this issue, I guess there's a problem in there. 😕

**Comment by schmidt-sebastian** [comment]
Can you see if you are still encountering this issue if you remove your manual dependency on `"@google-cloud/firestore"` (and do re-install of node_modules)?

**Comment by larssn** [comment]
@schmidt-sebastian This seems to have fixed itself. Only thing I've did was delete node_modules, but a few versions are newer as well.
