### ISSUE TITLE
Remove ambiguity around field validation message

### ISSUE THREAD

**Issue by skos-ninja** [googleapis/nodejs-firestore#858]
**Is your feature request related to a problem? Please describe.**
Sometimes the error message surrounding field validation failing is ambiguous to what the message actually means. An example of this is when a field is named "name" and as such the error message produces `(found in field name)`.
 **Describe the solution you'd like**
A simple solution to this is to wrap the field name in quotes to clearly identify it is the name of the field. As such the new error message would be `(found in field "name")`.

If this is an accepted solution to the issue I'm happy to submit a PR to correct this error message.

**Comment by schmidt-sebastian** [comment]
@skos-ninja Thanks for the bug report. That sounds like a good solution to me. We would be more than happy to accept your PR.
