### ISSUE TITLE
Firestore client retries a transaction when a document already exists

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-firestore#889]
This issue relates to the fix introduced for https://github.com/googleapis/nodejs-firestore/issues/827

#### Current behavior

When a document already exists, if one tries create a document using the same path with `create()` inside of a transaction, the transaction will keep retrying until it runs out of attempts.

#### Expected behavior

When a document is created with `create()` inside of a transaction, the transaction should intermediately terminate and throw the error.

#### Environment details

  - OS: Ubuntu 19.10
  - Node.js version: 10.18.0
  - npm version:6.12
  - `@google-cloud/firestore` version: 3.4.0

**Comment by schmidt-sebastian** [comment]
Thanks for reporting. We will try to address this shortly.

**Comment by schmidt-sebastian** [comment]
Note: This is next on my list, but I will be out on vacation until Feb 18.
