### ISSUE TITLE
Getting strange error regarding subchannels

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#890]
#### Environment details

  - OS: Mac OS 10.15 Beta (19A573a)
  - Node.js version: v12.10.0
  - npm version: 6.10.3
  - `@google-cloud/firestore` version: 3.3.4

#### Steps to reproduce

I am unsure how to reproduce as there doesn't seem to be much indication in my logs.
The problem I have is that I keep getting this error popping up:
```
(node:33) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Failed to start call on picked subchannel
    at Object.callErrorFromStatus (/api/node_modules/@grpc/grpc-js/src/call.ts:79:24)
    at Http2CallStream.<anonymous> (/api/node_modules/@grpc/grpc-js/src/client.ts:155:18)
    at Http2CallStream.emit (events.js:333:22)
    at Http2CallStream.EventEmitter.emit (domain.js:485:12)
    at /api/node_modules/@grpc/grpc-js/src/call-stream.ts:183:14
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by schmidt-sebastian** [comment]
Thanks for the report!

@murgatroid99 Do you have any leads here? This might be specific to our SDK as we delete and recreate clients, but it would be good to know if there was a way to avoid this issue.

**Comment by murgatroid99** [comment]
This error generally indicates that a connection dropped at almost the same time that we started a request on that connection. It's an UNAVAILABLE error to indicate that it can be retried, but I guess that doesn't help if the method can't be retried. It may be possible for grpc to handle that error without surfacing it to the user.

**Comment by schmidt-sebastian** [comment]
I moved this to grpc/grpc-node: https://github.com/grpc/grpc-node/issues/1250

Let's track all work there.
