### ISSUE TITLE
Documentation incorrectly states lastUpdateTime should be an ISO 8601 string

### ISSUE THREAD

**Issue by wspringer** [googleapis/nodejs-firestore#901]
#### Environment details

  - OS: MacOS
  - Node.js version: 8.16.2
  - npm version: 6.4.1
  - `@google-cloud/firestore` version: 3.3.3

#### Steps to reproduce

This is what the documentation says: 

![image](https://user-images.githubusercontent.com/100328/73460427-bfba1000-4378-11ea-90ae-bd59d10a9295.png)
https://googleapis.dev/nodejs/firestore/latest/global.html#Precondition

If I follow these steps, then I would do this:

1. Take the `updateTime` from a document reference.
2. Turn it into an ISO 8601 encoded string: `doc.updateTime.toDate().toISOString()`.
3. Pass that in as the value of `lastUpdateTime` in a precondition: `{ lastUpdateTime: doc.updateTime.toDate().toISOString()}`

Behold:

```
Error: Update() requires either a single JavaScript object or an alternating list of field/value pairs that can be followed by an optional precondition. Value for argument "preconditionOrValues" is not a valid precondition. "lastUpdateTime" is not a Firestore Timestamp.
    at WriteBatch.update (/srv/node_modules/@google-cloud/firestore/build/src/write-batch.js:358:23)
```

**Comment by schmidt-sebastian** [comment]
@thebrianchen Can you take a look at this?

**Comment by thebrianchen** [comment]
@wspringer Good catch! Thanks for flagging this out to us :)
