### ISSUE TITLE
Reexport Status from google-gax

### ISSUE THREAD

**Issue by leandro-manifesto** [googleapis/nodejs-firestore#902]
I'm trying to handle NOT_FOUND and ALREADY_EXISTS errors with the following code:

```typescript
...

async function updateExample() : Promise<boolean> {
  let col = db.col('examples');
  let doc = col.doc('id');

  try {
    await db.update({
      newData: 'new data',
    });

    return true;
  } catch (err) {
    switch (err.code) {
    case 'not-found':
      return false;
    default:
      throw err;
    }
  }
}
```

But, as it turns out, the error codes come straight from the `google-gax` package and they are defined as numbers in the `Status` enum, instead of strings.

I can solve this with a simple
```typescript
import { Status } from 'google-gax';

...

async function updateExample() : Promise<boolean> {
  let col = db.col('examples');
  let doc = col.doc('id');

  try {
    await db.update({
      newData: 'new data',
    });

    return true;
  } catch (err) {
    switch (err.code) {
    case Status.NOT_FOUND:
      return false;
    default:
      throw err;
    }
  }
}
```
but now I'm importing a transitive dependency that is not defined in my `package.json` and is clearly an implementation detail.

It would be very handy if this package could reexport that enum or provide a thin translation layer between errors.

**Comment by schmidt-sebastian** [comment]
Thanks for the request. We will get this done in an upcoming release.
