### ISSUE TITLE
Don't count FieldValue transformations against batch size limit

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#903]
Thanks for stopping by to let us know something could be better!
#### Environment details

  - OS: macOS Catalina 10.15.3 Beta (19D75a)
  - Node.js version: 13.7
  - npm version: 6.13.6
  - `@google-cloud/firestore` version: 3.4.1

#### Steps to reproduce
I have the following function:
```javascript
export const commitBatchUpdates = async (batchUpdates) => {
  const numUpdates = Object.keys(batchUpdates).length;
  if (!numUpdates) {
    return;
  }

  // The max number of updates per batch that firestore allows
  const BATCH_LIMIT = 500;

  // Construct an array of batches that can hold 500 updates each
  const batches = [...Array(Math.floor(numUpdates / BATCH_LIMIT + 1))].map(() => firestore.batch());

  console.log('NUM UPDATES:', numUpdates);

  // Add each batch update to the correct batch index
  Object.entries(batchUpdates).forEach(([docId, { payload, type }], i) => {
    const batchIndex = Math.floor(i / BATCH_LIMIT);
    const firestoreDoc = firestore.doc(docId);

    switch (type) {
      case 'update':
        batches[batchIndex].update(firestoreDoc, payload);
        break;
      case 'set':
        batches[batchIndex].set(firestoreDoc, payload);
        break;
      case 'delete':
        batches[batchIndex].delete(firestoreDoc);
        break;
      default:
        break;
    }
  });

  console.log('BATCH COUNT:', batches.length);
  for (let i = 0; i < batches.length; i++) {
    console.log('BATCH AT INDEX', i, 'has', batches[i]._ops.length, 'operations');
  }

  // Commit the batch updates
  try {
    await Promise.all(batches.map(async (batch) => batch.commit()));
  } catch (err) {
    console.log('it failed');
    console.log(err);
    throw err;
  }
};

```
I wrote this function to assist with making batch updates since there is a batch limit. The goal of the function is to take an input object of updates, convert it into an array of firestore batches, and commit each batch update. The input parameter `batchUpdates` is an object that has keys of document Ids (full paths with collection) and values of objects that contain a `type` that is either 'set', 'update', or 'delete' as well as a 'payload' that is a json payload to set/update a document with.
Examples of each type of value that could appear:
Set:
```javascript
{ type: 'set', payload: { a: 1}  }
```
Update:
```javascript
{ type: 'update', payload: { a: 1}  }
```
Delete:
```javascript
{ type: 'delete' }
```

You would expect that each batch would be deleted. However, this is what I see:
```
NUM UPDATES: 11466
BATCH COUNT: 23
BATCH AT INDEX 0 has 500 operations
BATCH AT INDEX 1 has 500 operations
BATCH AT INDEX 2 has 500 operations
BATCH AT INDEX 3 has 500 operations
BATCH AT INDEX 4 has 500 operations
BATCH AT INDEX 5 has 500 operations
BATCH AT INDEX 6 has 500 operations
BATCH AT INDEX 7 has 500 operations
BATCH AT INDEX 8 has 500 operations
BATCH AT INDEX 9 has 500 operations
BATCH AT INDEX 10 has 500 operations
BATCH AT INDEX 11 has 500 operations
BATCH AT INDEX 12 has 500 operations
BATCH AT INDEX 13 has 500 operations
BATCH AT INDEX 14 has 500 operations
BATCH AT INDEX 15 has 500 operations
BATCH AT INDEX 16 has 500 operations
BATCH AT INDEX 17 has 500 operations
BATCH AT INDEX 18 has 500 operations
BATCH AT INDEX 19 has 500 operations
BATCH AT INDEX 20 has 500 operations
BATCH AT INDEX 21 has 500 operations
BATCH AT INDEX 22 has 466 operations
it failed
Error: 3 INVALID_ARGUMENT: maximum 500 writes allowed per request
    at Object.callErrorFromStatus (/Users/myusername/myproj/node_modules/@grpc/grpc-js/src/call.ts:79:24)
    at Http2CallStream.<anonymous> (/Users/myusername/myproj/node_modules/@grpc/grpc-js/src/client.ts:155:18)
    at Http2CallStream.emit (events.js:333:22)
    at Http2CallStream.EventEmitter.emit (domain.js:485:12)
    at /Users/myusername/myproj/node_modules/@grpc/grpc-js/src/call-stream.ts:183:14
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 3,
  details: 'maximum 500 writes allowed per request',
  metadata: Metadata { internalRepr: Map(0) {}, options: {} }
}
```

It clearly shows that each batch has 500 operations or less, yet the update is erroring out.

**Comment by jakeleventhal** [comment]
I ran a binary search on different values for `BATCH_LIMIT` and found that if I set it to 421, that works. 422 or higher and I get the `maximum 500 writes allowed per request` error.

**Comment by schmidt-sebastian** [comment]
@jakeleventhal Thanks for reporting this. 

Our Batch Limit depends on how we serialize the writes - a single API call may result in multiple writes if FieldValue transforms are used (Increments, ArrayUnions, ArrayRemoves and ServerTimestamps). We know that this is not ideal and are currently revamping our protocol to remove this restriction. This should be addressed sometime in the first half of 2020.

In the meantime, refer to these docs for further information: https://firebase.google.com/docs/firestore/manage-data/transactions#batched-writes

**Comment by schmidt-sebastian** [comment]
Keeping this open until our protocol is revamp to remove this limitation.

**Comment by Elyx0** [comment]
So as of now we should set the server timestamp ourselves? Is there a FieldValue transforms guide?

**Comment by schmidt-sebastian** [comment]
You can use the existing FieldValue API as is. The implications pointed out by @jakeleventhal only apply if you are hitting the batch size limit in a WriteBatch, in which case you should reduce the number of documents you are adding to your batches.

**Comment by schmidt-sebastian** [comment]
The v4.0.0 release using a different mechanism for FieldValue transformations. All document writes now map to a single backend operation.

**Comment by jakeleventhal** [comment]
@schmidt-sebastian does this include the removal of the 500 ops per batch restriction as well?

**Comment by thebrianchen** [comment]
@jakeleventhal The 500 op limit is still in place for `WriteBatch`. Once BulkWriter is released, you will be able to write without needing to manually batch writes.

**Comment by jakeleventhal** [comment]
@thebrianchen @schmidt-sebastian is there a way to do a large (>500) atomic write?

**Comment by schmidt-sebastian** [comment]
No, there is not.

**Comment by jakeleventhal** [comment]
@schmidt-sebastian is there work tracking this?

**Comment by schmidt-sebastian** [comment]
I don't see any issues tracking this. You can search open issues at https://issuetracker.google.com/savedsearches/5337669?q=componentid:530136%2B%20status:open

You can also create a new issue. We do take this into account as we prioritize future work items.

**Comment by jakeleventhal** [comment]
@schmidt-sebastian @thebrianchen why would I want to use the bulk writer as opposed to the custom batch update tool that I provided?

**Comment by jakeleventhal** [comment]
@schmidt-sebastian @thebrianchen @Elyx0 I made this issue tracking it. Please vote for it!

**Comment by jakeleventhal** [comment]
@schmidt-sebastian @thebrianchen @Elyx0 I made this issue tracking it. Please give it a star!
https://issuetracker.google.com/issues/180813634
