### ISSUE TITLE
Support init Firestore instance with POJO

### ISSUE THREAD

**Issue by amio** [googleapis/nodejs-firestore#91]
Currently we need to init Firestore with a file:
```javascript
const firestore = new Firestore({
  projectId: 'YOUR_PROJECT_ID',
  keyFilename: '/path/to/keyfile.json',
});
```

Could we support a js object too?
```javascript
const key = require('/path/to/keyfile.json')
const firestore = new Firestore({
  projectId: 'YOUR_PROJECT_ID',
  key: key,
});
```

So I can load/create this object in runtime (from env or some thing else)

**Comment by amio** [comment]
I have found a way(according [this](https://github.com/firebase/firebase-admin-node/blob/5f10306a675a1d1875f7f45eee654df8aa6bbdf4/src/firestore/firestore.ts#L90-L96)):
```javascript
const { private_key, client_email, project_id } = require('path/to/keyfile.json')

const firebaseConfig = {
  credentials: {
    private_key,
    client_email
  },
  projectId: project_id
}

const firestore = new Firestore(firebaseConfig)
```

Maybe it would be added to README.md? Or is it an unstable internal api for now?

**Comment by stephenplusplus** [comment]
All of the `@google-cloud/*` APIs allow specifying `options.credentials`, so no need to worry about it being an internal API. Our docs are going through a bit of an overhaul, transitioning from a custom GitHub hosted site to cloud.google.com. The format we used for the former isn't fully compatible with the latter.

I'm going to use [this issue](https://github.com/GoogleCloudPlatform/google-cloud-node/issues/2783) to track the changes to the documentation, to clear these things up.

Sorry for the confusion.

**Comment by amio** [comment]
Thanks for clarifying 👍

**Comment by amio** [comment]
Thanks for clarifying!
