### ISSUE TITLE
Create and authorize a service account to run FirestoreAdminClient.exportDocuments.

### ISSUE THREAD

**Issue by shaunluttin** [googleapis/nodejs-firestore#911]
This is how we are authenticating and calling the FirestoreAdminClient.
```
import fs from 'fs';
import firebaseAdmin from 'firebase-admin';

const pathToServiceAccountKeyFile = '/path/to/service/account/key.json';

const serviceAccountKeyJSON = fs
  .readFileSync(pathToServiceAccountKeyFile)
  .toString();

const serviceAccountKeyObject = JSON.parse(serviceAccountKeyJSON);

firebaseAdmin.initializeApp({
  credential: firebaseAdmin.credential.cert(serviceAccountKeyObject)
});

const adminClient = new firebaseAdmin.firestore.v1.FirestoreAdminClient({
  keyFilename: pathToServiceAccountKeyFile
});

adminClient
  .exportDocuments({
    name: adminClient.databasePath('firebase-test-project-id', '(default)'),
    outputUriPrefix: 'gs://firebase-test-project-backups'
  })
  .then(response => console.log(response));
```
This is the response the client receives: 
```
7 PERMISSION_DENIED: The caller does not have permission

  at Object.callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:30:26)
  at Http2CallStream.call.on (node_modules/@grpc/grpc-js/build/src/client.js:96:33)
  at process.nextTick (node_modules/@grpc/grpc-js/build/src/call-stream.js:75:22)
```
This is where we generated the service account key.
![image](https://user-images.githubusercontent.com/2066637/73790059-b48a2a00-4754-11ea-9e21-8db2b7ec79ad.png)

How, if at all, can we authorize a service account to call `FirestoreAdminClient.exportDocuments`?

**Comment by schmidt-sebastian** [comment]
@shaunluttin Thanks for reporting.

If you are using a Firebase Admin Credential that you created via the Firebase Console, you will need to grant additional permissions. Please take a look at the required permissions:

https://firebase.google.com/docs/firestore/manage-data/export-import

I will close this issue for now, but if that doesn't work for you, please comment and we can re-open.
