### ISSUE TITLE
Closing an onSnapshot listener gives UnhandledPromiseRejectionWarnings when followed by client.terminate()

### ISSUE THREAD

**Issue by vdvleon** [googleapis/nodejs-firestore#913]
#### Environment details

  - OS: macOS Catalina (`10.15.1`)
  - Node.js version: `10.16.3`
  - npm version: `6.9.0`
  - `@google-cloud/firestore` version: `^3.4.1`

#### Problem

When closing an onSnapshot listener, followed by the termination of the firestore client, an 'UnhandledPromiseRejectionWarning' is shown:

```
onSnapshot { path: 'collection/doc-1', exists: false }
onSnapshot { path: 'collection/doc-1', exists: true }
(node:41140) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: No active request
    at ClientPool.release (/Users/vdvleon/Downloads/reproduction/node_modules/@google-cloud/firestore/build/src/pool.js:95:9)
    at op.catch.then (/Users/vdvleon/Downloads/reproduction/node_modules/@google-cloud/firestore/build/src/pool.js:162:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:41140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:41140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce

1. Open an onSnapshot listener (on either documents or queries) and store the 'close' callback.
   `const close = documentReference.onSnapshot(...);`
2. Call the 'close' callback.
   `close();`
3. Terminate the firestore client.
    `firestore.terminate();`

_Relevant code:_
```typescript
const documentReference = firestore.collection("collection").doc("doc-1");

const close = documentReference.onSnapshot((snapshot: DocumentSnapshot) => {
  console.log("onSnapshot", {
    path: snapshot.ref.path,
    exists: snapshot.exists
  });
});

const run = async (): Promise<void> => {
  await clearFirestoreData();

  await documentReference.set({});

  close();

  await firestore.terminate();
};
```

_The full reproduction can be found here:_
[reproduction.zip](https://github.com/googleapis/nodejs-firestore/files/4158731/reproduction.zip)

**To run the code:**

```bash
cd reproduction
npm install
npx ts-node index.ts
```

**Comment by schmidt-sebastian** [comment]
@vdvleon Thanks for reporting this!

The problem is that `firestore.terminate()` removes the internal references of internal clients. This is done to free up resources.  While `close()` is expressed as a synchronous call, it actually kicks of asynchronous operations that can finish after `terminate()` runs. This is indeed a problem in our client.

Possible solutions are:
- We keep a reference to all running operations and essentially "kill" them when terminate is invoked (by throwing an error/rejecting a Promise).
- We allow existing operations to continue to run after `terminate()` is invoked and only garbage collect when all operation counts go to zero.

**Comment by vdvleon** [comment]
Is there an ETA for the bug fix for this problem?

**Comment by thebrianchen** [comment]
@vdvleon We can't comment on a specific release date, but it's in our sprint right now, and we hope to have it out soon in an upcoming release. Sorry for the trouble!

**Comment by vdvleon** [comment]
Thanks for the fix, it seems to have solved the problem 👍
