### ISSUE TITLE
Cloud function 'connection error' when performing a Transaction.get after a Transaction.set

### ISSUE THREAD

**Issue by Poliziano** [googleapis/nodejs-firestore#923]
#### Environment details

  - OS: Cloud Function
  - Node.js version: 8.15
  - npm version: 6.4.1
  - `@google-cloud/firestore` version: 2.6.1
  - `firebase-admin` version: 8.6.1
  - `firebase-functions` version: 3.1.0

#### Report

This is not a bug as such, but something which could help other developers. As the firestore documentation explains, all reads must be done before any writes in a transaction. If you don't adhere to these rules on app engine then you get an exception about it. However, if this happens on cloud functions you get a nebulous 'connection error' written to the logs and nothing else - no exception or helpful log. I spent many hours debugging code until I found someone on my team erroneously performed a get after a set. Fixing that mistake fixed this issue, but I would have greatly appreciated an exception being thrown, or some helpful message logged to the console. What could have been a couple minutes fix turned into a day of debugging. 

Thank you.

**Comment by schmidt-sebastian** [comment]
@Poliziano Thanks for reporting this. We already have code to validate this exact edge case - see https://github.com/googleapis/nodejs-firestore/blob/7562033876dc006e77d00b576b2541a7dfd30c66/dev/src/transaction.ts#L126

Do you mind sharing your code snippet and debug logs ([setLogFunction](https://googleapis.dev/nodejs/firestore/latest/global.html#setLogFunction))? This will help us determine why you are not seeing this exception.

**Comment by schmidt-sebastian** [comment]
Closing this after a week of inactivity. Please ping us if you would like us to re-open.

**Comment by Poliziano** [comment]
Sorry for the hugely late response. I believe I discovered why we were not about to catch the exception - the transaction in question was executed inside a stream event callback, and our try-catch logic was wrapping this callback, instead of being inside it. Reworking our error handling logic has resolved this issue.
