### ISSUE TITLE
Add ability to have a test database for the purposes of testing

### ISSUE THREAD

**Issue by jakeleventhal** [googleapis/nodejs-firestore#927]
This is a pretty open ended request. I am looking for a way to create integration tests for my application using firestore in some way or another. It would be nice if there were some sort of test environment that could be used of sorts to mock the functionality of firestore with limited capacity for the sake of running tests.

i.e. I could run a test such as:
```javascript
it('should update the database', () => {
  await firestore.doc('Users/user1').update({name: getMyName()});

  const user = await firestore.doc('Users/user1').get();
  expect(user.data().name).toEqual('jake');
});
```

I understand this may be a bit large in scope so if this is an impossibility, what is the recommended way to run integration tests that rely on firestore? Are there best practices? I've thought about creating a very complex system of mocks, though this may be a bit too much overhead if a more elegant system exits.

**Comment by mad-it** [comment]
You can use the Firestore emulator. Here is a small guide: https://firebase.google.com/docs/emulator-suite/install_and_configure

Extra info can be found in this repo: https://github.com/firebase/firebase-tools

**Comment by thebrianchen** [comment]
The Firestore emulator is the recommended way to quickly test against Firestore. Closing this issue, but feel free to reopen if you have any other questions!

**Comment by jakeleventhal** [comment]
@mad-it @thebrianchen Hi, it appears that there are several different ways to do this:
* `@firebase/testing`
* `firebase-tools`
* https://cloud.google.com/sdk/gcloud/reference/beta/emulators/firestore/

Which of these is the best? And for whichever is, are there any examples? I can't seem to find anything that will suit the needs of my original post. I need to be able to spin up a test emulator where data can be added, removed, and modified in the database at will with unit tests along the way.

If it helps, I run my build through Google Cloud Build.
