### ISSUE TITLE
Batches set and FieldValues Timestamp throws error

### ISSUE THREAD

**Issue by Elyx0** [googleapis/nodejs-firestore#928]
#### Environment details 

  - OS: Mac Osx 18.7.0 Darwin Kernel
  - Node.js version: v10.15.0
  - npm version: 6.4.1
  - `@google-cloud/firestore` version: @google-cloud/firestore@3.5.0

```
{ FirebaseError: Function WriteBatch.set() called with invalid data. Unsupported field value: a custom object (found in field insertedAt)
          at new FirestoreError (/cloud-functions/functions/node_modules/@firebase/firestore/src/util/error.ts:166:5)
          at ParseContext.Object.<anonymous>.ParseContext.createError (/cloud-functions/functions/node_modules/@firebase/firestore/src/api/user_data_converter.ts:249:12)
```

#### Steps to reproduce

  1.
```js
item = {};
item.insertedAt = admin.firestore.FieldValue.serverTimestamp()
batch.set(itemRef,item);
```

Expected: No error.

I indeed see it as `insertedAt: ServerTimestampTransform {},`

I found https://stackoverflow.com/questions/51846914/add-timestamp-in-firestore-documents 
Searched for open and closed issues with batch/timestamp https://github.com/firebase/firebase-admin-node/issues?utf8=%E2%9C%93&q=batch

This not exactly like https://github.com/googleapis/nodejs-firestore/issues/801
But more like https://github.com/FirebaseExtended/flutterfire/issues/1322

**Comment by laljikanjareeya** [comment]
Hey @Elyx0 I am not able to re-produce the issue with the given version.
It's working fine with `@google-cloud/firestore` and `firebase-admin`.

Please refer below working demo:

```ts
import { Firestore, FieldValue } from '@google-cloud/firestore';
//import * as admin from "firebase-admin";
async function main() {
    const firestore = new Firestore();
    let batch = firestore.batch();
    let item: any = {};
    let itemRef= firestore.doc('Department/eUyydcVmEuLMZybMSzGq');
    //using @google-cloud/firestore
    item.insertedAt = FieldValue.serverTimestamp();
    //using firebase-admin
    //item.insertedAt = admin.firestore.FieldValue.serverTimestamp();
    batch.set(itemRef, item);
    await batch.commit();
}
```

**Comment by Elyx0** [comment]
Thanks for the reply. 

I'll try getting the `Fieldvalue` from '@google-cloud/firestore' to see if this fixes it.
Are you able to reproduce with taking `admin` from `@firebase/testing` ? 
(    
    "@firebase/testing": "^0.16.8"
    "firebase": "^7.8.1",
    "firebase-admin": "^8.9.2"
)
I'm 1 minor version behind on each than the latest

```js
import * as adminTesting from from '@firebase/testing';
adminTesting.initializeAdminApp({ projectId, databaseName });
main();
```

**Comment by schmidt-sebastian** [comment]
@Elyx0 This root cause of this issue is very likely a versioning conflict. If you have dependencies on both `firebase-admin` and `@google-cloud/firestore` and want to use types interchangeably, you need to ensure that `@google-cloud/firestore` and `firebase-admin`'s `@google-cloud/firestore` are the exact same version.

If this doesn't help, please let us know and we can investigate further.

**Comment by mstmustisnt** [comment]
In my case this happened because I messed up with `Timestamp` when writing e2e tests (imported it from `firebase-admin` whereas `firestore` itself was imported from `firebase-testing`). Make sure you import Timestamp from a proper place.
