### ISSUE TITLE
Collection Group query just hangs and doesn't return anything including error

### ISSUE THREAD

**Issue by sunnixx** [googleapis/nodejs-firestore#929]
#### Environment details

  - OS: Mac OS - Sierra
  - Node.js version: 12
  - npm version: 6.13.4
  - `@google-cloud/firestore` version: 7.12.1

#### Steps to reproduce

  1. Calling our collection of `alerts` with the collection group query. 
Following is the code snippet: 

```
try {
    console.log("before getting into group alerts")
    const doc = await db
    .collectionGroup("alerts")
    .where("sent", "==", false)
    .where("type","==","risk")
    // .offset(offset)
    .limit(1)
    .orderBy("createdAt","desc")
    .get();
  
    if(!doc.empty) {
      doc.forEach(alert => {
        collectiveAlerts.push(alert.data());
      });
      // offset += 10; 
      // sendEmailsToUsers()
    }
  
    console.log(collectiveAlerts);
    
    console.log("after getting into group alerts");
    
  } catch (error) {
    console.log('error: ', error);
  }
```
The indexes are created, but still when we hit the query nothing gets returned from the query such as any error or response.

**Comment by schmidt-sebastian** [comment]
@sunnixx Thanks for reporting. 

To investigate this, can you share debug logs from your client? You can enable debug logging by calling [setLogFunction](https://googleapis.dev/nodejs/firestore/latest/global.html#setLogFunction).

**Comment by sunnixx** [comment]
The above function is being used in a `pub/sub` function that is called every `2 minutes` 
So this being handled from the cloud function itself. Would `setLogFunction` still work ?

**Comment by sunnixx** [comment]
For proper reference I am sharing the complete code snippet file. 

```
/* eslint-disable promise/no-nesting */

/**
 * @description
 * This module will send out emails to different users who have alerts not sent out yet
 * @algorithm
 * 1 - Get all alerts where sent = false
 * 2 - Send out those alerts via the email module.
 */
const functions = require("firebase-functions");
const { db } = require("../helpers/firestore");
const { Email } = require("../EmailModule");

const { groupBy } = require("../helpers/groupBy");

exports.sendEmailsToUsers = functions.pubsub
  .schedule("every 2 minutes")
  .onRun(context => {
    return sendEmailsToUsers(context);
  });

exports.testSendEmailsToUsers = functions.https.onRequest(async (req, res) => {
  try {
    await sendEmailsToUsers("hello");
    res.sendStatus(200);
  } catch (error) {
    console.log(error);
    res.sendStatus(500);
  }
});

const offset = 0;
const collectiveAlerts = [];

async function sendEmailsToUsers(context) {
  let ref;
  try {
    let usersData = await db.collection("Users").get();

    if (!usersData.empty) {
      usersData.forEach(eachUser => {
        ref = eachUser.ref;
        collectiveAlerts.push(eachUser.data());
      });

      console.log("REF ===>", ref);
    } else {
      console.log("alerts didn't occur");
    }

    console.log("collectiveAlerts: ", collectiveAlerts);

    collectiveAlerts.map(async _user => {
      let alerts = await ref.collection("alerts").get();
      if (!alerts.empty) {
        console.log(alerts);
      } else {
        console.log("Alerts empty");
      }
    });
  } catch (error) {
    console.log("error: ", error);
  }
}

```

**Comment by sunnixx** [comment]
As you can see I am using multiple logs but the code gets stuck on the query call at
`db.collectionGroup . . . ` and never gets resolved. Don't see any `logs` after that line. It only works when I do `limit(1)` else it won't even give me any response on `limit(2)` either. 
I am using the `blaze` plan so I don't think I am hitting any limits either.

**Comment by sunnixx** [comment]
After further digging tracing the flow in reverse we came to `reference.js` in `node_modules` of `google/firestore` sdk. We found that there were three events 
`error`
`data`
`end` 

When the `on("data")` event was being called it would first fetch all the docs and then call `on('end')` event which would then return the `docs` to the callback function of `get()` in our original file. But the `end` event wasn't being called due to which our query got stuck in an infinite loop and eventually the function timed out. 

So we did some debugging on it and saw that on our local if we changed our version of node to `8.16` it worked fine but not on above that. 
So we changed our cloud function version to `10(beta)` and suddenly we started getting our data from firestore. 
We're still doing some more tests and see if this is the actual solution to this or not.

**Comment by sunnixx** [comment]
```
_get(transactionId) {
        const docs = [];
        return new Promise((resolve, reject) => {
            let readTime;
            this._stream(transactionId)
                .on('error', err => {
                reject(err);
            })
                .on('data', result => {
                // console.log("this runs")
                readTime = result.readTime;
                if (result.document) {
                    docs.push(result.document);
                }
            })
                .on('end', () => {
                    console.log("END !!!!")
                resolve(new QuerySnapshot(this, readTime, docs.length, () => docs, () => {
                    const changes = [];
                    for (let i = 0; i < docs.length; ++i) {
                        changes.push(new document_change_1.DocumentChange('added', docs[i], -1, i));
                    }
                    return changes;
                }));
            });

            docs.forEach(item => {
                console.log(item.data());
            })
        });
    }
```

The code gets stuck on `on("data . . . )` line of this code snippet found in `reference.js` file.

**Comment by MohammedMaaz** [comment]
I am also facing the same issue, @schmidt-sebastian please look into this.

**Comment by sunnixx** [comment]
Okay so I can confirm this that after changing the node version of cloud functions to `10` fixes the problem. But I still am not sure why it wasn't working on 8 ?

**Comment by schmidt-sebastian** [comment]
`setLogFunction(console.log)` will add Firestore's debug logs to Cloud/Firebase console (similar to what your `console.log` statements do).

I would like to point out thought that If this is indeed a Node runtime specific bug, then we may not be able to fix it. We are one of the first consumers of the HTTP/2 Stack available in Node 8 and beyond, and I wouldn't be surprised if there are version specific issues (there certainly have been before). As of last Decemeber, Node 8 is no longer officially supported by the Node runtime team and thus getting this fixed in the Node 8 release train is no longer possible.

**Comment by sunnixx** [comment]
I can understand. I think we can add a check to handle the `on("data")` to version specific so this may be handled in the later versions

**Comment by Portur** [comment]
Just got this issue on node12. Upgraded to node14 and seems to work

**Comment by qadirsuh** [comment]
@Portur I was using win 10 and node 11, this issue was occuring hanging issue.
I moved to node 14 and tried again it worked like charm. thank you for sharing. 
I wasted almost 4 hours on this. nothing worked.

**Comment by samatcolumn** [comment]
Is it possible that this is still an issue with collection group queries in Cloud Functions on Node 10?
