### ISSUE TITLE
FirestoreDataConverter.fromFirestore should use DocumentSnapshot instead of DocumentData

### ISSUE THREAD

**Issue by Pencl** [googleapis/nodejs-firestore#938]
**Is your feature request related to a problem? Please describe.**

The implementation and therefore the interface interface of the `FirestoreDataConverter` between the nodejs client and the web-js client diverges:

Whereas the web client uses the `DocumentSnapshot` as the input value of the `fromFirestore` function, the nodejs client only uses the `DocumentData` representation of the document:

[nodejs - client](https://github.com/googleapis/nodejs-firestore/blob/master/types/firestore.d.ts#L83):
```typescript
interface FirestoreDataConverter<T> {
  toFirestore(modelObject: T): DocumentData;
  fromFirestore(data: DocumentData): T;
}
```

[web - client](https://github.com/firebase/firebase-js-sdk/blob/eb614f0e7bcfee5b4bc1d390f894bea3d8f3867b/packages/firestore/src/api/database.ts#L1384):
```typescript
interface FirestoreDataConverter<T> {
  toFirestore(modelObject: T): DocumentData;
  fromFirestore(snapshot: QueryDocumentSnapshot, options: SnapshotOptions): T;
}
```

The problem with the current implementation is that it is impossible to access document metadata like the documents id.

 **Describe the solution you'd like**
My preferred solution would be to modify the behavior so that the `DocumentSnapshot` itself is handed to the `fromFirebase` method of the converter:

```typescript
interface FirestoreDataConverter<T> {
  toFirestore(modelObject: T): DocumentData;
  fromFirestore(snapshot: DocumentSnapshot<T>): T;
}
```

⚠️ This would result in a breaking change.

 **Describe alternatives you've considered**
Alternatives cloud be:
* Passing the metadata as a separate parameter to the converter. (would result in a non-breaking change). 😑
* Leaving everything as is. 😞 

 **Additional context**
I would be willing to do the implementation myself providing that there is a positive feedback on the change itself.

**Comment by thebrianchen** [comment]
@Pencl Thanks for writing in with your request! 

We originally replaced `DocumentSnapshot` with `DocumentData` in the node SDK since there were no `SnapshotOptions`, but I realize now that having access to the metadata would be useful. We'll look into adding `DocumentSnapshot` support in our next major version bump soon, which should happen when we drop node8 support.

**Comment by Pencl** [comment]
@thebrianchen Thanks for your quick reply.

> We'll look into adding DocumentSnapshot support in our next major version bump soon, which should happen when we drop node8 support.

Sounds great. 👍 

Please let me know if there is anything I can do on this topic.

**Comment by schmidt-sebastian** [comment]
This is part of the v4.0.0 release which will go out momentarily.

**Comment by goleary** [comment]
Cross posting this here: https://github.com/firebase/firebase-admin-node/issues/997

because my understanding is that after v4.0.0 I should be able to use the same converter either through `firebase-admin` or the js sdk which is currently not the case.

**Comment by thebrianchen** [comment]
@goleary This update only changed the signature of `fromFirestore()` in the admin SDK to use `QueryDocumentSnapshot` rather than `DocumentData` so that developers could access the snapshot metadata from the `fromFirestore()` method. Due to the absence of `SnapshotOptions` on the admin SDK, the signatures will remain different, and thus the converters are not compatible.

**Comment by goleary** [comment]
I see. That is rather disappointing. So you're saying I should define and maintain separate converters for use on the client and server?  That is quite counter-intuitive.  Is there somewhere I can register a vote for defining a common type that could be used in both places?

**Comment by taylorhoward92** [comment]
I was waiting for this feature as well so I only had to define my coverter once. This a simplified example of how I do it. If you use `SnapshotOptions` then this won't work and it does mean importing both the JS SDK and the Node SDK. Works for my use case though.

```ts
import firebaseClient from 'firebase/app';
import firebaseAdmin from 'firebase-admin';

interface User {
  name: string
}

const firestoreDataConverter = {
  toFirestore: (user: User): firebaseClient.firestore.DocumentData => {
    return user;
  },
  fromFirestore: (snapshot: firebaseAdmin.firestore.QueryDocumentSnapshot | firebaseClient.firestore.QueryDocumentSnapshot): User => {
    return snapshot.data();
  },
};
```

**Comment by goleary** [comment]
That seems like a good option @taylorhoward92 I'll try that out.
