### ISSUE TITLE
Support streaming for onSnapshot

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-firestore#955]
This is a feature request for supporting streaming for onSnapshot.

The use case:
I have a collection of 10000 documents. I would like to subscribe to changes to these 10000 documents. 
When starting my subscription I do not want the app to block until the first snapshot of 10000 documents is received. I want to be able to start processing data as they are streamed to the application.

Hope this is clear. If not please let me know.

**Comment by schmidt-sebastian** [comment]
@mad-it Thanks for the feature request!

Unfortunately, this will be pretty hard for us to implement. The backend doesn't provide any guarantees on the data they send to us until we get a confirmation that we have reached a consistent state. That means that the backend can send us outdated documents, before updating these to the most current state. While some of our users might not mind this behavior, this is likely something that we cannot offer in a mainline API.

The only suggestion I have at the moment is the `Query.stream()` API, but there is no migration path from Query streaming to live snapshots.
