### ISSUE TITLE
Emulator: Transaction rollback fails with Code UNKNOWN

### ISSUE THREAD

**Issue by merlinnot** [googleapis/nodejs-firestore#960]
#### Environment details

  - OS: Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020
  - Node.js version: v10.18.0
  - npm version: v6.13.7
  - `@google-cloud/firestore` version: v3.6.0

#### Steps to reproduce

```ts
import { Firestore } from '@google-cloud/firestore';
import { credentials } from '@grpc/grpc-js';

const firestore = new Firestore({
  port: 8080,
  projectId: 'test',
  servicePath: 'localhost',
  sslCreds: credentials.createInsecure(),
});

const documentReference = firestore.collection('collection').doc();

const run = async () => {
  await documentReference.set({});

  await firestore.runTransaction(async (transaction) => {
     transaction.create(documentReference, {});
  })
};

run().catch(x => console.error(x.message));
```

You can see `2 UNKNOWN` being printed, where a correct error (it worked in a previous version of the library) is `6 ALREADY_EXISTS`.

**Comment by schmidt-sebastian** [comment]
@merlinnot I just took a look at this. The problem is that the "rollback" fails with UNKNOWN in the emulator, which then replaces the existing ALREADY_EXIST error. Prior to 3.6, we did not send a rollback if the commit failed and had access previous error.

```
Firestore (3.6.0) 2020-03-09T21:58:12.998Z ZfXa3 [Firestore.request]: Sending request: {"database":"projects/test/databases/(default)","writes":[{"update":{"name":"projects/test/databases/(default)/documents/collection/3P5hIPvE1nNFKH0r4VJn","fields":{}},"currentDocument":{"exists":false}}],"transaction":{"type":"Buffer","data":[17,6,0,0,0,0,0,0,0]}}
Firestore (3.6.0) 2020-03-09T21:58:13.005Z ZfXa3 [Firestore.request]: Received error: { Error: 6 ALREADY_EXISTS: entity already exists: app: "dev~test"
path <
  Element {
    type: "collection"
    name: "3P5hIPvE1nNFKH0r4VJn"
  }
>

    at Object.callErrorFromStatus (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 6,
  details:
   'entity already exists: app: "dev~test"\npath <\n  Element {\n    type: "collection"\n    name: "3P5hIPvE1nNFKH0r4VJn"\n  }\n>\n',
  metadata:
   Metadata { internalRepr: Map { 'content-type' => [Array] }, options: {} } }
Firestore (3.6.0) 2020-03-09T21:58:13.006Z ZfXa3 [Firestore.runTransaction]: Rolling back transaction after callback error: { Error: 6 ALREADY_EXISTS: entity already exists: app: "dev~test"
path <
  Element {
    type: "collection"
    name: "3P5hIPvE1nNFKH0r4VJn"
  }
>

    at Object.callErrorFromStatus (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 6,
  details:
   'entity already exists: app: "dev~test"\npath <\n  Element {\n    type: "collection"\n    name: "3P5hIPvE1nNFKH0r4VJn"\n  }\n>\n',
  metadata:
   Metadata { internalRepr: Map { 'content-type' => [Array] }, options: {} } }
Firestore (3.6.0) 2020-03-09T21:58:13.006Z ZfXa3 [ClientPool.acquire]: Re-using existing client with 100 remaining operations
Firestore (3.6.0) 2020-03-09T21:58:13.006Z ZfXa3 [Firestore.request]: Sending request: {"database":"projects/test/databases/(default)","transaction":{"type":"Buffer","data":[17,6,0,0,0,0,0,0,0]}}
Firestore (3.6.0) 2020-03-09T21:58:13.009Z ZfXa3 [Firestore.request]: Received error: { Error: 2 UNKNOWN: 
    at Object.callErrorFromStatus (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at Http2CallStream.emit (events.js:187:15)
    at process.nextTick (/Users/mrschmidt/Desktop/nodetest/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
    at process._tickCallback (internal/process/next_tick.js:61:11)
  code: 2,
  details: '',
  metadata:
   Metadata { internalRepr: Map { 'content-type' => [Array] }, options: {} },
  note:
   'Exception occurred in retry method that was not classified as transient' }
2 UNKNOWN: 

```

I will see what it will take to get this fixed in the emulator. You should not see this issue against our Production servers.

**Comment by merlinnot** [comment]
Interesting, thanks for clarification!

**Comment by merlinnot** [comment]
@ryanpbrewster Is that something you could look into?

**Comment by ryanpbrewster** [comment]
Sadly I no longer work on the Firestore emulator. @yuchenshi @scottcrossen can one of you two dig into this? I imagine the issue is that we're failing to convert some exception somewhere.

**Comment by yuchenshi** [comment]
This is now tracked internally (b/151108414) and I'll look into it when I have more bandwidth.

**Comment by merlinnot** [comment]
@yuchenshi, do you know if you'll be able to pick it up this month? No rush, I'm just wondering if I should just wait or rather work around it somehow.

**Comment by yuchenshi** [comment]
@merlinnot I took a deep dive into it today and I believe I found a fix in our transaction handling logic in the Firestore Emulator. While we don't share timelines, this is likely to be fixed in the upcoming minor release soon.

**Comment by merlinnot** [comment]
Awesome, looking forward to it!

**Comment by yuchenshi** [comment]
Fixed with new Firestore Emulator release v1.11.3, which is bundled in `firebase-tools@8.1.0`.

**Comment by merlinnot** [comment]
I can confirm it's fixed, thank you!

**Comment by manwithsteelnerves** [comment]
firebase-tools@8.1.1
Firestore Emulator : 1.11.3

2 UNKNOWN: 
> at callErrorFromStatus (/functions/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
>        at Http2CallStream.call.on (/functions/node_modules/@grpc/grpc-js/build/src/call.js:79:34)
>        at Http2CallStream.emit (events.js:187:15)

Still seems to happen. I just updated to latest versions.

**Comment by manwithsteelnerves** [comment]
Ok, got the reason for the issue. It's not displaying the correct error and instead throwing 2 UNKNOWN.

> "3 INVALID_ARGUMENT: inequality filter property and first sort order must be the same: meta.defaultKeyword and name"

It was supposed to throw the above error. When tried with real firestore, it throwed the above message where as when using emulator it failed giving valid information.

Hope this helps and would be great to see a fix in upcoming versions. It took me 4hrs to debug but however was able to find out, phew!

**Comment by yuchenshi** [comment]
@manwithsteelnerves Hi! What you've described is a separate issue from the transaction rollback mentioned here. Would you mind opening a different issue on GitHub with detailed steps to reproduce? Please also include a code snippet there (e.g. your query) so I can start digging into it on my side.

**Comment by manwithsteelnerves** [comment]
@yuchenshi  Done!
