### ISSUE TITLE
query.stream() time out with Error: 14 UNAVAILABLE after 60 sec

### ISSUE THREAD

**Issue by klon** [googleapis/nodejs-firestore#964]
#### Environment details

  - OS: MacOS 10.13.6
  - Node.js version: v12.16.1
  - npm version: 6.13.4
  - `@google-cloud/firestore` version: 3.6.0 through firebase-admin 8.9.2

### Problem

When using query.stream() to stream documents from a large collection (100k+ docs) the query stream stalls at 60 seconds without any kind of error. It just hangs. After enabling setLogFunction(console.error) the output shows:

```
Firestore (3.5.0) 2020-03-10T19:00:34.189Z riRrx [Query._stream]: Query failed with stream error: Error: 14 UNAVAILABLE: The datastore operation timed out, or the data was temporarily unavailable.
    at callErrorFromStatus (node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.<anonymous> (node_modules/@grpc/grpc-js/build/src/call.js:79:34)
    at Http2CallStream.emit (events.js:323:22)
    at node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 14,
  details: 'The datastore operation timed out, or the data was temporarily unavailable.',
  metadata: Metadata {
    internalRepr: Map { 'content-disposition' => [Array] },
    options: {}
  }
}
```

### Expected outcome

That the stream would give me all of my result, alternatively emit an error to the stream when it fails.

**Comment by schmidt-sebastian** [comment]
@klon Thanks for filing this issue.

Unfortunately, 60 seconds is the maximum timeout we currently support on the backend. To work around this limitation, we suggest that you use the `startAt()/startAfter()/endAt()/endBefore()` APIs to limit the result set of a single query: https://firebase.google.com/docs/firestore/query-data/query-cursors

Alternatively, the `onSnapshot` API can potentially return larger result sets as the maximum timeout for the underlying onSnapshot RPCs is one hour.

**Comment by klon** [comment]
@schmidt-sebastian Ok that is unfortunate. It pretty much renders the query.stream() method useless to us and to most people I believe since streaming is mostly relevant with large result sets which will take some time to fetch. Also why isn't the stream error event triggered when this error occurs? I'd call that a bug regardless of the back end timeout limitations. Even stream end event isn't triggered.. my stream ended up in a stalled state.

**Comment by klon** [comment]
@schmidt-sebastian Also where is this limitation documented?

**Comment by schmidt-sebastian** [comment]
I will look at this and see if we are somehow dropping the error. 

As for getting this documented: Yes, we should do that (it is not right now). We are however also working on lifting this limitation.

**Comment by schmidt-sebastian** [comment]
@klon I just started looking at this again, but I am not able to reproduce this.

I am lowering the deadline manually:

```
 new Firestore( { 
    clientConfig: {
        interfaces: {
          'google.firestore.v1.Firestore': {
            methods: {
              RunQuery: {
                timeout_millis: 1
              }
            }
        }
    }
});
```

And running a query as such:

```
randomCol.stream().on('error', (e) => {
    console.log('Received error');
})
```

I am seeing the error here.

**Comment by merlinnot** [comment]
@schmidt-sebastian @bcoe I also bumped into that issue:

```
Firestore (3.7.4) 2020-04-23T15:39:40.585Z aAHmH [Firestore._initializeStream]: Received stream error: Error: 14 UNAVAILABLE: The datastore operation timed out, or the data was temporarily unavailable.
    at Object.callErrorFromStatus (/my-project-path/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/my-project-path/node_modules/@grpc/grpc-js/src/client.ts:552:32)
    at Object.onReceiveStatus (/my-project-path/node_modules/@grpc/grpc-js/src/client-interceptors.ts:402:48)
    at Http2CallStream.outputStatus (/my-project-path/node_modules/@grpc/grpc-js/src/call-stream.ts:228:22)
    at Http2CallStream.maybeOutputStatus (/my-project-path/node_modules/@grpc/grpc-js/src/call-stream.ts:278:14)
    at Http2CallStream.endCall (/my-project-path/node_modules/@grpc/grpc-js/src/call-stream.ts:262:12)
    at Http2CallStream.handleTrailers (/my-project-path/node_modules/@grpc/grpc-js/src/call-stream.ts:398:10)
    at ClientHttp2Stream.emit (events.js:315:20)
    at ClientHttp2Stream.EventEmitter.emit (domain.js:485:12)
    at emit (internal/http2/core.js:289:8) {
  code: 14,
  details: 'The datastore operation timed out, or the data was temporarily unavailable.',
  metadata: Metadata {
    internalRepr: Map(1) { 'content-disposition' => [Array] },
    options: {}
  }
}
```

The behavior described above is correct. I don't see any errors from the stream, although I have a listener attached. The "end" event is not emitted either, the stream literally just hangs.

My setup: a Node.js service with four queries to four distinct collections, each ~35k in size, documents of significant size (some ~100kB).

I looked at the previous log statement with a document and compared the timestamp of the log statement with the `readTime`, it's almost exactly 60 seconds.

Log timestamp: 2020-04-23T15:39:40.584Z
Read time: 2020-04-23T15:38:09.168Z

I'd be happy to assist you in reproducing the issue, let me know if you need some more details here or if you'd like to have a call.

**Comment by merlinnot** [comment]
To add to this, what I'm actually doing is a `query.stream` to populate my in-memory cache faster (partial results are very useful in my use case) and then `query.onSnapshot` on the same collection to keep the cache up to date.

It would be the best if I could stream results of `query.onSnapshot` straight away, instead of waiting for the initial (full) snapshot. Is it something that the back end API enables us to do? If so, would you welcome a PR to add this functionality after an alignment on the interface?

**Comment by mad-it** [comment]
> It would be the best if I could stream results of `query.onSnapshot` straight away, instead of waiting for the initial (full) snapshot. Is it something that the back end API enables us to do? If so, would you welcome a PR to add this functionality after an alignment on the interface?

Already tried requesting this last time 😭 https://github.com/googleapis/nodejs-firestore/issues/955

**Comment by merlinnot** [comment]
I actually tried to force my way to get streaming results from `query.onSnapshot` by hooking into `Watch.onData`, unfortunately `query.onSnapshot` listeners don't work either: https://github.com/googleapis/nodejs-firestore/issues/1040.

I might need to split queries into smaller ones and execute them sequentially - since it's a timeout, running them concurrently won't help, as there will be less network bandwidth per query (on my side, not Google's). Then probably merge the results somehow on my end 🤔

**Comment by schmidt-sebastian** [comment]
My one good piece of good news is that there is a lot of chatter on the backend side to finally lift the 60s deadline limitation. That doesn't quite solve the problem that we should be raising an error here. I will give this another spin next week. @merlinnot If you think there is anything special in your code, it might help me if you provide a code snippet that reproduces this problem on your end.

As for returning partial results from the Watch stream - I still think this is not a good idea in almost all use cases, as the backend does not provide any guarantees about what they sent to us before they confirm that they have sent a complete snapshot. If you really want to give this a spin, you can try commenting out `this.current` in https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/watch.ts#L459 and let us know if this helps.

**Comment by merlinnot** [comment]
When I look at the messages when executing `onSnapshot`, I get:

- One `targetChange`, `targetChangeType: 'ADD'`
- A lot of `documentChange`s
- One `targetChange`, `targetChangeType: 'REMOVE'`, `message: 'The datastore operation timed out, or the data was temporarily unavailable.'`

I don't get any `targetChangeType: 'NO_CHANGE'` that you referred to in your link, at least not before it crashes (note that `onSnapshot` correctly forwards the error, only `stream` hangs). I don't understand how would it help, but basically I didn't observe any change in the behavior.

I guess that you might have wanted to force the snapshot to be pushed regardless of the actual synchronization state. I added

```ts
this.pushSnapshot(Timestamp.fromMillis(Date.now()), undefined);
```

right after this line: https://github.com/googleapis/nodejs-firestore/blob/d13b9a6c052c4a8233d41b428daf498c443ad509/dev/src/watch.ts#L531

That resulted in a correct behavior, where my callback was called with every update. I noticed however that there's a significant overhead when computing this snapshot. Given that this feature is useful only for larger collections, we should focus on performance if we'd be to implement an API for this capability, therefore we might want to rethink what is the minimal possible code path required to transform the incoming gRPC messages to `DocumentSnapshot`s.

I'll work on a reproduction now, so it's easier for you to work on it, will post it later.

Thank you for your support.

**Comment by merlinnot** [comment]
Below you can find a reproduction, I tested it many times and it works for me all the time. I run it with various network settings (throttling to a various degree), but it doesn't seem to matter. Just in case you can't reproduce it yourself, there's some code to add backpressure, just uncomment the `spinCpu` call.

You should expect an error here:
https://github.com/googleapis/nodejs-firestore/blob/3aa9b0e8d5c8eeb40496058556aaa305a8277d34/dev/src/index.ts#L1211-L1216

You should also expect the process to exit before printing `500` as a number of fetched documents. Some streams might emit the `end` event. No streams will emit the `error` event.

```typescript
import { Firestore } from '@google-cloud/firestore';

const firestore = new Firestore({ projectId: 'com-ridedott-test' });
const collection = firestore.collection('collection');
const startedAt = Date.now();

const DOCUMENT_PROPERTIES_COUNT = 64;
const DOCUMENT_PROPERTY_SIZE = 128;
const DOCUMENT_PROPERTY_VALUE = '🔥';
const CPU_SPIN_TIME_MS = 500;
const DOCUMENTS_COUNT = 500;
const STREAM_COUNT = 8;

const largeDocumentData = Object.fromEntries(
  Array.from({ length: DOCUMENT_PROPERTIES_COUNT }, (_, index) => [
    `property${index}`,
    DOCUMENT_PROPERTY_VALUE.repeat(DOCUMENT_PROPERTY_SIZE),
  ]),
);

const spinCpu = (milliseconds: number) => {
  const now = Date.now();
  while (Date.now() - now < milliseconds);
};

const startStream = (id: number) =>
  collection
    .stream()
    .on('data', (snapshot) => {
      console.log(`stream ${id}: data`, Date.now() - startedAt, snapshot.id);

      // Uncomment the following to add backpressure.
      // spinCpu(CPU_SPIN_TIME_MS);
    })
    .on('end', () => console.log(`stream ${id.toPrecision(2)}: end`))
    .on('error', () => console.log(`stream ${id.toPrecision(2)}: error`));

const run = async () => {
  await Promise.all(
    Array.from({ length: DOCUMENTS_COUNT }, (_, i) =>
      collection.doc(i.toString()).set(largeDocumentData),
    ),
  );

  for (let i = 0; i < STREAM_COUNT; i++) {
    startStream(i);
  }
};

run();
```

**Comment by schmidt-sebastian** [comment]
Given the repro above, I was able to track down the root cause for this error. We swallowed errors for streams that were able to return some documents before failing. While we did have error handling in place, the way the error handler was registered suppressed the exception.

If I get #1046 reviewed this weekend (which shouldn't be a problem), this will get released when our release window opens again on Monday, 7 am Pacific.

Thank you for the repro @merlinnot. 

As for the behavior you are seeing on Watch: A "target remove" message means that the Watch backend wasn't able to process the result right away. This is usually silently handled by our clients, but this handling depends on all the code and the retry logic we have written in the SDK. Our team has decided early on that the Watch protocol and its state machine is not something that we expect external customer to use in their applications, and as such, I am not able to provide support here.

One suggestion for querying large collections is to use Query cursor to resume your query:

```
const query = firestore.collection(...);

let lastDoc: QueryDocumentSnapshot;
let stream = query.stream();
stream.on('data', d => { lastDoc = d; )};
stream.on('error', () => {
   stream = query.startAffter(lastDoc).stream();
   // ... register stream handlers again
});
```

This, however, will only work with #1046.

**Comment by merlinnot** [comment]
Thank you for the fix and the suggestion how to handle this error using `startAfter`, that's clean.

Is the wire protocol documented somewhere in detail? There's a documentation for all interfaces and methods, but I can't find any documentation for the _behavior_. If you don't want the `onSnapshot` stream be exposed in the library, I'd like to implement it myself for my needs. Documentation would be helpful.

**Comment by schmidt-sebastian** [comment]
The only external documentation for this API in the inline documentation in the Protos: https://github.com/googleapis/nodejs-firestore/blob/master/dev/protos/google/firestore/v1/firestore.proto#L567, which admittedly is only adequate if you combine it with the code in this SDK and weeks of trial and error.

**Comment by merlinnot** [comment]
Weeks of trial and error - that sound fun 😂 I managed to work around the issue by sequentialization of my subscriptions, so I dropped some parallelism as a tradeoff, but I'm afraid I'll have to get back to it at some point in the future. Maybe I'll be lucky and at that point there will be some other method to do that. Thanks again for a quick fix, helped a lot.

**Comment by PiotrDabkowski** [comment]
@schmidt-sebastian why can't stream() function handle this internally? The timeout is a bit arbitrary and causes errors one the application reaches a certain level of scale. Is it too much to ask for a proper stream fix without timeouts?

**Comment by klon** [comment]
When I filed this ticket a while back we worked around the issue by writing our own streaming query implementation that used normal querying and paginating 5,000 docs at a time. It worked quite well. 

We tried `query.stream()` again now hoping the latest version had improved the implementation but unfortunately it intermittently fails in production with:

```
Error: 9 FAILED_PRECONDITION: The requested snapshot version is too old.
    at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:360:49)
    at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
    at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:188:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeServerStreamRequest (/app/node_modules/@grpc/grpc-js/build/src/client.js:343:34)
    at ServiceClientImpl.<anonymous> (/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /app/node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:225:29
    at /app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:38:28
    at /app/node_modules/google-gax/build/src/normalCalls/timeout.js:44:16
    at Object.request (/app/node_modules/google-gax/build/src/streamingCalls/streaming.js:130:40)
    at makeRequest (/app/node_modules/google-gax/node_modules/retry-request/index.js:141:28)
    at retryRequest (/app/node_modules/google-gax/node_modules/retry-request/index.js:109:5)
    at StreamProxy.setStream (/app/node_modules/google-gax/build/src/streamingCalls/streaming.js:121:37)
    at StreamingApiCaller.call (/app/node_modules/google-gax/build/src/streamingCalls/streamingApiCaller.js:54:16) {
  code: 9,
  details: 'The requested snapshot version is too old.',
```

We are using `@google-cloud/firestore  6.4.0`

**Comment by schmidt-sebastian** [comment]
@ehsannas

**Comment by ehsannas** [comment]
Thanks for flagging this @klon . There seems to be different things going on at once in this issue. And IIUC the only outstanding issue today is the above error `The requested snapshot version is too old.`. I'm opening a new issue to look into that.
