### ISSUE TITLE
Upgrading from 3.6.0 to 3.7.0 throws internal error.

### ISSUE THREAD

**Issue by mad-it** [googleapis/nodejs-firestore#969]
I have an applications running on GKE. When upgrading this application's dependency from 3.6 to 3.7 I get the following error:
```
Error: INTERNAL ERROR: Client is not yet ready to issue requests.
    at Firestore.get projectId [as projectId] (/run/node_modules/@google-cloud/firestore/build/src/index.js:401:19)
    at CollectionReference.toProto (/run/node_modules/@google-cloud/firestore/build/src/reference.js:1556:42)
    at CollectionReference.stream (/run/node_modules/@google-cloud/firestore/build/src/reference.js:1521:30)
```

I tried using `setLogFunction` to print some other useful information, but there is nothing useful in the output. Only line I am getting before the stacktrace is the following:
```
Firestore (3.7.0) 2020-03-13T07:41:13.099Z ##### [Firestore]: Initialized Firestore
```

As you can see from the stacktrace, the only thing we use is the `CollectionReference.stream()` method.

Sorry that I could not add any additional reproduction steps.

**Comment by TheAmazingPT** [comment]
It seems that i have the same problem, when running my node app in **Google Cloud Functions**.
All credentials are provided and no changes have been made in the code.
The deployment is done via **Google Cloud Build**, where the node app is built and bundled.

In the package.json the Firestore package is declared as `"@google-cloud/firestore": "^3.3.2"`.

When forcing the version to `3.6.0`, it seems to work flawlessly.

**Comment by themikefuller** [comment]
Got this same error today when I was changing some settings on a Cloud Function. I thought initially my tinkering with the settings caused the problem. It wasn't fixed by reverting back to the old settings. I can confirm that forcing "@google-cloud/firestore":"3.6.0" in the dependencies corrected the issue.

**Comment by AndriiTsok** [comment]
We experience the same problem and error message.

>> Error: INTERNAL ERROR: Client is not yet ready to issue requests.

**Comment by schmidt-sebastian** [comment]
We are looking at this.

**Comment by schmidt-sebastian** [comment]
We have pinned 3.6.0 as our latest release.
