### ISSUE TITLE
Can not access to customClaims object into firestore security rules auth.token.customProp.

### ISSUE THREAD

**Issue by mpilalex** [googleapis/nodejs-firestore#97]
Thanks for stopping by to let us know something could be better!

Please run down the following list and make sure you've tried the usual "quick
fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-firestore/issues
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
  - Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
  - Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq

If you are still having issues, please be sure to include as much information as
possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - @google-cloud/firestore version:

#### Steps to reproduce

  1. Create customClaims object into user
  2. Try to access into customClaims into security rules like described at https://firebase.google.com/docs/auth/admin/custom-claims - customClaims not passed into auth.token from security rules scope;

Following these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by schmidt-sebastian** [comment]
This is an issue in the Firebase Admin SDK. Moving discussion over there: https://github.com/firebase/firebase-admin-node/issues/178
