### ISSUE TITLE
Support more GoogleAuthOptions

### ISSUE THREAD

**Issue by mbleigh** [googleapis/nodejs-firestore#973]
**Is your feature request related to a problem? Please describe.**
I need to authenticate to the Firestore SDK in an environment where I do not have a service account key nor Application Default Credentials, but do have a user refresh token.

**Describe the solution you'd like**
Support `UserRefreshClientOptions` (see [here](https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/googleauth.ts#L82)) as a credential type for Firestore.

**Describe alternatives you've considered**
There is no alternative here -- I don't have service account credentials and these clients aren't running in a GCP service that has ADC.

**Additional context**
This is to support the ability for the [Firebase CLI](https://github.com/firebase/firebase-tools) to instantiate a Firestore SDK on behalf of the user for a given project for some upcoming work to provide a new feature to Firebase developers (see [specific context](https://github.com/firebase/firebase-tools/pull/1865/files#diff-93226adece975b2a3f7e1426830bfb0cR58) of using Admin SDK).

**Comment by schmidt-sebastian** [comment]
@mbleigh Thanks for filing this. We will explore this option (likely next week) and keep this issue updated.

**Comment by schmidt-sebastian** [comment]
I think our types are not correct, but we may need a fix in the Google Auth Library to allow us to properly type UserRefreshTokens in our API. I have opened https://github.com/googleapis/google-auth-library-nodejs/issues/924 to get this addressed.

In the meantime, you can use a User Refresh Credential as such:

 ```
const firestore = new Firestore({
  projectId: "...",
  credentials: {
    type: "authorized_user", 
    client_id: "....apps.googleusercontent.com",
    client_secret: "...",
    refresh_token: "..."    
  } as any
});
```

**Comment by sofisl** [comment]
Hi all!

After doing some experimentation, I've confirmed that this should work: 

```
const firestore = new Firestore({
  projectId: "...",
  clientOptions: {
    type: "authorized_user",  // Note: Not documented
    client_id: "....apps.googleusercontent.com",
    client_secret: "...",
    refresh_token: "..."    
  } as UserRefreshClientOptions
});
```

Labeling it as UserRefreshClientOptions should eventually lead you [here](https://github.com/googleapis/google-auth-library-nodejs/blob/73f0b0f99a67ec099bc5e6f74f9396dcbadb7c32/src/auth/refreshclient.ts#L85) to authenticate properly.

Please feel free to reopen if this solution does not work for you!
