### ISSUE TITLE
DocumentSnapshot in startAt or startAfter cause an error: Error: Cannot encode type ([object Object]) to a Firestore Value

### ISSUE THREAD

**Issue by Erbolking** [googleapis/nodejs-firestore#98]
Hello,

According to the https://firebase.google.com/docs/firestore/query-data/query-cursors
we could be able to use a **document snapshot** to define the query cursor.

but in the fact, it throws an error: "Error: Cannot encode type ([object Object]) to a Firestore Value".

#### Environment details

  - OS: Windows 10
  - Node.js version: 9.2.0
  - npm version: 5.5.1
  - @google-cloud/firestore version: 0.10.0

#### Steps to reproduce

```js
const first = firestore.collection("collectionName")
  .orderBy("population")
  .limit(25)
  .get()
  .then(function (documentSnapshots) {
    // Get the last visible document
    const lastVisible = documentSnapshots.docs[documentSnapshots.docs.length-1];

    const next = firestore.collection("collectionName")
      .orderBy("population")
      .startAfter(lastVisible)
      .limit(25)
      .get()
      .then(data => {
        console.log(data.docs.length);
      });
  });
```

I tried the same with `@firebase/firestore` and it works just fine.

**Comment by schmidt-sebastian** [comment]
This is not (yet) supported by the Node Server SDK. If you look under the Node.JS tab, you will see that the code snippet for Node is missing. I am planning to add this support soon.
