### ISSUE TITLE
.where(admin.firestore.FieldPath.documentId(), 'in', ['id1', 'id2']) fails: '... FieldPath.documentId() must be a string or a DocumentReference'

### ISSUE THREAD

**Issue by xaphod** [googleapis/nodejs-firestore#990]
#### Environment details

  - OS: Firebase Function NodeJS, running on the emulator from Firebase CLI 7.16.1
  - Node.js version: 13.11.0
  - `@google-cloud/firestore` version: 3.7.2
  - `firebase-admin` version: 8.10.0

#### Steps to reproduce

```
    const admin = require('firebase-admin');
    const arr = ['id1', 'id2'];
    const m = await db
      .collection('media')
      .where(admin.firestore.FieldPath.documentId(), 'in', arr)
      .get();
```

Expected: able to query a list of document IDs in a single collection.

Actual: 

```
Error: The corresponding value for FieldPath.documentId() must be a string or a DocumentReference.
    at CollectionReference.validateReference (node_modules/@google-cloud/firestore/build/src/reference.js:1325:19)
    at CollectionReference.where (node_modules/@google-cloud/firestore/build/src/reference.js:1038:26)
```

Does anyone know a workaround? Thanks! (edited several times for clarity)

**Comment by Padreco-lbr** [comment]
Happening to me too, if not an issue, please provide information ou how to make a query based on a list of document Ids. There simply is no documentation examples on that.

**Comment by schmidt-sebastian** [comment]
I will get this fixed today.

**Comment by xaphod** [comment]
Thanks!

**Comment by pennjlin** [comment]
Looks like this issue persists when running with Firebase local emulator. Is there a way to verify the package version used in the emulator? @schmidt-sebastian

**Comment by schmidt-sebastian** [comment]
You can always use `npm list` to verify the installed version. In general, removing the package.lock and `node_modules` followed by a re-install should get you the latest version.

**Comment by ebeloded** [comment]
My `firebase-admin` is up to date, yet I am still running into this exact issue. Any suggestions?

**Comment by ebeloded** [comment]
After looking at the tests, I tried to use `@google-cloud/firestore` instead of `firebase-admin`, and it worked!

This works:
```typescript
import { FieldPath, Firestore } from '@google-cloud/firestore'

const firestore = new Firestore()

const menus = await firestore
  .collection('menus')
  .where(FieldPath.documentId(), 'in', ['cUKi4Kj42LOcLsqBZOBhM'])
  .get()

```

This doesn't:
```typescript
import admin from 'firebase-admin'

const menus = await admin
  .firestore()
  .collection('menus')
  .where(admin.firestore.FieldPath.documentId(), 'in', [
    'cUKi4Kj42LOcLsqBZOBhM',
  ])
  .get()

}

start()
```

It seems that `admin.firestore.FieldPath` is not the same as `FieldPath` from `@google-cloud/firestore`

**Comment by MathiasGilson** [comment]
This works for me

```js
const firebase = require("@firebase/testing")
const admin = firebase.initializeAdminApp({
    projectId: "my-test-project"
})

// ... //

// it as to be firebase from @firebase/testing
admin.firestore()
  .collection("users")
  .where(firebase.firestore.FieldPath.documentId(), "in", userIds) 
  .get()

```

**Comment by pablomaribondo** [comment]
This works for me

`
const admin = require("firebase-admin");

const arr = ["id1", "id2"];
const refArr = arr.map(id => admin.firestore().collection("media").doc(id));

const m = await admin
      .firestore()
      .collection("media")
      .where(admin.firestore.FieldPath.documentId(), "in", refArr)
      .get();
`

**Comment by 5amfung** [comment]
Somehow the query works without `orderBy`.  As soon as I added `orderBy`, I get empty result set.

```
admin.firestore()
  .collection('users')
  .where(firebase.firestore.FieldPath.documentId(), 'in', userIds) 
  .orderBy('firstName')
  .get()
```

**Comment by schmidt-sebastian** [comment]
@5amfung The query you are issuing should be rejected by the backend ("inequality filter property and first sort order must be the same: __key__ and firstName"). If you are using an "in" filter, you also need to use this field as the first orderBy constraint. You can then add additional orderBy constraints afterwards (e.g. `where(FieldPath.documentId(), 'in', [...]).orderBy(FieldPath.documentId()).orderBy('firstName')`).
