### ISSUE TITLE
error: the project does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database.

### ISSUE THREAD

**Issue by blasshak** [googleapis/nodejs-firestore#991]
I'm starting using firestore with nodejs and I'm getting the following error:

 The project xxxx does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=xxxx to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.
Object.callErrorFromStatus (/var/app/condor/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
Http2CallStream.<anonymous> (/var/app/condor/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
Http2CallStream.emit (events.js:323:22)
/var/app/condor/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22
processTicksAndRejections (internal/process/task_queues.js:79:11)
(node:302) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
condor_1  | (node:302) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I've already checked it in google clould and the firestore is working. 

code:
```
function initializeAppSA() {

  let serviceAccount = require('./config/serviceAccountKey.json');

  admin.initializeApp({
    //credential: admin.credential.applicationDefault(),
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "https://xxxxx.firebaseio.com"
  });

  let db = admin.firestore();

  return db;
}
const db = initializeAppSA();
let docRef = db.collection('users').doc('alovelace');

let setAda = docRef.set({
  first: 'Ada',
  last: 'Lovelace',
  born: 1815
});
```

Environment details

- OS: Ubuntu
- Node.js version: v12

**Comment by schmidt-sebastian** [comment]
@blasshak Thanks for filing this issue. Since this is likely project specific, this forum might not be the best platform to debug your issue. Do you mind filing a Support Request, where you can include your Project ID? Thank you.

https://cloud.google.com/support-hub
