### ISSUE TITLE
error: GCP Cloud function scheduled firestore export to multi-regional bucket eur4

### ISSUE THREAD

**Issue by ahipster** [googleapis/nodejs-firestore#992]
#### Environment details
  - GCP Cloud functions node.js 10 (beta)
  - `@google-cloud/firestore` version: 3.7.2

#### Steps to reproduce
Follow GCP tutorial on https://cloud.google.com/firestore/docs/solutions/schedule-export
  1. Deployed bucket is multi-regional in eur4 (which is actually dual region).
  2. Deployed function is in europe-west3.
  2. Triggered function results in runtime error:

Bucket gcp-yourprojectid-dev-buk-eur4-firestore-backup is in location EUR4. This project can only operate on buckets spanning location europe-north1 or europe-west1 or eu or europe-west2 or europe-west3 or europe-west4 or europe-west5 or europe-west6 or europe-west8 or europe-west9.

However, function works perfectly with single-region bucket...
P.S. Cloud Datastore Import Export Admin and Storage Admin role (on the bucket) are granted. 

Is that a google cloud bug, treating dual-region buckets as single?
Similar issue: https://stackoverflow.com/a/57890923

**Comment by schmidt-sebastian** [comment]
@ahipster Sorry to hear about your troubles! I was going to respond earlier, but I really don't know how to help you. This looks like it might be a problem deep down in our pipeline. Do you mind filing a support request? Thank you.

https://cloud.google.com/support-hub
